(#1013)(#1016)(#1017)(#1018)
chocolatey/docs pull request #1020
Opened 2024-06-26 17:00 UTC by st3phhays

## Description Of Changes

This addresses a number of small enhancements:

* Adds hash to CSS and JS for automatic cache busting
* Adds information to the README on how to build for production
* Adds information to the README for recommended VS Code extensions
* Adds the sitemap.xml to the <head> to allow search engines to find it easier

## Motivation and Context
All these items came out of the initial Astro conversion and training session.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [x] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue
* Fixes #1013
* Fixes #1016
* Fixes #1017
* Fixes #1018

2024-06-27 06:32 UTC, gep13 requested changes
Just a couple of minor things.

2024-06-27 06:32 UTC, gep13 commented on README.md
> +* [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces) - Highlights spelling errors and suggests fixes.
I don't think that this is linking to the right extension.

2024-06-27 06:32 UTC, gep13 commented on src/layouts/Layout.astro
> +        <link rel="sitemap" href="/sitemap-index.xml" />
Is the spacing at the start of this line correct? It doesn't line up with the others that are already here.

2024-06-27 13:06 UTC, st3phhays commented on README.md
> +* [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=shardulm94.trailing-spaces) - Highlights spelling errors and suggests fixes.
I have fixed this up.

2024-06-27 13:07 UTC, st3phhays commented on src/layouts/Layout.astro
> +        <link rel="sitemap" href="/sitemap-index.xml" />
Turns out this page had a mixture of spaces and tabs in it. I have added on a maint commit to make it all formatted correctly.

2024-07-01 15:04 UTC, gep13 approved these changes
LGTM!

2024-07-01 15:04 UTC, merged