(doc) Add dependency issues YouTube video
chocolatey/docs pull request #1041
Opened 2024-08-07 10:03 UTC by pauby

## Description Of Changes
Added the dependency issues YouTube video to the page, starting at 20m 8s.

## Motivation and Context
The page needed this video for more information.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2024-08-09 16:19 UTC, st3phhays commented on src/content/docs/en-us/choco/troubleshooting/dependency-troubles.mdx
> +<Iframe ratio="16x9" link="https://www.youtube.com/embed/mulMztVQzQU?si=ZOFdN8Tr4cjB0Dt6&amp;start=1208" />
Can you add a `title` attribute onto this? Some of the old ones don't have it, but going forward this would be good to have for accessibility. (https://design.chocolatey.org/components/iframe#pass-in-individual-options)

2024-08-09 16:20 UTC, st3phhays requested changes
@pauby Just one small change otherwise this is great.

2024-08-22 13:19 UTC, pauby commented on src/content/docs/en-us/choco/troubleshooting/dependency-troubles.mdx
> +<Iframe ratio="16x9" link="https://www.youtube.com/embed/mulMztVQzQU?si=ZOFdN8Tr4cjB0Dt6&amp;start=1208" />
Added.

2024-08-22 13:20 UTC, pauby commented
@st3phhays this has been fixed up and ready for review again.

2024-08-23 06:21 UTC, gep13 approved these changes
LGTM!

2024-08-25 12:21 UTC, st3phhays approved these changes
LGTM!

2024-08-25 12:21 UTC, merged