Added Nexus Upgrade doc to Azure docs
chocolatey/docs pull request #1052
Opened 2024-08-14 17:35 UTC by imm0rtalsupp0rt

In this commit I added upgrade documentation for Sonatype Nexus in the Azure documentation in preparation for upgrading Nexus due to database migration.

## Description Of Changes
Added upgrade documentation for Sonatype Nexus to the Azure documentation.

## Motivation and Context
With Nexus' migration from OrientDB to H2 we needed to include upgrade documentation for environments other than the Quick Start Environment. This is the first step of those additions.

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [X] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [X] Menu structure has been updated

2024-08-14 17:41 UTC, steviecoaster requested changes

2024-08-14 17:41 UTC, steviecoaster commented on src/content/docs/en-us/c4b-environments/azure/upgrading-nexus.mdx
> +If your server is restricted from access to the Chocolatey Community Repository, internalize the package to your internal repository.
```suggestion
<Xref title="internalize the package to your internal repository" value="package-internalizer" />
```

2024-08-15 10:00 UTC, pauby commented
@imm0rtalsupp0rt can you please amend your commit messages to [match the guidance](https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#prepare-commits)?

2024-08-15 11:55 UTC, steviecoaster approved these changes
🚀  LGTM

2024-08-15 11:56 UTC, merged