(#1031) Update wording of custom install location
chocolatey/docs pull request #1054
Opened 2024-09-03 18:55 UTC by corbob

## Description Of Changes

Updates the wording of the custom install location documents to clarify that the ChocolateyInstall variable must be available to the process that is installing Chocolatey.

## Motivation and Context

The previous wording was ambiguous.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] ~Minor documentation fix (typos etc.).~
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] ~New documentation page added.~
* [ ] ~The change I have made should have a video added, and I have raised an issue for this.~

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

* Fixes #1031
* ENGTASKS-3856

2024-09-04 09:45 UTC, pauby requested changes

2024-09-04 09:45 UTC, pauby commented on src/content/docs/en-us/choco/setup.mdx
> +The Chocolatey installation script looks for the `ChocolateyInstall` environment variable in order to identify where it should install to. If this environment varialbe does not exist, it will install
```suggestion
The Chocolatey installation script looks for the `ChocolateyInstall` environment variable in order to identify where it should install to. If this environment variable does not exist, it will install Chocolatey to the default location. In order to install to a non-default location, you should set this variable in a way that it is available in the process that will be running the install script.
```

2024-09-04 09:45 UTC, pauby commented on src/content/docs/en-us/choco/setup.mdx
> +The Chocolatey installation script looks for the `ChocolateyInstall` environment variable in order to identify where it should install to. If this environment varialbe does not exist, it will install
> In order to install to a non-default location, you should set this variable in a way that it is available in the process that will be running the install script.

I know you're not trying to be as prescriptive as the previous instructions, but could you elaborate or give an example of what you mean here to make it easier to understand?

2024-09-05 01:26 UTC, corbob commented on src/content/docs/en-us/choco/setup.mdx
> +The Chocolatey installation script looks for the `ChocolateyInstall` environment variable in order to identify where it should install to. If this environment varialbe does not exist, it will install
Thank you for catching that spelling mistake. I found both why my LanguageTool install wasn't working (wasn't enabled in the devcontainer)  and why the cSpell didn't catch it (it wasn't enabled for mdx files).

I've also updated the wording to hopefully provide context on ways to set an environment variable.

2024-09-06 08:40 UTC, pauby approved these changes

2024-09-06 08:40 UTC, merged

2024-09-06 08:40 UTC, pauby commented
Thanks for adding those changes @corbob!