(#1057) Add connection string info for CCM 0.13.0
chocolatey/docs pull request #1060
Opened 2024-09-11 15:36 UTC by vexx32

## Description Of Changes

Added a notice to the Database/Service/Web setup pages for CCM informing users about the change to CCM's connection strings, with information on what to do if they want a _completely_ secure connection to the SQL Server instance.

Also updated a few connection string examples in the docs, mainly the ones talking about which default values are used for the connection string in the `appsettings.json` file or otherwise showing its contents.

## Motivation and Context

Since these changes may affect users, it's important to call them out in our setup documentation.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue
Part of changes needed for #1057

2024-09-13 14:24 UTC, pauby requested changes
A lot of changes, but most of them are just consistency.

There are a couple of questions about .NET 6 and 8 that could just be my misunderstanding.

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
> Defaults to default

What does that mean? Does it mean that it defaults to the word, `default`? If so, can we put code quotes around it?

That whole sentence really doesn't read very well. I know you didn't write it.

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
```suggestion
* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance` and `/Database`, along with Integrated Security (`Server=<LOCAL COMPUTER FQDN NAME>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;`). The account should have [`db_owner`](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles#fixed-database-roles) access to the database.

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
>              **Installs**: Please ensure the user running the package installation is able to create databases unless you also pass `/SkipDatabasePermissionCheck` (in that case you simply need `db_own
```suggestion
            **Installation**: Please either ensure the user running the package installation is able to create databases or pass `/SkipDatabasePermissionCheck`, if you have `db_owner` permission to the pre-created database.
```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
>              **Upgrades**: Please ensure the user running the package installation has been granted `db_owner` access to an existing database.
```suggestion
            **Upgrade**: Please ensure the user running the package installation has been granted `db_owner` access to the existing database.
```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
>              **Installs**: Please ensure the login credentials provided are able to create databases unless you also pass `/SkipDatabasePermissionCheck` (in that case you simply need `db_owner` to the
```suggestion
            **Installation**: Please either ensure the user running the package installation is able to create databases or pass `/SkipDatabasePermissionCheck`, if you have `db_owner` permission to the pre-created database.
```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
>              **Upgrades**: Please ensure the login credentials provided have been given `db_owner` access to an existing database.
```suggestion
            **Upgrade**: Please ensure the user running the package installation has been granted `db_owner` access to the existing database.
```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
```suggestion
* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance` and `/Database`, along with Integrated Security (`Server=<LOCAL COMPUTER FQDN NAME>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;`). The account should have `db_owner` access to the database ([database owner](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles#fixed-database-roles)).

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
We should be consistent.

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/database.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
We should be consistent.

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
```suggestion
* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance` and `/Database`, along with Integrated Security (`Server=<LOCAL COMPUTER FQDN NAME>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True; `). The account should have `db_datareader`/`db_datawriter` access to the database ([data reader / data writer](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles#fixed-database-roles)).

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +        "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
        "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +If the Chocolatey Central Management Service is not able to be started due to "Error 1053: The service did not respond to the start or control request in a timely fashion.", it is likely caused due t
```suggestion
If the Chocolatey Central Management Service cannot be started due to "Error 1053: The service did not respond to the start or control request in a timely fashion.", it will likely be caused by no compatible versions of dotnet aspnetruntime being installed.

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +The installed runtimes can be listed with `dotnet --list-runtimes`. Ensure that a 6.x.x version of Microsoft.AspNetCore.App is listed. If there is not a version listed, reinstall `dotnet-6.0-aspnetru
I'm confused by this one - are we not moving to .NET 8?

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +There is a known issue with the aspnetcoremodule-v2 installer that will uninstall the aspnetruntime on upgrade, which may be the root cause for this missing runtime. https://github.com/dotnetcore-cho
Are we still using this? Or is this still an issue?

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/website.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
```suggestion
* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance` and `/Database`, along with Integrated Security (`Server=<LOCAL COMPUTER FQDN NAME>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;`). The account should have `db_datareader`/`db_datawriter` access to the database ([data reader / data writer](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/database-level-roles#fixed-database-roles)).

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/website.mdx
> +        "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
        "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/website.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/website.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=true;"
```suggestion
    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"

```

2024-09-13 14:24 UTC, pauby commented on src/content/docs/en-us/central-management/setup/website.mdx
> +Another possible cause for this error is if there are mismatching versions of `dotnet-6.0-aspnetruntime` and `dotnet-aspnetcoremodule-v2`. Ensure that both are on the same patch level. Note that `dot
Same question as above about using .NET 8?

2024-09-13 15:18 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/database.mdx
> +* `/ConnectionString:` - The SQL Server database connection string to be used to connect to the Chocolatey Central Management database. Defaults to default or explicit values for `/SqlServiceInstance
👀 

_Yeah_, I can reword that a bit, for sure. It's trying to say "the `ConnectionString` defaults to [a value that is constructed from the specified or default values for `/SqlServerInstance` and `/Database`, along with Integrated Security".

... Lemme workshop that a bit.

2024-09-13 15:24 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +The installed runtimes can be listed with `dotnet --list-runtimes`. Ensure that a 6.x.x version of Microsoft.AspNetCore.App is listed. If there is not a version listed, reinstall `dotnet-6.0-aspnetru
Yes we are, thanks! Hmm, thought I went through all the search results for `6.x.x` and `6.0`, not sure how I missed that one.

2024-09-13 15:26 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +There is a known issue with the aspnetcoremodule-v2 installer that will uninstall the aspnetruntime on upgrade, which may be the root cause for this missing runtime. https://github.com/dotnetcore-cho
I need to confirm this to be sure in the current version; based on what Gary has mentioned and what I have seen myself, it _may_ no longer be an issue at least for upgrades. I'll see about getting a VM set up to verify whether the installation and upgrade works without the additional fiddling around now.

2024-09-13 15:33 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/website.mdx
> +Another possible cause for this error is if there are mismatching versions of `dotnet-6.0-aspnetruntime` and `dotnet-aspnetcoremodule-v2`. Ensure that both are on the same patch level. Note that `dot
Yep, should be .NET 8, thanks.

2024-09-13 15:39 UTC, vexx32 commented on src/components/docs/CentralManagementSecureConnectionStrings.mdx
> +    To accommodate this new default, the package installation will automatically add the `TrustServerCertificate=true` parameter to the connection string it constructs or receives if the initial conn
I'm not sure what this suggestion was supposed to be? I'm assuming we want to capitalise `True` here for consistency, though.

2024-09-13 16:03 UTC, pauby commented on src/components/docs/CentralManagementSecureConnectionStrings.mdx
> +    To accommodate this new default, the package installation will automatically add the `TrustServerCertificate=true` parameter to the connection string it constructs or receives if the initial conn
Yes. Either capitalise it or have it lower case. As long as we are consistent in the string and on the page.

2024-09-13 16:18 UTC, vexx32 commented
@pauby I believe I have addressed all the review comments here.

2024-09-13 20:08 UTC, vexx32 commented
I've also added a commit updating the CCM dependency version matrix on [this page](https://docs.chocolatey.org/en-us/central-management/) since Cory pointed out that we should probably get that up to date too.

It was also mentioned we _might_ want to strip that down to just the versions we actually support, as well? Not sure if we want to do that though, so I've left the older ones in for now.

2024-09-16 18:42 UTC, vexx32 commented
Per conversations with @gep13, I have added a small commit to bump the minimum required SQL Server version to 2016 as we now have that requirement to run CCM (and [2014 is out of support as of July this year](https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver16#lifecycle-dates)).

2024-09-16 19:47 UTC, pauby commented
> Per conversations with @gep13, I have added a small commit to bump the minimum required SQL Server version to 2016 as we now have that requirement to run CCM (and [2014 is out of support as of July this year](https://learn.microsoft.com/en-us/sql/sql-server/end-of-support/sql-server-end-of-support-overview?view=sql-server-ver16#lifecycle-dates)).

@gep13 can we ensure this is called out in the release notes?

2024-09-16 19:49 UTC, pauby commented on src/content/docs/en-us/central-management/setup/service.mdx
> +There is a known issue with the aspnetcoremodule-v2 installer that will uninstall the aspnetruntime on upgrade, which may be the root cause for this missing runtime. https://github.com/dotnetcore-cho
Did you verify this @vexx32 ?

2024-09-16 20:20 UTC, pauby requested changes

2024-09-16 21:06 UTC, vexx32 commented on src/content/docs/en-us/central-management/index.mdx
>  |0.8.0                        |0.13.0+         | 3.2.0+                      | 0.12.0+  |
Done, and 0.13.0 added. I remember adding that too, I'm not sure where that one went, sorry. It's there now, at any rate.

2024-09-16 21:24 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +There is a known issue with the aspnetcoremodule-v2 installer that will uninstall the aspnetruntime on upgrade, which may be the root cause for this missing runtime. https://github.com/dotnetcore-cho
I have not been able to reproduce the same issue we have seen in earlier versions. I am not sure if we want to conclusively say people cannot run into it under any circumstances but I am not seeing a way to reproduce the original issue that causes this anymore.

Installing the `dotnet-aspnetcoremodule-v2` package after the `dotnet-8.0-runtime` / `dotnet-8.0-aspnetruntime` packages does not remove the installed software from the system anymore, according to `dotnet --list-runtimes`, as it was previously.

2024-09-17 19:01 UTC, gep13 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +There is a known issue with the aspnetcoremodule-v2 installer that will uninstall the aspnetruntime on upgrade, which may be the root cause for this missing runtime. https://github.com/dotnetcore-cho
I believe that this was a bug in the underlying software installer that caused this problem to happen at the time.  If we can no longer reproduce it, then it could be that they fixed the problem in the underlying installer.

I would say that we are good to remove this.

2024-09-18 13:52 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +There is a known issue with the aspnetcoremodule-v2 installer that will uninstall the aspnetruntime on upgrade, which may be the root cause for this missing runtime. https://github.com/dotnetcore-cho
I have added a commit to remove this 👍

2024-09-19 15:01 UTC, corbob commented on src/content/docs/en-us/central-management/setup/database.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"
I really wish I could comment on the line I want to... The line above  indicates that the default is as of `0.6.2`... Should that be updated? Or perhaps just removed?

Perhaps someting like "The currently supported version of Chocolatey Central Management contains these defaults" 🤔

2024-09-19 15:21 UTC, corbob commented on src/content/docs/en-us/central-management/setup/service.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"
Same comment as above... A few lines ago we talk about version `0.6.2`, but this change makes that technically wrong.

2024-09-19 15:23 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/database.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"
I think taking out the version number makes sense here, yep.

2024-09-19 15:25 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/database.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"
Hmm. Actually, I'm not sure. I think a "since 0.13.0" might be an alright thing, since it will make it a little clearer for any folks who are insisting on remaining on an older version for whatever reason.

2024-09-19 15:27 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"
This one I'm less sure about. The particular change it's worried about is the `CertificateThumbprint` which _was_ added in 0.6.2.

I can add a note here that this reflects the defaults as of 0.13.0 or something, perhaps.

2024-09-19 15:31 UTC, vexx32 commented on src/content/docs/en-us/central-management/setup/service.mdx
> +    "Default": "Server=<HOST_NAME_OF_MACHINE_BEING_INSTALLED_ONTO>; Database=ChocolateyManagement; Trusted_Connection=True; TrustServerCertificate=True;"
Updated.

2024-09-19 16:52 UTC, st3phhays approved these changes
I'm approving this on the basis that we may need to do small fixups later. This PR has had quite a bit of review, so for now, I think this looks good.

2024-09-20 13:53 UTC, merged