(doc) Update cmdlet docs for ShouldProcess support
chocolatey/docs pull request #1086
Opened 2024-10-22 15:09 UTC by vexx32

## Description Of Changes

- Update cmdlet docs with ShouldProcess parameters where they're supported

## Motivation and Context
As we're adding this support into the CLI helper commands that have been rewritten, we need to update our documentation to reflect this as well.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

https://github.com/chocolatey/choco/pull/3532

2024-10-25 09:28 UTC, gep13 requested changes

2024-10-25 09:28 UTC, gep13 commented on src/content/docs/en-us/create/cmdlets/Install-ChocolateyPath.mdx
> +### -Confirm
Shouldn't this be documented _after_ the `WhatIf` parameter?  The reason that I am asking is that in the syntax at the start there is:

```
Install-ChocolateyPath [-Path] <String> [[-PathType] <EnvironmentVariableTarget>]
 [-IgnoredArguments <Object[]>] [-WhatIf] [-Confirm] [<CommonParameters>]
```

where the parameters are ordered `WhatIf` then `Confirm`, but here they are the other way round.

Related to this, `IgnoredArguments` is arguably not in the correct order either.

2024-10-25 09:28 UTC, gep13 commented on src/content/docs/en-us/create/cmdlets/Set-EnvironmentVariable.mdx
> +### -Confirm
Same question as above.

2024-10-25 09:28 UTC, gep13 commented on src/content/docs/en-us/create/cmdlets/Uninstall-ChocolateyPath.mdx
> +### -Confirm
Also here 😄

2024-10-25 09:28 UTC, gep13 commented on src/content/docs/en-us/create/cmdlets/Update-SessionEnvironment.mdx
> +### -Confirm
And then here as well 😸

2024-10-25 09:29 UTC, gep13 commented
Assuming that this goes out in the 2.4.0 release, we will need to remember to include this in the documentation that goes out at the same time.  If/when that decision is made, can you add this PR into a documentation milestone, so that it doesn't get lost?

2024-10-25 20:56 UTC, vexx32 commented on src/content/docs/en-us/create/cmdlets/Install-ChocolateyPath.mdx
> +### -Confirm
I don't think it's worth doing any manual work with the ordering that PlatyPS outputs here, because it's just more finagling to sort out every single time this file needs to be touched by PlatyPS. If the parameters are out of its standard ordering, it will move them every time the script is run... which just feels like it's not worth messing around with every time.

Until PlatyPS' output adjusts this ordering, I think it's better to leave it as is.

2024-11-12 14:32 UTC, gep13 commented on src/content/docs/en-us/create/cmdlets/Install-ChocolateyPath.mdx
> +### -Confirm
Sounds like a plan.

2024-11-12 14:33 UTC, gep13 approved these changes
LGTM!

2024-11-12 14:34 UTC, merged

2024-11-12 14:34 UTC, gep13 commented
@vexx32 thanks for getting this updated!