(docs) Update documentation for CPMR0067
chocolatey/docs pull request #1102
Opened 2024-11-28 09:49 UTC by AdmiringWorm

## Description Of Changes

This updates the documentation that is stubbed out for the Chocolatey
Community Package Validator rule CPMR0067, by including information
about the rule.

## Motivation and Context

To keep the rules we have documented.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2024-11-29 16:28 UTC, pauby requested changes
A couple of comments, questions and changes.

2024-11-29 16:28 UTC, pauby commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0067.mdx
> +In the nuspec, the tag `notSilent` has been specified, indicating that the package is not silent. Normally this means that a window will be shown with a progressbar, or automated using Autohotkey.
```suggestion
In the nuspec, the tag `notSilent` has been specified, indicating that the package is not silent, which means that there is some indication that an install, upgrade or uninstall is taking place such as a window bieng shown, a progress bar or something else that is visible. 
```

2024-11-29 16:28 UTC, pauby commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0067.mdx
> +In the nuspec, the tag `notSilent` has been specified, indicating that the package is not silent. Normally this means that a window will be shown with a progressbar, or automated using Autohotkey.
I didn't add in the part about Autohotkey as I wasn't sure it was relevant?

2024-11-29 16:28 UTC, pauby commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0067.mdx
> +The tag `notSilent` should only be used to indicate that the package is not silent.
```suggestion
The tag `notSilent` should only be used to indicate that the package is not silent, which means there is some indication that an install, upgrade or uninstall is taking place such as a window bieng shown, a progress bar or something else that is visible. 
```

2024-11-29 16:28 UTC, pauby commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0067.mdx
> +The tag `notSilent` should only be used to indicate that the package is not silent.
I just added the definition from above into this one so it's clear. Happy to have the definition changed, but I think we should have it in both places so we are clear and specific.

2024-12-05 10:20 UTC, AdmiringWorm commented
@pauby I have fixed up those items now, as well as rebased the PR against the latest commit on the master branch.

2024-12-11 12:55 UTC, pauby approved these changes

2024-12-11 12:55 UTC, merged