(docs) Add documentation for new rule CPMR0076
chocolatey/docs pull request #1107
Opened 2024-12-05 13:35 UTC by AdmiringWorm

## Description Of Changes

This adds the new rule for flagging Icon URLs that make use of GitHub or
RawGit URLs in the nuspec file.

This rule is not currently planned for Package Validator, but is useful
to have as it will be implemented in the Chocolatey Community Validator
extension.

## Motivation and Context

To document rules that are implemented in Chocolatey Community Validation extension, and considered for Package Validator.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

- https://github.com/chocolatey/home/issues/16
- https://github.com/chocolatey-community/chocolatey-community-validation/issues/28

2024-12-05 14:48 UTC, gep13 requested changes

2024-12-05 14:48 UTC, gep13 commented on src/components/docs/PackageValidatorNotImplemented.mdx
> +    Once it has been implemented in Packge Validator, the severity or behavior may be changed in the Chocolatey Community Validation extension.
```suggestion
    Once it has been implemented in Package Validator, the severity or behavior may be changed in the Chocolatey Community Validation extension.
```

2024-12-05 14:48 UTC, gep13 commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0076.mdx
> +description: Information on how to remediate the Chocloatey Package Moderation Rule 0076
```suggestion
description: Information on how to remediate the Chocolatey Package Moderation Rule 0076
```

2024-12-05 14:48 UTC, gep13 commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0076.mdx
> +There existis CDN providers for GitHub links that can be used, like [JSDelivr](https://www.jsdelivr.com/) and [Statically](https://statically.io/).
```suggestion
There are CDN providers for GitHub links that can be used, like [JSDelivr](https://www.jsdelivr.com/) and [Statically](https://statically.io/).
```

2024-12-05 14:48 UTC, gep13 commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0076.mdx
> +GitHub has expressed it being unwanted to hotlink to _raw_ files in the past as these are not static assets, and RawGit has shut down.
Also, do we have a link to where we can point people to for the information about GitHub?

2024-12-05 14:48 UTC, gep13 commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0076.mdx
> +There existis CDN providers for GitHub links that can be used, like [JSDelivr](https://www.jsdelivr.com/) and [Statically](https://statically.io/).
Also, should we link to the section of the docs where this is discussed in more depth?

2024-12-05 14:58 UTC, AdmiringWorm commented on src/content/docs/en-us/community-repository/moderation/package-validator/rules/cpmr0076.mdx
> +GitHub has expressed it being unwanted to hotlink to _raw_ files in the past as these are not static assets, and RawGit has shut down.
I have added a link to the blog post on GitHub regarding this that I am aware of.

2025-02-13 21:58 UTC, ferventcoder commented
So this one is just waiting on changes to be reviewed and then merged?

2025-02-14 11:31 UTC, pauby approved these changes

2025-02-14 11:32 UTC, merged