#124 Nexus Upgrade Documentation
chocolatey/docs pull request #125
Opened 2021-01-22 19:11 UTC by ryanrichter94

This PR adds documentation for upgrading Nexus inside a QDE instance. 

Fixes #124

2021-01-22 19:14 UTC, steviecoaster requested changes

2021-01-22 19:14 UTC, steviecoaster commented on input/en-us/quick-deployment/setup/upgrade-nexus-qde.md
> +xref: v2-client-setup
Not sure what we need to do here, but this _will_ need changes. Just not sure to _what_.

2021-01-22 20:50 UTC, gep13 commented
@ryanrichter94 @steviecoaster I have made a couple of minor corrections on this PR.

The main one (which was causing the build failure) was the updating of the xref.  This needs to be unique for each page.  This then allows Statiq to uniquely identify each page.

I also then updated the order to control "where" the page appears in the menu, and then updated the title to make it fit with the other pages in the section.

![image](https://user-images.githubusercontent.com/1271146/105544990-7aae8c80-5cf3-11eb-8bcb-57365d44d5a5.png)

Let me know if you have any questions.

2021-01-23 11:40 UTC, gep13 approved these changes
LGTM!

2021-01-23 11:46 UTC, merged

2021-01-23 11:47 UTC, gep13 commented
@ryanrichter94 thanks for getting this added!  Your changes should be live on the site shortly.