(#139) Provide FAQ for Autosync and software upgrades
chocolatey/docs pull request #140
Opened 2021-02-24 18:02 UTC by steviecoaster

This PR adds a FAQ which explains the challenges around tracking software upgrades outside of Chocolatey and why they are currently not supported by AutoSync.

2021-02-24 18:31 UTC, gep13 requested changes
Just a minor suggestion

2021-02-24 18:31 UTC, gep13 commented on input/en-us/features/package-synchronization/automatic-sync.md
> +Because an installer version doesn't have to match the software version (Google's msi is a great example), and the consistency issues with where the information can potentially come from Chocolatey c
```suggestion
Due to the fact that an installer version doesn't have to match the software version (Google's msi is a great example), and the consistency issues with where the information can potentially come from, Chocolatey cannot _reliably_ track application upgrades.
```

2021-02-25 18:35 UTC, steviecoaster commented on input/en-us/features/package-synchronization/automatic-sync.md
> +Because an installer version doesn't have to match the software version (Google's msi is a great example), and the consistency issues with where the information can potentially come from Chocolatey c
I've made these changes.

2021-02-26 10:37 UTC, gep13 approved these changes
LGTM!

2021-02-26 10:37 UTC, merged

2021-02-26 10:37 UTC, gep13 commented
@steviecoaster your changes have been merged, thanks for your contribution 👍