(#165) Begins to add release notes for QDE v3
chocolatey/docs pull request #166
Opened 2021-04-08 16:29 UTC by steviecoaster

We'll need to flesh out package versions and make sure thet able is accurate.
We'll also want to make sure all the notable changes have been added.

2021-04-08 17:21 UTC, vexx32 commented on input/en-us/quick-deployment/release-notes.md
> + Name                               | Version             |
I think we're missing a pipe symbol at the start of this table here.

2021-04-08 18:37 UTC, steviecoaster commented on input/en-us/quick-deployment/release-notes.md
> + Name                               | Version             |
Yeah, noticed that. It's fixed in the latest commit.

2021-04-08 18:55 UTC, gep13 commented on input/en-us/quick-deployment/release-notes.md
> +- Running `Set-QDEnvironment.psq` is now idempotent
Should this file name end with `ps1`?

2021-04-27 15:38 UTC, steviecoaster commented
This is no longer a draft PR. Once approved, this can merge!

@pauby

2021-04-27 15:50 UTC, gep13 requested changes
Couple minot changes, and then some questions.

2021-04-27 15:50 UTC, gep13 commented on input/en-us/quick-deployment/release-notes.md
> +### Enhancements
I think it makes sense to move this section above the table to package versions.

2021-04-27 15:50 UTC, gep13 commented on input/en-us/quick-deployment/release-notes.md
> +- Running `Set-QDEnvironment.ps1` is now idempotent
Were there any links to public issues for these that folks can get more information?

2021-04-27 15:50 UTC, gep13 commented on input/en-us/quick-deployment/release-notes.md
> +- Nexus no longer has a hard-coded wait value
Not sure how much detail we want to go into here, but this by itself doesn't provide much to go on

2021-04-28 13:22 UTC, steviecoaster commented on input/en-us/quick-deployment/release-notes.md
> +- Running `Set-QDEnvironment.ps1` is now idempotent
All the issues are in Gitlab, so not publicly available. @pauby, not sure if we want to put some public-facing ones somewhere we can link too?

2021-04-28 15:55 UTC, gep13 approved these changes
LGTM!

2021-04-28 15:56 UTC, merged

2021-04-28 16:19 UTC, gep13 commented
@steviecoaster thanks for getting this added!

2021-04-30 00:24 UTC, Paul199888 reviewed
""