(#170) Mention ChocolateyPackageInstallLocation as a env variable
chocolatey/docs pull request #171
Opened 2021-04-20 03:35 UTC by TheCakeIsNaOH

Fixes #170 

If there is a better location than the FAQ, I'm happy to move this.

2021-04-21 18:57 UTC, steviecoaster requested changes

2021-04-21 18:57 UTC, steviecoaster commented on input/en-us/faqs.md
> +For packages that run installers, this can be be caused by installer for the software not setting it's install location.
```suggestion
For packages that run installers, this can be be caused by the installer not setting its install location.
```

2021-04-21 18:57 UTC, steviecoaster commented on input/en-us/faqs.md
> +The problem is that if this is hard coded for a package that runs an installer, it will display an incorrect location if the install location is changed manually by install arguments or via the licen
```suggestion
If this is hard coded for a package that runs an installer, it may display an incorrect location if the install location is changed manually, by install arguments, or via the licensed ubiquitous install directory switch.
```

2021-04-21 18:58 UTC, steviecoaster commented
@TheCakeIsNaOH left a couple of quick change suggestions for you.

2021-04-21 19:01 UTC, TheCakeIsNaOH commented
Thanks for the suggestions, I've added them.

2021-04-22 12:07 UTC, steviecoaster approved these changes
LGTM! Thanks for your contribution!

2021-04-22 19:56 UTC, merged

2021-04-22 19:56 UTC, gep13 commented
@TheCakeIsNaOH thanks for getting this added!