(#176) Add hardened endpoint install details
chocolatey/docs pull request #177
Opened 2021-05-04 16:40 UTC by steviecoaster

This commit clearly documents the TLS ciphers and registry keys that need to be applied to a system that is hardened for TLS1.2
in order for the ClientSetup.ps1 script that ships with QDE to be applied successfully on the hardened system

2021-05-04 18:38 UTC, gep13 requested changes

2021-05-04 18:38 UTC, gep13 commented on input/en-us/quick-deployment/setup/index.md
> +> Upon first booting the environment in ESXi 6.7 the mouse will not be available to the VM when using the HTML modal console control. You will need to use rather RDP or VMRC (VMWare Remote Console) t
This seems like an unrelated change. Should this be reverted?

2021-05-04 18:58 UTC, vexx32 commented on input/en-us/quick-deployment/setup/index.md
> +      "SchUseStrongCrypto" = dword:00000001
This probably isn't going to render well in the final page, it seems like it'll get all strewn together and isn't very easy to read. I'd suggest formatting it as a list with headings;
```suggestion
**[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v2.0.50727]**

- _SystemDefaultTlsVersions_ = `dword:00000001`
- _SchUseStrongCrypto_ = `dword:00000001`

**[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]**

- _SystemDefaultTlsVersions_ = `dword:00000001`
- _SchUseStrongCrypto_ = `dword:00000001`
```

2021-05-05 13:29 UTC, steviecoaster commented on input/en-us/quick-deployment/setup/index.md
> +> Upon first booting the environment in ESXi 6.7 the mouse will not be available to the VM when using the HTML modal console control. You will need to use rather RDP or VMRC (VMWare Remote Console) t
I'm...not sure where this is coming from? It's not showing up in my diff locally!

2021-05-05 13:33 UTC, steviecoaster commented on input/en-us/quick-deployment/setup/index.md
> +> Upon first booting the environment in ESXi 6.7 the mouse will not be available to the VM when using the HTML modal console control. You will need to use rather RDP or VMRC (VMWare Remote Console) t
Nvm. Found it.

2021-05-05 13:33 UTC, steviecoaster commented on input/en-us/quick-deployment/setup/index.md
> +      "SchUseStrongCrypto" = dword:00000001
Aye, Looked fine in VSCode preview, not so great in the local build. Added this suggestion.

2021-05-05 13:34 UTC, steviecoaster commented
@gep13 @vexx32 once you are in a position to do so, I've made your requested changes for review.

2021-05-05 13:42 UTC, gep13 commented on input/en-us/quick-deployment/setup/index.md
> -> Once VMWare Tools is installed, the mouse and other advanced VM functionality will be made available to the VM.
@steviecoaster is there a reason that this line is being removed?

2021-05-06 16:37 UTC, steviecoaster commented on input/en-us/quick-deployment/setup/index.md
> -> Once VMWare Tools is installed, the mouse and other advanced VM functionality will be made available to the VM.
None other than me being a dolt :) I put it back.

2021-05-06 17:16 UTC, vexx32 submitted a review, later dismissed
Other than one minor nit, this looks good. 🙂

2021-05-06 17:16 UTC, vexx32 commented on input/en-us/quick-deployment/setup/index.md
> +### What are the requirements for installing Chocolatey on a TLS1.2 hardened endpoint using ClientSetup.ps1 script
FAQ question should end in a question mark, to be consistent with the rest here.

2021-05-07 06:45 UTC, gep13 approved these changes
LGTM!

2021-05-07 06:45 UTC, gep13 commented
This looks good to me:

![image](https://user-images.githubusercontent.com/1271146/117408677-2dec6b80-af08-11eb-9d91-8b9a4b3c6c97.png)

**NOTE** I added in the `?` after taking the screenshot.

@steviecoaster I took the liberty of rebasing the commits down to a single commit.

2021-05-07 06:51 UTC, merged