Add bug & workaround description for choco install
chocolatey/docs pull request #185
Opened 2021-06-03 09:46 UTC by StefanoFrazzetto

Resolves #184
Original issue chocolatey/choco#877

2021-06-03 18:24 UTC, gep13 requested changes
Just one minor suggestion...

2021-06-03 18:24 UTC, gep13 commented on input/en-us/choco/commands/install.md
> +Note: due to a bug, Chocolatey doesn't currently support `windowsfeatures` as a source
This looks like a great addition, just one minor suggestion...

Can you add the following to the start of the note:

```
> :memo: **NOTE**
```

Similar to what is done here:

https://raw.githubusercontent.com/chocolatey/docs/78722c517718b073b18eba30f44370e27c85bc19/input/en-us/community-repository/moderation/package-verifier.md

This will style the note so that it stands out on the page.

2021-06-04 07:57 UTC, StefanoFrazzetto commented on input/en-us/choco/commands/install.md
> +Note: due to a bug, Chocolatey doesn't currently support `windowsfeatures` as a source
Good catch, I hadn't noticed that!

2021-06-05 08:07 UTC, gep13 approved these changes
LGTM!

2021-06-05 15:44 UTC, merged

2021-06-05 15:44 UTC, gep13 commented
@StefanoFrazzetto thanks again for getting this added!