Added "Recommended package parameters" page
chocolatey/docs pull request #203
Opened 2021-07-02 20:28 UTC by KerJoe

#198

2021-08-03 09:19 UTC, gep13 commented
@pauby you in a position to take a look at this, based on the discussion that you were having with @KerJoe on this, and previous discussions. Thanks

2021-10-02 14:38 UTC, pauby requested changes
@gep13 @AdmiringWorm Could you review this PR?

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/InstallDir:` - Changes package's installation directory.
```suggestion
* `/InstallDir:` - Changes package's installation directory. Note that this can also be done using the `--install-arguments` switch if the installer supports it.

```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoDesktopShortcut` and `/DesktopShortcut` - Explicitly set whether the package should or should not create a shortcut on desktop, if not specified the installers default parameter is used.
```suggestion
* `/NoDesktopShortcut` and `/DesktopShortcut` - Explicitly set whether the package should or should not create a shortcut on desktop. If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoStartMenuShortcut` and `/StartMenuShortcut` - Explicitly set whether the package should or should not create an entry in start menu.
```suggestion
* `/NoStartMenuShortcut` and `/StartMenuShortcut` - Explicitly set whether the package should or should not create an entry in start menu. If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoStartup` and `/Startup` - Explicitly set whether the packaged application should or should not launch on start up(Applicable to installers that already can startup by default).
```suggestion
* `/NoStartup` and `/Startup` - Explicitly set whether the packaged application should or should not launch on startup, if applicable. If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoQuickLaunchShortcut` and `/QuickLaunchShortcut` - Explicitly set whether the package should or should not create a shortcut in quick launch menu.
```suggestion
* `/NoQuickLaunchShortcut` and `/QuickLaunchShortcut` - Explicitly set whether the package should or should not create a shortcut in quick launch menu. If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoFileAssociation` and `/FileAssociation` - Whether to associate files with this application.
```suggestion
* `/NoFileAssociation` and `/FileAssociation` - Whether to associate files with this application. If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoShellIntegration:` and `/ShellIntegration:` - Explicitly set whether the package should or should not add itself into explorer's context menu
```suggestion
* `/NoShellIntegration:` and `/ShellIntegration:` - Explicitly set whether the package should or should not add itself into explorer's context menu. If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoAppendPath` and `/AppendPath` - Add program folder directory to environment variable "PATH"
```suggestion
* `/NoAppendPath` and `/AppendPath` - Add program folder directory to environment variable "PATH". If not specified, the installer default behaviour will apply.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/Components:` - override default installation components (every optional component is turned off, and allowed selectively), e.g.: `/Components:Include_pip,CompileAll`. Package maintainer must ment
@gep13 @AdmiringWorm This is a follow-on from the comments I made above.

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/Language:` - Specifies the language to use in the form of Language code (ISO 639-1), Hyphen (-) and Country code (ISO 3166-1 alpha-2), e.g.: en-US, en-UK
Some software will not use the language / country code format. Maintainers may therefore feel they can't use this parameter. I'd amend this to ensure that it uses the language codes that are used by the installer so that they don't feel they have to convert from what is above to what the installer uses.

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/Username:` and `/Password:` - Parameters to allow login into the remote download server for the package or the program, it should be allowed for the password to be read from the prompt.
I think these parameters should be a bit more loose in their definition. What if it's a username and password to set for the application to open. Or something else?

What should happen here if the user does not input the information at the prompt / it times out?

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/InstallDir:` - Where to install the binaries to, Default: `$env:ProgramFiles\GreatInnoProgram`
```suggestion
 * `/InstallDir:` - Where to install the binaries to. Default is `$env:ProgramFiles\GreatInnoProgram`. Example `/InstallDir:C:\Tools\MyProgram`.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/Components:` - Configure what additional components to install, Possible values: `docs`, `examples`, `sources`, Default: `/Components:docs,examples`
@gep13 @AdmiringWorm Follow-on from the above again.

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/NoStartMenuShortcut:` and `/StartMenuShortcut:` - Whether to add an entry into the "All Programs" folder, Default: Yes
```suggestion
 * `/NoStartMenuShortcut` and `/StartMenuShortcut` - Whether or not to add an entry into the "All Programs" folder.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/NoDesktopShortcut` and `/DesktopShortcut` - Whether to add a shortcut on desktop, Default: No
```suggestion
 * `/NoDesktopShortcut` and `/DesktopShortcut` - Whether or not to add a shortcut on desktop.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/NoFileAssociation` and `/FileAssociation` - Whether to associate applicable files with this program, Default: No
```suggestion
 * `/NoFileAssociation` and `/FileAssociation` - Whether or not to associate applicable files with the installed software.
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/NoAppendPath` and `/AppendPath` - Whether to add this programm's folder to 'PATH' environmental variable, Default: Yes
```suggestion
 * `/NoAppendPath` and `/AppendPath` - Whether or not to add this software install folder to 'PATH' environmental variable. 
```

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/NoShellIntegration` and `/ShellIntegration` - Whether the package should or should not add itself into explorer's context menu, Subparameters: `addcontextmenufiles` - add to file' context menu,
@gep13 @AdmiringWorm ... you know the drill 😄

2021-10-02 14:38 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +To have choco remember parameters on upgrade, be sure to set `choco feature enable -n=useRememberedArgumentsForUpgrades`.
```suggestion
To remember the parameters you have set when you upgrade a package, set `choco feature enable -n=useRememberedArgumentsForUpgrades`.
```

2021-10-04 08:16 UTC, AdmiringWorm commented on input/en-us/create/recommended-package-parameters.md
> +* Actions expanding on exsting parameter behaviour should create subparameters, not create new ones (e.g. `/DesktopShortcut:Component1Shortcut,Component2Shortcut`, not `/DesktopShortcutComponent1 /De
I agree. Having an explicit parameter for each component feels like it would be much clearer for the user, instead of a single parameter accepting each component.

My thoughts are that arguments like `/NoDesktopShortcut`, `/DesktopShortcut` (and other similar parameters) should disable/enable for all components while if there is a need to only make the change for certain components those are better specified as separate parameters.

2021-10-04 08:24 UTC, AdmiringWorm commented on input/en-us/create/recommended-package-parameters.md
> +~~~powershell
@pauby should this example be noted to be very specific about Inno Setup installers?

If someone tried to use the same example for other technologies it would not work.

2021-11-01 17:55 UTC, KerJoe commented on input/en-us/create/recommended-package-parameters.md
> +* `/InstallDir:` - Changes package's installation directory.
I don't think `--install-arguments ` should be mentioned here, as the `/InstallDir` package parameter should replace the installer dependant arguments in the first place.

2021-11-01 17:58 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/InstallDir:` - Changes package's installation directory.
I disagree. I think `/InstallDir` would really be for when you have to do some magic inside the package to override  the installation directory, or the installer uses a parameter to indicate the install directory that `--install-arguments` doesn't know about / understand.

2021-11-01 18:32 UTC, KerJoe commented on input/en-us/create/recommended-package-parameters.md
> +* `/NoShellIntegration:` and `/ShellIntegration:` - Explicitly set whether the package should or should not add itself into explorer's context menu
```suggestion
* `/NoShellIntegration` and `/ShellIntegration` - Explicitly set whether the package should or should not add itself into explorer's context menu
```
Colon removed, as /ShellIntegration is a boolen.

2021-11-01 18:35 UTC, KerJoe commented on input/en-us/create/recommended-package-parameters.md
> +* Actions expanding on exsting parameter behaviour should create subparameters, not create new ones (e.g. `/DesktopShortcut:Component1Shortcut,Component2Shortcut`, not `/DesktopShortcutComponent1 /De
```suggestion
* In cases where there are multiple binary actions of the same type (like multiple components, desktop shortcuts) there should be a single main action (e.g. /NoDesktopShortcut), which when passed will enable/disable every subactions, and all the subactions, created using the component name preceded by the main action (Subactions: `/NoDesktopShortcutComponent1`, `/DesktopShortcutComponent2`,)
```

2021-11-01 19:15 UTC, KerJoe commented on input/en-us/create/recommended-package-parameters.md
> +* `/InstallDir:` - Changes package's installation directory.
Using --install-arguments would defeat the purpose of creating standardized package parameters. Because --install-arguments pass parameters directly to the setup program, the user must check what particular installer the packages uses (to specify the correct arguments). Package parameters instead provide a installer agnostic way of specifying options.

2021-11-03 18:35 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/Language:` - Specifies the language to use in the form of Language code (ISO 639-1), Hyphen (-) and Country code (ISO 3166-1 alpha-2), e.g.: en-US, en-UK
That's a fair point. But I think you have to balance it with what is convenient for the maintainer too.

If we have a whole bunch of package parameters that are a pain for the maintainer to implement, they simply won't implement them, (as a maintainer, I wouldn't) and that is a detriment to the user. Remember, the package parameters on this page are _suggestions_. Lowering the friction to using them is a goal for both users and maintainers.

So if we leave it for the maintainer to decide, then the users only has to read the package description where the package parameters are described. The users will have to do that anyway to know what package parameters are available for them to use. So, it's not additional work.

2021-11-03 18:39 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/InstallDir:` - Changes package's installation directory.
I feel we are going off track here. Remember, the goal of this page is to help the user by providing a set of _suggested_ package parameters that a maintainer could use. What I'm suggesting we do is tell the user another way to do the thing that the `/InstallDir` package parameter does. We're not forcing the user to check anything. We're giving them options. I think that's reasonable.

`--install-arguments` is a feature of Chocolatey that has been around for some time. The impression I am getting is that you feel `/InstallDir` would replace that, or should be used instead of that. Just to be clear, that's not the direction we want to go in here.

2021-11-11 19:33 UTC, pauby requested changes

2021-11-11 19:33 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* Actions expanding on exsting parameter behaviour should create subparameters, not create new ones (e.g. `/DesktopShortcut:Component1Shortcut,Component2Shortcut`, not `/DesktopShortcutComponent1 /De
Can you rewrite the above as it's very confusing. It's needs to be clear and simple or people will not follow it.

2021-11-11 19:33 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> +* `/Components:` - override default installation components (every optional component is turned off, and allowed selectively), e.g.: `/Components:Include_pip,CompileAll`. Package maintainer must ment
Can this be rewritten in the same way as [this one](https://github.com/chocolatey/docs/pull/203/files#r740441142).

2021-11-11 19:33 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/Components:` - Configure what additional components to install, Possible values: `docs`, `examples`, `sources`, Default: `/Components:docs,examples`
Again, same as [above](https://github.com/chocolatey/docs/pull/203/files#r740441142).

2021-11-11 19:33 UTC, pauby commented on input/en-us/create/recommended-package-parameters.md
> + * `/NoShellIntegration` and `/ShellIntegration` - Whether the package should or should not add itself into explorer's context menu, Subparameters: `addcontextmenufiles` - add to file' context menu,
Again, same as [above](https://github.com/chocolatey/docs/pull/203/files#r740441142).

2021-11-23 18:00 UTC, pauby commented
@KerJoe Are you able to respond to the questions and update this?

2021-11-25 13:57 UTC, pauby commented
@KerJoe Unfortunately some of the review changes I'd asked for have not been made. Some of those changes have been marked as resolved when they have not been. I didn't perform the full review of the changes once I'd noticed the changes hadn't been made so I'm not able to give you a list.

Can I ask you to go back through the changes requested to ensure they have been made? I'm happy to discuss any changes requested.

2021-12-23 10:49 UTC, pauby commented
There hasn't been any update on this for almost a month now so I'm going to go ahead and close it.

Thanks for your effort here @KerJoe. It is appreciated.

2021-12-23 10:49 UTC, closed without merging