Adds QDE in Azure
chocolatey/docs pull request #205
Opened 2021-07-13 11:52 UTC by JPRuskin

Adds basic documentation for QDE in Azure.

Shouldn't be merged until we're ready to announce.

There are some spots that will be updated as part of upcoming cards - I will tag these.

2021-07-13 11:54 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +Find the Chocolatey Software QDE resource, and click `Create`. You will be taken to the `Create a [TODO]` page.
I don't yet know what this label will say. We will find out as part of GitLab issue 11, 'Create an Offer'.

2021-07-13 11:54 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +| None    | -                                                                 |
This table will be updated as part of card 19, 'Add Internalised Package Defaults'.

2021-07-13 11:54 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +```
I can remove this if it's inappropriate.

2021-07-13 11:54 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +```
Equally, this is unlikely to happen so should we just remove it?

2021-07-13 14:43 UTC, gep13 requested changes

2021-07-13 14:43 UTC, gep13 commented on input/en-us/quick-deployment/azure/index.md
> +RedirectFrom: docs/quick-deployment-environment-in-azure
This is a completely new page, that hasn't existed in the docs before, right? If so, we don't need a RedirectFrom line here.

2021-07-13 14:43 UTC, gep13 commented on input/en-us/quick-deployment/azure/index.md
> +Order: 10
With a value of 10 here, it means that a new menu item for QDE in Azure will appear before the other entries, as per this screenshot:

![2021-07-13_15-39-34](https://user-images.githubusercontent.com/1271146/125471928-ccadec64-2cee-4278-be87-173e21190fff.png)

Is this what is wanted?

2021-07-13 14:48 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +Order: 10
My apologies, I thought the hierarchy was at a folder level so it would only apply to the quick-deployment/azure items. I'll change it.

2021-07-19 08:01 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +Order: 10
Ah, I hadn't clocked that the _Index_ order affects the folder. Gotcha! Sorry for my missing it.

2021-07-27 17:53 UTC, adilio commented on input/en-us/quick-deployment/azure/index.md
> +```
There's a standard section format that @ferventcoder uses in docs for "`Common Errors and Resolutions`".

Example here: https://docs.chocolatey.org/en-us/central-management/setup/database#common-errors-and-resolutions

I suggest we follow the same format?

2021-07-28 03:02 UTC, ryanrichter94 requested changes
Found one little thing. May be my mis-understanding how this works.

2021-07-28 03:02 UTC, ryanrichter94 commented on input/en-us/quick-deployment/azure/packages.md
> +You can remove any of these packages from your repository without using them by signing in to Nexus, browsing to the `ChocolateyTest` repository, and deleting the package.
Are these packages not in the ChocolateyTest & ChocolateyInternal Repo? Thinking you would want to delete them out of both repos. This is from me assuming this works in the same fashion as current QDE.

2021-07-28 08:06 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/packages.md
> +You can remove any of these packages from your repository without using them by signing in to Nexus, browsing to the `ChocolateyTest` repository, and deleting the package.
Ah, absolutely! For some reason, I think when I wrote the first attempt at this, I had it in mind that I hadn't figured out how packages were promoted - but at this point, I think they get promoted pretty instantly, and with no actual test. I'll adjust this.

2021-07-28 09:40 UTC, Windos commented on input/en-us/quick-deployment/azure/index.md
> +You can either purge the KeyVault in the GUI, or use the PowerShell Az modules as follows:
My only feedback is: what's the ~~GUI~~ Portal process?

2021-07-28 09:41 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +You can either purge the KeyVault in the GUI, or use the PowerShell Az modules as follows:
Fair. One minute, please!

2021-07-28 10:17 UTC, Windos submitted a review, later dismissed
I'm sure I'm not looking for the same thing as others, but looks good (and factually correct to boot!)

2021-07-28 12:18 UTC, steviecoaster submitted a review, later dismissed
Approving, with one small nit. Great work.

2021-07-28 12:18 UTC, steviecoaster commented on input/en-us/quick-deployment/azure/index.md
> +* A valid certificate for your chosen FQDN, in PFX format, with exported private key
```suggestion
* A valid certificate for your chosen FQDN, in PFX format, with exportable private key
```

2021-07-29 11:07 UTC, pauby requested changes
A few changes I think.

One thing I did notice is that a lot of the text is separated by blank lines. I'm wondering why that is and why we're not just writing one paragraph but multiple paragraphs that are related?

2021-07-29 11:07 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +You can remove any of these packages from your repository without using them by signing in to Nexus, browsing to the `ChocolateyTest` and `ChocolateyInternal` repositories, and deleting the package f
'... by logging into Nexus ...'?

2021-07-29 11:07 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +> You can find packages in the [Chocolatey Community Repository](https://community.chocolatey.org/packages). Despite the best efforts of community moderators, you should review packages before intern
'You can find packages in the [Chocolatey Community Repository](https://community.chocolatey.org/packages). Despite the best efforts of community moderators, you should review packages before internalizing and deploying them.'

to:

'We recommend you review and test all packages before internalizing and deploying packages from the [Chocolatey Community Repository](https://community.chocolatey.org/packages).'

?

2021-07-29 11:07 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +The specified packages will then be downloaded and pushed to your Nexus repository, ready for use.
Which Nexus repository - there are two?

2021-07-29 11:07 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log in to the Jenkins instance at `https://{{FQDN}}/jenkins`, and click the Build icon next to the `Internalize packages from the Community Repository` job. This will take you to a screen w
* Same comment I made above about squirly brackets?
* Can we also remove the word 'instance'?
* Above we used 'Package IDs' rather than 'Package Ids'
* We have 'Build' and then we use `Build` later. Can we have both of them as `Build` (ie. with backticks)?

2021-07-29 12:28 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +You can now view and access the Secrets in this KeyVault.
In this case, I was copying the way the Portal refers to them, though  it's probably more valid to just refer to them as "secrets" in general rather than Azure KeyVault Secrets (not-TM)

![SecretsView](https://github.com/chocolatey/docs/blob/4bfd76896a438d2fce0a8891c812eedf1d3cd64b/input/assets/images/quickdeployazure/KeyVault-Secrets.png)

2021-07-30 16:51 UTC, pauby requested changes

2021-07-30 16:51 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +For portions of this document using PowerShell, we assume you have installed a recent version of the [Az modules](https://www.powershellgallery.com/packages/Az/) (easily available by running `choco i
```suggestion
For portions of this document using PowerShell, we assume you have installed a recent version of the [Az modules](https://www.powershellgallery.com/packages/Az/) (easily available by running `choco install az.powershell` in an elevated prompt), and have logged in to your account using `Connect-AzAccount`. You can also set a variable, `$ResourceGroupName`, to the name of the resource group you deployed QDE to as we will use this with the PowerShell code snippets below.
```

2021-07-30 16:51 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +Select the subscription, resource group, and region you intend to deploy to. As you currently need to deploy this to a resource group with no resources in, you may need to create a new resource group
```suggestion
Select the subscription, resource group, and region you intend to deploy to. As you need to deploy this to an empty resource group, you may need to create a new one by clicking the `Create new` button below the selector.
```

2021-07-30 16:51 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +You can remove any of these packages from your repository without using them by logging in to Nexus, browsing to the `ChocolateyTest` and `ChocolateyInternal` repositories, and deleting the package f
```suggestion
You can remove any of these packages from your repository without using them by logging into Nexus, browsing to the `ChocolateyTest` and `ChocolateyInternal` repositories, and deleting the package from each.
```

2021-07-30 16:51 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +> We recommend you review and test all packages before internalizing and deploying packages from the [Chocolatey Community Repository](https://community.chocolatey.org/packages).
```suggestion
> We recommend you review and test all packages before internalizing and deploying them from the [Chocolatey Community Repository](https://community.chocolatey.org/packages).
```

2021-07-30 16:51 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log in to Jenkins at `https://\<FQDN\>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to
```suggestion
To do so, log into Jenkins at `https://\<FQDN\>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to a screen where you can add Package IDs (as above) to the `P_PKG_LIST` parameter, before clicking `Build`.
```

2021-07-30 16:51 UTC, pauby commented on preview.ps1
> -dotnet tool restore
Is this file meant to be here?

2021-07-30 16:58 UTC, JPRuskin commented on preview.ps1
> -dotnet tool restore
Yes/no. It was something raised when discussing it with Gary, it's in a separate commit and I'll happily pull it out into another branch/PR, but it was intentional and I do intend to submit it, one way or t'other.

2021-07-30 16:59 UTC, pauby requested changes

2021-07-30 16:59 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +Please refer to [SMTP Configuration](xref:ccm-website#step-4.2-smtp-configuration) before creating any users in CCM.
```suggestion
You cannot create users in CCM until you have configured an SMTP server. To do this, please see [how to configure SMTP in CCM ](xref:ccm-website#step-4.2-smtp-configuration).
```

2021-07-30 16:59 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +Please refer to [SMTP Configuration](xref:ccm-website#step-4.2-smtp-configuration) before creating any users in CCM.
Can we also add this as a warning?

2021-07-30 17:18 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +You cannot create users in CCM until you have configured an SMTP server. To do this, please see [how to configure SMTP in CCM](xref:ccm-website#step-4.2-smtp-configuration).
```suggestion
You will now be able to log in to CCM using the credentials provided in the KeyVault (see [Accessing Services](#accessing-services), below).

You cannot create users in CCM until you have configured an SMTP server. To do this, please see [how to configure SMTP in CCM](xref:ccm-website#step-4.2-smtp-configuration).
```

2021-07-30 17:18 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +You cannot create users in CCM until you have configured an SMTP server. To do this, please see [how to configure SMTP in CCM](xref:ccm-website#step-4.2-smtp-configuration).
@JPRuskin Can we also add this as a warning?

2021-08-05 11:14 UTC, pauby commented
This now looks good to me. Lets wait until we are ready and then push it.

2021-08-06 11:20 UTC, pauby approved these changes

2021-08-06 11:21 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +You can remove any of these packages from your repository without using them by signing in to Nexus, browsing to the `ChocolateyTest` repository, and deleting the package.
As this has been resolved I'll go ahead and dismiss the review asking for changes, and merge it.

2021-08-06 12:45 UTC, gep13 commented
@JPRuskin should we use QDE here, rather than Quick Deployment Environment?

![2021-08-06_13-44-55](https://user-images.githubusercontent.com/1271146/128512339-9ca6de10-9a11-47fb-8900-91086135bdd0.png)

2021-08-06 12:46 UTC, gep13 commented
Image alignments are a bit "wonky" for me:

![2021-08-06_13-46-21](https://user-images.githubusercontent.com/1271146/128512477-99d0cafb-4ec9-43be-8585-f0be4dbf1965.png)

2021-08-06 18:22 UTC, pauby approved these changes

2021-08-06 18:22 UTC, merged