(doc) Basic Intune documentation
chocolatey/docs pull request #215
Opened 2021-08-03 09:28 UTC by AdmiringWorm

This is the start of implementing new documentation for the Intune
functionality that will be available as a preview for Chocolatey
Licensed v3.0.0.

2021-08-03 18:53 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +   - Remove everything in the `Notes` section of the package (*This will cause the package note to be picked up by `choco push`*).
It seems the portal doesn't allow you to blank out the notes field. You have to leave a non-whitespace character in there.

2021-08-04 02:20 UTC, corbob commented on input/en-us/licensed-extension/intune/convert.md
> +> This warning can be safely ignored, if these two packages has already been uploaded to your Intune tenant.
```suggestion
> This warning can be safely ignored, if these two packages have already been uploaded to your Intune tenant.
```

I'm not sure if this reads better this way or the other way.

```suggestion
> If these two packages have already been uploaded to your Intune tenant, this warning can be safely ignored.
```

2021-08-04 02:32 UTC, corbob requested changes
Just a few grammar/spelling suggestions. As well as the previously added comments regarding some of the Intune stuff.

2021-08-04 02:32 UTC, corbob commented on input/en-us/licensed-extension/intune/convert.md
> +This feature can be easily enabled by running
```suggestion
This feature can be enabled by running
```

IMHO we don't need to quantify if this is "easy" or not.

2021-08-04 02:32 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +
Should this have the same note about needing a business or trial license?

2021-08-04 02:32 UTC, corbob commented on input/en-us/licensed-extension/intune/configuration.md
> +This document contain information about the configuration values available through the use of
```suggestion
This document contains information about the configuration values available through the use of
```

2021-08-04 02:32 UTC, corbob commented on input/en-us/licensed-extension/intune/configuration.md
> +There are several new configuration values that can be set/updates for the new Intune functionality.
```suggestion
There are several new configuration values that can be set/updated for the new Intune functionality.
```

2021-08-04 02:32 UTC, corbob commented on input/en-us/licensed-extension/intune/configuration.md
> +- `intuneUploadChunkSizeInMegabytes` - THe size of the file, in megabyes, below which Chocolatey will split the upload ito multiple chunks. Above this size, Chocolatey will make a best efforts to spl
```suggestion
- `intuneUploadChunkSizeInMegabytes` - The size of the file, in megabytes, below which Chocolatey will split the upload into multiple chunks. Above this size, Chocolatey will make a best efforts to split the upload into logical chunk sizes (_Defaults to 10 Megabytes_).
```

2021-08-04 08:28 UTC, AdmiringWorm commented on input/en-us/licensed-extension/intune/push.md
> +   - Remove everything in the `Notes` section of the package (*This will cause the package note to be picked up by `choco push`*).
Good point, I forgot that you had mentioned that previously

2021-08-04 09:39 UTC, AdmiringWorm commented
@corbob I have fixed a few mistakes and rewrote parts of the docs.

Not completely sure I managed to hit all of your points, but I believe so.

2021-08-05 18:00 UTC, pauby requested changes
A lot of the text is only single lines that are not joined. Is something chopping the lines at a particular length? So you've got:

```
This
is
Some text
```

Rather than

```
This is some text
```

2021-08-06 01:33 UTC, corbob commented on input/en-us/licensed-extension/intune/configuration.md
> +- `intuneUploadTimeoutInSeconds` - The amount of time, in seconds, that Chocolatey should wait for completion while uploading files to Intune (_Defaults to 600 seconds_).
Initially it was 18000 milliseconds. Rob suggested 600 seconds (10 minutes) being more reasonable as not everyone has super fast internet.

2021-08-06 01:46 UTC, corbob commented on input/shared/intune-note.txt
> +> The Intune solution is planned to be released with the v3.0.0 release of the Chocolatey licensed extension and has not been made available.
I am so glad I looked at how to do the snippets here. This is exactly why! Changing it in one place will change it in all the places 😀

2021-08-06 02:02 UTC, corbob commented on input/en-us/licensed-extension/intune/convert.md
> +> the created Intune package, instead of the original version criteria specified.
I think they say the same thing, but the punctuation is tripping me up a little bit. It looks like a run on sentence. I'm not seeing an obvious way to split it or reduce it without removing key information. Before taking in this suggestion I'd like to see if anyone else has other suggestions to clean it up.

2021-08-06 13:17 UTC, AdmiringWorm commented on input/en-us/licensed-extension/intune/configuration.md
> +and the source argument is in the format of `<CLIENT ID>:<CLIENT SECRET>`, which is separated by a colon.
Since it is markdown, and Statiq follows the specs it doesn't really matter if the sentence is broken over multiple lines or on the same line.
With the same spec, I mean that the documentation uses soft breaklines which causes everything to be displayed on the website as a single line nonetheless (as long as it isn't broken up into different paragraphs).

I can of course update to have everything on a single line, but there really is no need in the case of how it will be displayed on the Website.
![image](https://user-images.githubusercontent.com/1474648/128516094-cd0c2709-53d2-454b-80ab-211c57ade7db.png)

2021-08-13 18:44 UTC, pauby requested changes

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +3. The original identifier for the Chocolatey package must have been `chocolatey-license`.
```suggestion
1. If there is no `chocolatey-license` package on the Intune tenant, ensure you push this package to Intune first. Otherwise, a new `chocolatey-license` package will be generated and will replace the custom one in your local directory.
1. The Chocolatey package ID must be `chocolatey-license`.
1. It must have been converted to a Chocolatey Intune package by calling `choco convert`.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +3. The original identifier for the Chocolatey package must have been `chocolatey-license`.
I'm not sure I entirely understand what point 1 is trying to say so please review what I said and amend if needed.

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +### I have a new license and want to update the license on Intune. How can I do this?
```suggestion
### How can I update my license in the Intune tenant when I have a new Chocolatey for Business license?
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +Currently, updates are not supported for Intune packages, and doing so is a manual or semi-manual process.
```suggestion
Updates to Intune packages through Chocolatey is not currently supported. There is a manual process that you can follow to do this within Intune:
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +   - Navigate once again to the Intune tenant, and update the dependencies for `Chocolatey Licensed Extension` to point to the new package (*remember to remove the dependence on the old package*).
```suggestion
1. Ensure the local computer that you will run the Chocolatey commands on has the new license applied to it.
1. Login to the Intune tenant and locate the `Chocolatey License` package.
1. Replace `Notes` section of the Intune package with a non-whitespace character (for example, the letter A). This will cause the Intune package not to be found by Chocolatey in the next step.
 1. Push a package to Intune as you would normally do. This will result in Chocolatey not finding a `chocolatey-license` package within the Intune tenant, and therefore automatically generating a new one using the Chocolatey for Business license of the local computer running the `push` command.
1. Locate the `Chocolatey Licensed Extension` package in the Intune tenant and add the new `Chocolatey License` package as a dependency and remove the previous `Chocolatey License` package as a dependency.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +### I get an error message about my file not being found of not a `nupkg` file
```suggestion
### What can I do if I receive an error about my file not being found or not being a `nupkg` file?
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +~~~
```suggestion
The command to `push` a Chocolatey Intune package (a package with the `intunewin` extension) is currently a preview feature, and the feature configuration `allowPreviewFeatures` needs to be enabled by running:

~~~sh
choco feature enable --name=allowPreviewFeatures
~~~
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +The instructions and all screenshots are current as of July 2021.
```suggestion
To allow Chocolatey to access the Intune tenant and work with packages, a user with the Global Administrator or Privileged Role Administrator permissions must create an Azure AD Application in your Azure tenant. See the [Microsoft Graph API documentation](https://docs.microsoft.com/en-us/graph/auth-v2-service) for further information.
 
_The steps and screenshots below are current as of July 2021._
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. Search for device expand **DeviceManagementApps** and check off **DeviceManagementApps.ReadWrite.All**.
```suggestion
1. Search for device and expand **DeviceManagementApps** and check off **DeviceManagementApps.ReadWrite.All**.

```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. Click Add permissions.
```suggestion
1. Click **Add permissions**.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +The secret is what Chocolatey will use to authenticate with Microsoft Graph and should be protected like any other password.
```suggestion
The secret is what Chocolatey will use to authenticate with the Microsoft Graph API and should be protected like any other password.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. Under Client secrets select **New client secret**.
```suggestion
1. Under **Client secrets** select **New client secret**.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. (Optional) Provide a description for this client secret and provide an expiry for the secret.
```suggestion
1. (Optional) Provide a description and expiry date for the client secret.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. Click Add.
```suggestion
1. Click **Add**.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. Note the Value (it will not be shown again, so be sure to save it or you will need to generate another secret).
```suggestion
1. Note the **Value** down (_it will not be shown again, so be sure to save it or you will need to generate another secret_).
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +
```suggestion

> :warning: **WARNING**
> 
> It's important to note down the secret generated below as you cannot retrieve it again. If you forget the secret you will need to generate another one.

```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +Once you’ve created the AzureAD Application and generated a secret for it, you will want to obtain it and use it with Chocolatey.
```suggestion
Once you’ve created both the AzureAD Application and the secret, you will want to obtain the registration information to use it with Chocolatey. Complete the folllowing steps to do so:

```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +  * Your FQDN if it’s configured in Azure (e.g. mytesttenant.com).
```suggestion
1. The **Directory ID** is the GUID value used when we talk about **INTUNE TENANT GUID**.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. The **Application ID** is the value used when we talk about **client id**.
```suggestion
1. The **Application ID** is the value used when we talk about **TENANT CLIENT ID**.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. The **Secret** is the value used when we talk about **client secret**.
```suggestion
1. The **Secret** is the value used when we talk about **TENANT CLIENT SECRET**.
```

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. The **Secret** is the value used when we talk about **client secret**.
This matches what we have when setting the api-key.

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +  * Your FQDN if it’s configured in Azure (e.g. mytesttenant.com).
This matches what we have when adding a source.

2021-08-13 18:44 UTC, pauby commented on input/en-us/third-party-integrations/intune/create-azure-ad-application.md
> +1. The **Application ID** is the value used when we talk about **client id**.
This matches what we have when setting the api-key.

2021-08-13 18:44 UTC, pauby commented on input/shared/intune-note.txt
> +> The Chocolatey Intune integration requires a valid Chocolatey For Business or Chocolatey For Business Trial license.
```suggestion
> The Chocolatey Intune integration requires a valid Chocolatey for Business or Chocolatey for Business Trial license.
```

2021-08-17 00:11 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +This will push the wanted package and any dependencies that do not already exist on the Intune tenant.
I ended up going with:

```
When using the `push` command the package path provided must be an `.intunewin` file that was previously converted to a Chocolatey Intune package using the [`convert`](xref:intune-convert) command. This will push the Chocolatey Intune package, and its dependencies if they do not already exist there, to the Intune tenant.
```

As this makes it more clear what the "if they don't already exist" is referring to.

2021-08-17 00:14 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +However, you cannot depend on a pre-release if the package passed in is a stable release.
This was committed with wording to say pushing instead of converting.

2021-08-17 00:55 UTC, corbob commented
@pauby I've updated all of the requested changes. There were 3 comments that are marked resolved by GitHub because of the commit, but they're not fully resolved:

+ [ ] https://github.com/chocolatey/docs/pull/215/files/6a53552982ad7d7c734025c92fba8a5a975448b8#r683673920 This one mentions also putting this note in the FAQ/Issues section of the docs. Just seeking clarification which part you mean for this to be (there is a FAQ file in the docs, and a section of the page for issues/FAQs.)
+ [ ] https://github.com/chocolatey/docs/pull/215/files/6a53552982ad7d7c734025c92fba8a5a975448b8#r686962903 You say to amend information regarding organizational use of CCR. Is there an existing message you'd like us to put here? Or should one be created for this?
+ [ ] https://github.com/chocolatey/docs/pull/215/files/6a53552982ad7d7c734025c92fba8a5a975448b8#r688662994 This didn't come in as a suggestion, if I were to guess I think you're suggesting that this be added to the document. If that's the case, I think the convert command also needs this added.

2021-09-20 11:26 UTC, gep13 commented
@pauby are you in a position to review this one again?

2021-09-21 20:39 UTC, pauby requested changes

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/configuration.md
> +When pushing packages to an Intune tenant, a combination of a Client ID and Client Secret is needed. These can be obtained from the [Azure AD Portal](https://aad.portal.azure.com/) where the Client I
```suggestion
When pushing packages to an Intune tenant, a combination of a Client ID and Client Secret is needed. These can be obtained from the [Azure AD Portal](https://aad.portal.azure.com/) where the Client ID is the value for **Application ID** and the **Secret** is the Client Secret. You can use these on the command line when running the `choco push` command by using the `--source=<INTUNE TENANT GUID>` argument with the `--api-key=<CLIENT ID>:<CLIENT SECRET>` argument.
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +Converting from Chocolatey packages to Intune packages that can be later pushed using `choco push` has been added to a new command called `convert`. This command allows a single package to be passed
```suggestion
Converting from Chocolatey packages to Intune packages that can be later pushed using `choco push` has been added to a new command called `convert`. This command allows the file path of a single package to be passed and Chocolatey will then convert it, and its dependencies, to Chocolatey Intune packages.
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +Ensure that the Chocolatey the package you want to convert and it's depedencies, are present in the current directory before running the `convert` command. You can do this with `choco download <PACKA
```suggestion
Ensure that the Chocolatey package you want to convert, and it's depedencies, are present in the current directory before running the `convert` command. You can do this with `choco download <PACKAGE NAME> --internalize`.
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +By specifying the path to a pre-release package, pre-release support will be enabled for the package and its dependencies. However, while the package you are converting can be a pre-release, you cann
I think this should be a 'WARNING' rather than just text? What do you think?

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +> If the packages `chocolatey` or `chocolatey.extension` do not exist in the same directory as the Chocolatey package you are converting, a warning about them being 'missing' will be shown. This warn
Can I just clarify that this is _still_ the case and hasn't been changed? If it has, can we remove it. If it hasn't that's cool, just confirm it and resolve.

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +This warning message comes from Chocolatey itself and is due to the program not knowing about the new `convert` command. The warning message can safely be ignored and will be removed in a future vers
Can I again just clarify that this is _still_ an issue? If not, can we remove it. If so, can you just clarify and resolve this?

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/prerequisites.md
> +2. Store the tenant information in the Chocolatey configuration using the command `choco config set --name=intuneTenantGUID --value=<INTUNE TENANT GUID>`.
```suggestion
2. Store the tenant information in the Chocolatey configuration using the command `choco config set --name=intuneTenantGUID --value=<INTUNE TENANT GUID>`. The GUID is available on the [Azure AD Application page](https://aad.portal.azure.com/).
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/prerequisites.md
> +2. Store the tenant information in the Chocolatey configuration using the command `choco config set --name=intuneTenantGUID --value=<INTUNE TENANT GUID>`.
I took that information from the `configuration.md`

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +The ability to push Chocolatey Intune packages (packages with the extension `.intunewin`) has been added to the `push` command. The command will push the specified Chocolatey Intune package, any depe
```suggestion
The ability to push Chocolatey Intune packages (packages with the extension `.intunewin`) has been added to the `push` command. The command will push the specified Chocolatey Intune package, any dependencies specified for the package along with the core Chocolatey Intune packages of  `chocolatey`, `chocolatey-license` and `chocolatey.extension` when the packages do not already exist on the Intune tenant. The `chocolatey-license` package will be automatically generated using the Chocolatey for Business license that is present on the local computer running the `push` command, if it does not exist in the Intune tenant.
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +
This hasn't been added.

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +By specifying the path to a pre-release package, pre-release support will be enabled for the package and its dependencies. However, while the package you are pushing can be a pre-release, you cannot
This was mentioned for a previous file. I think this should be a WARNING. Thoughts?

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +> If a package for `chocolatey-license` does not already exist on the specified Intune tenant, a new package will be created using the Chocolatey for Business license on the local computer the comman
```suggestion
> If a package for `chocolatey-license` does not already exist on the specified Intune tenant, a new package will be created using the Chocolatey for Business license that is present on the local computer the command is run from.
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +When resolving package dependencies that are specified in the converted `.intunewin` file, we first search the Intune tenant for a package that was previously uploaded that matches the same identifie
```suggestion
When resolving package dependencies that are specified in the converted `.intunewin` file, we first search the Intune tenant for a package that was previously uploaded that matches the same ID and is within the same version criteria constructed during the conversion of the package. If no package matching the mentioned criteria are found in the Intune tenant, we will fall back to looking in the same directory as the original `.intunewin` file passed to the `push` command, and check for the same criteria there. If no packages are found in either of the places, the `push` command will fail with an error mentioning the missing package.
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +When resolving package dependencies that are specified in the converted `.intunewin` file, we first search the Intune tenant for a package that was previously uploaded that matches the same identifie
We don't use 'identifier' anywhere else, I don't think?

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +You have two ways you may use to achieve updating the packages.
```suggestion
```

2021-09-21 20:39 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> + 1. Push a package to Intune as you would normally do. This will result in Chocolatey not finding a `chocolatey-license` package within the Intune tenant, and therefore automatically generating a new
```suggestion
 1. Push a package to Intune as you would normally do. This will result in Chocolatey not finding a `chocolatey-license` package within the Intune tenant, and therefore automatically generating a new one using the Chocolatey for Business license package using the license present on the local computer running the `push` command.
```

2021-09-21 20:42 UTC, pauby commented
@corbob with regards to [this comment](https://github.com/chocolatey/docs/pull/215#issuecomment-899913439), I can't see my comments. Can we have a chat about this and go through it?

2021-09-24 21:02 UTC, corbob reviewed
@pauby: I unresolved all of those comments that were mentioned [here](https://github.com/chocolatey/docs/pull/215#issuecomment-899913439) and added a comment to them. I will treat the one regarding not coming in as a suggestion as though it were and get it updated.

2021-09-24 21:02 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +
This didn't come in as a suggestion, if I were to guess I think you're suggesting that this be added to the document. If that's the case, I think the convert command also needs this added.

2021-09-24 22:31 UTC, corbob commented on input/en-us/licensed-extension/intune/convert.md
> +This warning message comes from Chocolatey itself and is due to the program not knowing about the new `convert` command. The warning message can safely be ignored and will be removed in a future vers
This is no longer an issue. I've removed it from the docs.

2021-09-24 22:31 UTC, corbob commented on input/en-us/licensed-extension/intune/convert.md
> +> If the packages `chocolatey` or `chocolatey.extension` do not exist in the same directory as the Chocolatey package you are converting, a warning about them being 'missing' will be shown. This warn
This is still the case.

2021-09-24 22:47 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +By specifying the path to a pre-release package, pre-release support will be enabled for the package and its dependencies. However, while the package you are pushing can be a pre-release, you cannot
That makes sense. I've added it as a warning.

2021-09-24 22:47 UTC, corbob commented on input/en-us/licensed-extension/intune/convert.md
> +By specifying the path to a pre-release package, pre-release support will be enabled for the package and its dependencies. However, while the package you are converting can be a pre-release, you cann
That makes sense. I've added it as a warning.

I also added a link over to push the same way push links back here.

2021-09-27 17:10 UTC, corbob commented
Need to try and create circular dependency and add issue to FAQ.
https://github.com/chocolatey/docs/pull/215#discussion_r715899360

2021-09-28 01:40 UTC, corbob commented on input/en-us/licensed-extension/intune/push.md
> +If no packages are found in either of the places, the `push` command will fail with an error mentioning the missing package.
This suggestion has been applied.

2021-09-28 01:42 UTC, corbob commented
I discovered what happens when you try to push a circular dependency to Intune. 
![image](https://user-images.githubusercontent.com/30301021/135008400-6d924213-392f-4f36-b300-6522827079cc.png)

It doesn't get any better if it's 100 packages long either. I suspect this would go on for about an hour until the Intune token failed and then you'd receive an error to that effect (I'll run this test overnight and we can check on it in the morning).

2021-10-01 16:41 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +To start converting Chocolatey packages to the Chocolatey Intune package format, you first need to download the packages. The location can be the Chocolatey Community Repository, your own internal re
```suggestion
To start converting Chocolatey packages to the Chocolatey Intune package format, you first need to download the packages. The location can be your own internal repository, or any other valid Chocolatey source. You can also use the Chocolatey Community Repository but be aware of [organizational use recommendations and limitations](https://docs.chocolatey.org/en-us/community-repository/community-packages-disclaimer). As an example, to download version `86.0` of the `firefox` Chocolatey package and convert it to a Chocolatey Intune package along with its dependencies:
```

2021-10-01 16:42 UTC, pauby commented on input/en-us/licensed-extension/intune/convert.md
> +The location can be the Community Repository, your own Internal Repository, or any other valid Chocolatey source.
I couldn't edit the above so added another comment that covers this. Resolving it.

2021-10-01 17:04 UTC, pauby requested changes
This is just a couple of spelling mistakes, a suggestion for the organizational use and a clarification.

2021-10-01 17:04 UTC, pauby commented on input/en-us/licensed-extension/intune/push.md
> +If you receive a message that certain packages are not in Intune over and over, you have likely created a circular dependency. Neither Chocolatey, nor Intune support circular dependencies and so you
```suggestion
If you receive a message that certain packages are not in Intune over and over, you have likely created a circular dependency. As Chocolatey and Intune do not support circular dependencies, you won't be able to push these packages to Intune.
```

2021-10-01 18:22 UTC, pauby approved these changes

2021-10-01 18:23 UTC, merged