Add Known Issue to QDE in Azure Docs
chocolatey/docs pull request #219
Opened 2021-08-10 10:10 UTC by Windos

This PR adds a known issue to the QDE in Azure docs that has surfaced since upgrading the included CCM to 0.6.x.

It also fixes a small issue on the packages subpage which specified the incorrect syntax when executing the Jenkins internalization job.

I have previewed these changes locally.

![local preview of changes](https://user-images.githubusercontent.com/6955786/128849176-58a68ffb-9fa2-4a0a-89a3-177707c1bdb3.png)

2021-08-10 10:13 UTC, Windos commented
I didn't notice my formatter removing all that end of line whitespace. If it's an issue let me know and I can tweak my commits.

2021-08-10 10:57 UTC, JPRuskin commented
> I didn't notice my formatter removing all that end of line whitespace. If it's an issue let me know and I can tweak my commits.

I was wondering about that. :) Given that the double-space-at-end-of-line _does_ have some effects in markdown, I was just checking to see if it had changed much.

2021-08-10 11:15 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log into Jenkins at `https://<FQDN>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to a
This against the custom packages section makes me think we should be consistent with semicolons _or_ commas, but that's for Dev Another Day™

2021-08-10 11:15 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +We have found that `.dev` domain names currently have trouble routing to the Chocolatey Central Management service.
Is it worth mentioning we think this is due to the HSTS preload, or ... I'm so mixed on not understanding the issue, here, vs wanting to give a better indication for the rare people who find this issue. I feel like we should at least mention it, as the issue isn't specifically with the TLD, but instead (we think) with the things that are enforced on that TLD.

2021-08-10 16:28 UTC, Windos commented
When GitHub is running properly again, this PR needs to be converted to draft. There's been changes to the situation which means this needs some wording changes.

2021-08-11 09:14 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +We have found that `.dev` domain names currently have trouble routing to the Chocolatey Central Management service.
I'd agree but I'd keep it short.

Looks like we're still adding text to separate lines? 298 is one line. 299 is another. 301 another. They should all be part of the same paragraph.

2021-08-11 09:15 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +if (-not $FQDN) {$FQDN = Read-Host 'Enter the Fully Qualified Domain Name, e.g. choco.example.com'}
Where is `$FQDN` set in this script? If it's a placeholder then we need to be consistent and use `<FQDN>`.

2021-08-11 09:16 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +if (-not $FQDN) {$FQDN = Read-Host 'Enter the Fully Qualified Domain Name, e.g. choco.example.com'}
```suggestion
if (-not $FQDN) { $FQDN = Read-Host -Prompt 'Enter the Fully Qualified Domain Name, e.g. choco.example.com' }
```

2021-08-11 09:20 UTC, pauby requested changes

2021-08-11 09:20 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +Currently it is not possible to fix this issue. If you run into it, you should redeploy with a FQDN which does not end in `.dev`.
I think here is why we should talk about the .dev TLD issue as to _why_ we can't fix it.

2021-08-11 09:20 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +We have found that `.dev` domain names currently have trouble routing to the Chocolatey Central Management service.
I'd agree. But also to keep it short. See the comment below.

2021-08-11 09:20 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +if (-not $FQDN) {$FQDN = Read-Host 'Enter the Fully Qualified Domain Name, e.g. choco.example.com'}
```suggestion
if (-not $FQDN) { $FQDN = Read-Host -Prompt 'Enter the Fully Qualified Domain Name, e.g. choco.example.com' }
```

2021-08-11 09:20 UTC, pauby commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log into Jenkins at `https://<FQDN>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to a
Just to pick up on the comment above - I thought in previous examples we were using commas? If that is the case we should be consistent.

2021-08-16 10:13 UTC, Windos commented
This PR is no longer needed. Closing it (some of the more general changes will show up in a name change PR)

2021-08-16 10:13 UTC, closed without merging