Updates to Quick-Start Guide V2 now using scripts repo
chocolatey/docs pull request #222
Opened 2021-08-13 06:17 UTC by adilio

Closes #199 .

This is the biggest update to the C4B QuickStart Guide (QSG) in about 2 years!

This update includes:
- Automated script setup, allowing users to simply copy-and-paste code
- Nexus repository setup
- **New** BYO Server; we have tested and support all current non-EOL Windows Server  versions (2016, 2019, 2022) on your infrastructure-of-choice
- **New** Complete CCM setup, including MS SQL Express
- **New** License validation and license package creation
- **New** Jenkins setup, along with job templates
- **New** SSL Setup, which **now accepts custom certs**

It's also worth mentioning that this guide bases most of its automation on code contained in the `choco-quickstart-scripts` repo here:
https://github.com/chocolatey/choco-quickstart-scripts

2021-08-13 09:00 UTC, Windos requested changes
Just a very quick grammar check and ensure the preview works. A few minor things to tweak from that.

2021-08-14 10:01 UTC, gep13 requested changes
Just a few suggestions/questions that occurred to me as I was reading through this.  On the whole, looks really good to me though, well done!

2021-08-15 22:08 UTC, adilio commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > <li>Configures Self-Service mode and installs Chocolatey GUI (chocolateygui)</li>
We are not, but we do download it to the repo; should we?

2021-08-15 22:08 UTC, adilio commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > <li>Licenses Chocolatey by installing the license package (chocolatey-license) created during QDE setup</li>
Good point

2021-08-15 22:09 UTC, adilio commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > <li>Installs MS SQL Express</li>
Good point, will do.

2021-08-16 06:22 UTC, adilio commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > <li>Configures Self-Service mode and installs Chocolatey GUI (chocolateygui)</li>
My bad, we already were. 😂 
https://github.com/chocolatey/choco-quickstart-scripts/blob/4ebb77e67440297ca4e4150d5aed1f68229d6adb/scripts/ClientSetup.ps1#L108
Added that to the doc in this last PR.

2021-08-16 15:07 UTC, JPRuskin requested changes
Hopefully some of this is helpful and not just me nitpicking - would suggest changing the blockquote stuff (if I guessed your intent right), at least, as it looks quite odd on my preview (though if Gary didn't notice it, I worry that it's not an issue anywhere else 😅).

2021-08-16 15:07 UTC, JPRuskin commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > ```
When in quoteblock _and_ codeblock, this renders like this:
![image](https://user-images.githubusercontent.com/1975761/129584903-41ce44c7-d72e-4607-ac74-e17d308bf455.png)

I would recommend just a codeblock?
```suggestion
    ```powershell
    Set-Location "$env:SystemDrive\choco-setup\files\scripts"
    .\Start-C4bCcmSetup2.ps1
    ```
```

2021-08-16 15:07 UTC, JPRuskin commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > ```
Ah, but I assume we want to bundle it in with the warning above. Hm. In that case, removing the blank line between the two quotes will result in this: 
![image](https://user-images.githubusercontent.com/1975761/129585259-91b41fbc-63e6-457e-bf07-099b4202a017.png)

(suggestion above)

2021-08-16 15:07 UTC, JPRuskin commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
The warning and code block are separated and render awkwardly. This should solve that!

```suggestion
```

2021-08-16 15:14 UTC, JPRuskin commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > <summary><strong>What does this script do? (click to expand)</strong></summary>
I've added what I think to be a suggested fix for this in various places, which ends up looking like this:

![image](https://user-images.githubusercontent.com/1975761/129586835-21c1e5f8-adec-4aba-859a-18091f03f88d.png)

and expanding to this:
![image](https://user-images.githubusercontent.com/1975761/129586861-40eb4326-72dd-4500-b608-beb4eeea1972.png)

2021-08-16 21:24 UTC, adilio commented
Heya @JPRuskin, thanks for all the GREAT input and call. 🙏🏼 

I have incorporated all the changes we've discussed in this last commit.

Ready for review.

2021-08-16 21:25 UTC, adilio commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    > <li>Licenses Chocolatey by installing the license package (chocolatey-license) created during QDE setup</li>
This breaks the formatting, btw. Had to revert back.

2021-08-16 21:32 UTC, JPRuskin submitted a review, later dismissed
Looks great! Sorry for my confusion around the quotes.

2021-08-17 18:21 UTC, adilio commented
Hey @JPRuskin, now it's my turn to apologize! For some reason, I accidentally dismissed your review. Could you re-review and approve if acceptable?
Many thanks! 🙏🏼

2021-08-17 19:14 UTC, JPRuskin approved these changes
LGTM!

2021-08-17 20:18 UTC, gep13 submitted a review, later dismissed
LGTM!

Only thing I would suggest is that the commits can/should be squashed down into a single commit, as they are really all changes that are based on the feedback that was received.

2021-08-17 20:33 UTC, ryanrichter94 submitted a review, later dismissed
LGTM

2021-08-18 19:29 UTC, steviecoaster approved these changes
LGTM 🚀

2021-08-18 19:31 UTC, merged