Name change from "QDE in Azure" to "Chocolatey for Business QDE Azure Environment"
chocolatey/docs pull request #223
Opened 2021-08-16 10:38 UTC by Windos

This PR changes the name of the QDE in Azure project to "Chocolatey for Business QDE Azure Environment"

It also tweaks the Jenkins specific docs to remove unneeded escape characters and swap to semi-colon list.

This will be tested via the preview and this message will be edited when that is complete.

2021-08-16 10:40 UTC, Windos commented on input/en-us/quick-deployment/azure/index.md
> +This is an overview of the Chocolatey for Business QDE (Quick Deployment Environment) Azure Environment.
I thought the full name of QDE is should be called out once. This is the opposite of how this would normally be done: Quick Deployment Environment (QDE)

Looking for feedback on this secifically.

2021-08-16 10:42 UTC, Windos commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log into Jenkins at `https://<FQDN>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to a
Yes, the create experience has this as a comma-separated list, and this is semi-colon.

I would prefer (personally) both to comma based, but this is the standard Jenkins job we provide across the QDE offerings, and I think changing it would cause more confusion

(e.g. someone goes to find docs and finds non C4B QDE AZ docs first that wouldn't work because we deviated from the standard.)

2021-08-16 11:12 UTC, JPRuskin submitted a review, later dismissed

2021-08-16 11:12 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/index.md
> +This is an overview of the Chocolatey for Business QDE (Quick Deployment Environment) Azure Environment.
Hm. Makes sense, given that we don't really have a chance to define it in the normal way, but it does feel interesting to read - equally doesn't really make sense to have it expanded and then define the acronyms normally as it's _the name_.

2021-08-16 11:12 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log into Jenkins at `https://<FQDN>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to a
Given that neither character is a valid package name char, it would be very easy to handle either being used in either the job or the deployment input - we could then adjust this documentation as needed, or let customers "fail into success" with a wink and a nod.

2021-08-16 12:22 UTC, Windos commented on input/en-us/quick-deployment/azure/packages.md
> +To do so, log into Jenkins at `https://<FQDN>/jenkins`, and click the `Schedule a Build...` icon on the right of the `Internalize packages from the Community Repository` job. This will take you to a
I've added a card to the project board for adding comma as an additional separator on the Jenkins job (and updating the docs to reflect this)

2021-08-16 16:11 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +This is an overview of the Chocolatey for Business QDE (Quick Deployment Environment) Azure Environment.
I don't think we should expand it because in this instance it could be confusing. 'QDE' is a product so having it 'QDE Azure' I think is okay.

2021-08-16 16:20 UTC, pauby requested changes

2021-08-16 16:20 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +This is an overview of the Chocolatey for Business QDE (Quick Deployment Environment) Azure Environment.
```suggestion
This is an overview of the Chocolatey for Business QDE Azure Environment.
```

2021-08-16 16:20 UTC, pauby commented on input/en-us/quick-deployment/azure/index.md
> +> A Chocolatey for Business QDE Azure Environment is a fully functional C4B environment; as such, it will require a business or trial license.
Do we define C4B earlier in this document (I didn't see it)? If we didn't, use the full 'Chocolatey for Business' name.

2021-08-17 09:20 UTC, Windos commented on input/en-us/quick-deployment/azure/index.md
> +> A Chocolatey for Business QDE Azure Environment is a fully functional C4B environment; as such, it will require a business or trial license.
It's not defined elsewhere... and also the TLA isn't used elsewhere so I've expanded it. It does read a little clunky, but not the end of the world.

2021-08-17 09:39 UTC, pauby approved these changes

2021-08-17 09:39 UTC, merged

2021-08-17 09:40 UTC, pauby commented
Awesome work! Thanks for your contribution @Windos !