(doc) Add client on-boarding guide for the Chocolatey for Business QDE Azure Environment
chocolatey/docs pull request #240
Opened 2021-09-08 09:53 UTC by Windos

Chocolatey for Business QDE Azure Environment is slightly different than regular QDE in terms of client on-boarding.

This is _mainly_ because of the change to the URL for Nexus, but also the fact that it is _always_ internet enabled.

This PR includes the new doc page and supporting images.

2021-09-08 09:56 UTC, Windos commented on input/en-us/quick-deployment/azure/client-setup.md
> +Ensure that you have [configured DNS](https://docs.chocolatey.org/en-us/quick-deployment/azure/#dns-configuration) to direct clients to your deployed environment.
I'm not sure if it is possible to link to anchors on xref's to avoid linking out to the full URL like this?

2021-09-08 16:47 UTC, ryanrichter94 requested changes
Found a possible improvement with handling self-signed certificates.

2021-09-08 16:47 UTC, ryanrichter94 commented on input/en-us/quick-deployment/azure/client-setup.md
> +1. Close the Microsoft Management Console
Have a question. Does AzureQDE not have the certificate import script hosted on IIS like current QDE has? [Link](https://docs.chocolatey.org/en-us/quick-deployment/setup/client-setup#import-self-signed-certificate-from-qde-server) to docs on importing the self-signed certificate in QDE. 

Asking clients to manually import the certificate on possibly hundreds of endpoints seems like a pain in the butt.

2021-09-08 21:32 UTC, ryanrichter94 commented on input/en-us/quick-deployment/azure/client-setup.md
> +1. Close the Microsoft Management Console
I am a moron and prefer us handling this scenario this way. Versus how we cater to having self-signed certs as an "easy" option with our current QDE offering. This is a much better solution considering this will be a Cloud offering.

2021-09-08 21:33 UTC, ryanrichter94 approved these changes
LGTM 🚀

2021-09-09 08:09 UTC, JPRuskin approved these changes

2021-09-10 00:05 UTC, adilio approved these changes
Thanks for adding these updates so quickly, as we've seen related questions from users pretty quickly.
Looks good to me! 🚀

2021-09-17 12:51 UTC, ryanrichter94 commented
@pauby Can we get your review on this please. Otherwise looks like team has approved the changes put forward in this PR.

2021-09-17 12:58 UTC, pauby approved these changes

2021-09-17 12:58 UTC, merged