(#242) Adds RDP Docs to QDE in Azure
chocolatey/docs pull request #243
Opened 2021-09-15 06:40 UTC by JPRuskin

This PR adds docs showing covering the process of adding firewall exceptions and IPs in order to connect to the VM within a QDE in Azure environment, as well as a ballpark estimate for monthly infrastructure costs.

2021-09-15 09:55 UTC, Windos requested changes
Just a couple of nitpicky things. As always, my suggestions can be taken or rejected 😅

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/index.md
> +Using some of the methods above can cut this cost significantly.
> some of the methods above

This reads a little weird, esp if skim reading. Above where?!

Maybe change the opening line to something more direct: "A ballpark estimate comes to around..."

Then call out the possibility of cutting the costs and bullet point the methods under that statement.

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +Even after deploying a Chocolatey for Business QDE Azure Environment, you may wish to link the machine to an existing Active Directory domain, install monitoring software, or otherwise tinker with co
```suggestion
After deploying a Chocolatey for Business QDE Azure Environment, you may wish to link the machine to an existing Active Directory domain, install monitoring software, or otherwise tinker with configuration. This page will show you how to gain access to the primary VM within the environment via Remote Desktop Protocol (RDP).
```

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +We need to add a publicly accessible IP address to the VM, and add an exception to the Network Security Group (NSG) to allow connections.
```suggestion
We need to add a publicly accessible IP address to the VM, and add a rule to the Network Security Group (NSG) to allow connections.
```

Feel free to take or leave this suggestion, I think **rule** may be more commonly understood vs. **exception**?

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +Now we will add an exception to the NSG. If you do not already know your current public IP address, you can find out by visiting [ipconfig.me](http://ifconfig.me/ip).
```suggestion
Now we will add a rule to the NSG. If you do not already know your current public IP address, you can find out by visiting [ipconfig.me](http://ifconfig.me/ip).
```

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +We should then create a NSG rule to allow traffic from our current IP to the VM over the port used for RDP (3389). If you want to create the exception for another IP address, you should change the va
```suggestion
We should then create a NSG rule to allow traffic from our current IP to the VM over the port used for RDP (3389). If you want to create the rule for another IP address, you should change the value of `$IPAddress` before running the `Add` and `Set` commands.
```

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +Finally, you can find the FQDN / IP address to connect to by running something similar to the following code:
```suggestion
Finally, you can find the IP address to connect to by running something similar to the following code:
```

This should only ever be an IP, right?

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +Finally, connect to the VM using the FQDN or IP address you procured in the previous steps, using [the credential from the Key Vault](xref:qdeazure#accessing-services).
```suggestion
Finally, connect to the VM using the IP address you procured in the previous steps, using [the credential from the Key Vault](xref:qdeazure#accessing-services).
```

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +Finally, connect to the VM using the FQDN or IP address you procured in the previous steps, using [the credential from the Key Vault](xref:qdeazure#accessing-services).
Would it also help to link to some docs here about _how_ to connect?

Azure has this: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/connect-logon

2021-09-15 09:55 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +For the sake of this section, we will assume that you have installed a recent copy of the Az modules and your session is authenticated with an account that has access to your Chocolatey for Business
```suggestion
For the sake of this section, we will assume that you have installed a recent copy of the [Az modules](https://www.powershellgallery.com/packages/Az) and your session is authenticated with an account that has access to your Chocolatey for Business QDE Azure Environment. We also assume that you haven't made significant modifications to the deployed resources.
```

Helpful link to the PowerShell Gallery, may save a Google.

2021-09-15 12:04 UTC, Windos submitted a review, later dismissed
Read through again via the preview. Looks good.

2021-09-17 21:03 UTC, adilio reviewed
LGTM 🚀

2021-09-17 21:03 UTC, adilio approved these changes
LGTM 🚀

2021-09-19 17:19 UTC, pauby requested changes

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +For the sake of this section, we will assume that you have installed a recent copy of the [Az modules](https://www.powershellgallery.com/packages/Az) and your session is authenticated with an account
```suggestion
For the sake of this section, we will assume that you have installed a an up-to-date version of [Az modules](https://www.powershellgallery.com/packages/Az) and your session is authenticated with an account that has access to your Chocolatey for Business QDE Azure Environment. We also assume that you haven't made significant modifications to the deployed resources.
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +You will follow the same steps covered in the Azure Portal directions, above. You can run the [entire script](https://gist.githubusercontent.com/JPRuskin/9c2f2d31f09bc2df9b8ae88b7f1fffdb/raw/ConnectT
Can we either remove the link to the gist in your GitHub account or add it to the Chocolatey account?

If we have the script in the docs, people can copy and paste them together to run the code?

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +$mgtNic = Get-AzNetworkInterface -ResourceGroupName $ResourceGroupName -Name *-nic
Can the user _reasonably_ name the nic something else? I don't think they can, but I want to make sure.

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +if (-not $mgtNic.IpConfigurations[0].PublicIpAddress.Id) {
If no nic's are returned from the code above, this code will throw an exception? Can we catch that and output some nice error message?

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +if (-not $ResourceGroupName) {$ResourceGroupName = Read-Host 'Enter the ResourceGroupName'}
Can we have some consistency with the if's? We are using multiple lines below in the code so we should do so here I feel.

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +
I thought I'd put this here.

Can we have some comments for the PowerShell code as to what it is doing?

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +if (-not $ResourceGroupName) {$ResourceGroupName = Read-Host 'Enter the ResourceGroupName'}
Multiple lines for an if statement for consistency?

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +We should then create a NSG rule to allow traffic from our current IP to the VM over the port used for RDP (3389). If you want to create the rule for another IP address, you should change the value o
Can we name the variables consistently (ie. camelCase)?

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +if (-not $ResourceGroupName) {$ResourceGroupName = Read-Host 'Enter the ResourceGroupName'}
```suggestion
if (-not $resourceGroupName) {
    $resourceGroupName = Read-Host 'Enter the ResourceGroupName'
}
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +        $mgtPublicIp = New-AzPublicIpAddress -ResourceGroupName $ResourceGroupName -Name 'tempip' -Location $ResourceGroup.Location -AllocationMethod Dynamic
```suggestion
    if (-not ($mgtPublicIp = Get-AzPublicIpAddress -ResourceGroupName $resourceGroupName -Name 'tempip')) {
        $resourceGroup = Get-AzResourceGroup -Name $resourceGroupName
        $mgtPublicIp = New-AzPublicIpAddress -ResourceGroupName $resourceGroupName -Name 'tempip' -Location $resourceGroup.Location -AllocationMethod Dynamic
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +We should then create a NSG rule to allow traffic from our current IP to the VM over the port used for RDP (3389). If you want to create the rule for another IP address, you should change the value o
```suggestion
We should then create a NSG rule to allow traffic from our current IP to the VM over the port used for RDP (3389). If you want to create the rule for another IP address, you should change the value of `$ipAddress` before running the `Add` and `Set` commands.
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +if (-not $ResourceGroupName) {$ResourceGroupName = Read-Host 'Enter the ResourceGroupName'}
```suggestion
if (-not $resourceGroupName) {
    $resourceGroupName = Read-Host 'Enter the ResourceGroupName'
}
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +$IPAddress = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content
```suggestion
$ipAddress = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +$NSG = Get-AzNetworkSecurityGroup -ResourceGroupName $ResourceGroupName
```suggestion
$nsg = Get-AzNetworkSecurityGroup -ResourceGroupName $resourceGroupName
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +$RDPRule = @{
```suggestion
$rdpRule = @{
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +    Priority                 = (($NSG.SecurityRules.Priority | Sort-Object)[0] - 1)
```suggestion
    Priority                 = (($nsg.SecurityRules.Priority | Sort-Object)[0] - 1)
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +    SourceAddressPrefix      = $IPAddress
```suggestion
    SourceAddressPrefix      = $ipAddress
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +$null = Set-AzNetworkSecurityGroup -NetworkSecurityGroup $NSG
```suggestion
$null = Add-AzNetworkSecurityRuleConfig @rdpRule -NetworkSecurityGroup $nsg
$null = Set-AzNetworkSecurityGroup -NetworkSecurityGroup $nsg
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +Finally, you can find the IP address to connect to by running something similar to the following code:
```suggestion
Finally, you can find the IP address to connect to by running the following code:
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +(Get-AzPublicIpAddress -ResourceGroupName $ResourceGroupName -Name $mgtNic.IpConfigurations.PublicIpAddress.Id.Split('/')[-1]).IpAddress
```suggestion
if (-not $resourceGroupName) {
    $resourceGroupName = Read-Host 'Enter the ResourceGroupName'
}

if (-not $mgtNic) {
    $mgtNic = Get-AzNetworkInterface -ResourceGroupName $resourceGroupName -Name *-nic
}

(Get-AzPublicIpAddress -ResourceGroupName $resourceGroupName -Name $mgtNic.IpConfigurations.PublicIpAddress.Id.Split('/')[-1]).IpAddress
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +> It can sometimes take a few minutes for the NSG to update rules.
```suggestion
> It can sometimes take a few minutes for the Network Security Group rules to be updated.
```

2021-09-19 17:19 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +Finally, [connect to the VM](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/connect-logon) using the IP address you procured in the previous steps, using [the credential from the Key
```suggestion
Finally, use the IP address that we found in the previous steps to [connect to the VM](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/connect-logon) using [the credential from the Azure Key Vault](xref:qdeazure#accessing-services).
```

2021-09-20 07:53 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/rdp.md
> +$mgtNic = Get-AzNetworkInterface -ResourceGroupName $ResourceGroupName -Name *-nic
There's no way for them to change the suffix without _really_ messing about, so the `*-nic` filter should be alright.

2021-09-20 08:04 UTC, JPRuskin commented on input/en-us/quick-deployment/azure/rdp.md
> +You will follow the same steps covered in the Azure Portal directions, above. You can run the [entire script](https://gist.githubusercontent.com/JPRuskin/9c2f2d31f09bc2df9b8ae88b7f1fffdb/raw/ConnectT
I've actually got a version of this script going into a directory on the repository itself at some point (as part of a QOL update), though the repository isn't public. I'll investigate popping it onto Chocolatey's Gists, though I don't know if it would potentially be cleaned up in a year.

2021-09-21 20:44 UTC, pauby commented on input/en-us/quick-deployment/azure/rdp.md
> +You will follow the same steps covered in the Azure Portal directions, above. You can run the [entire script](https://gist.githubusercontent.com/JPRuskin/9c2f2d31f09bc2df9b8ae88b7f1fffdb/raw/ConnectT
Can we check the criteria of the Chocolatey gist cleanup? Does it cleanup private gists? If not, we could use one of those for this?

2021-09-22 06:22 UTC, Windos commented on input/en-us/quick-deployment/azure/rdp.md
> +You will follow the same steps covered in the Azure Portal directions, above. You can run the [entire script](https://gist.githubusercontent.com/JPRuskin/9c2f2d31f09bc2df9b8ae88b7f1fffdb/raw/ConnectT
The gist clean-up job currently looks at **all** gists.

If we want to only do public gists going forward, it appears to be a case of changing the oath from `/gists` to `/gists/public`.

I'll put an issue up on that repo to discuss.

2021-09-24 16:16 UTC, adilio approved these changes
Looks good to me. In the interest of time and specific customer request, I'm gonna go ahead and merge this.
Just a heads up @pauby, we can definitely discuss further next week.

2021-09-24 16:21 UTC, merged