(#260) Running on Non-Windows systems
chocolatey/docs pull request #280
Opened 2021-10-28 00:28 UTC by TheCakeIsNaOH

Fixes #260 

Don't merge this until close to the first release of the docker container.

2021-10-29 18:01 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +When running on non-Windows systems, Chocolatey has a much more specific focus: the creation and maintenance of packages. This means that you can create, pack, and push packages, but not install soft
Changed.

2021-10-29 18:01 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +The packages available on the Chocolatey Community Repository, and presumably internal packages as well, primarily install software that is built for Windows. There is not much point in trying to ins
Changed.

2021-10-29 18:01 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +### Command that are supported
Changed.

2021-10-29 18:01 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +> :memo: **NOTE** This list is not final and may change as commands are added, modified, and (rarely) removed.
Changed.

2021-10-29 18:02 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +These commands are supported and should be fully functional:
Changed.

2021-10-29 18:02 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +Ever since we released 0.9.9 back in 2015, we've had it running in Mono which allows you to do package maintenance and simple things outside of managing software installations on Linux and macOS envi
Changed.

2021-10-29 18:02 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +In 2017, community member linuturk [contributed a Dockerfile](https://github.com/chocolatey/choco/pull/1153) to the Choco source, and [uploaded an unofficial image to Docker Hub](https://hub.docker.c
Changed.

2021-10-29 18:02 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +The licensed extension is currently not supported and does not work correctly on non-Windows systems. Options are being explored.
Changed.

2021-10-29 18:02 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +## Chocolatey licensed
Changed.

2021-10-29 18:03 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +## Limitations on Non-Windows systems
Changed.

2021-10-29 18:03 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +In the very long term, Chocolatey may support installing Non-Windows software, although that is [well past the end of the current planned roadmap](https://github.com/chocolatey/choco/issues/1854).
Why do you think this should be removed?

2021-10-29 18:04 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +- unpackself
Hmm, yup, that sounds like a good idea, this has been updated.

2021-11-01 18:32 UTC, pauby commented on input/en-us/non-windows.md
> +In the very long term, Chocolatey may support installing Non-Windows software, although that is [well past the end of the current planned roadmap](https://github.com/chocolatey/choco/issues/1854).
At the moment it's speculation as to whether this will be supported or not and I don't think that's helpful.

2021-11-11 19:19 UTC, pauby requested changes
I missed a couple of things. And just a question around the licensed extension options.

Otherwise, this is good to go once the Docker image is released.

2021-11-11 19:19 UTC, pauby commented on input/en-us/non-windows.md
> +The Chocolatey Licensed Extension is currently not supported and does not work correctly on non-Windows systems. Options are being explored.
> Options are being explored.

What options are being explored?

2021-11-11 19:19 UTC, pauby commented on input/en-us/non-windows.md
> +In 2017, community member linuturk [contributed a Dockerfile](https://github.com/chocolatey/choco/pull/1153) to the Chocolatey, and [uploaded an unofficial image to Docker Hub](https://hub.docker.com
```suggestion
In 2017, community member linuturk [contributed a Dockerfile](https://github.com/chocolatey/choco/pull/1153) to Chocolatey, and [uploaded an unofficial image to Docker Hub](https://hub.docker.com/r/linuturk/mono-choco/).
```

2021-11-11 19:19 UTC, pauby commented on input/en-us/non-windows.md
> +Alternatively, to create the Mono build of Chocolatey CLI  from source, see [the choco readme](https://github.com/chocolatey/choco#other-platforms) for instructions. Chocolatey CLI can be run on top
```suggestion
Alternatively, to create the Mono build of Chocolatey CLI from source, see [the chocolatey/choco repository README](https://github.com/chocolatey/choco#other-platforms) for instructions. Chocolatey CLI can be run on top of Mono on both Linux and MacOS systems.
```

2021-11-12 01:31 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +Alternatively, to create the Mono build of Chocolatey CLI  from source, see [the choco readme](https://github.com/chocolatey/choco#other-platforms) for instructions. Chocolatey CLI can be run on top
Fixed

2021-11-12 01:31 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +In 2017, community member linuturk [contributed a Dockerfile](https://github.com/chocolatey/choco/pull/1153) to the Chocolatey, and [uploaded an unofficial image to Docker Hub](https://hub.docker.com
Fixed

2021-11-12 01:36 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +The Chocolatey Licensed Extension is currently not supported and does not work correctly on non-Windows systems. Options are being explored.
Primarily if the licensed extension should be supported, unsupported (may or may not work), or explicitly disabled for non-window systems.

I talked about this with @gep13, and he said that it is something that needs to be discussed internally.

2021-11-25 13:51 UTC, pauby commented on input/en-us/non-windows.md
> +The Chocolatey Licensed Extension is currently not supported and does not work correctly on non-Windows systems. Options are being explored.
Until a decision is made, we should remove this. If we decide to explore any options, then we can come back and update it.

2021-11-29 15:15 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +The Chocolatey Licensed Extension is currently not supported and does not work correctly on non-Windows systems. Options are being explored.
Done.

2022-01-17 10:17 UTC, gep13 requested changes

2022-01-17 10:17 UTC, gep13 commented on input/en-us/non-windows.md
> +ShowInSidebar: false
Is there a reason that we are hiding this completely?  Is this not something that we would want to show _somewhere_ in the navigation?

2022-01-17 10:17 UTC, gep13 commented on input/en-us/non-windows.md
> +Alternatively, to create the Mono build of Chocolatey CLI  from source, see [the chocolatey/choco repository README](https://github.com/chocolatey/choco#other-platforms) for instructions. Chocolatey
```suggestion
Alternatively, to create the Mono build of Chocolatey CLI from source, see [the chocolatey/choco repository README](https://github.com/chocolatey/choco#other-platforms) for instructions. Chocolatey CLI can be run on top of Mono on both Linux and MacOS systems.
```

2022-01-17 10:17 UTC, gep13 commented on input/en-us/non-windows.md
> +The exception to this is `.template` packages, which can be installed and used on non-Windows systems to create new packages with a custom template.
@TheCakeIsNaOH This is not strictly true, based on the changes that we discussed. We are going to leave all commands as being runnable on non-Windows systems, with a warning that things might not work.

2022-01-17 10:17 UTC, gep13 commented on input/en-us/non-windows.md
> +These commands are supported for management of `.template` packages:
@TheCakeIsNaOH I think these need updated as well, right?

2022-01-17 16:08 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +ShowInSidebar: false
Sure. I'm open to suggestions on where to show it.

2022-01-17 16:26 UTC, gep13 commented on input/en-us/non-windows.md
> +ShowInSidebar: false
How about under the `Guides` section? Perhaps a new section called `Non Windows`?  @pauby thoughts?

2022-01-17 17:27 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +Alternatively, to create the Mono build of Chocolatey CLI  from source, see [the chocolatey/choco repository README](https://github.com/chocolatey/choco#other-platforms) for instructions. Chocolatey
Done.

2022-01-17 17:29 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +The exception to this is `.template` packages, which can be installed and used on non-Windows systems to create new packages with a custom template.
I've updated this section.

2022-01-17 17:29 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +These commands are supported for management of `.template` packages:
I've updated this section.

2022-01-17 18:10 UTC, pauby commented on input/en-us/non-windows.md
> +ShowInSidebar: false
Maybe `Non-Windows Platforms` or `Non-Windows Operating Systems` or `Non-Windows OS's` or `Running Chocolatey on Non-Windows Systems`? Or ...

2022-01-17 20:37 UTC, gep13 commented on input/en-us/non-windows.md
> +ShowInSidebar: false
@pauby name aside, would you be happy with the position of the page in the nav bar?

2022-01-17 20:37 UTC, pauby commented on input/en-us/non-windows.md
> +ShowInSidebar: false
Yes.

2022-01-17 20:41 UTC, gep13 commented on input/en-us/non-windows.md
> +ShowInSidebar: false
How about `Running on Non-Windows Systems` i.e. we don't need the `Chocolatey` in there, which will make it fit better in the menu.

2022-01-17 20:46 UTC, TheCakeIsNaOH commented on input/en-us/non-windows.md
> +ShowInSidebar: false
Done

2022-01-18 12:06 UTC, pauby submitted a review, later dismissed

2022-01-18 12:07 UTC, pauby commented
LGTM. Thanks @TheCakeIsNaOH for putting this together!

2022-01-18 16:15 UTC, gep13 approved these changes
LGTM!

2022-01-18 16:16 UTC, gep13 commented
@TheCakeIsNaOH thanks for getting this written up!

2022-01-18 16:23 UTC, merged