Update proxy-settings-for-chocolatey.md
chocolatey/docs pull request #286
Opened 2021-11-02 12:05 UTC by tijazz

This solution completely resolves the issue around installing chocolatey behind proxy using the command to force the WebRequest to use the Default Credentials for the proxy setting.

2021-11-02 12:12 UTC, tijazz commented
This solution completely resolves the issue around installing chocolatey behind proxy using the command to force the WebRequest to use the Default Credentials for the proxy setting.

It took me about 48 hours to be able to resolve this issue. This solution is so simple and easy to use.

2021-11-11 19:13 UTC, pauby commented
@vexx32 @AdmiringWorm Can you test these steps out?

2022-01-07 20:57 UTC, vexx32 requested changes
Thanks for the contribution! There's a couple things here I think could be improved to make this a bit more cohesive and understandable alongside the rest of this page, but otherwise this looks pretty good. 🙂

2022-01-07 20:57 UTC, vexx32 commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +
Given this section references the exact same error condition as is already mentioned below, I think it makes more sense if this is moved after the original text, near line 30, especially since both these resolution sections start with the same `Steps to help address this:`

It looks like we could combine the two into more of a "try this first, and then if that doesn't work, try the following to explicitly set the proxy authentication values necessary"

2022-01-07 20:57 UTC, vexx32 commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +  `@powershell -NoProfile -ExecutionPolicy Unrestricted -Command "[Net.WebRequest]::DefaultWebProxy.Credentials = [Net.CredentialCache]::DefaultCredentials; iex ((New-Object Net.WebClient).DownloadSt
All our existing docs typically state that the user is running in a PowerShell session before running any code. I think it's best to follow that pattern here, and avoid being overly brief as well. Code examples in docs should be as legible as possible. If we assume the user is in a PowerShell session already, we can write this code as:

```powershell
[System.Net.WebRequest]::DefaultWebProxy.Credentials = [System.Net.CredentialCache]::DefaultCredentials
Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

Setting the path isn't typically necessary; the Chocolatey installer generally does this already. Did you have issues without setting the PATH values?

2022-01-07 20:57 UTC, vexx32 commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +4. This solution completely resolves the issue around installing chocolatey behind proxy using the command to force the WebRequest to use the Default Credentials for the proxy setting.
These two "steps" are saying the same thing in the same way, and they're also not actionable steps, so would probably be better condensed into a follow up sentence rather than being part of the list of steps.

2022-01-07 20:57 UTC, vexx32 commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +For more information, kindly refer to this link https://duanenewman.net/blog/post/installing-chocolatey-behind-a-corporate-proxy/ or https://stackoverflow.com/questions/30897204/how-do-i-install-choc
I'm not really sure where we sit on linking to other sites to be honest. There is some credit due to folks who found solutions, but given the docs are generally intended to be the source of truth as much as possible, it feels... odd... to be linking to someone else's pages for information on our own products.

I think it might be better to avoid the links. Does anyone else have any strong opinions on this? @pauby @gep13?

2022-09-15 15:09 UTC, vexx32 commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +For more information, kindly refer to this link https://duanenewman.net/blog/post/installing-chocolatey-behind-a-corporate-proxy/ or https://stackoverflow.com/questions/30897204/how-do-i-install-choc
@gep13 thoughts on whether we should take this change as-is, or remove these links?

2022-09-15 15:25 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +For more information, kindly refer to this link https://duanenewman.net/blog/post/installing-chocolatey-behind-a-corporate-proxy/ or https://stackoverflow.com/questions/30897204/how-do-i-install-choc
I would remove the links from this part of the docs. We can add them under [here](https://docs.chocolatey.org/en-us/information/learning-resources/resources#community).

2022-09-15 17:55 UTC, vexx32 commented
@gep13 I've updated this PR according to the review comments I left, this should be good for a review and merge

2023-01-31 12:44 UTC, pauby approved these changes

2023-01-31 12:54 UTC, pauby commented
@gep13 can you re-review and merge?

2023-04-10 10:16 UTC, gep13 approved these changes
LGTM!

2023-04-10 10:27 UTC, merged

2023-04-10 10:27 UTC, gep13 commented
@tijazz @vexx32 thank you both for getting this updated!