(doc) Release notes for CCM v0.7.0
chocolatey/docs pull request #290
Opened 2021-11-16 10:32 UTC by AdmiringWorm

This This puquest adds the upcoming release notes with the included changes for CCM 0.7.0.

2021-11-16 16:19 UTC, pauby requested changes

2021-11-16 16:19 UTC, pauby commented on input/en-us/central-management/release-notes.md
> +   * Previously sent Email Addresses where the email can be activated, or a Password Reset can be initiated will be made invalid after a passphrase change.
```suggestion
* Encryption passphrase is required.
   * To enhance the security of sensitive fields in the database we require the encryption passphrase to be set to a value you provide.
   * When any user with the CCM Administrator role logs in they will be redirected to the Settings page where the passphrase can be changed.
   * The passphrase change can be deferred but on the 5th login it will be required to set this passphrase before any other changes can be made.
   * Users who are not a member of the CCM Administrator role will only be shown a warning that the passphrase needs to be changed and to contact their Administrator to do so.
   * The links provided in email activation or password reset emails that were sent prior to the passphrase change will no longer be valid. The user clicking the link will be directed to a page where they can request them again.
```

2021-11-16 16:19 UTC, pauby commented on input/en-us/central-management/release-notes.md
> + * Fix - Central Management - Sensitive Package Parameters Shown in DB & Deployment Step Page - see [Licensed #267](https://github.com/chocolatey/chocolatey-licensed-issues/issues/267)
```suggestion
 * Fix - CCM - Sensitive package parameters shown in database & Deployment step page - see [Licensed #267](https://github.com/chocolatey/chocolatey-licensed-issues/issues/267).
```

2021-11-16 16:19 UTC, pauby commented on input/en-us/central-management/release-notes.md
> + * API - Hide Token API endpoints from Swagger documentation
```suggestion
 * API - Hide token API endpoints from Swagger documentation.
```

2021-11-16 16:19 UTC, pauby commented on input/en-us/central-management/release-notes.md
> + * Web - Update jQuery dependency - see [Licensed #271](https://github.com/chocolatey/chocolatey-licensed-issues/issues/271)
```suggestion
 * Web - Update jQuery dependency - see [Licensed #271](https://github.com/chocolatey/chocolatey-licensed-issues/issues/271).
```

2021-11-17 10:13 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +### ENHANCEMENTS
```suggestion
### ENHANCEMENTS
 * Web - Ability to add sensitive variables to advanced PowerShell deployment steps - see [documentation](https://docs.chocolatey.org/en-us/central-management/usage/website/sensitive-variables)
```

2021-11-17 10:13 UTC, gep13 requested changes
Small suggested change

2021-11-17 10:17 UTC, gep13 approved these changes
LGTM!

2021-11-17 10:31 UTC, pauby approved these changes

2021-11-17 12:03 UTC, gep13 approved these changes
LGTM!

2021-11-17 12:03 UTC, merged

2021-11-17 12:03 UTC, gep13 commented
@AdmiringWorm thanks for getting these created!