(doc) Add documentation for Commercial Validation Rule
chocolatey/docs pull request #293
Opened 2021-11-18 10:35 UTC by AdmiringWorm

This is basic documentation for the upcoming rule that validates if packages make use of commercial cmdlets in their automation scripts or not.
The cmdlets is not called out specifically as these can change between versions.

ref: https://github.com/chocolatey/home/issues/76

2021-11-19 18:58 UTC, pauby requested changes

2021-11-19 18:58 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0071.md
> +Description: Information on how to remediate the Chocolatey Package Moderation Rule 0071
```suggestion
Description: Information on how to remediate the Chocolatey Package Moderation Rule 0071.
```

2021-11-19 18:58 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0071.md
> +In an automation script (`.ps1`/`.psm1`), one or more calls to a commercial function that is only available in commercial editions of Chocolatey is being used.
```suggestion
In an automation script (`.ps1`/`.psm1`), one or more calls to a licensed function that is only available in licensed editions of Chocolatey, is being used.
```

2021-11-19 18:58 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0071.md
> +Please do not use commercial features when creating packages that you will push to the Community repository. Update all automation scripts to use functions that are available in Open Source Chocolate
```suggestion
Please do not use licensed features when creating packages that you will submit to the Chocolatey Community Repository. Update all automation scripts to use functions that are available in open-source Chocolatey.
```

2021-11-19 18:58 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0071.md
> +Packages created with commercial features should not be made available in Chocolatey Community Repository and are meant to be used by businesses by hosting the package in their internal repository.
```suggestion
Packages created with licensed features should not be made available in the Chocolatey Community Repository and are intended for use by organizations hosting their own internal package repository.
```

2021-11-19 18:58 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0071.md
> +All packages submitted to the Chocolatey Community Repository are for the community and should work on all editions available for Chocolatey.
```suggestion
All packages submitted to the Chocolatey Community Repository are for the community and should work on all editions of Chocolatey.
```

2021-11-25 09:53 UTC, gep13 approved these changes
LGTM!

2021-11-25 10:15 UTC, pauby approved these changes

2021-11-25 10:15 UTC, merged

2021-11-25 10:16 UTC, pauby commented
Awesome work @AdmiringWorm! Thanks for your contribution!