(#291) Add documentation around Passphrase Encryption
chocolatey/docs pull request #294
Opened 2021-11-18 13:56 UTC by AdmiringWorm

This pull request adds some documentation around the new
functionality for encryption and its use of the Passphrase.

fixes #291

2021-11-18 19:46 UTC, pauby requested changes
Are the numbered bullets not supposed to be 1. each time? I thought they were but maybe I was wrong.

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +Description: Information on the Encryption Passphrase within Chocolatey Central Management
```suggestion
Description: Information on the Encryption Passphrase within Chocolatey Central Management.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +Starting in Chocolatey Central Management 0.7.0 we are giving the ability to control the passphrase being used when encrypting secret values and certain requests that happens between both the website
```suggestion
Starting in Chocolatey Central Management 0.7.0 we are providing the ability to control the passphrase that is used when encrypting both secret values and certain requests that happen between the website and the service.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The Encryption Passphrase can be changed by accessing the Administrator -> Settings section and selecting the tab called Security of Chocolatey Central Management. The settings for the encryption pas
```suggestion
The encryption passphrase can be changed in Chocolatey Central Management by accessing the `Administrator -> Settings` section and selecting the `Security` tab. The settings for the encryption passphrase will only be visible to users who are a member of the CCM Administrator role.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +> We recommend to set this passphrase as soon as possible, and we will enforce this after users in the CCM Administrator Role have logged in after 5 times.
```suggestion
> We recommend this passphrase is set as soon as possible. However, a user who is a member of the CCM Administrator role will be able to defer this for 4 logins. On the 5th login they will be restricted to only being able to set the passphrase.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +> Changing the Encryption Passphrase will make existing emails sent out for Email Activation, and Password Resets contain invalid links. A user will be notified of this when they follow such links, a
```suggestion
> Changing the encryption passphrase will invalidate the links in Email Activation and Password Resets emails sent out prior to the change. The user clicking on the invalid link will be notified of this, and will be requested to enter their information again to have a new email sent.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +> During this time, any user browsing the Central Management or calls to the API may result in a request being returned as `500 - Internal Server Error`.
```suggestion
> ```suggestion
> Once the passphrase has been changed and saved, there will be a short delay while both the website and the API are updated. During that time they will be unavailable for any other use and browsing the website or calling the API may result in a `500 - Internal Server Error` response.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +1. Navigate to the `Administrator -> Settings` section of Central Management, and click on the `Security` tab to show the location that new a new passphrase can be set (_New `CCM Admin` Logins will b
```suggestion
1. Navigate to the `Administrator -> Settings` section of Central Management, and click on the `Security` tab to show the location that a new passphrase can be set (_New `CCM Admin` Logins will be redirected to this location_).
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +2. Enter the passphrase to use in the box labeled as `New Passphrase`.
```suggestion
2. Enter the passphrase to use in the box labeled `New Passphrase`.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > The new passphrase must contain the following information:
```suggestion
   > The new passphrase must meet the following requirements:
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > 3. At least 1 uppercase character (`a-z`).
```suggestion
   > 3. At least 1 uppercase character (`A-Z`).
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +3. Enter the same passphrase in the box labeled as `Confirm New Passphrase`.
```suggestion
3. Enter the same passphrase in the box labeled `Confirm New Passphrase`.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > Chocolatey Software, Inc. will not be responsible for any misplaced passphrases or restoring the database if the passphrase have been forgotten.
```suggestion
   > Chocolatey Software, Inc. will not be responsible for any misplaced passphrases or restoring the database if the passphrase has been forgotten or lost.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > Depending on the performance of the Machine running the Central Management, this may take between 5-10 seconds (in rare cases more).
```suggestion
   > Depending on the performance of the Machine running Chocolatey Central Management, this may take between 5 and 10 seconds (in some cases more).
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > During this time it is not recommended to navigate to any other pages, or making any API calls as these may result in an error.
```suggestion
   > During this time it is not recommended to navigate to any other pages, or make any API calls as these may result in an error.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > A dialog to refresh the page will displayed to refresh the page once the changes have completed.
```suggestion
   > A dialog to refresh the page will displayed once the changes have completed.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +5. Users following links for email activation or password resets will be granted with the following information and need to enter their information again.
```suggestion
5. Users following links for email activation or password resets will be see the following. They will need to renter their information to get a new email sent.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +## Changes to navigation
```suggestion
## Additional warnings that may be seen

We have added a number of warnings to help highlight that chanegs need to be made, where and by whom. Please see these screen below.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   ![Central Management Settings, encryption passphrase location](/assets/images/ccm/encryption-passphrase/ccm-admin-encryption-location.png)
```suggestion
   ![Chocolatey Central Management Settings, encryption passphrase location](/assets/images/ccm/encryption-passphrase/ccm-admin-encryption-location.png)
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   ![Central Management, Email Activation Link Invalid](/assets/images/ccm/encryption-passphrase/ccm-email-activation-link-invalid.png)
```suggestion
   ![Chocolatey Central Management, invalid Forgot Password link ](/assets/images/ccm/encryption-passphrase/ccm-reset-password-link-invalid.png)
   ![Chocolatey Central Management, invalid Email Activation link](/assets/images/ccm/encryption-passphrase/ccm-email-activation-link-invalid.png)
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +  ![Central Management Settings, encryption passphrase required](/assets/images/ccm/encryption-passphrase/ccm-admin-encryption-required.png)
```suggestion
- Before a user is logged in, they will see a warning on the login screen confirming that additional changes need to be made by a user who is a member of the CCM Administrator role.

  ![Chocolatey Central Management Login warning, pointing out changes are needed](/assets/images/ccm/encryption-passphrase/ccm-login-warning.png)
- If a user is logged in, but is not in the CCM Administrator role, the same warning is displayed to the user.

  ![Chocolatey Central Management Dashboard warning for normal users](/assets/images/ccm/encryption-passphrase/ccm-normal-user-warning.png)
- A user that is a member of the CCM Administrator role, will be redirected to set the encryption passphrase, when they log in.

  ![Chocolatey Central Management Settings, encryption passphrase location](/assets/images/ccm/encryption-passphrase/ccm-admin-encryption-location.png)

- A user that is a member of the CCM Administrator role, will be able to navigate to other sections of Chocolatey Central Management when they have not set the encruption passphrase and have logged in less than 5 times.

  ![Chocolatey Central Management Dashboard warning on Administrators](/assets/images/ccm/encryption-passphrase/ccm-admin-user-warning.png)

- On the 5th and subsequent logins, a user who is a member of the CCM Administrator role will be redirected to set the encryption passphrase and will not be able to navigate to other sections of Chocolatey Central Management unti the passphrase has been set.
  > :memo: **NOTE**
  >
  > A user who is not a member of the CCM Administrators role will still be available to use Chocolatey Central Management website and API, as normal .

  ![Chocolatey Central Management Settings, encryption passphrase required](/assets/images/ccm/encryption-passphrase/ccm-admin-encryption-required.png)
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The encryption passphrase is the password (along with a salt value) that will be used to encrypt certain settings in the database, as well as some requests and/or links in sent emails uses this encry
```suggestion
The encryption passphrase is the password (along with a salt value) that will be used to encrypt sensitive settings in the database, as well as links in Password Reset and Email Activation emails.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The new functionality for [`Sensitive Variables`](xref:ccm-sensitive-variables) will use the passphrase when encrypting and decrypting the values, some settings like the SMTP and LDAP passwords uses
```suggestion
The following items are encrypted using the passphrase:

- [`Sensitive Variables`](xref:ccm-sensitive-variables) when encrypting and decrypting the values.
- SMTP and LDAP passwords.
- Links used in Email Activation and Password Reset emails.
```

2021-11-18 19:46 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +This is done for your own security, so that all encrypted values are encrypted with a unique passphrase for your organization only, instead of using a passphrase that is shared between all Central Ma
```suggestion
We have enhanced the security of fields stored in the database to use encryption that requires a unique passphrase that you control and can change if/when needed. This allows you to ensure the encryption passpharse is always secure, regularly updated and meets the standards of your organization.
```

2021-11-19 09:17 UTC, AdmiringWorm commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +5. Users following links for email activation or password resets will be granted with the following information and need to enter their information again.
This suggestion sounds a bit incomplete and possibly broken. Should it be:

```suggestion
5. Users following links for email activation or password resets will see the following. They will need to re-enter their information to get a new email sent.
```

2021-11-19 18:54 UTC, pauby requested changes
Some things I missed. Apologies @AdmiringWorm

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > During this time it is not recommended to navigate to any other pages, or make any API calls as these may result in an error.
```suggestion
   > This will take between 5 and 10 seconds but could take more depending on performance.
   > During this time it is not recommended to navigate to any other pages or make any API calls as they may result in an error.
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +   > 1. A length equal to or higher than 5 characters.
```suggestion
   > 1. A length equal to, or higher than, 5 characters.
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +5. Users following links for email activation or password resets will see the following. They will need to re-enter their information to get a new email sent.
```suggestion
5. Users following links for email activation or password resets will need to re-enter their information to have a new email sent.
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The same procedure can be followed as was detailed in the `Set the encryption passphrase for the first time` section.
```suggestion
The same procedure can be followed as was detailed in the [`Set the encryption passphrase for the first time`](#set-the-encryption-passphrase-for-the-first-time) section above.
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The same procedure can be followed as was detailed in the `Set the encryption passphrase for the first time` section.
I'm fairly sure that link is correct.

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The only difference is that a user will have to enter the previous/current passphrase as well as the new passphrase.
```suggestion
The only difference is that the current passphrase, as well as the new passphrase, will have to be entered.
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +We have added a number of warnings to help highlight that changes need to be made, where and by whom. Please see these screen below.
```suggestion
We have added a number of warnings to help highlight that changes need to be made, where and by whom. Please see these screenshots below.
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +### What _things_ are encrypted using the passphrase?
```suggestion
### What items are encrypted using the passphrase?
```

2021-11-19 18:54 UTC, pauby commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +- [`Sensitive Variables`](xref:ccm-sensitive-variables) when encrypting and decrypting the values.
```suggestion
- [`Sensitive Variables`](xref:ccm-sensitive-variables).
```

2021-11-24 10:56 UTC, AdmiringWorm commented
> Are the numbered bullets not supposed to be 1. each time? I thought they were but maybe I was wrong.

Sorry, had missed this initially, and just noticed the comment now.

It doesn't really matter whether they are 1. each time, or if they are some other number.
As long as it is a number it should create a numbered list.

I can change everything to be 1 though if that is preferred.

2021-11-24 11:13 UTC, AdmiringWorm commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +The same procedure can be followed as was detailed in the `Set the encryption passphrase for the first time` section.
To be completely certain, I'll force the id of the header it should reference to use the same identifier. So if it is changed, we don't have to update the link itself.

2021-11-24 11:14 UTC, AdmiringWorm commented on input/en-us/central-management/usage/website/encryption-passphrase.md
> +## Set the encryption passphrase for the first time
```suggestion
## Set the encryption passphrase for the first time { #set-the-encryption-passphrase-for-the-first-time }
```

To set a fixed id for the header, since we reference it further down.

2021-11-24 11:22 UTC, AdmiringWorm commented
@pauby I have updated according to your review, I also set the id of the `Set the encryption passphrase for the first time` header to a fixed id, so even if the header changes we don't need to update any links to it.

2021-11-25 13:49 UTC, pauby approved these changes

2021-11-25 13:49 UTC, merged

2021-11-25 13:49 UTC, pauby commented
Awesome work @AdmiringWorm! Thanks for your contribution!