Update of CCM Compatibility Matrix and Outdated Info on Page
chocolatey/docs pull request #332
Opened 2022-01-20 02:13 UTC by ryanrichter94

## Description Of Changes
- Updated CCM Compatibility Matrix to include all releases up to current (0.7.0).
- Got rid of mentions of QDE and replaced with QSG and Azure QDE
- Added API and ChocoCCM to links section of page
- Other small formatting or deleting of redundant info.
- 
## Motivation and Context
The page in general had a lot of out of date or needing updated info. 

## Testing
Previewing changes via local Statiq build.

## Change Types Made
* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.
* [X] Docs Updates

## Related Issue

Fixes #331 

## Change Checklist

* [X] Requires a change to the documentation
* [X] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [X] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

2022-02-04 21:48 UTC, steviecoaster submitted a review, later dismissed

2022-02-04 21:48 UTC, steviecoaster commented on input/en-us/central-management/index.md
> +* You can standup CCM from one powershell script as part of our [C4B Quick Start Guide](xref:c4b-quick-start-guide). Allowing you setup an entire Chococlatey enviornment in just 6 simple steps.
```suggestion
* As part of our [C4B Quick Start Guide](xref:c4b-quick-start-guide)
```

2022-02-04 21:48 UTC, steviecoaster commented on input/en-us/central-management/index.md
> +* CCM is stood up as part of our [C4B Azure Enviornment](xref:qdeazure)
```suggestion
* As part of our [C4B Azure Enviornment](xref:qdeazure)
```

2022-02-04 21:48 UTC, steviecoaster commented on input/en-us/central-management/index.md
> +* You can also setup CCM on its own following the [CCM Setup Docs](xref:ccm-setup)
```suggestion
* By following the [CCM Setup Docs](xref:ccm-setup)
```

2022-03-11 10:55 UTC, pauby requested changes
We need to avoid using abbreviations for our products and spell it out completely. Some people will have no idea what CCM / C4B stand for and we shouldn't assume that everybody does.

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* Chocolatey (`chocolatey` package)
```suggestion
* Chocolatey CLI (`chocolatey` package)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* CCM Database (`chocolatey-management-database` package)
```suggestion
* Chocolatey Central Management Database (`chocolatey-management-database` package)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* CCM Service (`chocolatey-management-service` package)
```suggestion
* Chocolatey Central Management Service (`chocolatey-management-service` package)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* CCM Website (`chocolatey-management-web` package)
```suggestion
* Chocolatey Central Management Website (`chocolatey-management-web` package)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
>  ### CCM Component Compatibility Matrix
```suggestion
### Chocolatey Central Management Component Compatibility Matrix
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
>    * This is the CCM front end website that is the main user interface of the application
```suggestion
  * This is the Chocolatey Central Management front-end website that is the main user interface of the application.
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* [Central Management Release Notes](xref:ccm-release-notes)
```suggestion
* [Chocolatey Central Management Release Notes](xref:ccm-release-notes)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +### Central Management API
```suggestion
### Chocolatey Central Management API
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* [CCM API](xref:ccm-api)
```suggestion
* [Chocolatey Central Management API](xref:ccm-api)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* [C4B Quick Start Guide(QSG)](xref:c4b-quick-start-guide)
```suggestion
* [Chocolatey For Business Quick Start Guide(QSG)](xref:c4b-quick-start-guide)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* [C4B Azure Enviornment](xref:qdeazure)
```suggestion
* [Chocolatey For Business Azure Enviornment](xref:qdeazure)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* [CCM Development Roadmap](xref:roadmap#chocolatey-central-management)
```suggestion
* [Chocolatey Central Management Development Roadmap](xref:roadmap#chocolatey-central-management)
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +See [CCM Component Compatibility Matrix](#ccm-component-compatibility-matrix).
```suggestion
See [Chocolatey Central Management Component Compatibility Matrix](#ccm-component-compatibility-matrix).
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +Please see [Central Management Release Notes](xref:ccm-release-notes).
```suggestion
Please see [Chocolatey Central Management Release Notes](xref:ccm-release-notes).
```

2022-03-11 10:55 UTC, pauby commented on input/en-us/central-management/index.md
> +* By following the [CCM Setup Docs](xref:ccm-setup)
```suggestion
* As part of our [Chocolatey For Business Quick Start Guide](xref:c4b-quick-start-guide). Allowing you setup an entire Chococlatey enviornment in just 6 simple steps.
* As part of our [Chocolatey For Business Azure Enviornment](xref:qdeazure)
* By following the [Chocolatey Central Management Setup Docs](xref:ccm-setup)
```

2022-04-12 15:44 UTC, pauby submitted a review, later dismissed

2022-04-12 15:44 UTC, pauby commented on input/en-us/central-management/index.md
>  Central Management has specific needs that are mostly handled by packaging aspects. As the Chocolatey Agent and Central Management communicate with each other, there are some versions that may not be
```suggestion
Chocolatey Central Management has specific needs that are mostly handled by packaging aspects. As the Chocolatey Agent and Chocolatey Central Management communicate with each other, there are some versions that may not be compatible with each other due to mistakes or fixes that needed to be implemented. This serves as a means of capturing that for you.
```

2022-04-12 15:44 UTC, pauby commented on input/en-us/central-management/index.md
>  > Central Management packages (all three) are treated as a singular unit, meaning all three packages across one or more machines must all be on the same version. Using different versions of Central M
```suggestion
> Chocolatey Central Management packages are treated as a singular unit, meaning that they all must all be on the same version across one or more machines. Using different versions of Chocolatey Central Management packages is unsupported and will likely not work properly.
```

2022-04-12 15:44 UTC, pauby commented on input/en-us/central-management/index.md
>  > Central Management packages (all three) are treated as a singular unit, meaning all three packages across one or more machines must all be on the same version. Using different versions of Central M
I removed the reference to the individual packages or 'three' so that we don't have to revisit this in future if we ever change the number / type of them.

2022-04-12 15:44 UTC, pauby commented on input/en-us/central-management/index.md
>  CCM will only be available in Chocolatey for Business (C4B).
```suggestion
Chocolatey Central Management will only be available in Chocolatey for Business (C4B).
```

2022-04-12 15:44 UTC, pauby commented on input/en-us/central-management/index.md
>  CCM will only be available in Chocolatey for Business (C4B).
I know this was one of your changes but I saw it and we should update it for consistency.

2022-04-12 15:44 UTC, pauby commented on input/en-us/central-management/index.md
>  ### What's the minimum version of the Chocolatey packages I need to use CCM?
```suggestion
### What's the minimum version of the Chocolatey packages I need to use Chocolatey Central Management?
```

2022-04-13 20:11 UTC, ryanrichter94 commented on input/en-us/central-management/index.md
>  > Central Management packages (all three) are treated as a singular unit, meaning all three packages across one or more machines must all be on the same version. Using different versions of Central M
makes sense. good suggestion

2022-04-13 20:14 UTC, ryanrichter94 commented
@pauby Pushed final wording changes hopefully. I bumped the versions listed for CCM 0.8.0 in the table because of the agent changes we put in [chocolatey-agent V0.13.0](https://docs.chocolatey.org/en-us/agent/release-notes#breaking-changes).

2022-09-05 13:14 UTC, gep13 approved these changes
LGTM!

2022-09-05 13:15 UTC, gep13 commented
@ryanrichter94 thanks for getting this updated, and apologies that this took so long!

2022-09-05 13:30 UTC, gep13 approved these changes
LGTM!

2022-09-05 13:30 UTC, merged