Added release notes for GUI 0.20.0
chocolatey/docs pull request #373
Opened 2022-02-09 15:01 UTC by gep13

## Description Of Changes

Added in the release notes for Chocolatey GUI 0.20.0

## Motivation and Context

This is shipping soon, and we need the release notes to be there ready for notifications.

## Testing

1. Ran the .\preview.ps1 and looked at the output

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.

## Related Issue

N/A

## Change Checklist

* [x] Requires a change to the documentation
* [x] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

2022-02-09 18:27 UTC, pauby requested changes

2022-02-09 18:27 UTC, pauby commented on input/en-us/chocolatey-gui/release-notes.md
> +## [0.20.0]() (February 10, 2022)
You adding the milestone link in later?

2022-02-09 18:27 UTC, pauby commented on input/en-us/chocolatey-gui/release-notes.md
> +> If you use Chocolatey GUI alongside the Chocolatey GUI Licensed Extension, if you install v0.29.0 of Chocolatey GUI then you will also have to install v0.4.0 of Chocolatey GUI Licensed Extension, o
```suggestion
> If you install v0.20.0 of Chocolatey GUI then you will also have to install v0.4.0 of Chocolatey GUI Licensed Extension if you use it. You will see errors when attempting to run Chocolatey GUI if you do not do so.
```

2022-02-10 08:38 UTC, gep13 commented on input/en-us/chocolatey-gui/release-notes.md
> +## [0.20.0]() (February 10, 2022)
Indeed!

2022-02-10 08:40 UTC, gep13 commented
@pauby I have fixed up the requested changes, can you take another look?

2022-02-10 11:19 UTC, pauby approved these changes

2022-02-10 11:29 UTC, merged