Add release notes for Chocolatey Agent 0.13.0
chocolatey/docs pull request #392
Opened 2022-02-24 11:08 UTC by gep13

## Description Of Changes

Add release notes for v0.13.0 of Chocolatey Agent

## Motivation and Context

We we releasing v0.13.0 of Chocolatey Agent, and we need to capture the release notes.

## Testing

Ran the site locally to verify that it looks correct.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes

## Related Issue

N/A

## Change Checklist

* [ ] Requires a change to the documentation
* [x] Documentation has been updated

2022-02-24 12:49 UTC, pauby requested changes

2022-02-24 12:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
What's a 'WCF interfaces / contract'? Remember these are written for the end users.

Can we also say 'Chocolatey Central Management' and not CCM or Central Management? I haven't changed 'issues' in the Improvements  section because they are issue titles.

2022-02-24 12:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +  - **NOTE:** There is no hard requirement to update to CCM 0.8.0 as this version of Chocolatey Agent will work in a backwards compatible way, but we do recommend updating to the latest version of CC
```suggestion
  - **NOTE:** This version of Chocolatey Agent is backwards compatible with versions of Chocolatey Central Management earlier than 0.8.0. However, we always recommend updating to the latest version of Chocolatey Central Management.
```

2022-02-24 12:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +- Central Management
```suggestion
- Chocolatey Central Management
```

2022-02-24 12:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +  - Add logic to retry reporting of a deployment step result to CCM if it initially fails
```suggestion
  - Add logic to retry reporting of a deployment step result to CCM if it initially fails.
```

2022-02-24 12:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +  - Ensure that no expanded sensitive variables are captured in log that is returned to CCM
```suggestion
  - Ensure that no expanded sensitive variables are captured in log that is returned to CCM.
```

2022-02-24 13:08 UTC, gep13 commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
Happy to take suggestions on how else to say this.  WCF is Windows Communication Foundation, and it is how Chocolatey Agent communicates with Chocolatey Central Management.

2022-02-24 13:13 UTC, pauby commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
I know we both know what they are. But that is a technical description of a change. If you had to explain that to somebody who doesn't know, what would we say?

'Enhanced communication method for reporting information in Chocolatey Central Management'?

2022-02-24 13:14 UTC, pauby commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
As this doesn't requires a new version of Chocolatey Central Management, is it a breaking change?

2022-02-24 13:20 UTC, gep13 commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
Yes, according to the new procedure that I followed:

> Changes to dependencies or other prerequisites should be noted in a warning at the top of the release notes and is regarded as a BREAKING CHANGE.

2022-02-24 15:09 UTC, pauby commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
What dependencies are changing?

2022-02-24 15:11 UTC, gep13 commented on input/en-us/agent/release-notes.md
> +- Central Management - Use new WCF interfaces/contracts when reporting information into CCM
Chocolatey Agent has a dependency on Chocolatey Licensed Extension where the new enhanced communication mechanism is defined, and it needs to use the latest 3.2.0 version.

2022-02-25 16:38 UTC, pauby approved these changes

2022-02-28 11:03 UTC, merged