(docs) Initial commit of ccm roles page
chocolatey/docs pull request #405
Opened 2022-03-10 21:36 UTC by ryanrichter94

## Description Of Changes
Added roles page to ccm docs.

## Motivation and Context
Often get asked about certain permissions in CCM and noticed we have no documentation on CCM roles.

## Testing
Build locally using statiq preview.

## Change Types Made

* [ ] Bug fix (non-breaking change)
* [ ] Feature / Enhancement (non-breaking change)
* [ ] Breaking change (fix or feature that could cause existing functionality to change)
* [ ] PowerShell code changes.
* [X] Docs addition

## Related Issue
#402 #237 

Fixes #

## Change Checklist

* [X] Requires a change to the documentation
* [X] Documentation has been updated
* [ ] Tests to cover my changes, have been added
* [ ] All new and existing tests passed.
* [ ] PowerShell v2 compatibility checked.

2022-03-11 11:13 UTC, pauby requested changes
Some fixes to language, typos and a few for clarification.

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> If you do not see the **Edit** menu entry or the :gear: **Actions** buttons, consult your administrator to determine if your Central Management account has _Edit Roles_ permissions.
```suggestion
> If you do not see the **Edit** menu entry or the :gear: **Actions** buttons, please see your Administrator to determine if your account has the _Edit Roles_ permission.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +You can also use the _Select Permissions (0)_ modal to filter the roles listed based on them having the permissions you select within the modal.
```suggestion
You can also use _Select Permissions (0)_ to filter the Roles based on the permissions you select.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +Select the :gear: **Actions** button on the left-hand side of the role, and then select **Edit** to open the _Edit Group_ modal.
```suggestion
Select the :gear: **Actions** button on the left-hand side of the role, and then select **Edit** to open the _Edit Group_ window.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +From the **Edit Role** modal, you can modify the role name, optinally set ti to be the defualt role, an edit its permissions.
```suggestion
From the **Edit Role** window, you can modify the name, set it to be the Default role and edit its permissions.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> If you do not see the **Delete** menu entry or the :gear: **Actions** buttons, consult your administrator to determine if you have the appropriate permissions assigned to your account.
```suggestion
> If you do not see the **Delete** menu entry or the :gear: **Actions** buttons, please see your Administrator to determine if you have the appropriate permissions assigned to your account.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> If a role is listed as **Static** next to its name. It cannot be deleted.
```suggestion
> Roles labelled **Static** cannot be deleted.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> You cannot delete a role while being logged into Central Management as a user assigned to the role you are trying to delete.
```suggestion
> You cannot delete a Role if the account you are using also has the  Role assigned to it.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +On the main Roles page, find the role you want to delete. You can also use the _Select Permissions (0)_ modal to filter the roles listed based on them having the permissions you select within the mod
```suggestion
On the main Roles page, find the role you want to delete. You can also use _Select Permissions (0)_ to filter the roles listed based on permission. Similar to the [Edit Role](#editing-a-role) action, select the :gear: **Actions** button on the left-hand side of the role, and  select **Delete**. You will be prompted to confirm the deletion.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +When first browsing to the roles page you'll be presented with 5 pre-configured roles that come with Central Management out of box.
```suggestion
When first browsing the Roles page, you'll be presented with 5 pre-configured roles that are built-in to Chocolatey Central Management.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +These pre-configured roles are labeled as static and cannot be deleted. They can however be edited by name, default role selection, and permissions.
```suggestion
These pre-configured roles are labeled as **Static** and cannot be deleted. They can however be edited by name, default role selection, and permissions.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +We recommend you review the permissions these roles have. Then edit them, if needed, to work within your enviornment for the different user access levels you need.
```suggestion
We recommend you review the permissions these roles have. Then edit them, if needed, to work within your environment.
```

2022-03-11 11:13 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +* [Central Management - Reports](xref:ccm-reports)
```suggestion
* [Chocolatey Central Management - Deployments](xref:ccm-deployments)
* [Chocolatey Central Management - Reports](xref:ccm-reports)
```

2022-03-14 20:21 UTC, ryanrichter94 commented
Thanks for the wording review. Gosh I talk too much.

2022-04-12 15:36 UTC, pauby requested changes
A few typos and some changes to be consistent.

2022-04-12 15:36 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +You will then be presented with the Role properties window where you can enter the name for the new rule. You also have the option to make your new role the Default which will be added to all new use
```suggestion
You will then be presented with the Role properties window where you can enter the name for the new role. You also have the option to make your new role the Default which will be added to all new users by default.
```

2022-04-12 15:36 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> If you do not see the **Edit** menu entry or the :gear: **Actions** buttons, please see your administrator to determine if your account has the _Edit Roles_ permissions.
```suggestion
> If you do not see the **Edit** menu entry or the :gear: **Actions** buttons, please see your Administrator to determine if your account has the _Edit Roles_ permission.
```

2022-04-12 15:36 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +From the **Edit Role** window, you can modify the name, set it to be the Defualt role, and edit its permissions.
```suggestion
From the **Edit Role** window, you can modify the name, set it to be the Default role, and edit its permissions.
```

2022-04-12 15:36 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> If you do not see the **Delete** menu entry or the :gear: **Actions** buttons, please see your Administrator to determine if you have the appropriate permissions assigned to your account.
```suggestion
> If you do not see the **Delete** menu entry or the :gear: **Actions** buttons, please see your Administrator to determine if your account has the _Edit Roles_ permissions.
```

2022-04-12 15:36 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +> If you do not see the **Delete** menu entry or the :gear: **Actions** buttons, please see your Administrator to determine if you have the appropriate permissions assigned to your account.
Changed this here to make it consistent with the one above.

2022-04-12 15:36 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +When first browsing to the Roles page, you'll be presented with 5 pre-configured roles that are built-in to Central Management.
```suggestion
When first browsing to the Roles page, you'll be presented with 5 pre-configured roles that are built-in to Chocolatey Central Management.
```

2022-05-12 11:10 UTC, pauby requested changes
Just one small change. Otherwise looks good to me @ryanrichter94 !

2022-05-12 11:10 UTC, pauby commented on input/en-us/central-management/usage/website/roles.md
> +Title: Roles
```suggestion
Title: Chocolatey Central Management Roles
```

2022-05-12 21:02 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/roles.md
> +Title: Roles
@pauby I'm not a fan of this change as all the other website pages aren't labeled with Chocolatey Central Management. Feel this is the one place where short is good since having longer names in the left hand docs nav clutters things. Plus all of these pages are under the Chocolatey Central Management umbrella in the nav.

Picture of nav with this change in effect:

![image](https://user-images.githubusercontent.com/57045117/168166881-f88a0e35-ed84-49e8-9e2a-7a0bc34e7eb4.png)

2022-09-05 12:38 UTC, gep13 commented on input/en-us/central-management/usage/website/roles.md
> +Title: Roles
Agreed. TO remain consistent, we should leave this as `Roles`, at least for now, as there would need to be many other changes to make this done everywhere.

2022-09-05 12:39 UTC, gep13 approved these changes
LGTM!

2022-09-05 12:40 UTC, gep13 commented
@ryanrichter94 thank you for taking the time to get this added, and apologies for this taking so long to get merged in!

2022-09-05 12:46 UTC, merged