Add documentation of deployment statuses
chocolatey/docs pull request #424
Opened 2022-03-23 19:57 UTC by ryanrichter94

## Description Of Changes
commit 402: Add documentation of deployment statuses.
maint commit: general upkeep 

## Motivation and Context
Wanna explain the different CCM deployment statuses.

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
#237 
Fixes #402

2022-04-12 14:56 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +> Please see <https://blog.chocolatey.org/2020/05/announcing-deployments/> for now.
These `<` and `>` are not needed.

2022-04-12 20:46 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +> Please see <https://blog.chocolatey.org/2020/05/announcing-deployments/> for now.
Removed this section in (maint) Remove WIP status commit since this points to an old blog post from the release of CCM 0.3.0 that references QDE and when we first launched deployment. Feel it's better to remove entirely as the package is now up to date.

2022-04-13 11:32 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status is presented once a deployment enters the active state. It is now waiting for the next agent check-in to grab the deployment from CCM.
```suggestion
This deployment status is presented once a deployment enters the active state. It is now waiting for the next agent check-in to grab the deployment from Chocolatey Central Management.
```

2022-04-13 11:33 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status is given once the agent on the client machine accepts the deployment from CCM. It then begins processing the deployment and also reports back to Central Management that is has
```suggestion
This deployment status is given once the agent on the client machine accepts the deployment from Chocolatey Central Management. It then begins processing the deployment and also reports back to Chocolatey Central Management that is has started this deployment step.
```

2022-04-13 11:33 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status is reported when a deployment step has gone to active, but Central Management doesn't get a reply back as to the status of the deployment step running on the client machine. It
```suggestion
This deployment status is reported when a deployment step has gone to active, but Chocolatey Central Management doesn't get a reply back as to the status of the deployment step running on the client machine. It is best to look at the `chocolatey-agent.log` file from the client machine as to why it was not able to report back to Chocolatey Central Management.
```

2022-04-13 11:34 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +This status is reported when a deployment step or deployment as a whole cannot be interpreted by Central Management and placed into one of the other statuses. This should only happen in the case of a
```suggestion
This status is reported when a deployment step or deployment as a whole cannot be interpreted by Chocolatey Central Management and placed into one of the other statuses. This should only happen in the case of a bug. If you get this status please reach out to us via the means listed when running `choco support`.
```

2022-04-13 11:35 UTC, pauby commented
@ryanrichter94 I can review the content but @gep13 will need to review to see if it is correct (ie. the statuses).

2022-04-14 20:18 UTC, ryanrichter94 commented
Appreciate you running through and double checking the content @pauby. @gep13 This should be ready for your review now.

2022-05-12 10:17 UTC, pauby requested changes
Ryan this is awesome. Thanks for putting it together.

Most of the changes were about consistency with using 'Deployments' (big D) and headings. We go from a mix of Title case to not.  There is also a mix of using the word 'computer', 'client agent' and 'machine' where they all refer to the same thing, I didn't pick up on most of those as there were too many.

I think what we need to do is put together a guide for what we should do in documentation and this serves as a good guide to this.

My apologies for suggesting so many changes here.

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +This status is reported when a deployment step or deployment as a whole cannot be interpreted by Chocolatey Central Management and placed into one of the other statuses. This should only happen in th
```suggestion
This is a catch-all status when a Deployment step or whole Deployment does not the criteria to fit one of the other statuses. If you get this status please reach out to us via the means listed when running `choco support`.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  * Chocolatey Agents (`chocolatey-agent` package on all clients) - v0.11.0+
```suggestion
* Chocolatey Agent (`chocolatey-agent` package on all clients) - v0.11.0+
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +Chocolatey Central Management(CCM) has specific compatibility requirements with quite a few moving parts. It is important to understand that there are some Chocolatey Agent versions that may not be a
```suggestion
Chocolatey Central Management has specific compatibility requirements with quite a few moving parts. It is important to understand that there are some Chocolatey Agent versions that may not be able to communicate with some versions of Chocolatey Central Management and vice versa.  Please see the [Chocolatey Central Management Component Compatibility Matrix](xref:central-management#ccm-component-compatibility-matrix) for details.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +Chocolatey Central Management(CCM) has specific compatibility requirements with quite a few moving parts. It is important to understand that there are some Chocolatey Agent versions that may not be a
Because we always used the full name, using CCM in this one sentence wasn't consistent. So I thought I'd mention it.

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +If you are on the Groups screen, you may notice that some machines show up highlighted with a coloring, and one of those colorings is an orange - the legend below it mentions "Not Opted In For Deploy
```suggestion
If you are on the Groups screen, you may notice that some machines show up highlighted with an orange color. The legend below it mentions "Not Opted In For Deployments (Configuration)".
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +Likely you absolutely can, just keep in mind that there may be a specific ordering in how you would upgrade everything and adhere to that order. In some instances, you may need to upgrade agents firs
```suggestion
Likely you absolutely can, just keep in mind that there may be a specific ordering in how you would upgrade everything and adhere to that order. In some instances, you may need to upgrade agents first, then Chocolatey Central Management components as once CCM is upgraded it may not be able to talk to the agents. However agents will stop being able to talk to Chocolatey Central Management for a small period of time while you are upgrading it, but then things will start working again.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +Likely you absolutely can, just keep in mind that there may be a specific ordering in how you would upgrade everything and adhere to that order. In some instances, you may need to upgrade agents firs
@gep13 I don't think this is something we recommend or have tested? 

@ryanrichter94 has this been tested?

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  ### What Happens if More Than One Deployment is "Active" at the Same Time?
```suggestion
### What happens if more than one Deployment is "Active" at the same time?
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  ### What Happens if More Than One Deployment is "Active" at the Same Time?
Can you check the other headings? Either use Title case or don't. We just need to ensure we are consistent.

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +As of v0.4.0 of Chocolatey Central Management, this has been fine tuned a little bit so that any computer which is acted on by a deployment will not pick up any steps from unrelated deployments until
```suggestion
As of v0.4.0 of Chocolatey Central Management, this has been fine tuned so that any client machine that runs a Deployment will not pick up any steps from unrelated Deployments until all its assigned steps in the first Deployment are completed.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  ### Why do My Computers or Groups Show as Ineligible for Deployments While They're Opted In?
```suggestion
### Why do my Computers or Groups show as Ineligible for Deployments while they're opted in?
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>    * If the deployment is not scheduled, it cannot be started until all computers/groups are eligible again.
```suggestion
  * If the Deployment is scheduled, it will not run until all computers/groups are eligible again.
  * If the Deployment is not scheduled, it cannot be started until all computers/groups are eligible again.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +  Once Chocolatey Central Management has confirmed the problem computer(s)/group(s) are eligible again, the deployment can be started.
```suggestion
  Once Chocolatey Central Management has confirmed the problem computer(s)/group(s) are eligible again, the Deployment can be started.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +  * As soon as Chocolatey Central Management detects the ineligible computer, it will terminate the current deployment step.
```suggestion
  * As soon as Chocolatey Central Management detects the ineligible computer, it will terminate the current Deployment step.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>    * Then, all following deployment steps will be `Cancelled`.
```suggestion
  * Then, all following Deployment steps will be `Cancelled`.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  ### How Can I Run Deployments in a Semi-Connected Environment?
```suggestion
### How can I run Deployments in a semi-connected environment?
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
> +As of Chocolatey Central Management(CCM) v0.4.0, you are able to configure deployments to tolerate semi-connected environments.
```suggestion
As of Chocolatey Central Management v0.4.0, you are able to configure deployments to tolerate semi-connected environments.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  This effectively allows CCM deployments to simply wait until a machine is connected to the network before it begins a given deployment step.
```suggestion
This effectively allows Chocolatey Central Management Deployments to simply wait until a machine is connected to the network before it begins a given Deployment step.
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  ### A computer or group is not showing as available for deployments but I have plenty of available licenses
```suggestion
### A computer or group is not showing as available for Deployments but I have plenty of available licenses
```

2022-05-12 10:17 UTC, pauby commented on input/en-us/central-management/usage/website/deployments.md
>  ### Using `choco` commands in a script deployment break if semicolons are used to separate the statements
```suggestion
### Using `choco` commands in a Script Deployment breaks if semicolons are used to separate the statements
```

2022-05-12 20:24 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  Central Management's Deployments functionality allows for pre-defined actions to be executed across any Chocolatey-managed computers.
fixed

2022-05-12 20:28 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  Deployments that are in a completed state can also be `Archived` to hide them from the main Deployments screen.
thx, fixed.

2022-05-13 13:53 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  Central Management's Deployments functionality allows for pre-defined actions to be executed across any Chocolatey-managed computers.
fixed

2022-05-13 13:56 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  Deployments that are in a completed state can also be `Archived` to hide them from the main Deployments screen.
Thx. Fixed

2022-05-13 14:49 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +## Deployment Statuses
Took a stab at defining deployment state. As well as mentioning and linking to deployment statuses to differentiate them from states. Lastly explained that it all flows the same as the workflow show in the deployments tab of the CCM dashboard. 

Fully open to alternative ways/review of explaining this concept as i'll be honest, it's a bit difficult.

2022-05-13 14:53 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status is presented once a deployment enters the active state. It is now waiting for the next agent check-in to grab the deployment from Chocolatey Central Management.
fixed

2022-05-13 14:57 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status is reported when a deployment is queued up in Chocolatey Central Management. But the client machine agent is unable to receive or accept the deployment. This is usually the sta
fixed

2022-05-13 15:19 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status is reported when a deployment step has gone to active, but Chocolatey Central Management doesn't get a reply back as to the status of the deployment step running on the client
fixed

2022-05-13 15:21 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +This status is reported anytime a deployment step or deployment as a whole is manually cancelled by someone.
fixed

2022-05-13 15:37 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status indicates the step completed and reported back as successful.
fixed

2022-05-13 15:39 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +This deployment status indicates the deployment failed for some reason. You can click the `View Log` button on the individual deployment step to get more data as why the failure may have occurred.
fixed

2022-05-13 15:46 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  * Chocolatey Agents (`chocolatey-agent` package on all clients) - v0.11.0+
fixed

2022-05-13 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +Chocolatey Central Management(CCM) has specific compatibility requirements with quite a few moving parts. It is important to understand that there are some Chocolatey Agent versions that may not be a
fixed

2022-05-13 16:44 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +If you are on the Groups screen, you may notice that some machines show up highlighted with a coloring, and one of those colorings is an orange - the legend below it mentions "Not Opted In For Deploy
fixed

2022-05-13 16:56 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +Likely you absolutely can, just keep in mind that there may be a specific ordering in how you would upgrade everything and adhere to that order. In some instances, you may need to upgrade agents firs
Fixed with links to chocolatey-agent upgrade via CCM deployment and CCM itself upgrade documentation links.

2022-05-13 18:56 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  ### What Happens if More Than One Deployment is "Active" at the Same Time?
Capitalized all heading according to APA writing style using https://capitalizemytitle.com/style/APA/#

2022-05-13 19:02 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  ### Why do My Computers or Groups Show as Ineligible for Deployments While They're Opted In?
fixed when styling all titles to APA Title Case.

2022-05-13 19:03 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +As of v0.4.0 of Chocolatey Central Management, this has been fine tuned a little bit so that any computer which is acted on by a deployment will not pick up any steps from unrelated deployments until
fixed

2022-05-13 19:05 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>    * If the deployment is not scheduled, it cannot be started until all computers/groups are eligible again.
fixed

2022-05-13 19:05 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +  Once Chocolatey Central Management has confirmed the problem computer(s)/group(s) are eligible again, the deployment can be started.
fixed

2022-05-13 19:06 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +  * As soon as Chocolatey Central Management detects the ineligible computer, it will terminate the current deployment step.
fixed

2022-05-13 19:06 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>    * Then, all following deployment steps will be `Cancelled`.
fixed

2022-05-13 19:06 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  ### How Can I Run Deployments in a Semi-Connected Environment?
fixed part of titles.

2022-05-13 19:08 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
> +As of Chocolatey Central Management(CCM) v0.4.0, you are able to configure deployments to tolerate semi-connected environments.
fixed

2022-05-13 19:09 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  This effectively allows CCM deployments to simply wait until a machine is connected to the network before it begins a given deployment step.
fixed

2022-05-13 19:09 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  ### A computer or group is not showing as available for deployments but I have plenty of available licenses
title fixed

2022-05-13 19:11 UTC, ryanrichter94 commented on input/en-us/central-management/usage/website/deployments.md
>  ### Using `choco` commands in a script deployment break if semicolons are used to separate the statements
title fixed

2022-05-13 19:23 UTC, ryanrichter94 commented
Hopefully addressed all edit suggestions and changes around them.

2022-09-05 13:06 UTC, gep13 commented
@ryanrichter94 sorry for taking so long to get back to you, I actually forgot about this PR 😢 

As part of the documentation update that was done as part of 0.10.0, the work done in this PR was largely already completed.  I have just done another commit to address some of the other feedback that was contained within this PR as well.

As such, I am going to go ahead and close out this PR.

2022-09-05 13:06 UTC, closed without merging