(#439) Add verification step to QuickStart Guide
chocolatey/docs pull request #446
Opened 2022-04-01 16:16 UTC by steviecoaster

## Description Of Changes

Add documentation for verification step, which will run a suite of Pester tests against the server as the last step of the QuickStart Implementation Guide.

## Motivation and Context

We added a Pester suite of tests to the Quickstart Guide which will
verify the installation was correct.

## Testing

* [ x ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ x ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #439

2022-04-12 09:43 UTC, pauby requested changes

2022-04-12 09:43 UTC, pauby commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    If you expect services to be available at `chocoserver.yourcompany.com`, then you command would look like: `.\Start-C4bVerification.ps1 -Fqdn 'chocoserver.yourcompany.com'`
```suggestion
    If you expect services to be available at `chocoserver.yourcompany.com`, then your command would look like: `.\Start-C4bVerification.ps1 -Fqdn 'chocoserver.yourcompany.com'`

```

2022-05-02 18:08 UTC, steviecoaster commented on input/en-us/guides/organizations/chocolatey-for-business-quick-start-guide.md
> +    If you expect services to be available at `chocoserver.yourcompany.com`, then you command would look like: `.\Start-C4bVerification.ps1 -Fqdn 'chocoserver.yourcompany.com'`
Fixed!

2022-05-11 11:50 UTC, pauby approved these changes

2022-06-23 20:42 UTC, ryanrichter94 reviewed
Found the following when running the Test suite on a new QSG deployment.

2022-06-30 07:50 UTC, gep13 approved these changes
LGTM!

2022-06-30 07:55 UTC, merged