(doc) Add info about Maintenance and Support
chocolatey/docs pull request #450
Opened 2022-04-06 06:52 UTC by gep13

## Description Of Changes

Added a new fragment with information about Mainteance and Support for
licensed customers, and how this can impact them when we release a new
version of Chocolatey that is no longer compatible with older version
of the Chocolatey Components.

This has direct impacts on some customers that may be using a perpetual
license.

This fragment has been added to the release notes pages for Chocolatey,
Chocolatey Licensed Extension, and the Chocolatey GUI Licensed
Extension, but it can be added to others as required.

## Motivation and Context

With the release of v1.0.0 of Chocolatey CLI, there was some feedback that
this area was as well documented as it could be.  This is an attempt to make
this area as clear as possible.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2022-04-07 00:13 UTC, vexx32 commented
Given the amount of text being included as a snippet here I kinda wonder if we're better off making that a distinct page of its own. As it is, the release notes pages have a fairly lengthy snippet with the dependency information, and adding this means folks will have to scroll a good couple pages' worth before they actually get to the release notes themselves.

I feel like we may be better off mentioning this as a link to a page with the full information rather than an additional snippet on the release notes page. 🤔

2022-04-08 19:36 UTC, pauby requested changes

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +- Maintenance - allows you download newer versions of the licensed components of Chocolatey
```suggestion
- Maintenance - allows you to download newer versions of the licensed components of Chocolatey.
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +- Support - access to our commercial support team
```suggestion
- Support - access to our commercial support team.
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +## Maintenance and Support contract considerations for perpetual license customers
```suggestion
## Maintenance and Support contract considerations for Perpetual License customers
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +And you would be able to download updates to the licensed components that came available during the active period of your Maintenance and Support contract.
```suggestion
A Perpetual License means that you have a license which never expires and you are able to use the Chocolatey Licensed Extension with versions of Chocolatey CLI that are compatible.
While your Maintenance and Support contract is valid, you are able to download updates to the licensed components.
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +This can cause problems when there is a dependency that exists between a new version of Chocolatey CLI and the Chocolatey Licensed Extension.
```suggestion
A Perpetual License customer that does not have a valid Maintenance and Support contract will not be in a position to upgrade to the latest version of Chocolatey Licensed Extension.
This can cause problems when there is a dependency that exists between a new version of Chocolatey CLI and the Chocolatey Licensed Extension.
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +If you are in this position, we would suggest that you follow one of the following two options to prevent any unexpected changes to how Chocolatey CLI functions:
```suggestion
If you are in this position, we suggest that take one of the actions to prevent any unexpected changes to how Chocolatey CLI functions:
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +1. Request a Maintenance and Support renewal and upgrade the Chocolatey Licensed Extension to the newest version, then upgrade Chocolatey CLI.
```suggestion
1. Request a Maintenance and Support contract renewal, upgrade the Chocolatey Licensed Extension to the latest  version and then upgrade Chocolatey CLI.
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +1. Forego the Maintenance and Support renewal and stick with an older version of Chocolatey CLI. Pin to that version and ensure you are using an internal repository and not linked up to the Chocolate
```suggestion
1. Forego the Maintenance and Support contract renewal and stay with a with the version of Chocolatey CLI you use. To prevent accidental upgrade of Chocolatey CLI we would suggest that you pin the version and ensure you are using an internal repository.
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +If you have any questions about anything related to the above, then please [reach out to the Sales team](https://chocolatey.org/contact/sales-general).
```suggestion
If you have any questions about your Perpetual License or your Maintenance and Support contract, please [reach out to the Sales team](https://chocolatey.org/contact/sales-general).
```

2022-04-08 19:36 UTC, pauby commented on input/shared/maintenance-and-support.txt
> +1. Forego the Maintenance and Support renewal and stick with an older version of Chocolatey CLI. Pin to that version and ensure you are using an internal repository and not linked up to the Chocolate
If we ask people to pin to a version of Chocolatey CLI, why do they need to ensure they are using an internal repository?

2022-04-15 08:32 UTC, pauby commented
> Given the amount of text being included as a snippet here I kinda wonder if we're better off making that a distinct page of its own. As it is, the release notes pages have a fairly lengthy snippet with the dependency information, and adding this means folks will have to scroll a good couple pages' worth before they actually get to the release notes themselves.
> 
> I feel like we may be better off mentioning this as a link to a page with the full information rather than an additional snippet on the release notes page. 🤔

I really don't like this idea because I think a page on it's won just for this doesn't make a lot of sense.

But I do agree that this has now grown arms and legs. A separate page makes sense or people are going to have to scroll for a long time before getting to what they went to the page for in the first place.

One advantage of adding it as a snippet means it's in front of people right away. Adding it to a separate page means we need to make sure we really call it out very clearly.

Can we add this and the text around dependencies at the top of the release notes (in another snippet) to this new page?

2022-05-03 09:59 UTC, gep13 commented on input/shared/maintenance-and-support.txt
> +1. Forego the Maintenance and Support renewal and stick with an older version of Chocolatey CLI. Pin to that version and ensure you are using an internal repository and not linked up to the Chocolate
@pauby this was the wording that was provided elsewhere, I just lifted it into this section.

2022-05-03 10:24 UTC, gep13 commented
@pauby @vexx32 I have updated this PR based on your suggestions.  Can you please take it for a spin, and let me know what you think? Thanks!

2022-05-09 18:14 UTC, gep13 commented
@pauby @vexx32 just wanted to send a ping on this. Thanks

2022-05-09 19:32 UTC, vexx32 reviewed
This mostly looks good to me, I think this makes sense. A few comments/questions here and there. Nice work!

2022-05-12 09:39 UTC, pauby requested changes

2022-09-05 13:48 UTC, gep13 commented on input/en-us/what-should-this-page-be-called.md
> +<?! Include "./shared/chocolatey-component-dependencies.txt" /?>
Yes, I believe that this is the type of information that will make its way into various places, so I think it makes sense to have them as a snippet. Perhaps this is a premature optimisation, but in the long run, I think it will pan out.

2022-09-05 13:51 UTC, gep13 commented on input/shared/maintenance-and-support.txt
> +1. Forego the Maintenance and Support contract renewal and stay with a with the version of Chocolatey CLI you use. To prevent accidental upgrade of Chocolatey CLI we would suggest that you pin the ve
Makes sense to me.

2022-09-05 13:53 UTC, gep13 commented on input/shared/maintenance-and-support.txt
> +1. Forego the Maintenance and Support contract renewal and stay with a with the version of Chocolatey CLI you use. To prevent accidental upgrade of Chocolatey CLI we would suggest that you pin the ve
Will get this updated

2022-09-05 13:57 UTC, gep13 commented
@pauby @vexx32 I believe that this is ready for a final review.

2022-09-15 15:08 UTC, vexx32 approved these changes, later dismissed
This looks good to me, great work!

I'm happy to merge this but given this deals with licensing/billing related stuff, I think it best if we get signoff from @pauby as well before merging, if possible.

2022-09-30 21:27 UTC, ryanrichter94 submitted a review, later dismissed
Some minor changes I can see just based on my knowledge on the support and maintenance line items of a Chocolatey For Business license agreement.

2022-09-30 21:27 UTC, ryanrichter94 commented on input/shared/maintenance-and-support.txt
> +While your Maintenance and Support contract is valid, you are able to download updates to the licensed components.
```suggestion
While your Maintenance contract is valid, you are able to download updates to the licensed components.
```

2022-09-30 21:27 UTC, ryanrichter94 commented on input/shared/maintenance-and-support.txt
> +While your Maintenance and Support contract is valid, you are able to download updates to the licensed components.
This part only requires a maintenance contract and not a support contract.

2022-09-30 21:27 UTC, ryanrichter94 commented on input/shared/maintenance-and-support.txt
> +A Perpetual License customer that does not have an active Maintenance and Support contract will not be in a position to upgrade to the latest version of Chocolatey Licensed Extension.
```suggestion
A Perpetual License customer that does not have an active Maintenance contract will not be in a position to upgrade to the latest version of Chocolatey Licensed Extension.
```

2022-09-30 21:27 UTC, ryanrichter94 commented on input/shared/maintenance-and-support.txt
> +A Perpetual License customer that does not have an active Maintenance and Support contract will not be in a position to upgrade to the latest version of Chocolatey Licensed Extension.
Again just maintenance. An active support contract is not needed.

2022-09-30 21:27 UTC, ryanrichter94 commented on input/shared/maintenance-and-support.txt
> +- Forego the Maintenance and Support contract renewal and stay with a with the version of Chocolatey CLI and Chocolatey Licensed Extension that you use. To prevent accidental upgrade of Chocolatey CL
```suggestion
- Forego the Maintenance and Support contract renewal and stay with the version of Chocolatey CLI and Chocolatey Licensed Extension that you use. To prevent accidental upgrade of Chocolatey CLI we would suggest that you [pin](xref:choco-command-pin) to the version you use and ensure you are using an [internal repository](xref:organizational-deployment-guide).
```

2022-11-03 12:31 UTC, pauby approved these changes

2022-11-03 12:33 UTC, merged