Add QSG Cert Renewal Page
chocolatey/docs pull request #463
Opened 2022-05-02 21:12 UTC by ryanrichter94

## Description Of Changes
Added page on certificate renewal scripts that were added to QSG.
Also put QSG content under its own folder. 

## Motivation and Context
Needed to document the cert renewal scripts that were merged into QSG.

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [X] New documentation page added.

## Change Checklist

* [X] Requires a change to menu structure (top or left hand side)/
* [X] Menu structure has been updated

## Related Issues

https://github.com/chocolatey/choco-quickstart-scripts/issues/130
Fixes #448 
Fixes #449

2022-05-02 21:13 UTC, ryanrichter94 commented
Added the new cert renewal page as index 40 because I intend to write up a maintaining QSG components page on index 30 that will link to our Nexus and CCM upgrade documentation.

2022-05-04 19:23 UTC, steviecoaster requested changes

2022-05-04 19:23 UTC, steviecoaster commented on input/en-us/guides/organizations/quick-start-guide/certificate-renewal.md
> +## Set-NexusCert
```suggestion
## Set-NexusCert.ps1
```

2022-05-04 19:23 UTC, steviecoaster commented on input/en-us/guides/organizations/quick-start-guide/certificate-renewal.md
> +This script should be on your quick start guide server at `C:\choco-setup\scripts\Set-NexusCert.ps1`. If it isn't, you can download it from the choco-quickstart-scripts project repo on GitHub at http
```suggestion
This script should be saved on your repository server at `C:\choco-setup\scripts\Set-NexusCert.ps1`

You can download this file directly from [here)(https://github.com/chocolatey/choco-quickstart-scripts/blob/main/scripts/Set-NexusCert.ps1), or copy the below code and manually save it.

2022-05-04 19:23 UTC, steviecoaster commented on input/en-us/guides/organizations/quick-start-guide/certificate-renewal.md
> +- The script will remove you previous keystore.jks file
```suggestion
- The script will remove your previous keystore.jks file
```

2022-05-04 19:23 UTC, steviecoaster commented on input/en-us/guides/organizations/quick-start-guide/certificate-renewal.md
> +## Set-CCMCert
```suggestion
## Set-CCMCert.ps1
```

2022-05-04 19:23 UTC, steviecoaster commented on input/en-us/guides/organizations/quick-start-guide/certificate-renewal.md
> +This script should be on your quick start guide server at `C:\choco-setup\scripts\Set-CCMCert.ps1`. If it isn't, you can download it from the choco-quickstart-scripts project repo on GitHub at https:
Same verbage as above

2022-05-04 19:23 UTC, steviecoaster commented on input/en-us/guides/organizations/quick-start-guide/certificate-renewal.md
> +- The script will prompt for a $CertificateThumbprint value when run. Please enter the thumbprint value of the certificate you wish to have the IIS endpoint of Chocolatey Central Management run over.
Don't call out the variable here, but rather be generic with what it is.

2022-05-06 17:26 UTC, ryanrichter94 commented
@steviecoaster Changes you requested should be in latest push.

2022-05-06 19:29 UTC, steviecoaster approved these changes

2022-05-06 19:30 UTC, merged