(PROJ-83) Add C4B Azure Environment certificate renewal documentation
chocolatey/docs pull request #468
Opened 2022-05-09 11:25 UTC by Windos

## Description Of Changes

**_NOTE_**: This PR relies on #371 being merged first, and so this has been added as a draft until that is complete. Once the blocking PR is merged, this will be rebased and taken out of draft.

This PR adds documentation and supporting images related to updating the certificate used by a Chocolatey for Business Azure Environment. It includes instructions for carrying out this task using both the Azure Portal and with PowerShell.

## Motivation and Context

Certificates expire, and inevitably need to be replaced. This documentation helps walk through that process as it's not immediately clear.

## Testing

* [x] I have previewed these changes using the `preview.ps1` script.
* [x] I have taken the previewed text and run it through a spell checker.

![Preview of changes](https://user-images.githubusercontent.com/6955786/167400199-0575cc1b-327a-4fc5-91d5-ea4892f139df.png)

## Change Types Made

~~* [ ] Minor documentation fix (typos etc.).~~
~~* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~~
* [x] New documentation page added.

## Change Checklist

~~* [ ] Requires a change to menu structure (top or left hand side)/~~
~~* [ ] Menu structure has been updated~~

## Related Issue

N/A

2022-05-11 17:14 UTC, JPRuskin approved these changes
Looks good. Waiting on Paul's review for wording et al.

2022-05-11 17:14 UTC, JPRuskin commented on input/en-us/c4b-environments/azure/certificate-update.md
> +    CertificateFile    = $FileBrowser.FileName
My original code sourced the certificate data from the KeyVault - switched it as I wasn't sure we could rely on folk to run stuff in order. But I'd happily change it back, as it was nicely elegant.

2022-05-12 07:14 UTC, Windos commented on input/en-us/c4b-environments/azure/certificate-update.md
> +$FileBrowser = New-Object System.Windows.Forms.OpenFileDialog -Property @{
I did notice a PR in the other docs getting rid of the read hosts, etc. Should we be taking that same philosophy here (in which case the dialog just becomes a "path to certificate" string that the user edits)?

2022-05-12 12:17 UTC, JPRuskin commented on input/en-us/c4b-environments/azure/certificate-update.md
> +$FileBrowser = New-Object System.Windows.Forms.OpenFileDialog -Property @{
We found a fix during our call.

2022-05-13 13:23 UTC, pauby requested changes
This looks really good. Awesome work @Windos and @JPRuskin!

2022-05-13 13:23 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +> In addition to the certificate in a PFX format that was used in the [previous section](xref:c4b-azure-cert-update#updating-the-azure-key-vault), you will need a copy of the certificate in a copy of
```suggestion
> In addition to the certificate in a PFX format that was used in the [previous section](xref:c4b-azure-cert-update#updating-the-azure-key-vault), you will need a copy of the certificate in CER format.
```

2022-05-13 13:23 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +> You can convert your existing certificate using OpenSSL (installable with Chocolatey using `choco install openssl.light`):
```suggestion
> You can convert your existing certificate using OpenSSL (easily installed by running `choco install openssl.light`):
```

2022-05-13 13:23 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Navigate to the Resource Group the contains your C4B Azure Environment
```suggestion
1. Navigate to the `Resource Group` the contains your C4B Azure Environment
```

2022-05-13 13:23 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Navigate to the Resource Group the contains your C4B Azure Environment
This change would appear to make it consistent with other steps that put things in code blocks.

2022-05-13 13:23 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +Please note that until the `Set-AzApplicationGateway` command is run, the Application Gateway will not be updated. The update itself can take up to thirty minutes, but the command should return immed
```suggestion
Please note that until the `Set-AzApplicationGateway` command is run, the Application Gateway will not be updated. **The update can take up to 30 minutes**, but the command should return immediately.
```

2022-05-16 15:01 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Click `+ New Version`
```suggestion
1. Click `+ New Version`.
```

2022-05-16 15:01 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Upload your certificate PFX file, and provide the password needed to import it
```suggestion
1. Change the `Method of Certificate Creation` to `Import`.
1. Upload your certificate PFX file, and provide the password needed to import it.
```

2022-05-16 15:01 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. The new certificate will now be listed as the `CURRENT VERSION` and any previous certificates will be listed under `OLDER VERSIONS`
```suggestion
1. Click `Create`.
1. The new certificate will now be listed as the `CURRENT VERSION` and any previous certificates will be listed under `OLDER VERSIONS`.
```

2022-05-16 15:03 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Select the Application gateway
```suggestion
1. Navigate to the `Resource Group` the contains your C4B Azure Environment.
1. Select the `Application gateway`.
```

2022-05-16 15:04 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Select `CCMService`
```suggestion
1. Under `Settings` on the left of the blade, select `Backend settings`.
1. Select `CCMService`.
```

2022-05-16 15:04 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. On the `Add Backend settings` blade, click `+ Add certificate`
```suggestion
1. On the `Add Backend settings` blade, click `+ Add certificate`.
```

2022-05-16 15:05 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Click `+ Add certificate`
```suggestion
1. Ensure `Create new` is selected and browse to the `.cer` version of your certificate.
1. Provide a descriptive `Cert name` that is different to the existing certificate. The initial certificate is called `CCMCert`.
1. Click `+ Add certificate`.
```

2022-05-16 15:05 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Click `Save`
```suggestion
1. Click the `...` (three dots) to the right of the previous certificate and choose `Delete`.
1. Click `Save`.
```

2022-05-16 15:05 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Select `CCM`
```suggestion
1. Under `Settings` on the left of the blade, select `Listeners`.
1. Select `CCM`.
```

2022-05-16 15:06 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. Click `Save`
```suggestion
1. Ensure `SslCertificate` is the selected certificate.
1. Check `Renew or edit selected certificate`.
1. Browse to select the `.pfx` version of your certificate.
1. Enter the `Password` required to import the certificate.
1. Click `Save`.
```

2022-05-16 15:07 UTC, pauby commented on input/en-us/c4b-environments/azure/certificate-update.md
> +1. It can some time for the Application Gateway to update, when it has finished you will be able check that the new certificate is being served by visiting on the C4B Azure Environment [services](xre
```suggestion
1. It can take some time for the Application Gateway to update. When it has finished you will be able check that the new certificate is being served by visiting on the C4B Azure Environment [services](xref:c4b-azure#accessing-services).
```

2022-05-17 01:32 UTC, Windos commented
@pauby all suggestions pulled in, thanks for catching that

2022-05-19 09:54 UTC, pauby submitted a review, later dismissed

2022-05-19 09:54 UTC, pauby commented
LGTM! Thanks for making those changes. Can you squash the commits and we can merge it?

2022-05-19 10:03 UTC, Windos commented
@pauby - Squashed and good to go!

2022-05-19 10:15 UTC, pauby approved these changes

2022-05-19 10:16 UTC, merged

2022-05-19 10:17 UTC, pauby commented
Thanks @Windos and @JPRuskin for this. Awesome work!