Add Intune Section to Integration Doc
chocolatey/docs pull request #471
Opened 2022-05-10 20:31 UTC by ryanrichter94

## Description Of Changes
Add Intune section to integrations doc.

## Motivation and Context
No prior reference to intune integration besides the setup and use docs. Also brought page up to current linting standards.

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [X] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated
* [X] No navigation changes needed

## Related Issue

Fixes #436

2022-05-10 20:37 UTC, steviecoaster requested changes

2022-05-10 20:37 UTC, steviecoaster commented on input/en-us/features/integrations.md
> +Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and `choco convert` them into an intunewin app. It then allows
```suggestion
Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and `choco convert` it into an intunewin application. It then allows you to `choco push` your converted Chocolatey packages to your Intune tenant for hosting and distribution.

2022-05-11 11:57 UTC, pauby commented on input/en-us/features/integrations.md
> +Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and `choco convert` them into an intunewin app. It then allows
```suggestion
Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and convert them into an `.intunewin` format for pushing to your Intune tenant for hosting and distribution.
```

2022-05-11 11:58 UTC, pauby commented on input/en-us/features/integrations.md
> +Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and `choco convert` them into an intunewin app. It then allows
intunewin is not an actual thing, it's a format.

2022-05-11 14:48 UTC, ryanrichter94 commented on input/en-us/features/integrations.md
> +Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and `choco convert` them into an intunewin app. It then allows
Fixed, thanks for the clarification.

2022-05-11 14:49 UTC, ryanrichter94 commented on input/en-us/features/integrations.md
> +Chocolatey's Intune Integration is only available to our Chocolatey for Business customers. It allows you to take any Chocolatey package and `choco convert` them into an intunewin app. It then allows
Went with @pauby's recommendations as it seemed more concise. Thanks for the suggestions though.

2022-05-11 15:20 UTC, pauby approved these changes
LGTM. Just need to squash the commits, and we're good to merge from my perspective.

2022-05-11 15:28 UTC, merged

2022-05-13 06:16 UTC, gep13 commented
@ryanrichter94 am I right in saying that you used the "big green" button here, and squashed the commits through the UI?

2022-05-13 11:23 UTC, ryanrichter94 commented
Yes