(#473) Adds C4BAE License Update Instructions
chocolatey/docs pull request #474
Opened 2022-05-16 11:38 UTC by JPRuskin

## Description Of Changes
This adds a section to the C4BAE documentation covering how a user might update their business license from a random machine.

## Motivation and Context
There was nothing covering how a user would update their Chocolatey For Business license in the Chocolatey for Business Azure Environment.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* ~[ ] Minor documentation fix (typos etc.).~
* ~[ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* [x] New documentation page added.

## Change Checklist

* ~[ ] Requires a change to menu structure (top or left hand side)/~
* ~[ ] Menu structure has been updated~

## Related Issue

Fixes #473
Clickup PROJ-50

2022-05-16 11:39 UTC, JPRuskin commented on input/en-us/c4b-environments/azure/license-update.md
> +Title: Updating Your Chocolatey For Business License
I worry this title is too long. 
![image](https://user-images.githubusercontent.com/1975761/168584677-e8937958-5111-4ca1-b140-1031a1de5a00.png)

![image](https://user-images.githubusercontent.com/1975761/168584690-abba6aca-98e3-4615-b026-498eb79a953e.png)

Thoughts?

2022-05-16 11:54 UTC, Windos requested changes
Normalizing the C4B name = "Chocolatey for Business"

2022-05-16 11:54 UTC, Windos commented on input/en-us/c4b-environments/azure/license-update.md
> +Title: Updating Your Chocolatey For Business License
```suggestion
Title: Updating Your Chocolatey for Business License
```

2022-05-16 11:54 UTC, Windos commented on input/en-us/c4b-environments/azure/license-update.md
> +If you use Chocolatey For Business Azure Environment for longer periods of time, the license you used to deploy it may expire. In these cases, you will need to update the license used in your Chocola
```suggestion
If you use Chocolatey for Business Azure Environment for longer periods of time, the license you used to deploy it may expire. In these cases, you will need to update the license used in your Chocolatey for Business environment.
```

2022-05-16 11:54 UTC, Windos commented on input/en-us/c4b-environments/azure/license-update.md
> +- You will need the FQDN of your Chocolatey For Business Azure Environment
```suggestion
- You will need your new Chocolatey for Business license file
- You will need the FQDN of your Chocolatey for Business Azure Environment
```

2022-05-16 11:54 UTC, Windos commented on input/en-us/c4b-environments/azure/license-update.md
> +When you initially deploy a Chocolatey For Business Azure Environment, you upload your Chocolatey For Business license. This is then used to create a Chocolatey Package that installs the license on y
```suggestion
When you initially deploy a Chocolatey for Business Azure Environment, you upload your Chocolatey for Business license. This is then used to create a Chocolatey Package that installs the license on your nodes.
```

2022-05-16 11:54 UTC, Windos commented on input/en-us/c4b-environments/azure/license-update.md
> +Title: Updating Your Chocolatey For Business License
I think it's fine.

If you do want to change it, could consider dropping the "your" ("Chocolatey for Business License Update") or go for the same format as the certificate guide and trim it all the way down to "License Update" but I feel like this benefits from being a little more verbose than that.

2022-05-16 12:46 UTC, JPRuskin commented on input/en-us/c4b-environments/azure/license-update.md
> +Title: Updating Your Chocolatey For Business License
I went full terse, in the end. Just matches the rest a bit better, and the description is still nicely verbose.

2022-05-16 12:51 UTC, Windos commented
One thing before I forget, check the the order number. I think it's currently sharing that with the RDP docs.

2022-05-17 01:35 UTC, Windos submitted a review, later dismissed
This LGTM, but very keen for @pauby to have a read as he has a better eye for docs style than I!

2022-05-19 10:14 UTC, pauby submitted a review, later dismissed

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +Description: How to update the license in use on Chocolatey for Business Azure Environment
```suggestion
Description: How to update the license in use on your Chocolatey for Business Azure Environment.
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +If you use Chocolatey for Business Azure Environment for longer periods of time, the license you used to deploy it may expire. In these cases, you will need to update the license used in your Chocola
```suggestion
If you use the Chocolatey for Business Azure Environment for long periods of time, the license you used to deploy it may expire and you will need to update it.
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +- You will need the API Key for your Nexus repository (or access to the Resource Group / Azure Key Vault)
```suggestion
- You will need a recent version of Chocolatey CLI installed.
- You will need your new Chocolatey for Business license file.
- You will need the FQDN of your Chocolatey for Business Azure Environment.
- You will need the API Key for your Nexus repository (or access to the Resource Group hosting your Azure Key Vault to be able to [retrieve it]((xref:c4b-azure#accessing-services))).
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +- You will need a recent version of Chocolatey CLI installed
This is a bit non-specific. What does 'recent version' mean? Is there a minimum version? Is there a 'thing' that means there is a specific minimum version that's needed?

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +Please refer to [accessing services](xref:c4b-azure#accessing-services) if you need to retrieve the API key, which is stored in the Key Vault as `PackageApiKey`.
```suggestion
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +## Creating a new License Package
```suggestion
## Creating a New License Package
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +When you initially deploy a Chocolatey for Business Azure Environment, you upload your Chocolatey for Business license. This is then used to create a Chocolatey Package that installs the license on y
```suggestion
When you initially deploy a Chocolatey for Business Azure Environment, you upload your Chocolatey for Business license. This is then used to create a Chocolatey package that installs the license on your nodes.
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +Open a PowerShell window and run the following code (filling in prompts or setting values appropriately):
Does that PowerShell session need to be elevated?

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +We now need to upload this new package to the Nexus repository. This is very simple:
```suggestion
We now need to upload this new package to the Nexus repository. Open a PowerShell window and run the following code (which will prompt you for information for values are not set):
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +    $NexusApiKey = "$(Read-Host -Prompt 'Please enter the API Key for pushing nuget packages to Nexus')"
```suggestion
    $NexusApiKey = "$(Read-Host -Prompt 'Please enter the API Key to be used to push Chocolatey packages to Nexus')"
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +Open a PowerShell window and run the following code (filling in prompts or setting values appropriately):
```suggestion
Open a PowerShell window and run the following code (which will prompt you for information for values that are not set)::
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +    $FQDN = "$(Read-Host -Prompt 'Please enter the FQDN for the C4BAE application')"
```suggestion
    $FQDN = "$(Read-Host -Prompt 'Please enter the FQDN for the Chocolatey for Business Azure Environment application')"
```

2022-05-19 10:14 UTC, pauby commented on input/en-us/c4b-environments/azure/license-update.md
> +## Pushing the new License to Nodes
```suggestion
## Pushing the New License to Nodes
```

2022-05-25 15:42 UTC, JPRuskin commented on input/en-us/c4b-environments/azure/license-update.md
> +Open a PowerShell window and run the following code (filling in prompts or setting values appropriately):
Yep, given the limited scope of commands (using a temp dir and `choco pack`) it works fine without elevation.

2022-05-25 15:42 UTC, JPRuskin commented on input/en-us/c4b-environments/azure/license-update.md
> +- You will need a recent version of Chocolatey CLI installed
Looking into it, this should be fine with any version of Chocolatey - even pre-0.9.8.

```suggestion
- You will need Chocolatey CLI installed.
```

2022-05-25 16:08 UTC, Windos commented
@JPRuskin - looks like this'll need a rebase. Will do a review when I get online tomorrow!

2022-05-26 07:14 UTC, Windos commented on input/en-us/c4b-environments/azure/license-update.md
> +- You will need a recent version of Chocolatey CLI installed
@JPRuskin - if you want to add in that edit (I can't from this UI anymore), I think this is ready to merge 🚀

2022-05-26 13:01 UTC, Windos approved these changes
Just gave this a re-read and looks even better with @pauby's suggestions!

2022-05-26 13:04 UTC, Windos commented
Thanks for getting this in @JPRuskin! Awesome stuff

2022-05-26 13:04 UTC, merged