(#458) Update Intune FAQ (PROJ-117)
chocolatey/docs pull request #480
Opened 2022-05-26 23:12 UTC by corbob

## Description Of Changes

Move Intune FAQ into its own section instead of on each of the commands for Intune. Add a Convert question regarding intunewinapputil failing for large pacakges.

## Motivation and Context

This allows for more general Intune FAQ. Also addresses an issue we identified where intunewinapputil doesn't pack large packages.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

Fixes #458

2022-05-31 10:15 UTC, pauby requested changes

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +### Must I have all Chocolatey package dependencies already downloaded?
```suggestion
### Must I download all of the Chocolatey package dependencies before conversion?

```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +You may skip the handling of dependencies when converting a package by using the `--ignore-dependencies` argument. However, it is recommended not to skip dependency handling as the package may not in
```suggestion
It is recommended that all package dependencies are converted to ensure that the package installs and upgrades correctly, and to ensure the software functions as intended. If the dependencies do not exist either locally or in your Intune tenant you may be prevented from pushing the Chocolatey package.

With the above recommendations in mind, if you do need to skip converting package dependencies, use the `--ignore-dependencies` switch when running the `convert` command.
```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +When trying to convert packages that are larger than ~2 GB, you may encounter the error `[IntuneWinAppUtil] ERROR  System.IO.IOException: Stream was too long.` There is a [known issue](https://github
```suggestion
When trying to convert packages that are larger than around 2 GB, you may encounter the error `[IntuneWinAppUtil] ERROR  System.IO.IOException: Stream was too long.` There is a [known issue](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/issues/58) with version 1.8.3 of `intunewinapputil` which is used to generate the Chocolatey Intune package `intunewin` file. You can work around this by either downgrading to `1.8.2.20220507` with the command `choco install intunewinapputil -y --version 1.8.2.20220507 --allow-downgrade --force`, or you can upgrade to the latest intunewinapputil with the command `choco upgrade intunewinapputil -y`
```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +## Convert FAQs
```suggestion
## Intune Convert Command
```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +## Push FAQs
```suggestion
## Push to Intune Command
```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +Yes, but there are a few things to know before doing so.
```suggestion
Yes, but there are a few things to know before doing so:
```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +Updates to Intune packages through Chocolatey is not currently supported. There is a manual process that you can follow to do this within Intune:
```suggestion
Follow these steps to do this:

```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +1. Ensure the local computer that you will run the Chocolatey commands on has the new license applied to it.
```suggestion
1. Ensure the local computer that you will run the Chocolatey CLI commands on has the new license applied to it.

```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> + 1. Push a package to Intune as you would normally do. This will result in Chocolatey not finding a `chocolatey-license` package within the Intune tenant, and therefore automatically generating a new
```suggestion
1. Replace the `Notes` section of the Intune package with a non-whitespace character (for example, the letter A).
1. Push a package to Intune as you would normally do. This will result in Chocolatey automatically generating a new `chocolatey-license` package using the license present on the local computer running the `push` command.
```

2022-05-31 10:15 UTC, pauby commented on input/en-us/licensed-extension/intune/faq.md
> +1. Locate the `Chocolatey Licensed Extension` package in the Intune tenant and add the new `Chocolatey License` package as a dependency and remove the previous `Chocolatey License` package as a depen
```suggestion
1. Locate the `Chocolatey Licensed Extension` package in the Intune tenant and add the new `Chocolatey License` package, created above, as a dependency and remove the previous `Chocolatey License` package as a dependency.

```

2022-06-22 17:21 UTC, gep13 approved these changes
LGTM

2022-06-22 17:23 UTC, merged