Update with 0.10.0 changes
chocolatey/docs pull request #532
Opened 2022-08-23 06:33 UTC by gep13

## Description Of Changes

The documentation section for Chocolatey Central Management has been extended to allow documentation of the new features that are coming with version 0.10.0.  This has meant creation of a number of placeholder pages that will need to be filled at a later date.

## Motivation and Context

There is a new release of Chocolatey Central Management coming out that contains a number of new features, and these need to be documented.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [x] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #531

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

N/A

2022-08-23 13:05 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +   * For _Basic_ deployment steps, select a `Script command` from the list, a `Package name` to install, and optionally a specific package version to install, or whether to use the `--pre` option, i.
```suggestion
   * For _Basic_ deployment steps, select a `Script command` from the list, a `Package name` to install, and optionally a specific package version to install or whether to allow Chocolatey to install the latest prerelease package version.  **NOTE:** It is not possible to use a space character within the `Package name` or `Package Version` textboxes, and the `Package Version` textbox must contain at least one digit.
```

My understanding is that often abbreviations like `i.e.` have inconsistent at best readability for some screen readers, and can also be unfamiliar for those learning English as a second language. Best to avoid them where possible, IMO.

Also, I'm not sure it's particularly relevant to mention the individual Chocolatey CLI command option in this instance. It's related, sure, but IMO Central Management's feature sets don't need to call out the individual CLI features they happen to be using. (We don't mention `--version` the same way, either.)

See also: https://www.oit.va.gov/accessibility/getting-started/abbreviations

2022-08-23 13:16 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +Let's take as example a deployment in the [Ready](#ready) state that is scheduled to start on `23rd August 2022 at 07:11 UTC`, and a Repeat Period of `Weekly` has been chosen.  Once this instance of
Not really a fan of giant chunks on one line like this, it makes it difficult to diff later on (and review!). 😕

We're also putting general information in the same paragraph as the specific example, which I think is confusing.

I think we could use less commas and more distinct sentences to make it a little easier to follow as well.

```suggestion
Let's take as example a deployment in the [Ready](#ready) state that is scheduled to start on `23rd August 2022 at 07:11 UTC`, with a Repeat Period of `Weekly` set.
Once this instance of the deployment moves to the [Active](#active) state, another instance of the deployment will be created.
The new instance will have the same steps and settings except for the scheduled start date/time, which will be set to exactly 1 week from the scheduled start date/time of the previous instance (in this case `30th August 2022 at 07:11 UTC`).

For repeating deployments, a new instance of the deployment will be created once a scheduled deployment moves to the [Active](#active) state.
If a repeating deployment specifies a maintenance window date/time (`Last Scheduled Date Time`), the new instance's maintenance window will also be adjusted from the previous instance's value by the same period as the scheduled start date/time.
```

2022-08-23 13:20 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +> One important thing to remember is that if a scheduled start date/time of a deployment is overridden using the [Run Now](#run-now) action, the scheduled date/time of the new instance of the recurri
```suggestion
> :warning: WARNING
>
> If the scheduled start date/time of a deployment is overridden using the [Run Now](#run-now) action, the new instance of the recurring deployment will use the **scheduled** start date/time of the previous instance when calculating the next scheduled start date/time, **not** the date/time that the deployment actually started.
> If you want to change the scheduled start date/time of the recurring deployment, edit the deployment while it is in the [Ready](#ready) state to ensure that future instances of the recurring deployment will use that value when calculating the next scheduled date/time.
```

2022-08-23 13:23 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +> Any further modifications to a deployment in this state will revert it back to the [`Draft`](#draft) state.
```suggestion
> Any modifications to a deployment in this state will revert it back to the [`Draft`](#draft) state.
```

2022-08-23 13:24 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +You can access archived deployments from the `Deployments` page and clicking on the `View Archived Deployments` button.  [`Archived](#archived) deployments will not appear in any other reports that c
```suggestion
You can access archived deployments from the `Deployments` page and clicking on the `View Archived Deployments` button.  [`Archived`](#archived) deployments will not appear in any other reports that contain deployment plans.
```

2022-08-23 13:26 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +The action makes an exact copy (with the exception of any scheduled start/end time) of any given deployment plan.  Once the duplicate has been created, you will be taken to the edit page ready to mak
```suggestion
The action makes an exact copy (with the exception of any scheduled start/end time or repeat period) of any given deployment plan.  Once the duplicate has been created, you will be taken to the edit page ready to make any additional required changes.  The name of the new deployment plan will be the same as the original with some additional information added to the end.  For example, if the original deployment plan was called `Install Papercut`, the name given to the duplicate would be `Install Papercut - Copy (19 Aug 2022 12:52:25)` where the timestamp is the current date time.
```

2022-08-23 13:27 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +> There is a specific permission to allow duplication of a deployment plan. If you want to configure this permission, it can be done either for an individual [user](xref:ccm-administration-users), or
```suggestion
> There is a specific permission to allow duplication of a deployment plan. If you want to configure this permission, it can be done either for an individual [user](xref:ccm-administration-users), or a specific [role](xref:ccm-administration-roles)

```

2022-08-23 13:29 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +If a deployment plan is in the ready state, but is waiting for the scheduled start time before automatically starting, it is possible to override this start time using the `Run Now` action.  Care sho
```suggestion
If a deployment plan is in the ready state, but is waiting for the scheduled start time before automatically starting, it is possible to override this start time using the `Run Now` action.  Care should be taken here though if the deployment plan is also a recurring deployment plan.  In this case, the overriding the scheduled start time will mean that the next deployment plan will be configured to use the scheduled start time for the next iteration, and _not_ the overridden start time.
```

Do we need to mention this again given it was called out in a warning above already? Should we copy the warning down to here rather than rephrasing the same warning and putting it in the main text?

2022-08-23 13:32 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +Care should be taken when choosing to cancel a scheduled deployment, which has also been setup to a be a recurring deployment.  If you cancel the non-active version of a recurring deployment, no new
This reads a bit indirect and a little confusing to me.

```suggestion
If a recurring deployment is Cancelled from the [`Ready`](#ready) state, all future instances of the plan are also cancelled.
If you want to skip an iteration of a recurring deployment, instead change its scheduled start time directly.
```

I think this framing might be a little more clear?

2022-08-23 13:34 UTC, vexx32 commented on input/en-us/central-management/usage/website/deployments.md
> +This action opens up the details for the selected deployment plans, allowing the user to see the progress so far.  i.e. which step is currently active, which computers have picked up this step, etc.
```suggestion
This action opens up the details for the selected deployment plans, allowing the user to see the progress so far.  For example: the currently active step, or which computers have picked up this step.  This view is useful for monitoring the progress in real time, as the details pages update automatically.
```

2022-08-23 13:37 UTC, vexx32 commented on input/en-us/central-management/usage/website/general.md
> +The selection that is made here is persisted, meaning that it will be remembered after to sign out of the Chocolatey Central Management website.
This is unclear in its phrasing. Is it saved per user? A cookie (so, per browser)? A combination of the two?

```suggestion
The selection that is made here is persisted, meaning that it will be remembered after you sign out of the Chocolatey Central Management website.
```

2022-08-23 13:38 UTC, vexx32 commented on input/en-us/central-management/usage/website/general.md
> +It is possible to dismiss this warning using the "x" on the far right of the banner, however, the banner will re-appear again in 2 days time to remind yo.u.  This will repeat until the license is ren
```suggestion
It is possible to dismiss this warning using the "x" on the far right of the banner, however, the banner will re-appear again in 2 days' time to remind you.  This will repeat until the license is renewed, or until the license expires.
```

2022-08-23 17:06 UTC, pauby commented
The `usage->website->administraton` folder is named incorrectly. It should be `administration` (ie. an `i` third letter from the end).

2022-08-24 06:27 UTC, gep13 commented on input/en-us/central-management/usage/website/administraton/settings/audit-retention.md
> +```
No, there currently isn't a snippet for this information. I think the creation of such a snippet was suggested, but never implemented.  Given that the creation of this page was just a move of the existing information into a dedicated page, I am going to leave this as-is.

2022-08-24 06:28 UTC, gep13 commented on input/en-us/central-management/usage/website/administraton/settings/stale-computer-deletion.md
> +```
No, there currently isn't a snippet for this information. I think the creation of such a snippet was suggested, but never implemented.  Given that the creation of this page was just a move of the existing information into a dedicated page, I am going to leave this as-is.

2022-08-24 06:39 UTC, gep13 commented on input/en-us/central-management/usage/website/deployments.md
> +If a deployment plan is in the ready state, but is waiting for the scheduled start time before automatically starting, it is possible to override this start time using the `Run Now` action.  Care sho
That is a good catch, I will get this fixed up, using the warning in both places.

2022-08-24 06:41 UTC, gep13 commented
@vexx32 @pauby thank you both for the review. I have fixed up the comments and suggestions that were left on this PR, and this is now ready for another review.

2022-08-24 13:54 UTC, st3phhays commented
> @vexx32 @pauby thank you both for the review. I have fixed up the comments and suggestions that were left on this PR, and this is now ready for another review.

Giving this a review this morning too.

2022-08-24 15:30 UTC, st3phhays requested changes
Overall this looks good! 

I did notice a lot of inconsistencies on these pages that were modified between the formatting of the "Notes" and "Warnings" callouts. The ones that you added though in these commits seemed to be right though. It might be a separate issue to go back and fix the ones that don't follow the correct format.

For the images, I went back and forth on whether to add them here or in the images repo. I think this is fine for now, and when we pick that back up we can get them moved over and keep this same folder structure you got since it is well organized. 👍

2022-08-24 15:30 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/settings/email.md
> +![Test email sent successfully](/assets/images/features/ccm/test_email_sent_correctly.png)
Is this picture current? I notice it is blue.. I thought it was green.

2022-08-24 15:30 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/settings/general.md
> +Order: 10
```suggestion
Order: 5
```

Both this "General" page and the "Encryption PassPhrase" page have an order of 10. I think it makes more sense to change this to "5" so that it comes first in the list since it's about general information. Currently this is shown second in the nav bar.

Or if we stick to the convention of "10's", you'd need to update the rest of the pages too.

2022-08-29 09:45 UTC, gep13 commented on input/en-us/central-management/usage/website/general.md
> +Across the various pages within the Chocolatey Central Management website, there are a number of different tables. Showing, for example, all the [computers](xref:ccm-computers) that are currently rep
Great catch! Will get this fixed up!

2022-08-29 09:46 UTC, gep13 commented on input/en-us/central-management/usage/website/computers.md
> +
Yip, that sounds better, will get this added.

2022-08-29 09:53 UTC, gep13 commented on input/en-us/central-management/usage/website/administration/settings/general.md
> +Order: 10
This is a great catch as well! I am going to move the encryption page to the bottom of that section, as I think (at some point) not just now, that this needs to be broken out to somewhere else.

2022-08-29 09:56 UTC, gep13 commented on input/en-us/central-management/usage/website/administration/settings/email.md
> +![Test email sent successfully](/assets/images/features/ccm/test_email_sent_correctly.png)
I think it used to be blue, a while back, and this screenshot wasn't updated. I will get this updated in this round of updates.

2022-08-29 09:57 UTC, gep13 commented on input/en-us/central-management/usage/website/administration/audit-logs.md
> +Title: Roles
:+1: Will get this fixed

2022-08-29 09:57 UTC, gep13 commented on input/en-us/agent/upgrade.md
> +> :memo: **NOTE** Be sure to use [Sensitive Variables](xref:ccm-administration-sensitive-variables) to ensure the username and password don't get added to the Chocolatey logs when using Chocolatey Ce
Great catch!

2022-08-29 10:46 UTC, gep13 commented on input/en-us/central-management/usage/website/administraton/settings/stale-computer-deletion.md
> +In Chocolatey Central Management, a stale computer is one which hasn't reported in for a long period of time. This could be perfectly normal, but it could also be a sign that this computer is no long
As discussed, don't think any other detail is required here.

2022-08-29 10:46 UTC, gep13 commented
@st3phhays @vexx32 I believe I have addressed all your feedback so far. Can I get you to take another review of this at some point? Thanks!

2022-08-29 17:04 UTC, st3phhays submitted a review, later dismissed
This all looks good to me. Great job getting all that documented, it was a lot!

2022-08-29 17:08 UTC, vexx32 approved these changes
This looks good to me as well! Thanks for your hard work on this one! 💖

2022-08-30 14:58 UTC, vexx32 commented
After conferring with @pauby I've added a mention about agent retries and how that can affect deployments in the Inconclusive completed status to the section on the Completed deployment statuses. Otherwise this is good to go so I'll merge it. Thanks for all this! 💖

2022-08-30 15:00 UTC, vexx32 approved these changes

2022-08-30 15:10 UTC, merged