(#563) Add documentation about hooks
chocolatey/docs pull request #564
Opened 2022-10-11 03:28 UTC by TheCakeIsNaOH

## Description Of Changes

Adds documentation about hooks

## Motivation and Context

See #563

Should not be merged until hooks go out in a Chocolatey CLI release.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #563

2022-10-19 18:30 UTC, corbob requested changes
Just a few minor changes.

2022-10-19 18:30 UTC, corbob commented on input/en-us/features/hook.md
> +Hooks allow you to run code before a package automation script like a `chocolateyInstall.ps1` runs, or after. They even work when automation scripts are not included in the package. Each script can s
This last sentence feels a little out of place.

```suggestion
Hooks allow you to run code before a package automation script like a `chocolateyInstall.ps1` runs, or after. They even work when automation scripts are not included in the package. Each script can selectively target a single package ID, or run for all packages. Then they can be distributed using `.hook` packages.
```

2022-10-19 18:30 UTC, corbob commented on input/en-us/features/hook.md
> +Hook script are PowerShell `.ps1` files, and are run in the same environment as package automation scripts are, so they can access all the same environment variables and helpers.
```suggestion
Hook scripts are PowerShell `.ps1` files, and are run in the same environment as package automation scripts run, so they have access to all of the same environment variables and helpers. 
```

2022-10-19 18:30 UTC, corbob commented on input/en-us/features/hook.md
> +The conditions for when a hook is run is based on the filename of the hook. `<pre|post>-<install|beforemodify|uninstall>-<packageID|all>.ps1` is the filename format. The first section is for timing o
```suggestion
The conditions for when a hook is run is based on the filename of the hook. The filename format is `<pre|post>-<install|beforemodify|uninstall>-<packageID|all>.ps1`. The first section is for the timing of when the hook script runs. Filenames that start with `pre` run before the package automation script (e.g. the `chocolateyInstall.ps1`), while filenames that start with `post` are run afterwards. The second section of the filename determines which package automation script the hook is run before or after. The third section of the filename is either a string of the package ID for which the hook should be run, or the keyword `all` to specify that the hook should be run for all package IDs.
```

2022-10-19 18:30 UTC, corbob commented on input/en-us/features/hook.md
> +## Still under development
This is supposed to be a subheading of Recommendations right?

```suggestion
### Still under development
```

2022-10-19 18:30 UTC, corbob commented on input/en-us/features/hook.md
> +## Avoid taking dependencies on regular packages
This is supposed to be a subheading of Recommendations right?

```suggestion
### Avoid taking dependencies on regular packages
```

2022-10-19 18:30 UTC, corbob commented on input/en-us/features/hook.md
> +## Do take dependencies on extension packages
This is supposed to be a subheading of Recommendations right?

```suggestion
### Do take dependencies on extension packages
```

2022-10-27 01:40 UTC, TheCakeIsNaOH commented on input/en-us/features/hook.md
> +Hooks allow you to run code before a package automation script like a `chocolateyInstall.ps1` runs, or after. They even work when automation scripts are not included in the package. Each script can s
Yup, change looks good.

2022-10-27 01:40 UTC, TheCakeIsNaOH commented on input/en-us/features/hook.md
> +## Still under development
Fixed

2022-10-27 01:40 UTC, TheCakeIsNaOH commented on input/en-us/features/hook.md
> +## Do take dependencies on extension packages
Fixed

2022-10-27 01:41 UTC, TheCakeIsNaOH commented on input/en-us/features/hook.md
> +## Avoid taking dependencies on regular packages
Fixed

2022-10-27 01:41 UTC, TheCakeIsNaOH commented on input/en-us/features/hook.md
> +The conditions for when a hook is run is based on the filename of the hook. `<pre|post>-<install|beforemodify|uninstall>-<packageID|all>.ps1` is the filename format. The first section is for timing o
Fixed

2022-10-27 01:41 UTC, TheCakeIsNaOH commented on input/en-us/features/hook.md
> +Hook script are PowerShell `.ps1` files, and are run in the same environment as package automation scripts are, so they can access all the same environment variables and helpers.
Fixed

2022-11-01 16:23 UTC, gep13 approved these changes
LGTM!

2022-11-01 16:25 UTC, merged

2022-11-01 16:25 UTC, gep13 commented
@TheCakeIsNaOH this looks great! Thanks for getting this new page added, and for the hook feature in general!