(#584) Update documentation for Chocolatey CLI/CLE
chocolatey/docs pull request #585
Opened 2022-10-21 16:00 UTC by AdmiringWorm

## Description Of Changes

This pull request updates the documentation we have for the Commands
and the PowerShell Functions available in Chocolatey CLI and in
Chocolatey Licensed Extension.

There are more work needed to get the proper documentation from
Chocolatey Licensed Extension.

## Motivation and Context

To keep the documentation up to date with the latest codebase.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [xa] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated (I think this was done automatically)

## Related Issue

Fixes #584

2022-10-21 19:38 UTC, gep13 requested changes

2022-10-21 19:38 UTC, gep13 commented on input/en-us/choco/commands/support.md
> -~~~
Why is this part being removed?

2022-10-21 19:38 UTC, gep13 commented on input/en-us/create/functions/get-chocolateypath.md
> +  - docs/helpersgetchocolateypath
Did you do work to add these, or were they created automatically? Since this is a new page, these redirects will not be required.

2022-10-24 08:59 UTC, AdmiringWorm commented on input/en-us/choco/commands/support.md
> -~~~
The `GenerateDocs` removed it. As it was for the support command, I didn't think it made sense to keep it.

2022-10-24 08:59 UTC, AdmiringWorm commented on input/en-us/create/functions/get-chocolateypath.md
> +  - docs/helpersgetchocolateypath
Automatically generated by `GenerateDocs`

2022-11-01 11:34 UTC, gep13 commented on input/en-us/choco/commands/support.md
> -~~~
Running the site locally with these changes in place, I see the following:

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/1271146/199223957-00270a67-2abe-4c65-9eb2-08be2145ac8c.png">

As opposed to:

![image](https://user-images.githubusercontent.com/1271146/199224021-27f30893-ee9c-4758-b05c-b53d1856e7ce.png)

So I believe that we need to get this change backed out.  I can take care of that.

2022-11-01 11:36 UTC, gep13 commented on input/en-us/create/functions/get-chocolateypath.md
> +  - docs/helpersgetchocolateypath
There is no harm in them being there, it is just that they will never be used.  Perhaps the GenerateDocs.ps1 script need to be "smarter" about exactly when they are added in.

2022-11-01 11:38 UTC, gep13 commented on input/en-us/choco/commands/support.md
> -~~~
If anything, it looks like the output from running `choco support -h` isn't quite right.  This could be an oversight on that command's help output.  I will raise an issue if I find anything.

2022-11-01 13:06 UTC, gep13 approved these changes
LGTM!

2022-11-01 13:06 UTC, gep13 commented
@AdmiringWorm thanks for getting all of this updated!

2022-11-01 13:13 UTC, merged