(#618) Update AU docs and links
chocolatey/docs pull request #620
Opened 2022-12-16 15:04 UTC by vexx32

## Description Of Changes

- Update links and docs mentioning AU.

## Motivation and Context

As AU is no longer being maintained by the original owner and we have forked it with the intent that it be maintained by the chocolatey community

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

#618

2022-12-16 15:08 UTC, pauby requested changes

2022-12-16 15:08 UTC, pauby commented on input/en-us/create/automatic-packages.md
> +- RECOMMENDED - Using only Powershell via [Automatic Update module AU](https://github.com/chocolatey-community/chocolatey-au).
```suggestion
- RECOMMENDED - Using only Powershell via [Chocolatey Automatic Package Updater Module](https://github.com/chocolatey-community/chocolatey-au).
```

2022-12-16 15:08 UTC, pauby commented on input/en-us/create/automatic-packages.md
> +- RECOMMENDED - Using only Powershell via [Automatic Update module AU](https://github.com/chocolatey-community/chocolatey-au).
This is consistent with the text below.

2022-12-16 16:36 UTC, pauby commented
LGTM! Can you rebase @vexx32 ?

2022-12-16 18:25 UTC, vexx32 commented
Sorted 🙂

2022-12-16 19:19 UTC, gep13 requested changes
Just a small suggestion...

2022-12-16 19:19 UTC, gep13 commented on input/en-us/create/automatic-packages.md
> +- RECOMMENDED - Using only Powershell via [Chocolatey Automatic Package Updater Module](https://github.com/chocolatey-community/chocolatey-au).
```suggestion
- RECOMMENDED - Using only PowerShell via [Chocolatey Automatic Package Updater Module](https://github.com/chocolatey-community/chocolatey-au).
```

2022-12-16 22:09 UTC, vexx32 commented on input/en-us/create/automatic-packages.md
> +- RECOMMENDED - Using only Powershell via [Chocolatey Automatic Package Updater Module](https://github.com/chocolatey-community/chocolatey-au).
Amended, thanks!

2022-12-17 19:42 UTC, pauby approved these changes

2022-12-17 19:43 UTC, merged