(#119) Overhaul package moderation docs
chocolatey/docs pull request #624
Opened 2022-12-16 18:20 UTC by pauby

## Description Of Changes
Overhauling the package moderation docs to make them easier to follow for both moderators and maintainers going through the process.

## Motivation and Context
Many reasons. #119 has the best explanation.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

#119

2022-12-19 09:49 UTC, gep13 requested changes

2022-12-19 09:49 UTC, gep13 commented on input/en-us/create/create-packages.md
> +   This is the name of the package itself and must exist to be able to use the `choco pack` command to create a package. This will contain the package name provided to the `choco new` command automat
```suggestion
   This is the name of the package itself and must exist to be able to use the `choco pack` command to create a package. This will contain the package name provided to the `choco new` command automatically. An example would be `<id>microsoft-teams.install</id>`. See [naming your package](#naming-your-package) for more information and guidance.
```

2022-12-19 09:49 UTC, gep13 commented on input/en-us/community-repository/moderation/index.md
> +* The `<licenseUrl>` field must contain a valid URL that points to th elicense for the project. Note that this should not be a generic license definition but the location of where the license is stat
```suggestion
* The `<licenseUrl>` field must contain a valid URL that points to the license for the project. Note that this should not be a generic license definition but the location of where the license is stated within the project. See [package metadata](xref:create-packages#package-metadata-in-the-nuspec-file) for more information on what this field should contain.
```

2022-12-19 09:49 UTC, gep13 commented on input/en-us/create/create-packages.md
> +### Package Metadata in the Nuspec file
Should this part be made into a fragment, as similar information is provided earlier in this PR.

2024-06-01 11:05 UTC, closed without merging

2024-06-02 05:09 UTC, TheCakeIsNaOH commented
@pauby are you planning on taking another go at this, or is the issue available for someone else to be assigned to it?

2024-06-03 09:52 UTC, pauby commented
@TheCakeIsNaOH was an overzealous branch cleanup. I've raised #1002 to cover it.

> or is the issue available for someone else to be assigned to it

You are welcome, as is anybody else, to contribute to this. Just a heads-up though, my goal is to completely rewrite the moderation docs rather than updating them.