(#632) Add page for setting up client certificate authentication
chocolatey/docs pull request #634
Opened 2023-01-12 21:35 UTC by TheCakeIsNaOH

## Description Of Changes

Adds a page about setting up client certificate authentication

## Motivation and Context

See #632

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #632

2023-09-07 15:27 UTC, pauby requested changes
A lot of the changes are just from the [writing guidelines](https://github.com/chocolatey/docs#writing-documentation).

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +Description: Set Up A Repository With Certificate Authentication
```suggestion
Title: How To Set Up a Repository With Certificate Authentication
Description: How To Set Up a Repository With Certificate Authentication
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +## Summary
We normally end with a Summary rather than start with one. In other documentation there is usually a heading here but the closest I could find was 'Overview'.

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +Certificates can also be added to configured sources. Just like for other commands, the `--cert` argument is used to specify the path to the `.pfx` file and the the `--certpassword` argument is used
```suggestion
Certificates can also be added to configured sources. Just like for other commands, the `--cert` option is used to specify the path to the `.pfx` file and the the `--certpassword` option is used to specify the password, if required. When adding/updating a source and specifying a certificate, it applies to that source only.
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +choco source add --name="Internal-Repository" --source="https://repository.example.com/api/v2/" --cert="C:\path\to\certificate.pfx" --certpassword="VALUE"
```suggestion
choco source add --name="'Internal-Repository'" --source="'https://repository.example.com/api/v2/'" --cert="'C:\path\to\certificate.pfx'" --certpassword="'<CER6TIFICATE PASSWORD>'"
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +Most package repositories do not naively support client certificate authentication, instead requiring a reverse proxy like Nginx or Apache to do the heavy lifting. This may take the form of having th
```suggestion
## Repository Setup

Most package repositories do not naively support client certificate authentication, instead requiring a reverse proxy like Nginx or Apache to do that. This may take the form of having the repository allowing anonymous access, and handling all authentication on the reverse proxy side, or the repository may support user authentication via a header after the reverse proxy validates the certificate.
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +In other cases, a certificate authority and client certificates will need to be generated. There is a [external blog post](https://fardog.io/blog/2017/12/30/client-side-certificate-authentication-wit
```suggestion
### Generating the Certificates

In organizational contexts, where the organization already has client certificates distributed to users, the certificate of the certificate authority can be used to authenticate clients. 

In other cases, a certificate authority and client certificates will need to be generated. There is an [external blog post](https://fardog.io/blog/2017/12/30/client-side-certificate-authentication-with-nginx/) that goes into detail about how these could be generated for Nginx.
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +2. Add these lines to the nginx configuration under the `server` that is reverse-proxying the repository:
```suggestion
### Reverse Proxy Setup

There are many configuration scenarios, and reverse proxies available, to give specific recommendations. For Nginx, once the reverse proxy is set up, client certificates can be enabled like this:

1. Copy the public key of the certificate authority to a location that Nginx can access.
2. Add these lines to the Nginx configuration under the `server` that is reverse-proxying the repository:
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +JFrog has somewhat different recommendations for Artifactory, see [their setup instructions](https://www.jfrog.com/confluence/display/JFROG/HTTP+Settings#HTTPSettings-ConfiguringaReverseProxytoSuppor
```suggestion
3. Reload the Nginx configuration with `nginx -S reload`.

The following guides are available:

* For Apache, there is a [guide from Sonatype](https://help.sonatype.com/repomanager3/nexus-repository-administration/user-authentication/authentication-via-remote-user-token#AuthenticationviaRemoteUserToken-ConfiguringtheReverseProxy).
* For Artifactory, [JFrog has different recommendations](https://www.jfrog.com/confluence/display/JFROG/HTTP+Settings#HTTPSettings-ConfiguringaReverseProxytoSupportmTLSconfigreverseproxy).
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +1. Add the below snippet to the Nginx configuration, right before the `server` block. [Source](https://stackoverflow.com/questions/55325548/getting-common-name-from-distinguished-name-of-client-certi
```suggestion
### Using Sonatype Nexus

Sonatype Nexus has the capability to use the client certificate common name to authenticate a a specific user. There are set up instructions below, which are based on the [official documentation](https://help.sonatype.com/repomanager3/nexus-repository-administration/user-authentication/authentication-via-remote-user-token), but modified to be based on Nginx instead of Apache:

1. Create a user named `Choco-User` that can access the `nuget-testing` repository.
1. Enable the "Rut Auth Realm" in Settings -> Security -> Realms.
1. Add the "Ruth Auth" capability under Settings -> System ->  Capabilities -> Create Capability with the http header name being `X-SSO-USER`.
1. Add the [below snippet to the Nginx configuration](https://stackoverflow.com/questions/55325548/getting-common-name-from-distinguished-name-of-client-certificate-in-nginx), right before the `server` block:
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +1. Add the below snippet inside the `location` block in the `server` block of the reverse proxy and then reload the Nginx config
```suggestion
1. Add the below snippet inside the `location` block in the `server` block of the reverse proxy and then reload the Nginx config:
```

2023-09-07 15:27 UTC, pauby commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +1. Test out the configuration, see the Client Setup section above
```suggestion
1. Test out the configuration, see the Client Setup section above.
```

2023-09-08 03:13 UTC, TheCakeIsNaOH commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +
Done

2023-09-08 03:13 UTC, TheCakeIsNaOH commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +## Summary
I switched it to "Overview"

2023-09-08 11:30 UTC, pauby requested changes

2023-09-08 14:58 UTC, pauby submitted a review, later dismissed
Thanks for making those changes @TheCakeIsNaOH

2023-09-08 14:59 UTC, pauby commented
@corbob will also pick this up and go through the instructions.

2023-09-09 20:15 UTC, corbob requested changes
I haven't had a chance to test out the steps yet, hopefully will have an opportunity in the next week or so. Having had a read through it, there are a few spots that stood out to me.

2023-09-09 20:15 UTC, corbob commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +Most package repositories do not naively support client certificate authentication, instead requiring a reverse proxy like Nginx or Apache to do that. This may take the form of having the repository
```suggestion
Most package repositories do not natively support client certificate authentication, instead requiring a reverse proxy like Nginx or Apache to do that. This may take the form of having the repository allowing anonymous access, and handling all authentication on the reverse proxy side, or the repository may support user authentication via a header after the reverse proxy validates the certificate.
```

I assume the word intended is natively not naively.

2023-09-09 20:15 UTC, corbob commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +There are many configuration scenarios, and reverse proxies available, to give specific recommendations. For Nginx, once the reverse proxy is set up, client certificates can be enabled like this:
The first sentence here feels a little awkward. Perhaps something like this:

```suggestion
There are many configuration scenarios and reverse proxies available. Far too many to give specific recommendations. However, to give a general idea for using Nginx; once the reverse proxy is set up, client certificates can be enabled like this:
```

2023-09-09 20:15 UTC, corbob commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +1. Add the "Ruth Auth" capability under Settings -> System ->  Capabilities -> Create Capability with the http header name being `X-SSO-USER`.
One of these is presumably wrong. I presume it's either Rut Auth, or Ruth Auth...

2023-09-09 20:15 UTC, corbob commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +1. Add users to Nexus with the usernames the same as the Common Name (CN) of each client certificate. Assign appropriate permissions to each Nexus user, according to what the owner of the client cert
This feels like a lot for a single step, and maybe not proper to split into multiple steps... Perhaps something like this?

```suggestion
1. Add users to Nexus.
    * The username should match the Common Name (CN) of the client certificate.
    * Assign appropriate permissions to each Nexus user, according to what the owner of the client certificate should have access to.
    * Depending on how the client certificates are generated and the pattern of Common Names used, it may be possible to use external role mapping to automatically set this up.
```

2023-09-09 22:16 UTC, TheCakeIsNaOH commented on input/en-us/guides/organizations/set-up-certificate-authentication.md
> +1. Add the "Ruth Auth" capability under Settings -> System ->  Capabilities -> Create Capability with the http header name being `X-SSO-USER`.
It's Rut Auth, fixed

2023-09-25 18:48 UTC, corbob approved these changes
LGTM!

2023-09-25 18:49 UTC, corbob commented
Thanks for getting this added @TheCakeIsNaOH! I've taken it for a spin and can confirm it all works as expected. I've rebased your PR and enabled auto-merge 👍

2023-09-25 19:04 UTC, merged

2023-09-25 20:30 UTC, TheCakeIsNaOH commented
Thank you very much for the reviews and testing @pauby @corbob