(#673) Add third party notice to environment documentation
chocolatey/docs pull request #674
Opened 2023-03-14 16:31 UTC by steviecoaster

## Description Of Changes

Adds documentation around which packages are 3rd party software, and outlines the responsibility of the customer.

## Motivation and Context

From a security perspective we should clearly outline what software Chocolatey Software _does not own_.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #673

2023-03-15 12:55 UTC, pauby requested changes

2023-03-15 12:55 UTC, pauby commented on input/shared/third-party-notice.txt
> +This software includes, but is not limited too:
```suggestion
This software includes, but is not limited to:
```

2023-03-15 12:55 UTC, pauby commented on input/shared/third-party-notice.txt
> +- Dotnet ASP Net Core Module for IIS (`dotnet-6.0-aspnetcoremodule-v2`)
```suggestion
- .NET Runtime (`dotnet-6.0-runtime`)
- .NET ASP Net Core Runtime (`dotnet-6.0-aspnetruntime`)
- .NET ASP Net Core Module for IIS (`dotnet-6.0-aspnetcoremodule-v2`)
```

2023-03-15 12:55 UTC, pauby commented on input/shared/third-party-notice.txt
> +This solution has been provided as a quick way to get up and running with Chocolatey, it is not a SaaS solution. It is the responsibility
```suggestion
This solution has been provided as a quick way to get up and running with Chocolatey For Business. It is not a SaaS solution. It is the responsibility
```

2023-03-15 12:55 UTC, pauby commented on input/shared/third-party-notice.txt
> +of you, the customer, to ensure the versions of software included as part of the Solution are kept updated per your needs.
```suggestion
of you, the customer, to ensure the software included as part of the solution is updated according to your needs.
```

2023-03-17 15:23 UTC, steviecoaster commented
@pauby your comments have been addressed, and are ready for a re-review.

2023-03-17 17:25 UTC, pauby requested changes

2023-03-17 17:25 UTC, pauby commented on input/shared/third-party-notice.txt
> +If you would like to be subscribed to this mailing list, you can do so by visiting https://groups.google.com/forum/#!forum/chocolatey-announce and providing the email address you would like to use to
```suggestion
Please subscribe to the [mailing list](https://groups.google.com/forum/#!forum/chocolatey-announce) if you would like to receive those annoucements.
```

2023-03-17 17:25 UTC, pauby commented on input/shared/third-party-notice.txt
> +If you would like to be subscribed to this mailing list, you can do so by visiting https://groups.google.com/forum/#!forum/chocolatey-announce and providing the email address you would like to use to
Bare links look terrible 😢

2023-03-17 18:03 UTC, steviecoaster commented on input/shared/third-party-notice.txt
> +If you would like to be subscribed to this mailing list, you can do so by visiting https://groups.google.com/forum/#!forum/chocolatey-announce and providing the email address you would like to use to
Fixed!

2024-06-01 13:34 UTC, pauby commented
@steviecoaster is this PR still needed? Can you see the comment from @ryanrichter94 [above](https://github.com/chocolatey/docs/pull/674#issuecomment-1580868273)?

2024-07-17 04:00 UTC, closed without merging