Add group membership example to CCM api
chocolatey/docs pull request #687
Opened 2023-04-04 18:40 UTC by steviecoaster

## Description Of Changes

Add examples to CCM API documentation for using external data to manipulate groups

## Motivation and Context

With no native integration to LDAP or other systems, the best way to manage group memberships in CCM is programmatically via the API

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

2023-04-05 08:33 UTC, pauby requested changes
The code in here I feel belongs in a module. Does ChocoCCM not have this functionality already that we can re-use rather than having the code here?

Note that I haven't tested the code works. I'll leave that to somebody else, but the code needs to be tested and confirmed working before we approve this.

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +## Sync Central Management Groups with external data sources
```suggestion
## Sync Chocolatey Central Management Groups With External Data Sources
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +It is possible to keep your Central Management group(s) and their memberships up to date  with external data sources by leveraging the
```suggestion
It is possible to keep your Chocolatey Central Management group(s), and their memberships, up to date with external data sources by leveraging the
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +The following functions will help you to use an external datasource such as SCCM, Active Directory, or a file to manage your Central Management groups!
```suggestion
The following functions will help you to use an external datasource such as SCCM, Active Directory, or a file to manage your Chocolatey Central Management groups!
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +### Authenticating to the API
```suggestion
### Authentication
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +The first thing you'll need to do is authenticate to your Central Management instance with credentials that have appropriate permissions to manage group memberships. We'll use the following `Connect-
```suggestion
The first thing you'll need to do is authenticate to your Chocolatey Central Management instance with credentials that have appropriate permissions to manage group memberships. We'll use the following `Connect-CCMServer` function to provide that capability:
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +        $CcmServerHostname,
Should this not just be `Name` to be consistent with standard PowerShell functions / cmdlets? The function name indicates it's a server we're connecting to.

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This function accepts a `PSCredential` object via `-Credential` to store your credentials for Central Management. Additionally the `-CcmServerHostname` parameter accepts the DNS name you use to acces
```suggestion
This function accepts a `PSCredential` object via `-Credential` to store your credentials for Chocolatey Central Management. Additionally the `-CcmServerHostname` parameter accepts the DNS name you use to access Central Management's web interface. Use the `-UseSSL` switch parameter if you've configured your Central Management web interface to be accessed via an HTTPS connection (You _really_ should!).
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This function accepts a `PSCredential` object via `-Credential` to store your credentials for Central Management. Additionally the `-CcmServerHostname` parameter accepts the DNS name you use to acces
Should this not go into comments in the code itself? That way it is transported whenever the code is copied and will work for comment based function help?

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +### Retrieving all computers currently in Central Management
```suggestion
### Retrieving All Computers Currently In Chocolatey Central Management
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +In order to accurately manage group membership we will need to retrieve all of the machines that are currently enrolled into Central Management. The following function will accomplish this.
```suggestion
In order to accurately manage group membership we will need to retrieve all of the machines that are currently enrolled in Chocolatey Central Management. The following function will accomplish this:
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +        if (-not $Session) { throw "Not connected to CCM instance. Run Connect-CCMServer first!" }
Should that not be `$global:Session` to indicate that this is coming from somewhere else? Or should it be explicitly passed in?

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +        $script:Session = $Session
Should this not be `$global:Session = $Session`? I'm unsure why we set this to a script level variable?

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +            Uri        = "$($protocol)://$CcmHost/api/services/app/Computers/GetAll"
This looks like it's assuming those variables exist, but they are not passed to the function. Chaining the functions together like this doesn't feel right. If we need anything inside the function, then this should be part of an overall script or module and call out specific `$script:` level variables so that you are not polluting the user session. Or it should be separate functions (which is what you have) that provide everything the function needs via parameters.

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +
Do we not need to add any error checking here for invalid data?

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This script works in conjunction with `Connect-CCMServer`. Failure to connect to your instance first will result in an error! This script includes a `-Detailed` switch parameter that can be used to i
This kind of answers my question above, but there are two separate functions here. It's not a script.

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +### Validating a Group
```suggestion
### Validating A Group
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +We don't want to unnecessarily duplicate Groups inside of our Central Management instance. The following function sets up some guardrails
```suggestion
We don't want to unnecessarily duplicate groups inside of our Chocolatey Central Management instance. The following function sets up some guardrails:
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This function queries your Central Management instance for the group provided via the mandatory `-Group` parameter and returns `$true` or `$false` based on the group's existence in your environment.
```suggestion
This function queries your Chocolatey Central Management instance for the group provided via the mandatory `-Group` parameter and returns `$true` or `$false` based on the group's existence.
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +### Adding a Group
```suggestion
### Adding A Group
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +Once we have connected to our environment, retrieved all our reporting computers, and validated our group we may need to actually _create_ the Group we want. The following function does just that!
```suggestion
Once we have connected to our Chocolatey Central Management server, retrieved all our reporting computers, and validated our groups, we may need to actually _create_ the group we want. The following function does just that!
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +            return $Group
```suggestion
            [pscustomObject](Invoke-RestMethod @params |
            Select-Object -ExpandProperty result |
            Where-Object Name -EQ $Group | Select-Object Name, Id)
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +            return $Group
Same result, just a suggestion to condense the code.

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This function accepts the mandatory `-Group` parameter for the Group that we would like to create, and an optional `-Desciption` parameter if we would like to add a description to our newly created G
```suggestion
This function accepts the mandatory `-Group` parameter for the group that we would like to create, and an optional `-Desciption` parameter if we would like to add a description to our newly created group.
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +### Managing the Group's membership
```suggestion
### Managing Group Memberships
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +Whew, getting closer! We've now got our functions for:
```suggestion
Phew, getting closer! We've now got our functions for:
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +- Connecting to CCM
```suggestion
- Connecting to Chocolatey Central Management
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +- Verifying a Group's existence
```suggestion
- Verifying a group's existence
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +- Creating a new Group
```suggestion
- Creating a new group
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This function will actually manipulate the members of our Group.
```suggestion
This function will actually manipulate the members of our group:
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +        #Loop SCCM Computers, and build object for Group payload into CCM API
```suggestion
        #Loop CCM Computers, and build object for group payload into CCM API
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +### Put it all together
```suggestion
### Putting It All Together
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +#### Example - SSCM Collections
```suggestion
#### Example - SCCM Collections
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This example gets the computers from an Active Directory OU and creates a Central Management group
```suggestion
This example gets the computers from an Active Directory OU and creates a Chocolatey Central Management group.
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This example reads data from a CSV file and creates a Central Management group
```suggestion
This example reads data from a CSV file and creates a Chocolatey Central Management group.
```

2023-04-05 08:33 UTC, pauby commented on input/en-us/central-management/usage/api/examples.md
> +This example is rather simple and assumes you have copied the above functions into your PowerShell session so they are available.
```suggestion
This example reads data from SCCM and creates a Chocolatey Central Management group. It's assumes you have copied the above functions into your PowerShell session so they are available.
```

2023-04-06 14:13 UTC, steviecoaster commented
> A lot of the changes are consistency. For headings, looking at other docs, we capitalise them.
> 
> The code in here I feel belongs in a module. Does ChocoCCM not have this functionality already that we can re-use rather than having the code here?
> 
> Note that I haven't tested the code works. I'll leave that to somebody else, but the code needs to be tested and confirmed working before we approve this.

Code here is from a Professional Services engagement. It's working in production, so thoroughly tested. Bits and pieces of this are ripped out of ChocoCCM, but they've been fixed to actually work whereas they are broken in the module currently.

I know that module is slated for re-write _sometime_, so this example can be changed in future to leverage the module once that has been completed. But being able to point to this example in the interim will be really helpful, as we get this kind of question _kinda_ frequently.

2023-04-19 16:41 UTC, steviecoaster commented on input/en-us/central-management/usage/api/examples.md
> +        $script:Session = $Session
Same answer as before. Allows the CCM functions here to use it, but not be available elsewhere

2023-04-19 16:44 UTC, steviecoaster commented on input/en-us/central-management/usage/api/examples.md
> +            Uri        = "$($protocol)://$CcmHost/api/services/app/Computers/GetAll"
They are set by Connect-CCMServer and will come along for the ride. Since we check for `$session`, also made by that function they'll be available. This keeps the function easier to use.

2023-04-20 00:14 UTC, vexx32 commented on input/en-us/central-management/usage/api/examples.md
> +        if (-not $Session) { throw "Not connected to CCM instance. Run Connect-CCMServer first!" }
That only makes sense if this is distributed as a module. Which it's not, here, it's just a loose collection of functions, no? If folks are just copy-pasting this into a console, script: and global: are identical scopes.

2023-05-11 17:47 UTC, steviecoaster commented on input/en-us/central-management/usage/api/examples.md
> +        $script:Session = $Session
Shoot, good catch. Fixed it, waiting for remaining review for more changes before it is pushed up.

2024-03-21 18:23 UTC, vexx32 approved these changes
I think this looks good for now. Will be good to get ChocoCCM sorted out proper again eventually, but this'll do for now. Thanks for sorting this out @steviecoaster!

2024-06-01 13:33 UTC, pauby commented
@steviecoaster with the recent changes in CCM (All Computers Group and Recurring Deployments) is this still needed?

2024-07-17 04:00 UTC, closed without merging