Utilized the tabs of choco-theme for CCM documentation.
chocolatey/docs pull request #693
Opened 2023-04-11 14:45 UTC by imm0rtalsupp0rt

## Description Of Changes
There were two scenarios for database authentication that were unsupported or not recommended. These were removed and the rest of the scenarios were put into tabs. I also updated the SQL server requirement to 2019 and made some of the warnings and notes consistent across the tabs.

## Motivation and Context
The original design was cluttered and left customers with questions about whether they were following the right steps. With the tabs in place, the other scenarios are hidden from view so there is less of a chance that someone can lose their place while going through the documentation.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #

2023-04-11 16:10 UTC, st3phhays reviewed
This is lookin pretty good! I made a few comments over removing acronyms and spelling out the terms instead.

I will pull this down and test out the tabs locally to ensure those are good, kind of hard to tell by looking at the diffs.

One thing I would say too, can you create an issue for this pull request and then attribute this commit to it and the pr? Since we're introducing the tabs for the first time in the docs and it's a pretty big change, it might be good to have this tracked. In your commit, it would be great if you added a body to it with some of the details you put in the pull request itself as well. 

So your commit would be something like:

```
(#1234) Add tabs to CCM database docs
There were two scenarios for database authentication that were
unsupported or not recommended. These were removed and the rest of the
scenarios were put into tabs. I also updated the SQL server requirement
to 2019 and made some of the warnings and notes consistent across the
tabs.
```

2023-04-11 16:10 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +The quickest option to get going with the database is to use the Community Repository, or an internalized version of a SQL Server package from the community repository. For SQL Server Express 2019, r
```suggestion
The quickest option to get going with the database is to use the Community Repository, or an internalized version of a SQL Server package from the Community Repository. For SQL Server Express 2019, run the following:

```

We have this capitalized in some places and not in others. I think it should be capitalized. I'm questioning also if it should be Chocolatey Community Repository too? @steviecoaster

2023-04-11 16:43 UTC, st3phhays requested changes
Here I've changed the heading levels of the content inside the tabs. Since this tab component is nested under an `<h3>` element, all other headings inside it must be `<h4>` & `<h5>` to maintain hieachy. This is especially important for things like screen readers to understand the context of a document.

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +## Windows Authentication to Local SQL Server
```suggestion
#### Windows Authentication to Local SQL Server

```

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +### Licensed SQL Server
```suggestion
##### Licensed SQL Server

```

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +### SQL Server Express
```suggestion
##### SQL Server Express

```

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +## Active Directory Authentication to Remote SQL Server
```suggestion
#### Active Directory Authentication to Remote SQL Server

```

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +## SQL Server Authentication to Local SQL Server
```suggestion
#### SQL Server Authentication to Local SQL Server

```

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +### Licensed SQL Server
```suggestion
##### Licensed SQL Server

```

2023-04-11 16:43 UTC, st3phhays commented on input/en-us/central-management/setup/database.md
> +### SQL Server Express
```suggestion
##### SQL Server Express

```

2023-04-12 16:42 UTC, ryanrichter94 requested changes
Couple of minor things change.

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +The quickest option to get going with the database is to use the Chocolatey Community Repository, or an internalized version of a SQL Server package from the community repository. For SQL Server Expr
```suggestion
The quickest option to get going with the database is to use the Chocolatey Community Repository, or an internalized version of a SQL Server package from the community repository. For SQL Server Express 2022, run the following:

```

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +The quickest option to get going with the database is to use the Chocolatey Community Repository, or an internalized version of a SQL Server package from the community repository. For SQL Server Expr
Latest sql-server-express package installs 2022 by default now.

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +# TODO: THIS LINE IS VERSION DEPENDENT! Replace MSSQL15 with whatever version you have
```suggestion
# TODO: THIS LINE IS VERSION DEPENDENT! Replace MSSQL16 with whatever version you have

```

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +# TODO: THIS LINE IS VERSION DEPENDENT! Replace MSSQL15 with whatever version you have
SQL Express 2022's value is MSSQL16

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +New-ItemProperty 'HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQLServer\' -Name 'LoginMode' -Value 2 -Force
```suggestion
New-ItemProperty 'HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQLServer\' -Name 'LoginMode' -Value 2 -Force

```

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +> Items suffixed with "`:`" mean a value should be provided; items without are simply switches.
```suggestion
> Items suffixed with "`:`" mean a value should be provided. Items without are simply switches.

```

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +> Items suffixed with "`:`" mean a value should be provided; items without are simply switches.
Reduces confusion as `;` is also a line ending used within the commands.

2023-04-12 16:42 UTC, ryanrichter94 commented on input/en-us/central-management/setup/database.md
> +* [Scenario 4 - SQL Server Authentication to Remote SQL Server](http://localhost:5080/en-us/central-management/setup/database#scenario-four)
Remove localhost:5080 from URL references.

2023-04-12 16:52 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +> CCM packages do **NOT** install SQL Server. You must take care of that in the prerequisites. Do not even start on CCM installs until you have a SQL Server instance up and ready. I repeat, SQL Serve
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:53 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +The Central Management Database package:
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:53 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +The quickest option to get going with the database is to use the Community Repository, or an internalized version of a SQL Server package from the community repository. For SQL Server Express 2019, r
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:53 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
>  The CCM database package will add or update a database to an existing SQL Server instance.
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:53 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +## Windows Authentication to Local SQL Server
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:54 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +### Licensed SQL Server
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:54 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +## Active Directory Authentication to Remote SQL Server
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:54 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +## SQL Server Authentication to Local SQL Server
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:54 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +### Licensed SQL Server
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:54 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +### SQL Server Express
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:54 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +### SQL Server Express
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 16:55 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +## SQL Server Account to Remote SQL Server
Made change in commit [89b12cb](https://github.com/chocolatey/docs/pull/693/commits/89b12cb27a852bb07b1744917ebf06cb3cd03e4a)

2023-04-12 17:03 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +The quickest option to get going with the database is to use the Chocolatey Community Repository, or an internalized version of a SQL Server package from the community repository. For SQL Server Expr
Made change with commit [fb382fe](https://github.com/chocolatey/docs/pull/693/commits/fb382fe32760c3a823d02b6252b0a6a009e45543)

2023-04-12 17:04 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +# TODO: THIS LINE IS VERSION DEPENDENT! Replace MSSQL15 with whatever version you have
Made change with commit [fb382fe](https://github.com/chocolatey/docs/pull/693/commits/fb382fe32760c3a823d02b6252b0a6a009e45543)

2023-04-12 17:04 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +New-ItemProperty 'HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQLServer\' -Name 'LoginMode' -Value 2 -Force
Made change with commit [fb382fe](https://github.com/chocolatey/docs/pull/693/commits/fb382fe32760c3a823d02b6252b0a6a009e45543)

2023-04-12 17:04 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +> Items suffixed with "`:`" mean a value should be provided; items without are simply switches.
Made change with commit [fb382fe](https://github.com/chocolatey/docs/pull/693/commits/fb382fe32760c3a823d02b6252b0a6a009e45543)

2023-04-12 17:04 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +* [Scenario 4 - SQL Server Authentication to Remote SQL Server](http://localhost:5080/en-us/central-management/setup/database#scenario-four)
Made change with commit [fb382fe](https://github.com/chocolatey/docs/pull/693/commits/fb382fe32760c3a823d02b6252b0a6a009e45543)

2023-04-18 11:40 UTC, gep13 requested changes
Noticed something that I think needs to be changed.

@imm0rtalsupp0rt are you happy with how to re-word commits as per @st3phhays suggestion here: https://github.com/chocolatey/docs/pull/693#pullrequestreview-1379615422. If not, happy to jump on a call to walk you through it at some point.

2023-04-18 11:40 UTC, gep13 commented on input/en-us/central-management/setup/database.md
> +* [Scenario 4 - SQL Server Authentication to Remote SQL Server](http://docs.chocolatey.org/en-us/central-management/setup/database#scenario-four)
@imm0rtalsupp0rt is there a reason that we need to use direct absolute URL's here?  Is this something that is required to make the tabs work?

If not, it would be better to use a xref link, similar to what we do elsewhere, since that will mean that generated links will continue to work, if we change the structure of the site.

2023-04-18 11:40 UTC, gep13 commented on input/en-us/central-management/setup/service.md
> +Please refer to the [Chocolatey Central Management Service Windows Account Considerations](https://docs.chocolatey.org/en-us/central-management/setup/service#chocolatey-central-management-service-win
Similar comment to elsewhere.  Can we make this an xref link?

2023-04-18 16:46 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/database.md
> +* [Scenario 4 - SQL Server Authentication to Remote SQL Server](http://docs.chocolatey.org/en-us/central-management/setup/database#scenario-four)
[I made this change in this commit.](https://github.com/chocolatey/docs/commit/50b286283a5023eff96874addf0c71a95df6f468)

2023-04-18 16:47 UTC, imm0rtalsupp0rt commented on input/en-us/central-management/setup/service.md
> +Please refer to the [Chocolatey Central Management Service Windows Account Considerations](https://docs.chocolatey.org/en-us/central-management/setup/service#chocolatey-central-management-service-win
[I made this change in this commit.](https://github.com/chocolatey/docs/commit/50b286283a5023eff96874addf0c71a95df6f468)

2023-06-07 15:18 UTC, merged