Add support lifecycle, update Choco requirements
chocolatey/docs pull request #699
Opened 2023-04-19 21:04 UTC by vexx32

## Description Of Changes

- Update Chocolatey CLI requirements
- Added a new page that enumerates the support lifecycle and supported Windows versions
- Add a link to MS docs on enabling TLS 1.2 on older operating systems to the troubleshooting page

## Motivation and Context

As we get closer to v2.0, we need to update our support info and requirements for the new chocolatey versions.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

[Clickup](https://app.clickup.com/t/20540031/PROJ-406)

2023-04-19 21:04 UTC, vexx32 commented
@gep13 @pauby 

I checked through CLE and Agent pages, and neither of those currently mention required framework versions and so on. Should they? They essentially "inherit" the same supported frameworks and windows versions that CLI does, by virtue of CLI being required to be present before they can be installed or used. So I guess it's not _necessary_ that they mention explicit requirements beyond the minimum Chocolatey versions, but it is a little odd to me that it doesn't really mention much there...

2023-04-21 14:40 UTC, pauby requested changes

2023-04-21 14:40 UTC, pauby commented on input/en-us/choco/setup.md
> +- Windows PowerShell v2.0 or higher (PowerShell 6+ is not yet supported)
'PowerShell 6+ is not yet supported' is a very vague statement that prompts more questions than it answers.

PowerShell 6+ isn't supported inside a Chocolatey package but I'm not sure that's relevant as we are dealing with the Chocolatey CLI setup.

2023-04-21 14:40 UTC, pauby commented on input/en-us/choco/setup.md
> +  - Windows PowerShell v3 is required for directly installing Chocolatey from the Chocolatey.org website due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tl
That doesn't affect just Chocolatey CLI.

2023-04-21 14:40 UTC, pauby commented on input/en-us/choco/setup.md
> +  - .NET Framework 4.5+ is required for installing directly from the Chocolatey.org website, due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/)
Can we not use 'the Chocolatey.org website' as they're not installing it from there. This also affects more than Chocolatey CLI.

2023-04-21 14:40 UTC, pauby commented on input/en-us/choco/setup.md
> +## Installing Chocolatey
Can we use the proper product name?

2023-04-21 14:40 UTC, pauby commented on input/en-us/choco/setup.md
> +1. If you don't see any errors, you are ready to use Chocolatey!
Can we use the proper product name here?

2023-04-21 14:40 UTC, pauby commented on input/en-us/information/support-lifecycle.md
> +Title: Support Lifecycle and Supported Operating Systems
```suggestion
Title: Product Support Lifecycle and Supported Operating Systems
```

2023-04-21 14:40 UTC, pauby commented on input/en-us/information/support-lifecycle.md
> +Description: Information about which versions of Chocolatey are supported, and the operating systems they're supported on.
Can we use the proper product name here?

2023-04-21 14:40 UTC, pauby commented on input/en-us/information/support-lifecycle.md
> +All current released stable versions of Chocolatey products are fully supported and will periodically receive new features, bug fixes, and security fixes.
```suggestion
All of the latest released stable versions of Chocolatey products are fully supported and will periodically receive new features, bug fixes, and security fixes as appropriate.
```

2023-04-21 14:40 UTC, pauby commented on input/en-us/information/support-lifecycle.md
> +We recommend customers update to newly released minor and patch versions as soon as they are able, in order to benefit from new features and fixes as they are released.
```suggestion
We recommend customers update to the latest versions to benefit from new features and fixes as they are released.
```

2023-04-21 14:40 UTC, pauby commented on input/en-us/information/support-lifecycle.md
> +   - We _may_ issue security fixes for FOSS versions, on a case-by-case basis.
```suggestion
```

2023-04-21 14:40 UTC, pauby commented on input/en-us/troubleshooting.md
> +Then you are likely running an older operating system that needs to be upgraded to be able to use TLS 1.2 at a minimum.
```suggestion
Then you are likely running an older operating system that needs to be upgraded to be able to use TLS 1.2 as a minimum.
```

2023-04-21 14:40 UTC, pauby commented on input/en-us/troubleshooting.md
> +The post provides some options if you have older clients that need to install Chocolatey.
Can you use the proper product name?

2023-04-21 14:40 UTC, pauby commented on input/en-us/troubleshooting.md
> +community.chocolatey.org now requires TLS 1.2 at a minimum.
Can we use the website name, and link to the URL rather than it's raw URL?  Can you also expand on that a little. It feels very out of place there.

2023-04-21 14:43 UTC, vexx32 commented on input/en-us/choco/setup.md
> +- Windows PowerShell v2.0 or higher (PowerShell 6+ is not yet supported)
I can probably just take this part out since I changed it to Windows PowerShell anyway

2023-04-21 14:46 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +community.chocolatey.org now requires TLS 1.2 at a minimum.
I'll see what I can do. I think this was already on this page, wasn't too sure what more to put here, but it felt out of place to me as well.

2023-04-21 14:47 UTC, vexx32 commented on input/en-us/choco/setup.md
> +  - Windows PowerShell v3 is required for directly installing Chocolatey from the Chocolatey.org website due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tl
No, but this is the setup doc so we're primarily concerned with getting Chocolatey CLI setup here.

2023-04-21 18:31 UTC, TheCakeIsNaOH commented on input/en-us/choco/setup.md
> +- .NET Framework 4.8
```suggestion
- .NET Framework 4.8
    - The installation script will attempt to install .NET 4.8 if it is not installed
```

2023-04-24 12:13 UTC, vexx32 commented
That makes sense to me, aye. 🙂

2023-04-24 19:03 UTC, vexx32 commented on input/en-us/choco/setup.md
> +- Windows PowerShell v2.0 or higher (PowerShell 6+ is not yet supported)
Removed this.

2023-04-24 19:03 UTC, vexx32 commented on input/en-us/choco/setup.md
> +  - .NET Framework 4.5+ is required for installing directly from the Chocolatey.org website, due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/)
Changed to just mention Community Repository.

2023-04-24 19:03 UTC, vexx32 commented on input/en-us/choco/setup.md
> +## Installing Chocolatey
Done!

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/choco/setup.md
> +1. If you don't see any errors, you are ready to use Chocolatey!
Done!

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +Title: Support Lifecycle and Supported Operating Systems
Done!

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +Description: Information about which versions of Chocolatey are supported, and the operating systems they're supported on.
Changed to `Chocolatey products` for now.

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +All current released stable versions of Chocolatey products are fully supported and will periodically receive new features, bug fixes, and security fixes.
Updated.

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +We recommend customers update to newly released minor and patch versions as soon as they are able, in order to benefit from new features and fixes as they are released.
Updated.

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +   - We _may_ issue security fixes for FOSS versions, on a case-by-case basis.
Removed.

2023-04-24 19:04 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +Then you are likely running an older operating system that needs to be upgraded to be able to use TLS 1.2 at a minimum.
Fixed!

2023-04-24 19:05 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +The post provides some options if you have older clients that need to install Chocolatey.
Aye, done :)

2023-04-24 19:05 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +community.chocolatey.org now requires TLS 1.2 at a minimum.
I've restructured this a bit and added a proper link with appropriate text.

2023-04-24 19:05 UTC, vexx32 commented on input/en-us/choco/setup.md
> +- .NET Framework 4.8
Sorted, thanks!

2023-04-25 15:24 UTC, pauby requested changes
Thanks for fixing that up @vexx32. Just a couple of small changes.

2023-04-25 15:24 UTC, pauby commented on input/en-us/troubleshooting.md
> +If you see this error when attempting to download Chocolatey or any other packages from the Community Repository, you are likely running an older operating system that needs to be upgraded to be able
```suggestion
If you see this error when attempting to download Chocolatey CLI or any other packages from the Chocolatey Community Repository, you are likely running an older operating system that needs to be upgraded to be able to use TLS 1.2 as a minimum.
```

2023-04-25 15:24 UTC, pauby commented on input/en-us/choco/setup.md
> +  - .NET Framework 4.5+ is required for installing directly from the Community Repository, due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/)
```suggestion
  - .NET Framework 4.5+ is required for installing directly from the Chocolatey Community Repository, due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/)

```

2023-04-25 15:43 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +If you see this error when attempting to download Chocolatey or any other packages from the Community Repository, you are likely running an older operating system that needs to be upgraded to be able
Updated!

2023-04-25 15:43 UTC, vexx32 commented on input/en-us/choco/setup.md
> +  - .NET Framework 4.5+ is required for installing directly from the Community Repository, due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/)
Updated!

2023-04-25 16:18 UTC, pauby requested changes

2023-04-25 16:18 UTC, pauby commented on input/en-us/choco/setup.md
> +  - Windows PowerShell v3 is required for directly installing Chocolatey from the Community Repository due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-
```suggestion
  - Windows PowerShell v3 is required for directly installing Chocolatey CLI from the Chocolatey Community Repository due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/)

```

2023-04-25 16:18 UTC, pauby commented on input/en-us/choco/setup.md
> +  - Windows PowerShell v3 is required for directly installing Chocolatey from the Community Repository due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-
I missed this one.

2023-04-25 18:05 UTC, vexx32 commented on input/en-us/choco/setup.md
> +  - Windows PowerShell v3 is required for directly installing Chocolatey from the Community Repository due to the [TLS 1.2 requirement](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-
Fixed!

2023-04-26 10:27 UTC, pauby submitted a review, later dismissed

2023-04-26 15:45 UTC, ferventcoder requested changes
This looks great, only a couple of things may need to be adjusted for clarity.

2023-04-26 15:45 UTC, ferventcoder commented on input/en-us/choco/setup.md
> +- Windows PowerShell v2.0 or higher
Ooh, I like that this is explicit!

2023-04-26 15:45 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +We will continue to add features, fix bugs, and address security concerns as normal while we work towards a v1.0 release.
I came into this page thinking Chocolatey CLI. So it took a moment before I was clear we were talking about more than just CLI. Not sure if it should be more explicitly called out in the Product Support Lifecycle summary as an example (like `Chocolatey products (e.g. Chocolatey CLI, Chocolatey GUI, etc)`) just to help reframe my (and others) mind when I come into this page.

2023-04-26 15:45 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +   - For example: at v2.0, v1.x versions of the product will receive security fixes; at v3.0, only v2.0x versions of the product will continue to receive security fixes.
Small inconsistency between v1.x and v2.0x - not sure which might have been a typo.

2023-04-26 15:45 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +This information is up to date as of April 2023.
Good call out  on when this list was last updated.

2023-04-26 15:49 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +All of the latest released stable versions of Chocolatey products are fully supported and will periodically receive new features, bug fixes, and security fixes as appropriate.
```suggestion
All of the latest released stable versions of Chocolatey products (e.g. Chocolatey CLI, Chocolatey GUI, Chocolatey Central Management, etc) are fully supported and will periodically receive new features, bug fixes, and security fixes as appropriate.
```

2023-04-26 15:51 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +1. We will support the previous major version for bug fixes for licensed customers for 6 months following the release of the next major version.
Also, with this, should we spell out `6`?

2023-04-26 18:42 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +We will continue to add features, fix bugs, and address security concerns as normal while we work towards a v1.0 release.
Yeah, that's a good idea, I'll add that. :)

2023-04-26 18:44 UTC, vexx32 commented on input/en-us/information/support-lifecycle.md
> +1. We will support the previous major version for bug fixes for licensed customers for 6 months following the release of the next major version.
Yeah, I think you're right. Perhaps if we specify "non-breaking" bug fixes to clarify here might be a good idea? Otherwise it'll just raise more questions than it answers, I think.

2023-04-26 18:50 UTC, vexx32 commented
@ferventcoder I think I got everything updated from what you mentioned, thanks for the review! :3

2023-04-26 19:02 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +1. We will support the previous major version for bug fixes for licensed customers for 6 months following the release of the next major version.
Either could raise questions. So I'm six to one and half dozen to the other for what we put there. I just don't want what could be perceived as a blanket statement for bug fixes.

2023-04-26 19:04 UTC, ferventcoder approved these changes
Looks great, thanks for making those adjustments!

2023-04-26 19:05 UTC, ferventcoder commented on input/en-us/information/support-lifecycle.md
> +1. We will support the previous major version for bug fixes for licensed customers for 6 months following the release of the next major version.
I like what you did there when I saw the update. Resolving.

2023-05-10 18:48 UTC, vexx32 commented
Marking this as draft as we don't want it merged until closer to the v2 release.

2023-05-31 13:47 UTC, AdmiringWorm approved these changes
LGTM

2023-05-31 13:47 UTC, merged