(doc) Add known issues for Chocolatey GUI
chocolatey/docs pull request #705
Opened 2023-05-02 12:29 UTC by gep13

## Description Of Changes

This commit adds information about the known times that this can
happen, and how it affects Chocolatey GUI.

## Motivation and Context

When using some repository servers, the information that is returned
isn't correct, which means that Chocolatey GUI doesn't work as
expected.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2023-05-02 12:55 UTC, pauby requested changes
As we are specifically seeing this issue in one repository server only, can we be more specific and link to the issue that we raised with that repository manager?

2023-05-02 12:55 UTC, pauby commented on input/en-us/chocolatey-gui/known-issues.md
> +within its UI, so that the correct `Next`, `Previous`, `First`, and `Last` buttons can be shown.  When the information is returned incorrectly from the repository server, the result is that
```suggestion
so that the correct `Next`, `Previous`, `First`, and `Last` buttons can be shown.  When the information is returned incorrectly from the repository server, the result is that
```

2023-05-02 14:37 UTC, vexx32 requested changes

2023-05-02 14:37 UTC, vexx32 commented on input/en-us/chocolatey-gui/known-issues.md
> +## Not all available packages are shown, or there is no way to navigate to next page of results
I also think the majority of what's currently written here is good information but not especially useful or actionable for people using ChocolateyGUI. I think we may want to put what's currently here under a `### Technical details` subheader and write a more approachable summary for this issue.

Perhaps something along the lines of:

> Chocolatey GUI is reliant on the repository server providing accurate information in order to determine whether there are more packages available than it was given in the first set of results. In some implementations of NuGet v3 feeds, we have observed that the repository server is returning incorrect information. As a result, there are cases where Chocolatey GUI may not be able to display all packages that the repository server has in its list.

2023-05-10 19:40 UTC, vexx32 commented
@gep13 @pauby I've gone ahead and applied the suggestions from Paul's review and from mine, and added the Jira ticket for the Nexus issue. 

@corbob could you give this one a once-over and make sure we're not missing anything else here? :3

2023-05-10 19:54 UTC, vexx32 commented
Marking as draft as we don't want this pulled in till closer to v2 release as well.

2023-05-10 21:37 UTC, corbob approved these changes
This looks good to me.

2023-05-31 14:54 UTC, vexx32 approved these changes

2023-05-31 15:03 UTC, merged