Add what's new in v2 page + some additional v2 information
chocolatey/docs pull request #710
Opened 2023-05-10 13:58 UTC by vexx32

## Description Of Changes

- Add new page for what's new in Chocolatey v2

**Note**: this currently won't build properly as-is because it contains an `xref` link to a document that was only added in this yet-to-be-merged PR: https://github.com/chocolatey/docs/pull/699

Once that PR is merged and this is rebased, it will work. Marking this as draft for this reason, but it's ready for review.

## Motivation and Context

Giving folks a decent summary of what's changed since v1.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

Clickup: PROJ-596

2023-05-10 19:30 UTC, TheCakeIsNaOH commented on input/en-us/choco/new-in-v2.md
> +- Package version numbers which contain leading zeroes for parts of the version number (for example: `9.00.01`) are no longer permitted.
It probably would be better to just say that they will be normalized, instead of being not permitted. Since `.nuspec`s can still have leading zeros, they just automatically get normalized during pack.

2023-05-10 19:30 UTC, TheCakeIsNaOH commented on input/en-us/choco/new-in-v2.md
> +If a query that may return a large number of packages is given, Chocolatey CLI will now impose a default limit on the number of packages returned.
It might be good to explicitly note what commands this applies for.

2023-05-10 19:30 UTC, TheCakeIsNaOH commented on input/en-us/choco/new-in-v2.md
> +For more information on SemVer 2.0.0, please see [the SemVer website](https://semver.org/spec/v2.0.0.html).
Chocolatey v2 does not follow SemVer exactly. A couple of examples are that elements are limited to int32 length, that a fourth element is allowed in the version, and that build metadata is allowed in the nuspec version but ignored otherwise. 
Maybe https://github.com/chocolatey/docs/issues/375 could be completed?

2023-05-10 20:02 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +For more information on SemVer 2.0.0, please see [the SemVer website](https://semver.org/spec/v2.0.0.html).
Mmm true, but the wording is "supports", not "requires", so having a few things in addition to what semver allows is fine... I will add a note that version parts are limited to int32.MaxValue though.

I agree it would be good to get #375 done itself, I don't think this doc is quite the right place for all those details atm.

2023-05-10 20:33 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- Package version numbers which contain leading zeroes for parts of the version number (for example: `9.00.01`) are no longer permitted.
I've rephrased this a bit, thanks!

2023-05-10 20:33 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +If a query that may return a large number of packages is given, Chocolatey CLI will now impose a default limit on the number of packages returned.
Added a note for the affected commands, cheers :3

2023-05-10 20:34 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +For more information on SemVer 2.0.0, please see [the SemVer website](https://semver.org/spec/v2.0.0.html).
I've rephrased this a bit and added a note that this doesn't mean we're no longer supporting older version styles just yet.

2023-05-10 20:35 UTC, TheCakeIsNaOH commented on input/en-us/choco/new-in-v2.md
> +For more information on SemVer 2.0.0, please see [the SemVer website](https://semver.org/spec/v2.0.0.html).
It looks great now.

2023-05-10 20:36 UTC, TheCakeIsNaOH approved these changes

2023-05-11 16:12 UTC, pauby requested changes
After reading all of this, I actually think this would be better as a blog post? Thoughts?

I don't think it's much more work to make it a blog post.

2023-05-11 16:12 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +On hitting these limits, you will be prompted to refine your query in order to find what you're looking for.
Does Chocolatey CLI 'warn' you?

2023-05-11 16:12 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +- :sparkles: The `defaultPushSource` configuration option was added, which sets a default URL to push to when using `choco push`.
```suggestion
## New Options, Configurations and Features

- `--online` option added for commands' `--help`. This will now take you to an online version of the command help.
  For example, `choco install --help --online` will open the [Install command docs page](https://docs.chocolatey.org/en-us/choco/commands/install) in your default browser.
- `choco feature` now supports the `get` subcommand, which will show a single feature state.
- The `defaultPushSource` allows you to sets a default URL to push to when using `choco push`. By default this is set to `https://push.chocolatey.org` but will change in v3.0.0.
```

2023-05-11 16:12 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +- :sparkles: The `defaultPushSource` configuration option was added, which sets a default URL to push to when using `choco push`.
@gep13, the last statement about `defaultPushSource` default changing in v3.0.0 is correct and as we discussed?

2023-05-11 16:12 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +  For example, `09.00.001` will be normalized to `9.0.1`.
```suggestion
## Removed Options and Features

- Removed the deprecated side-by-side install functionality (aka `--allow-multiple`).
- Removed the deprecated default push location of `push.chocolatey.org`.
  Use the new `defaultPushSource` configuration instead (see above).
- Removed the deprecated configuration options for `cacheLocation` and `commandExecutionTimeoutSettings`.
- Only Chocolatey CLI configuration is shown for the `choco config list`.
  Use `choco feature list` to view features, and `choco apikey list` to view API key entries.
- [WebPi has been removed by Microsoft](https://github.com/chocolatey/choco/issues/2958) and the `--source webpi` alternative source has been removed from Chocolatey CLI.
- Removed installing directly from a `nupkg` or `nuspec` file.
  Use `choco install packagename -s ./local/path/to/folder` instead, and ensure packages are packed with `choco pack` before attempting to install them.
- Package version numbers will no longer retain leading zeroes in any parts of the version number when using `choco pack`.
  For example, `09.00.001` will be normalized to `9.0.1`.
```

2023-05-11 16:12 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +  For example, `09.00.001` will be normalized to `9.0.1`.
@gep13 leaving this comment here as depending on your answers to the comment above, the second one on this list may need to be changed.

2023-05-11 16:40 UTC, st3phhays commented
> After reading all of this, I actually think this would be better as a blog post? Thoughts?
> 
> I don't think it's much more work to make it a blog post.

On the blogs I follow like Bootstrap and Astro, they do put blogs up that relay the changes of each release, which I like. However, with major version changes, a lot of docs also put a "Migration" link of some sort in their docs too. Bootstrap has one at the very end of their docs https://getbootstrap.com/docs/5.2/migration/ and Algolia does too https://docsearch.algolia.com/docs/migrating-from-legacy, which honestly, I really appreciated when I was migrating us over to the new version. 

I think with a major version change some kind of migration guide is nice to have in the docs, or at least a link to the blog post from the left nav where it can be viewed.

2023-05-11 18:27 UTC, vexx32 commented
Yeah I'm not fussed either way. I think there should be _something_ in the docs as Steph says, but whether that's better off being a shorter summary or maybe more technical detail than the blog post (or the reverse, the blog being more of a summary with the doc page being a little more comprehensive) I'm not sure.

2023-05-11 18:30 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +You can now use NuGet v3 package feeds with Chocolatey!
Added

2023-05-11 18:33 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +This allows users to work with newer package repository solutions that only provide v3 NuGet feeds, and also opens the door to adding NuGet v3 feeds to our own package repositories at some point in t
Added

2023-05-11 18:33 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +Some examples of repositories with NuGet v3 feed support that you can start using with Chocolatey v2:
Added

2023-05-11 18:34 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +
Looks like GItLab is Nuget v3 as well, added links for these.

2023-05-11 18:36 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +Starting in v2.0, Chocolatey supports SemVer 2.0.0, although it requires that all version parts fit into the range `0-2147483647`.
Amended, cheers :3

2023-05-11 18:36 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +This allows some additional prerelease package version variants like `1.0.1-alpha.23` (note the period in the prerelease tag following the hyphen, which was previously considered not valid for a vers
Added

2023-05-11 18:37 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +> Chocolatey v2 is adopting NuGet's current versioning system, so any version numbers supported by NuGet are also supported by Chocolatey.
Added!

2023-05-11 18:37 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## Minimum operating system support changes
Fixed

2023-05-11 18:37 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## SemVer 2.0.0 support
Fixed

2023-05-11 18:38 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## NuGet v3 feed support
Fixed

2023-05-11 18:38 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- Windows Client versions 10 and 11 are supported
Done!

2023-05-11 18:39 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +> On Server 2008r2 and 2012, you will need to ensure the relevant patches are installed and registry entries configured to enable TLS v1.2 by default in order to interact with the Chocolatey Communit
Sorted

2023-05-11 18:40 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## .NET Framework uplift
Fixed

2023-05-11 18:41 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +However, installing .NET Framework 4.8 will require a reboot to be completed before Chocolatey can be installed.
Updated

2023-05-11 18:41 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +For the smoothest upgrade experience, we recommend you install .NET Framework 4.8 and reboot before installing or upgrading to Chocolatey v2.0.
Added

2023-05-11 18:42 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## `choco apikey` subcommands
Updated

2023-05-11 18:42 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +In v2.0, the `choco apikey` syntax has changed.
Sorted

2023-05-11 18:44 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +choco apikey remove -s https://source.url/api/v2/
😩 Fair. I know it's our standard and exists for a reason but there are _so many_ things I dislike about many parts of it. I'll fix it though. 😅

2023-05-11 18:44 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +choco apikey remove -s https://source.url/api/v2/
Fixed!

2023-05-11 18:45 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- `choco apikey -s https://source.url/api/v2/ -k API_KEY_HERE` with both arguments defaults to `add`, adding a new API key
Added

2023-05-11 18:47 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## Shims for `cpack`, `cinst`, `cpush`, `cuninst`, `cup`, and `chocolatey` removed
Hmm. I agree, but I think we need to be slightly more clear here. "Shim Removal" makes it sound like we're ditching shimgen entirely, so I'll put it as "Builtin Shims Removed" to be a little clearer, I think...

2023-05-11 18:48 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +As a result, we [deprecated these shims in v1.0](https://github.com/chocolatey/choco/issues/2641), and now in v2.0 [they have been removed](https://github.com/chocolatey/choco/issues/2642).
:( hey I liked that reference 😂

2023-05-11 18:49 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +As a result, we [deprecated these shims in v1.0](https://github.com/chocolatey/choco/issues/2641), and now in v2.0 [they have been removed](https://github.com/chocolatey/choco/issues/2642).
Fixed :)

2023-05-11 18:49 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +
Removed

2023-05-11 18:50 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +For the folks who are accustomed to using them, it's still possible to define these as either batch files you manually place on your PATH, or PowerShell functions you add to your profile.
Fixed

2023-05-11 18:50 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +However, they will not be provided by Chocolatey any longer.
Removed

2023-05-11 18:51 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## `choco list` only lists local packages
Updated

2023-05-11 18:52 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +In v2.0, `list` has become the command used for listing locally-installed packages, while `search` and `find` target remote repositories.
Sorted

2023-05-11 18:53 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +We plan to remove `--local-only` for `list` in v3.0.
That's a lot of commas, I might cut down on those a little. But fixed :3

2023-05-11 18:59 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- :sparkles: The `defaultPushSource` configuration option was added, which sets a default URL to push to when using `choco push`.
I believe that was the original plan. During conversations when this was being implemented, though, we realised we had already deprecated the default push source way back in the v1.0 release. If I recall correctly, I think the decision we came to and implemented was as I originally stated here -- there is no default push source set in v2.0 as it was already deprecated in v1.0.

I'll leave that last one off till Gary confirms one way or the other and fix up the rest here. 👍

2023-05-12 12:50 UTC, pauby requested changes

2023-05-12 12:50 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +Some examples of repositories with NuGet v3 feed support that you can start using with Chocolatey CLI v2.0.0 and later:
```suggestion
Shown below are some examples of repository managers that support NuGet v3 feeds, that you can start using with Chocolatey CLI v2.0.0 and later:
```

2023-05-12 12:50 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +Some examples of repositories with NuGet v3 feed support that you can start using with Chocolatey CLI v2.0.0 and later:
```suggestion
Shown below are some examples of repository managers that support NuGet v3 feeds, that you can start using with Chocolatey CLI v2.0.0 and later:
```

2023-05-12 12:50 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +> To use the Chocolatey Community Repository with Windows Server 2008r2 and 2012, you need to ensure the relevant patches are installed and registry entries configured to enable TLS v1.2 by default.
```suggestion
> To use the Chocolatey Community Repository with Windows Server 2008 R2 and 2012, you need to ensure the relevant patches are installed and registry entries configured to enable TLS v1.2 by default.
```

2023-05-12 12:50 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +## New Options, Configurations, and Features
```suggestion
## Added Options, Configurations, and Features
```

2023-05-12 12:50 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +- [WebPi has been removed by Microsoft](https://github.com/chocolatey/choco/issues/2958) and the `--source webpi` package source has been removed.
```suggestion
- [WebPi has been removed by Microsoft](https://github.com/chocolatey/choco/issues/2958) and the `--source webpi` alternative package source has been removed.
```

2023-05-12 13:05 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +> To use the Chocolatey Community Repository with Windows Server 2008r2 and 2012, you need to ensure the relevant patches are installed and registry entries configured to enable TLS v1.2 by default.
Fixed

2023-05-12 13:06 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +## New Options, Configurations, and Features
Sorted

2023-05-12 13:06 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- [WebPi has been removed by Microsoft](https://github.com/chocolatey/choco/issues/2958) and the `--source webpi` package source has been removed.
Added!

2023-05-16 18:24 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- :sparkles: The `defaultPushSource` configuration option was added, which sets a default URL to push to when using `choco push`.
Hmm... Had a look, the page for creating packages suggests using an explicit source already, it doesn't rely on the implicit default thankfully. I'll add an additional note there that folks can add the new config value to set a default and add it to this PR.

2023-05-16 18:33 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +- :sparkles: The `defaultPushSource` configuration option was added, which sets a default URL to push to when using `choco push`.
Added a commit for this.

2023-05-18 18:58 UTC, corbob commented on input/en-us/agent/upgrade.md
> +1. Ensure you are on the latest stable version of Chocolatey, Chocolatey Licensed Extension, and Chocolatey Agent.
Because 2.x/6.x will be the latest stable version of things when this is published, we should be clear about what "stable" is here...

```suggestion
1. Ensure you are on the latest v1.x version of Chocolatey, v5.x version of Chocolatey Licensed Extension, and v1.x version of Chocolatey Agent.
```

2023-05-18 19:16 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +1. Ensure you are on the latest stable version of Chocolatey, Chocolatey Licensed Extension, and Chocolatey Agent.
yeah, good catch...

2023-05-25 17:43 UTC, pauby requested changes

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +### SecurityProtocol was set to (some value), resetting to SystemDefault
Can you capitalize the headers?

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +This can be a security hazard, especially if the package is installing software over the Internet.
```suggestion
Ensure you understand the implications of this change and contact the package maintainer to inform them of their package behaviour.
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +Rather, you should manage the allowed TLS versions through your operating system; as of v2.0.0, Chocolatey CLI will defer to the operating system configuration for the allowed TLS versions.
```suggestion
Rather, you should manage the allowed TLS versions through your Operating System. Chocolatey CLI v2.0.0 and later, will defer to the Operating System configuration for the allowed TLS versions.
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +## `choco upgrade all` fails to upgrade a package, which cascades into failing many more seemingly unrelated packages
Can you capitalize the heading?

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +As a result, Chocolatey CLI's packages may be in an inconsistent state.
```suggestion
Typically this will be encountered with meta-packages, such as `obs-studio` which takes a dependency on `obs-studio.install`. When running `choco upgrade all` it will attempt to upgrade every installed package. Any packages which fail to install may be retried as part of a later dependency chain.
For example, `obs-studio.install` may be upgraded, fail, and then later be tried again as part of the dependency chain for `obs-studio` itself.
As a result, Chocolatey CLI's packages may be in an inconsistent state.
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +This is typically characterised by a dependency resolution error message when performing package operations, which looks like this:
```suggestion
This is typically characterised by a dependency resolution error message when performing package operations:
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +
```suggestion
This is normally resolved by upgrading the affected dependency.
In this example, you would run `choco upgrade obs-studio.install` to resolve the issue.
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +Due to the dependency version range specified by `obs-studio`, the version of `obs-studio.install`that remains installed due to the upgrade failure does not satisfy the dependency requirement.
```suggestion
Due to the dependency version range specified by `obs-studio`, the version of `obs-studio.install` that remains installed, due to the upgrade failure, does not satisfy the dependency requirement.
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +To resolve the issue, we can address the cause of the upgrade failure and then call `choco upgrade obs-studio.install` to get the correct dependency version installed once again.
```suggestion
To resolve the issue, we run `choco upgrade obs-studio.install` to get the correct dependency version installed.
```

2023-05-25 17:43 UTC, pauby commented on input/en-us/troubleshooting.md
> +For packages that have a specific version dependency, you may want to use `--version` to specify an exact version to install in order to resolve the dependency error.
```suggestion
For packages that have a specific version dependency, add the `--version` option and specify the exact version to install..
```

2023-05-25 18:01 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +### Major Versions
Maybe? But it would also apply to upgrading v2 to v3 as well when we get there, so it felt more useful to generalise so we needn't have to come back and add a bunch more / revise this again too much later on.

2023-05-25 18:01 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +### Minor / Patch versions (for example 1.1.x to 1.3.x, or 1.1.1 to 1.1.5)
Currently, sure, but as we release more versions it means the guidance is more confusing and less relevant, doesn't it?

2023-05-25 18:02 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +Due to the related dependencies and how they are typically specific across major versions of Chocolatey Agent, a specific upgrade process must be followed.
hmm, I think one of those was meant to be "specified"...

I'll have a look.

2023-05-25 18:04 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +### Using Chocolatey Central Management to upgrade chocolatey-agent
Sure! Don't think title case generally capitalises "to" though.

2023-05-25 18:10 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +For example, when upgrading from **v1.x** to a **v2.x** version of Chocolatey Agent, the process looks like this:
I'm not sure we want to have to add a whole new section every major release here just because we were overly specific about the version numbers, though :/

2023-05-25 18:12 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +This allows users to work with newer package repository solutions that only provide NuGet v3 feeds.
Sorted!

2023-05-25 18:21 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +See our brand-new [Support Lifecycle](xref:support-lifecycle) page for a full run-down.
Sorted, ty!

2023-05-25 18:23 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +choco apikey remove --source "https://source.url/api/v2/"
This suggestion also isn't following the best practices guide... and tbh we _really_ need to overhaul that and evaluate whether all of that is relevant or wise. Single quotes and double quotes have very specific meanings in PowerShell and our recommendations there don't really account of that well at all.

That's a rant for another day tho. :>

2023-05-25 18:30 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +### SecurityProtocol was set to (some value), resetting to SystemDefault
I avoided it because there's a lot of headers here which aren't capitalised, but... sure, I suppose.

2023-05-25 19:58 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +### SecurityProtocol was set to (some value), resetting to SystemDefault
Mmm... running back through all these... This references an exact error message, as is done a few times previously in this file. I'm not sure we should be forcing capitalisation of things like this which are more or less an excerpt of an error message? It _shouldn't_ affect searches either way but it may make them less obviously recognisable to the eye?

2023-05-25 19:59 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +## `choco upgrade all` fails to upgrade a package, which cascades into failing many more seemingly unrelated packages
Sure

2023-05-25 20:01 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +## `choco upgrade all` fails to upgrade a package, which cascades into failing many more seemingly unrelated packages
Sorted, ty

2023-05-25 20:04 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +Due to the dependency version range specified by `obs-studio`, the version of `obs-studio.install`that remains installed due to the upgrade failure does not satisfy the dependency requirement.
Amended! Removed a few commas, though.

2023-05-25 20:06 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +Due to the dependency version range specified by `obs-studio`, the version of `obs-studio.install`that remains installed due to the upgrade failure does not satisfy the dependency requirement.
Maybe parentheses... hmm. I'll fiddle a bit.

2023-05-25 20:18 UTC, vexx32 commented
@pauby I _think_ I've responded to or incorporated this round of suggestions. It did start to feel like I was losing track a bit somewhere in the middle of it all, but I think I've gotten to everything suggested or at least asked for clarification etc on bits I'm not sure about. I'm not seeing anything I've outright missed, but please let me know if I did. Thanks for the suggestions! :3

2023-05-26 12:21 UTC, pauby commented on input/en-us/agent/upgrade.md
> +### Using Chocolatey Central Management to upgrade chocolatey-agent
It doesn't. I got overzealous. 👍

2023-05-26 12:22 UTC, pauby commented on input/en-us/agent/upgrade.md
> +For example, when upgrading from **v1.x** to a **v2.x** version of Chocolatey Agent, the process looks like this:
Is this not in the major updates section? If that is the case is there any point in having the version numbers at all?

2023-05-26 12:25 UTC, pauby commented on input/en-us/choco/new-in-v2.md
> +choco apikey remove --source "https://source.url/api/v2/"
You're absolutely right. I updated later code to follow it, but didn't come back to this. Apologies. It should have been:

```
choco apikey add --source="'https://source.url/api/v2/'" --key="'API_KEY_HERE'"
choco apikey list
choco apikey remove --source="'https://source.url/api/v2/'"
```

2023-05-26 12:26 UTC, pauby commented on input/en-us/create/create-packages.md
> +For example, if pushing to the Chocolatey Community Repository, you will need to have previously set an API key for `https://push.chocolatey.org/` (`choco apikey add --source https://push.chocolatey.
This is the bit I updated correctly.

2023-05-26 12:26 UTC, pauby commented on input/en-us/troubleshooting.md
> +### SecurityProtocol was set to (some value), resetting to SystemDefault
Nope. I completely agree. This is an error message so should be verbatim (as much as possible).

2023-05-26 12:27 UTC, pauby commented on input/en-us/troubleshooting.md
> +Due to the dependency version range specified by `obs-studio`, the version of `obs-studio.install`that remains installed due to the upgrade failure does not satisfy the dependency requirement.
It reads correctly to me with the commas 😄

2023-05-26 12:28 UTC, pauby commented
@vexx32 I responded to the comment I think needed responses. Let me know if I missed anything.

2023-05-26 12:32 UTC, pauby commented
As I mentioned to you @vexx32, we may need to amend this once the 'Upgrading' doc is completed. I'm happy with all the changes though and will 'Approve' once we're done.

Thank you for making those changes.

2023-05-26 12:38 UTC, vexx32 commented on input/en-us/troubleshooting.md
> +Due to the dependency version range specified by `obs-studio`, the version of `obs-studio.install`that remains installed due to the upgrade failure does not satisfy the dependency requirement.
It can but it's ambiguous I think so i went with parentheses for now, it reads like there's comma splicing with that many commas 😁

2023-05-26 12:40 UTC, vexx32 commented on input/en-us/agent/upgrade.md
> +For example, when upgrading from **v1.x** to a **v2.x** version of Chocolatey Agent, the process looks like this:
Yeah it is. I agree it would be nicer to have just no version numbers at all, but I had a lot of difficulty trying to phrase how it would work in more general terms, so I went with using the v1 -> v2 route as the example to follow as it should be pretty similar for any major version, but a specific example makes it much easier to talk about.

2023-05-30 17:54 UTC, vexx32 commented on input/en-us/choco/new-in-v2.md
> +choco apikey remove --source "https://source.url/api/v2/"
So many quotes 😭 

I think I have this all updated tho, ty!

2023-05-30 20:57 UTC, pauby commented
@vexx32 Contrary to what I said, I'm not going to pull anything out of this doc. Let's leave it as is, just now. If it's ready for review and merge, can you take it out of Draft?

2023-05-30 21:22 UTC, vexx32 commented
@pauby done!

2023-05-31 13:55 UTC, pauby approved these changes

2023-05-31 14:02 UTC, AdmiringWorm approved these changes
LGTM

2023-05-31 14:12 UTC, merged