Add documentation for upgrading to 2.0.0 / 6.0.0 of Chocolatey products
chocolatey/docs pull request #722
Opened 2023-05-26 17:28 UTC by pauby

## Description Of Changes
Adds a document to help with upgrading to version 2.0.0 and 6.0.0 of Chocolatey products.

## Motivation and Context
Give customers and community clear information on upgrading.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #

2023-05-26 17:29 UTC, pauby commented
This is a very early draft, but I wanted to get _something_ up for people to comment on.

2023-05-30 15:49 UTC, AdmiringWorm commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +If you are unable to upgrade to .NET Framework 4.8, **we do not recommend** you upgrade to Chocolatey CLI version 2.0.0.
Should we include a warning that only licensed users can get support for `1.x`?

That any new issues created for the previous major version by OSS users will not be accepted?

2023-05-30 15:49 UTC, AdmiringWorm commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +We have addded support for [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html) that allows previously invalid pre-release version numbering such as `1.0.1-alpha.23`. The only constraint is that the v
Should we mention that CCR won't be supporting SemVer v2 for the time being?
And SemVer v2 should only be used for local or custom/internal sources?

2023-05-30 15:49 UTC, AdmiringWorm commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +To upgrade, you need to ensure you are at the latest stable version of the Chocolatey products which are:
Do you think we should mention that this is only required for licensed customers with more than just CLI, GUI, and CLE installed?

If just those three products are installed, it should work without any problems without needing to upgrade all products.

2023-05-30 16:36 UTC, pauby commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +If you are unable to upgrade to .NET Framework 4.8, **we do not recommend** you upgrade to Chocolatey CLI version 2.0.0.
Added a link to the Support Lifecycle docs.

2023-05-30 16:41 UTC, pauby commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +* `cver`: `choco version`.
I was getting confused as I knew it was in there. It's now `choco --version`. Updated it.

2023-05-30 16:42 UTC, pauby commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +If you want to add these shortcuts back, you can can create a PowerShell function or batch file to provide the same functionality.
No :) I deliberately strayed away from that. I'll add some though.

2023-05-30 16:45 UTC, pauby commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +To upgrade, you need to ensure you are at the latest stable version of the Chocolatey products which are:
I was trying to stay away from having multiple options when upgrading. They need to be on the latest versions for all the product they use. I might be misreading what you're asking, but are you asking me to make it clearer they only need to be on the latest version for the products _they use_?

2023-05-30 16:58 UTC, pauby commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +  1. The second Deployment Step ensures that all other Chocolatey products are now at their latest stable 2.0.0 and 6.0.0 versions. The Advanced Deployment Powershell script should be `choco upgrade
Yes. I'll add it up at the top (under Upgrading Considerations). Please review that to ensure I'm correct.

2023-05-30 17:13 UTC, pauby commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +  1. The second Deployment Step ensures that all other Chocolatey products are now at their latest stable 2.0.0 and 6.0.0 versions. The Advanced Deployment Powershell script should be `choco upgrade
I've added that above.

2023-05-30 17:57 UTC, st3phhays commented
@pauby Since you've created a new folder for this document to live in, you'll also need to create a new `index.md` file inside of the new `migrations` folder you created. This will allow it to show up in the left side navigation, and on the child page listings. The content of this file should be something similar to the below:

```
---
Order: 15
xref: migrations
Title: Migrations
Description: Information on how to migrate to new versions of Chocolatey.
---
```

2023-05-30 17:59 UTC, st3phhays requested changes
@pauby Since you've created a new folder for this document to live in, you'll also need to create a new index.md file inside of the new migrations folder you created. This will allow it to show up in the left side navigation, and on the child page listings. The content of this file should be something similar to the below:

---
Order: 15
xref: migrations
Title: Migrations
Description: Information on how to migrate to new versions of Chocolatey.
---

2023-05-30 18:12 UTC, st3phhays requested changes
Found just a couple typos when looking at the video. The video looks great, except I suggested some other dimensions to make it a bit bigger. Looking good though!

2023-05-30 18:12 UTC, st3phhays commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +We have addded support for [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html) that allows previously invalid pre-release version numbering such as `1.0.1-alpha.23`. The only constraint is that the v
```suggestion
We have added support for [SemVer 2.0.0](https://semver.org/spec/v2.0.0.html) that allows previously invalid pre-release version numbering such as `1.0.1-alpha.23`. The only constraint is that the version number segments fit into the range `0` to `2147483647`.

```

2023-05-30 18:12 UTC, st3phhays commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +Side-by-side installs were introduced in Chocolatey CLI to help with the challenge of installing multiple versions of the same package. As use of the functionality grew and expanded beyond the bondar
```suggestion
Side-by-side installs were introduced in Chocolatey CLI to help with the challenge of installing multiple versions of the same package. As use of the functionality grew and expanded beyond the boundaries of the narrow use case that it was intended to help with, so to did the number of users running into issues with it. The use of side-by-side installs began to cause more problems that it solved and the decision was made to remove it from version 2.0.0 of Chocolatey CLI.

```

2023-05-30 18:12 UTC, st3phhays commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +To ensure we do not break any existing automation or scripts using the `--limit-output` or `-r` options, we add a warning to the logs but otherwise ignore the options. As this will be removed in a fu
```suggestion
To ensure we do not break any existing automation or scripts using the `--limit-output` or `-r` options, we add a warning to the logs but otherwise ignore the options. As this will be removed in a future release, please ensure remove the `--local-only` and `-lo` options from any automations or scripts that you have.

```

2023-05-30 18:12 UTC, st3phhays commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +The shims removed (inlcuding the earlier ones) and their equivalent full commands are:
```suggestion
The shims removed (including the earlier ones) and their equivalent full commands are:

```

2023-05-30 18:12 UTC, st3phhays commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +The Chocolatey products are inter-dependent on each other and all of the products must be upgraded. You cannot upgrade one product and leave the others at older vesions.
```suggestion
The Chocolatey products are inter-dependent on each other and all of the products must be upgraded. You cannot upgrade one product and leave the others at older versions.

```

2023-05-30 18:12 UTC, st3phhays commented on input/en-us/guides/migrations/upgrading-to-chocolatey-v2-v6.md
> +<video class="img-fluid" width="320" height="240" poster="/assets/images/chocolatey-upgrade-to-2-banner.png" autoplay muted loop>
```suggestion
<video class="img-fluid" width="800" height="594" poster="/assets/images/chocolatey-upgrade-to-2-banner.png" autoplay muted loop>

```

Here we are adjusting the width and height of that to the video that you took. Doing this makes it much larger and able to read. It was showing very small before. Looks good with these changes!

2023-05-30 20:49 UTC, pauby commented
> @pauby Since you've created a new folder for this document to live in, you'll also need to create a new `index.md` file inside of the new `migrations` folder you created. This will allow it to show up in the left side navigation, and on the child page listings. The content of this file should be something similar to the below:

I've moved it out of the migrations folder and into the root of guides. Hopefully, that makes life easier.

2023-05-30 20:53 UTC, pauby commented
@gep13 @st3phhays @AdmiringWorm @vexx32 From my point of view this is done. I cannot run it in the Docker container though, as I get this error (twice):

![Code_OmFDbQIuUN](https://github.com/chocolatey/docs/assets/12760779/63e15286-e3b6-4b2b-8a5d-2983e17bcd20)

I will try again tomorrow, however if somebody could run it through that, it would be appreciated.

2023-05-30 21:26 UTC, vexx32 commented
Huh, that's odd. Havent seen that one before, myself. The invalid xref will prevent it being previewed though unless we rebase it against the branch that contains that page. I'm at the tail end of my day here so I've not done that just yet but I can take a look first thing tomorrow.

2023-05-31 01:05 UTC, st3phhays commented
@pauby Yeah, @vexx32 is right. The preview/build will not work until the pages with the references xrefs are merged. If you scroll up into the build log it should tell you what those xrefs are. That second big chunk of red warnings there is basically just saying it can't start the preview (because of xrefs). I sometimes get this error if have a preview running and I close my laptop, and then come back to it later. It usually goes away though if I make a change, and it rebuilds. 🤷‍♀️

To get this to build locally for me, I removed the xrefs in question temporarily, and it all worked fine.

2023-05-31 01:24 UTC, st3phhays submitted a review, later dismissed

2023-05-31 01:24 UTC, st3phhays commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +If you are unable to upgrade to .NET Framework 4.8, **we do not recommend** you upgrade to Chocolatey CLI version 2.0.0 at this time. Please see our [Support Lifecycle](support-lifecycle) for Chocola
```suggestion
If you are unable to upgrade to .NET Framework 4.8, **we do not recommend** you upgrade to Chocolatey CLI version 2.0.0 at this time. Please see our [Support Lifecycle](xref:support-lifecycle) for Chocolatey products.

```

2023-05-31 01:24 UTC, st3phhays commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +Order: 20
```suggestion
Order: 50
```

Where in the sidebar do we want this to be? Right now it has an `Order: 20`, which is competing against the Package Creation link, which also has an `Order: 20`. If we change this to `Order: 50`, then it will appear at the very bottom of the list instead of in the middle. Depending on where we want to put it, we may need to change the order of the other documents (in the `index.md` file in each of the containing folders).

<img width="281" alt="Screenshot 2023-05-30 at 8 13 58 PM" src="https://github.com/chocolatey/docs/assets/42750725/b3f8bcde-38b3-460d-afa5-8e4dd684d95e">

2023-05-31 01:24 UTC, st3phhays commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +If your computers have the latest versions of Chocolatey products installed, you can immediately move onto [Step 2](#step-2---upgrade-to-the-new-2.0.0-and-6.0.0-product-versions).
```suggestion
If your computers have the latest versions of Chocolatey products installed, you can immediately move onto [Step 2](#step-2-upgrade-to-the-new-2.0.0-and-6.0.0-product-versions-1).

```

This has a `-1` at the end because there is another heading with the same text in a different section.

2023-05-31 09:35 UTC, AdmiringWorm submitted a review, later dismissed
Just a single change not already being requested to be changed. Otherwise this looks good to me.

Do note that this PR can not be merged until after the PRs #710 and #709, as well as whatever PR that introduces the xref `support-lifecycle`.

2023-05-31 10:18 UTC, pauby commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +Order: 20
Would be looking for this to appear at the top of hte list I think. I've set this to 5 to appear above the Using Chocolatey one. But this has got me thinking, is there a better place to put this? We haven't added docs like this before.

2023-05-31 12:29 UTC, pauby commented
@st3phhays the video is set to auto-play which I assume means it will have to be downloaded? This is what I was trying to avoid with the animated GIF. I wans't sure how to disable autoplay (maybe autoplay=false or just remove it entirely) so that it only plays when clicked?

2023-05-31 12:57 UTC, vexx32 commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +If you are unable to upgrade to .NET Framework 4.8, **we do not recommend** you upgrade to Chocolatey CLI version 2.0.0 at this time. Please see our [Support Lifecycle](xref:support-lifecycle) for Ch
I've pushed a commit to update this as it's a pretty straightforward change. Once I've confirmed it builds, we can merge this.

2023-05-31 12:58 UTC, vexx32 commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +Order: 20
I think this place is fine for now, we may figure out a better home for it in future, but this is not a bad place for it to start out.

2023-05-31 13:56 UTC, st3phhays commented
> @st3phhays the video is set to autoplay which I assume means it will have to be downloaded? This is what I was trying to avoid with the animated GIF. I wasn't sure how to disable autoplay (maybe autoplay=false or just remove it entirely) so that it only plays when clicked?

@pauby  You can remove the `autoplay` attribute and add the `controls` attribute in it's place. This will give the user a play button and it will not be downloaded until they interact with it.

2023-05-31 14:21 UTC, vexx32 approved these changes
LGTM for now, if there are some minor fixes needed later, we can add those in as needed.

Great work, thanks for putting this together! 💖

2023-05-31 14:28 UTC, merged