(#724) Add FAQ Regarding Changing Public IP
chocolatey/docs pull request #726
Opened 2023-05-31 13:06 UTC by imm0rtalsupp0rt

We have received questions about changing the public IP in the Application Gateway from Dynamic to Static and, while this is not possible, there is a workaround involving creating a CNAME record and then pointing the DNS record to it since it will remain static no matter what.

## Description Of Changes
I added an FAQ to the C4BAE around changing the public IP in the Application Gateway.

## Motivation and Context
This did not exist before and had been asked about, so we figured we'd include it.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #724

2023-05-31 22:27 UTC, Windos commented
Could I suggest linking through to the [existing docs](https://docs.chocolatey.org/en-us/c4b-environments/azure#dns-configuration) regarding creating the CNAME for the Azure Environment rather than re-stating them? Means only having to update it once if the process changes (plus there's a screenshot! 😅)

I think the full anchor to link to for the is `[link text](xref:c4b-azure#dns-configuration)`

2023-09-28 13:48 UTC, ryanrichter94 requested changes

2023-09-28 13:48 UTC, ryanrichter94 commented on input/en-us/c4b-environments/azure/index.md
> +That will remain static, even if the IP address itself does not.
You'll wanna replace these steps with the link back to setting a DNS record as @Windos suggested in his comment.
```suggestion
For assistance on setting this CNAME DNS record please see our [supporting documentation](xref:c4b-azure#dns-configuration).
```

2023-09-29 15:42 UTC, ryanrichter94 approved these changes
LGTM 🚀

2023-09-29 15:53 UTC, merged