(#753) Add Video to Package Prefixes FAQ Doc
chocolatey/docs pull request #754
Opened 2023-06-14 20:29 UTC by ryanrichter94

## Description Of Changes
Added Gary's video the Chocolatey FAQ on difference between ,install and .portable packages.

## Motivation and Context
Adds additional outlet of context to the doc.

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [X] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #753 

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #753

2023-06-15 08:00 UTC, gep13 requested changes

2023-06-28 15:47 UTC, st3phhays commented on input/en-us/faqs.md
> +<div class="ratio ratio-16x9">
I also like @gep13's suggestion on the context text 😃

2023-10-04 19:49 UTC, ryanrichter94 commented on input/en-us/faqs.md
> +<div class="ratio ratio-16x9">
Went in and added the video under a Video Explanation sub-heading to call it out more. Also added the `mb-3` in my HTML div calling the video. Lastly added a link to a GitHub issue around the future addition of virtual packages and removed a non-working link that went to one of Rob's old sites.

2023-10-04 19:56 UTC, gep13 approved these changes
LGTM!

2023-10-04 19:57 UTC, merged

2023-10-04 19:57 UTC, gep13 commented
@ryanrichter94 thanks for getting this updated!