Add notes for 2.1.0 and 6.1.0 Chocolatey products
chocolatey/docs pull request #757
Opened 2023-06-20 09:16 UTC by gep13

## Description Of Changes

Add release notes for releases of 4 of the main Chocolatey products.

## Motivation and Context

There are releases coming up, and we need to get this documented.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2023-06-20 09:17 UTC, gep13 commented
@pauby this is in draft while we finalize a few things, but I thought it would make sense to get these release notes created, since we know roughly what is going out in these releases.

2023-06-20 13:49 UTC, pauby requested changes

2023-06-20 13:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.0.0.
```suggestion
> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.x.
```

2023-06-20 13:49 UTC, pauby commented on input/en-us/agent/release-notes.md
> +> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.0.0.
That documentation will need to be updated to say 2x now that we're releasing 2.1.0.

2023-06-20 13:49 UTC, pauby commented on input/en-us/choco/release-notes.md
> +> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.0.0.
```suggestion
> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.x.
```

2023-06-20 13:49 UTC, pauby commented on input/en-us/chocolatey-gui/release-notes.md
> +> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.0.0.
```suggestion
> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 1.x versions to 2.x.
```

2023-06-20 13:49 UTC, pauby commented on input/en-us/licensed-extension/release-notes.md
> +> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 5.x and earlier versions to 6.0.0.
```suggestion
> Refer to our [Upgrade Guide](xref:upgrading-to-chocolatey-v2-v6) for recommendations before upgrading from 5.x and earlier versions to 6.x.
```

2023-06-20 15:43 UTC, gep13 commented
@pauby I have made the suggested changes, and this is now ready for another review.

2023-06-20 16:19 UTC, pauby approved these changes

2023-06-28 15:56 UTC, pauby requested changes

2023-06-28 15:56 UTC, pauby commented on input/en-us/licensed-extension/release-notes.md
> +- Performance degradation after upgrading to version Chocolatey Licensed Extension v6.0.0.
```suggestion
- Degraded performance after upgrading to version Chocolatey Licensed Extension v6.0.0.
```

2023-06-28 16:26 UTC, gep13 commented
@pauby I have made the suggestion. Can you do a final review and approval? Thanks!

2023-06-28 16:27 UTC, pauby submitted a review, later dismissed

2023-06-29 13:07 UTC, merged