Clarify Package Environment variables and their contents
chocolatey/docs pull request #764
Opened 2023-06-27 23:09 UTC by corbob

## Description Of Changes

Add a note to the upgrade guide for Package Maintainers to be aware that the ChocolateyPackageVersion is normalized in Chocolatey CLI Version 2.0.0. Add some clarifying words around the ChocolateyPackageName variable that it is a lower case version of the id.

## Motivation and Context

The normalization of Version numbers could behave differently depending on the package scripts. There used to be at least one package that expected ChocolateyPackageName to exactly match the nuspec file and it didn't work when the casing was changed.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

No issue was raised as this was identified during discussion of the Chocolatey CLI 2.1.0 milestone.

2023-06-28 10:47 UTC, pauby requested changes

2023-06-28 10:47 UTC, pauby commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The [normalized version](xref:upgrading-to-chocolatey-v2-v6#package-version-normalization) of the package, equivalent to the `<version />` field in the nuspec.
From conversations with Gary and Kim, this isn't the case. The nuspec could contain a non-normalized version.

2023-06-28 10:47 UTC, pauby commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +
Can we link to the variable on the functions page, here?

2023-06-28 14:42 UTC, AdmiringWorm commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The [normalized version](xref:upgrading-to-chocolatey-v2-v6#package-version-normalization) of the package, equivalent to the `<version />` field in the nuspec.
Starting in Chocolatey CLI v2.1.0, this variable will always be a normalized version number (which should have been in v2.0.0 as well, but unfortunately had been missed).

We might want to expand this description with a message that it can be a non-normalized version number in v1.x, as that version will use exactly what is specified in the nuspec file.

2023-06-28 17:41 UTC, corbob commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The [normalized version](xref:upgrading-to-chocolatey-v2-v6#package-version-normalization) of the package, equivalent to the `<version />` field in the nuspec.
I've updated this to expand on the difference between the versions.

2023-06-28 17:42 UTC, corbob commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +
I've linked to the environment variables section, and reworded this a bit as it felt a little odd.

2023-07-14 15:51 UTC, vexx32 requested changes
Couple things, but otherwise this looks good :3

2023-07-14 15:51 UTC, vexx32 commented on input/en-us/create/functions/index.md
> +* [Install-ChocolateyZipPackage](xref:install-chocolateyzippackage).
All of these... _feel_ wrong to me, why are we changing these?

2023-07-14 15:51 UTC, vexx32 commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +> **Important information for package maintainers.** The `ChocolateyPackageVersion` [environment variable](xref:powershell-reference#environment-variables) follows the below version normalization. If
```suggestion
> **Important information for package maintainers.** The `ChocolateyPackageVersion` [environment variable](xref:powershell-reference#environment-variables) follows the below version normalization. If your package scripts use this variable, and the nuspec specified version falls outside of the normalized format, then they may not behave as expected. We recommend using specific version numbers within your scripts rather than depending on these environment variables.
```

2023-07-14 15:59 UTC, corbob commented on input/en-us/create/functions/index.md
> +* [Install-ChocolateyZipPackage](xref:install-chocolateyzippackage).
These are part of the initial maint commit that updated the lists to have periods at the end.

2023-07-14 16:30 UTC, vexx32 commented on input/en-us/create/functions/index.md
> +* [Install-ChocolateyZipPackage](xref:install-chocolateyzippackage).
I don't think a simple list of items like this makes sense to put periods on. A bulleted list of sentences, absolutely. A bulleted list of individual items just reads.... _strange_ to me. 🤷‍♀️

2023-07-18 02:19 UTC, corbob commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +> **Important information for package maintainers.** The `ChocolateyPackageVersion` [environment variable](xref:powershell-reference#environment-variables) follows the below version normalization. If
I don't know how I didn't get this updated Friday, but it's updated now 😁

2023-07-18 10:40 UTC, pauby commented on input/en-us/create/functions/index.md
> +* [Install-ChocolateyZipPackage](xref:install-chocolateyzippackage).
I don't know if there are any rules around this, but what @vexx32 says makes sense to me. Unless we have precedent for doing it elsewhere, and if that is the case, we should be consistent.

2023-07-18 14:45 UTC, corbob commented on input/en-us/create/functions/index.md
> +* [Install-ChocolateyZipPackage](xref:install-chocolateyzippackage).
I've reverted this portion of the commit with a fixup commit. Will get it all rebased on master and force pushed shortly.

2023-07-19 14:49 UTC, vexx32 submitted a review, later dismissed

2023-07-19 15:52 UTC, pauby requested changes

2023-07-19 15:52 UTC, pauby commented on input/en-us/create/functions/index.md
> +> As such, it is recommended to do your own validation of the values if you rely on them for automation purposes.
I'm not sure if this should be here. I think it will unnecessarily alarm people. None of these have changed since the start of Chocolatey CLI and `$env:ChocolateyPackageVersion` is still there, we're just warning people they perhaps shouldn't use it under certain scenarios.

2023-07-19 15:52 UTC, pauby commented on input/en-us/create/functions/index.md
> +> As such, it is recommended to do your own validation of the values if you rely on them for automation purposes.
I also know this isn't new, and I didn't pick up on it, and other things, earlier.

2023-07-19 15:52 UTC, pauby commented on input/en-us/create/functions/index.md
> +> For instance: if you rely on `ChocolateyPackageName` for a command, ensure that command works with all possible casing of the package ID.
Given the `ChocolateyPackageName`, evaluates to the lowercase version of the ID, should we have this at all?

2023-07-19 15:52 UTC, pauby commented on input/en-us/create/functions/index.md
> +> Likewise, if you rely on `ChocolateyPackageVersion` in a URL, ensure that all possible permutations of the package version work (eg: `1.0.0.0`, `1.0.0`, `1.0`, `1.0.00.0`).
Can we add this next to `ChocolateyPackageVersion`?

2023-07-19 15:52 UTC, pauby commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The version of the package, prior to Chocolatey CLI version 2.1.0 this is equivalent to the `<version />` field in the nuspec. Starting with Chocolatey CLI version 2.1.0
Did we not have an issue to document what package version normalization does on its own page (it's on the v2-to-v6 page)?

2023-07-19 15:52 UTC, pauby commented on input/en-us/create/functions/index.md
> + * ChocolateyExitOnRebootDetected - Are we exiting on a detected reboot? Set by ` --exit-when-reboot-detected`  or the feature `exitOnRebootDetected`.
```suggestion
 * ChocolateyExitOnRebootDetected - Are we exiting on a detected reboot? Set by `--exit-when-reboot-detected`  or the feature `exitOnRebootDetected`.

```

2023-07-19 17:22 UTC, corbob commented on input/en-us/create/functions/index.md
> +> For instance: if you rely on `ChocolateyPackageName` for a command, ensure that command works with all possible casing of the package ID.
Ah, I think I was incorrect in the ReSharper package: https://github.com/flcdrg/au-packages/issues/152 where I thought the variable had started being cast to lowercase, but I don't see that being the case, unless it's cast to lower case somewhere earlier (doesn't look likely). I'll take the part about the package ID out completely.

2023-07-19 17:24 UTC, corbob commented on input/en-us/create/functions/index.md
> +> As such, it is recommended to do your own validation of the values if you rely on them for automation purposes.
This isn't "new" per se, but it is a section added between your first review and this one.

2023-07-19 17:41 UTC, corbob commented on input/en-us/create/functions/index.md
> +> Likewise, if you rely on `ChocolateyPackageVersion` in a URL, ensure that all possible permutations of the package version work (eg: `1.0.0.0`, `1.0.0`, `1.0`, `1.0.00.0`).
I've moved this down along with the variable, and adjusted the list. It felt like it would be too long with multiple sentences on the end, so I added them as a sublist: 
![2023-07-19_10-38-43](https://github.com/chocolatey/docs/assets/30301021/5562695e-53ff-40e2-8c30-9c44fab43f75)

2023-07-19 17:44 UTC, corbob commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The version of the package, prior to Chocolatey CLI version 2.1.0 this is equivalent to the `<version />` field in the nuspec. Starting with Chocolatey CLI version 2.1.0
> Did we not have an issue to document what package version normalization does on its own page (it's on the v2-to-v6 page)?

I don't recall seeing one directly, but there could be one. #770 which this is targeting is about documenting the variable is now normalized. I'll take a look through the issues and open one to add a normalization page if needed.

2023-07-20 09:50 UTC, pauby commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The version of the package, prior to Chocolatey CLI version 2.1.0 this is equivalent to the `<version />` field in the nuspec. Starting with Chocolatey CLI version 2.1.0
When you open that can you make a note to come back to this page and update that link, so it points there rather than the v2 upgrade docs?

2023-07-20 09:51 UTC, pauby commented on input/en-us/create/functions/index.md
> +> Likewise, if you rely on `ChocolateyPackageVersion` in a URL, ensure that all possible permutations of the package version work (eg: `1.0.0.0`, `1.0.0`, `1.0`, `1.0.00.0`).
Given what we have to work with here, I think this is a good compromise. Good work!

2023-07-20 09:57 UTC, pauby approved these changes
Good work @corbob. Thanks for persevering.

2023-07-20 11:50 UTC, pauby commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The version of the package, prior to Chocolatey CLI version 2.1.0 this is equivalent to the `<version />` field in the nuspec. Starting with Chocolatey CLI version 2.1.0
Ignore the above. I found the issue and added a comment.

2023-07-21 11:40 UTC, pauby commented on input/en-us/create/functions/index.md
> + * ChocolateyPackageVersion - The version of the package, prior to Chocolatey CLI version 2.1.0 this is equivalent to the `<version />` field in the nuspec. Starting with Chocolatey CLI version 2.1.0
I've created a [PR for this](https://github.com/chocolatey/docs/pull/793). The xref is `version-normalization` so we can update the above.

2023-07-25 06:40 UTC, gep13 commented
In order to get this one over the line, I am going to get it rebased to fix up the merge conflict, and then get it merged.  This is based on the fact that @pauby has already approved it.

2023-07-25 06:53 UTC, gep13 approved these changes
LGTM!

2023-07-25 07:05 UTC, merged