Update proxy documentation
chocolatey/docs pull request #765
Opened 2023-06-28 23:32 UTC by corbob

## Description Of Changes

Update the proxy documentation to be clear about the order of proxy configurations applying. Add known issues with links.

## Motivation and Context

The proxy configuration has changed slightly from Chocolatey CLI 1.4 to 2.1.0

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

* ENGTASKS-3200

2023-06-28 23:51 UTC, TheCakeIsNaOH commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +* Chocolatey Licensed Extension - [VirusTotal checking at runtime does not use any proxy](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/681)
This is not a publicly available issue, it probably should be linked/synced to the home repository.

2023-06-29 16:39 UTC, corbob commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +* Chocolatey Licensed Extension - [VirusTotal checking at runtime does not use any proxy](https://gitlab.com/chocolatey/collaborators/choco-licensed/-/issues/681)
Thanks for noting that. These have been updated with public issues now.

2023-07-07 10:36 UTC, pauby requested changes

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +## Proxy setting considerations
```suggestion
## Proxy Setting Considerations
```

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +## Proxy setting considerations
Please be consistent with headings.

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +Chocolatey applies proxy configurations based on where they are supplied. The order of the configuration applying is:
```suggestion
Chocolatey applies proxy configuration based on the order below:
```

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +1. [System configured proxy server](#system-proxy-settings).
```suggestion
1. [Command line arguments](#explicit-proxy-settings-at-runtime).
1. [Chocolatey config](#explicit-proxy-settings).
1. [Environment variables](#existing-proxy-environment-variables).
1. [System configured proxy server](#system-proxy-settings).
```

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +1. [System configured proxy server](#system-proxy-settings).
Please be consistent.

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +* Chocolatey Agent - [Agent communications do not use any proxy configuration](https://github.com/chocolatey/chocolatey-licensed-issues/issues/350)
```suggestion
* Chocolatey GUI - [Downloading icons does not honor Chocolatey CLI proxy settings](https://github.com/chocolatey/ChocolateyGUI/issues/1013).
* Chocolatey Licensed Extension - [VirusTotal checking at runtime does not use any proxy](https://github.com/chocolatey/chocolatey-licensed-issues/issues/351).
* Chocolatey Agent - [Agent communications do not use any proxy configuration](https://github.com/chocolatey/chocolatey-licensed-issues/issues/350).
```

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +* Chocolatey Agent - [Agent communications do not use any proxy configuration](https://github.com/chocolatey/chocolatey-licensed-issues/issues/350)
Please be consistent.

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +## Installing Chocolatey From Behind A Proxy Server
```suggestion
## Installing Chocolatey From Behind a Proxy Server
```

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +Chocolatey has explicit proxy
This line looks incomplete?

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
>  choco config set --name proxy --value <locationandport>
Can you fix up all of this code based on best practices? Can you also capitalize the parts in the `<` brackets, for example `<LOCATION-AND-PORT>`?

2023-07-07 10:36 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
>  ~~~sh
Can you fixup this code too?

2023-07-14 14:43 UTC, corbob commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
> +## Proxy setting considerations
😂 I explicitly added a maint commit to bring the headings into consistency, and then committed this one without it 😂. I've gotten that fixed up.

2023-07-14 14:59 UTC, corbob commented
I've updated the docs with the requested changes from pauby. I have included them as a `fixup!` commit with the intention that we should `git rebase upstream/master -i --autosquash` before the merge which will bring the branch in line with `master`, as well as fixup the mentioned commit into the original commit where the changes were made.

2023-07-14 17:21 UTC, vexx32 approved these changes
This looks good to me, thanks for fixing this up! 💖

2023-07-14 19:19 UTC, merged