(#786) Set required memory for container
chocolatey/docs pull request #791
Opened 2023-07-21 09:47 UTC by pauby

## Description Of Changes
Sets the required memory for the docs repo container to 4 GB. Note that this is the amount that I need to set it to. The issue #786 didn't specify a memory number.

## Motivation and Context
Less than 4GB memory in the container, _in my setup_, causes the site not to build.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #786

2023-07-21 13:22 UTC, corbob requested changes
I want to say also that 4GB is what the base codespace that I have uses, but when running locally 4GB is fine 🤔 .

<img width="515" alt="2023-07-21_06-18-31" src="https://github.com/chocolatey/docs/assets/30301021/2372fee5-2c90-4948-86f4-4cd83eeb3e64">

For now I'd say we leave it with the 4, and once the parsing error is fixed up can run it in codespaces and confirm it works. 

Looking closer at the docs, they show a whole collection of code spaces, while I only have two listed. Now I'm starting to wonder if the memory issue is intermittent and depends on if other codespaces are running at the same time 🤔

2023-07-21 13:22 UTC, corbob commented on .devcontainer/devcontainer.json
> +	}
```suggestion
	},
```
I think this is what the codespace error is saying is missing... Although not too sure 😂 

![2023-07-21_06-03-27](https://github.com/chocolatey/docs/assets/30301021/a158be16-4b48-4a42-927c-71660c9c595c)

2023-07-21 14:00 UTC, corbob commented
So it looks like... In codespaces, the container when given 4GB idles at about 1700 MB of free memory... locally it idles at about 2000... This is only 300 MB so seems like it shouldn't really be a concern... However, when Statiq is previewing the site locally, the container has around 100 MB free 😂  Locally it also seems to dip into swap which codespaces is a constant 0.

I'd be interested to see if bumping the memory to 8 GB resulted in adverse behaviours locally if you don't have the 8 GB assigned to docker.

2023-07-21 14:59 UTC, pauby commented on .devcontainer/devcontainer.json
> +	}
Good catch. Fixed this.

2023-07-21 15:42 UTC, corbob commented
> Based on what you said, do we bump this from 4GB to 8GB?

@pauby I think so. At least for this PR, then can easily test that codespaces launches the proper container.

2023-07-21 16:17 UTC, pauby commented
I've updated to use 8GB.

2023-07-21 16:54 UTC, corbob commented
OK, Codespaces are hurting my brain. To my knowledge, all of the ones I create say they're being created under `corbob`, but with the memory set to 8, I get this message regarding not being an applicable SKU:
![image](https://github.com/chocolatey/docs/assets/30301021/f41477fc-715f-4a6f-9c00-f2b127810df5)

When I try to create any codespace, I have two options, one 2 core with 4 GB memory, and the other 4 core with 8GB memory. Would it make sense to try setting `cpus` to `4` and `memory` to `8gb`?
![2023-07-21_09-53-53](https://github.com/chocolatey/docs/assets/30301021/a541c024-29e8-4846-ab18-60801fe12a77)

2023-11-27 09:39 UTC, gep13 commented
@corbob @pauby this PR seems to have been forgotten about.

Can either of you please provide an update here on what needs to be done to get this completed?

2024-06-01 13:15 UTC, pauby commented
Based on @corbob comment [above](https://github.com/chocolatey/docs/pull/791#issuecomment-1645989846) I've added `cpus` and rebased. @gep13 this is ready for review / merge.

2024-06-01 14:34 UTC, gep13 approved these changes
LGTM

2024-06-01 14:35 UTC, merged

2024-06-01 14:35 UTC, gep13 commented
Happy to see this merged in for just now, this requirement will likely not be needed once @st3phhays has finished her upcoming work with Astro.