Add notes for Chocolatey CLI 2.2.1
chocolatey/docs pull request #800
Opened 2023-08-03 08:30 UTC by gep13

## Description Of Changes

Add release notes for Chocolatey CLI v2.2.1.

## Motivation and Context

There is a release coming up, and we need to get this documented.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2023-08-03 08:31 UTC, gep13 commented
@AdmiringWorm @pauby this is ready for review, however, please don't merge once the review is complete.  I will do this when everything else is ready.

2023-08-03 08:36 UTC, AdmiringWorm requested changes
Other than a single comment, this look good to me

2023-08-03 08:36 UTC, AdmiringWorm commented on input/en-us/choco/release-notes.md
> +- Fix - Unable to do non-elevated operations when cache location is set to restricted directory - see [#3291](https://github.com/chocolatey/choco/issues/3291).
I think

```suggestion
- Fix - Unable to do non-elevated operations when cache location is set to a restricted directory - see [#3291](https://github.com/chocolatey/choco/issues/3291).
```

2023-08-03 08:40 UTC, AdmiringWorm submitted a review, later dismissed
LGTM

2023-08-03 09:17 UTC, pauby requested changes

2023-08-03 09:17 UTC, pauby commented on input/en-us/choco/release-notes.md
> +- Fix - Can't find choco.exe after upgrading Chocolatey with MSI - see [#3286](https://github.com/chocolatey/choco/issues/3286).
```suggestion
- Fix - Can't find `choco.exe` after upgrading Chocolatey CLI using the MSI - see [#3286](https://github.com/chocolatey/choco/issues/3286).
```

2023-08-03 09:17 UTC, pauby commented on input/en-us/choco/release-notes.md
> +- Fix - Unable to do non-elevated operations when cache location is set to a restricted directory - see [#3291](https://github.com/chocolatey/choco/issues/3291).
```suggestion
- Fix - Unable to do non-elevated operations when `cacheLocation` is set to a restricted directory - see [#3291](https://github.com/chocolatey/choco/issues/3291).
```

2023-08-04 08:55 UTC, pauby requested changes

2023-08-04 08:55 UTC, pauby commented on input/en-us/choco/release-notes.md
> +> Instead, work will be completed to correct this issue, and a new Chocolatey CLI 2.2.2 release will be completed.
```suggestion
>  Chocolatey CLI 2.2.1 was removed from public availability due to a bug identified just prior to the release.
```

2023-08-04 09:11 UTC, pauby approved these changes

2023-08-04 09:20 UTC, merged