(#796) Add info about missing config/features
chocolatey/docs pull request #802
Opened 2023-08-04 12:34 UTC by gep13

## Description Of Changes

This commit adds this information in, using the descriptions from the code base for consistency.

## Motivation and Context

Information about 4 pieces of configuration:

Configuration
  - defaultPushSource
  - logRetentionPolicyInDays Features
  - disableCompatibilityChecks
  - useLogRetentionPolicy

were missing.  

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #796

2023-08-04 13:01 UTC, pauby requested changes

2023-08-04 13:01 UTC, pauby commented on input/en-us/configuration.md
> +* [ ] `disableCompatibilityChecks` - Disable Compatibility Checks - Should a warning we shown, before and after command execution, when a runtime compatibility check determines that there is an incom
```suggestion
* [ ] `disableCompatibilityChecks` - Disable Compatibility Checks - Disable showing a warning when there is an incompatibility between Chocolatey CLI and Chocolatey Licensed Extension. Available in 1.1.0+.
```

2023-08-04 13:01 UTC, pauby commented on input/en-us/configuration.md
> +* [x] `useLogRetentionPolicy` - Use Automatic Log Retention Policy - Cleans any rolled over log files once a day that are older than the configured retention policy day value. Licensed editions only
```suggestion
* [x] `useLogRetentionPolicy` - Use Automatic Log Retention Policy - Once per day, remove any log files that are older than the `logRetentionPolicyInDays` value. Licensed editions only (version 5.0.0+).
```

2023-08-08 10:49 UTC, gep13 commented
@pauby can I get you to re-review this, based on our discussion internally, thanks.

2023-08-08 12:24 UTC, merged