Add notes on specifically downgrading to 1.x and 5.x of Chocolatey products
chocolatey/docs pull request #803
Opened 2023-08-04 14:52 UTC by pauby

## Description Of Changes
Add notes on downgrading.

## Motivation and Context
See this [internal issue](https://gitlab.com/chocolatey/solutions/support-issues/-/issues/28).

We didn't have any documentation to help with specifically downgrading.

## Testing

**NOTE that YET AGAIN my Docker container is not running.**

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

n/a

2023-08-04 17:32 UTC, imm0rtalsupp0rt requested changes

2023-08-04 17:32 UTC, imm0rtalsupp0rt commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +1. This steps requires you to downgrade products depending on what you have installed.
"This step requires..." or "These steps require..."; either would work here in my opinion.

2023-08-04 17:32 UTC, imm0rtalsupp0rt commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +The Sonatype Nexus Repository Manager has an [issue that can cause it to go into an infinite loop of querying for packages from a NuGet v2 feed](https://issues.sonatype.org/browse/NEXUS-13426) (you w
> The only affects Sonatype Nexus NuGet v2 feeds as it has been fixed for NuGet v3 feeds.

This only affects Sonatype Nexus NuGet v2 feeds as it has been fixed for NuGet v3 feeds.

2023-08-04 17:32 UTC, imm0rtalsupp0rt commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
>  In version 1.0.0 of Chocolatey CLI, we added notices that the `choco list` command will list only local packages, and deprecated the `-l` and it's alias options. See this [GitHub issue for more infor
> In version 1.0.0 of Chocolatey CLI, we added notices that the `choco list` command will list only local packages, and deprecated the `-l` and _it's_ alias options. See this [GitHub issue for more information](https://github.com/chocolatey/choco/issues/158). We have also removed the `-a` and _it's_ alias options from the `list` command as it no longer made sense to have that option once side-by-side installs were removed.

Please change these to 'its'  as in 'its alias options' with no apostrophe.

2023-09-14 10:38 UTC, pauby commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +The Sonatype Nexus Repository Manager has an [issue that can cause it to go into an infinite loop of querying for packages from a NuGet v2 feed](https://issues.sonatype.org/browse/NEXUS-13426) (you w
@imm0rtalsupp0rt Can you come back to me about this?

2023-09-14 10:43 UTC, imm0rtalsupp0rt commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +The Sonatype Nexus Repository Manager has an [issue that can cause it to go into an infinite loop of querying for packages from a NuGet v2 feed](https://issues.sonatype.org/browse/NEXUS-13426) (you w
Apologies; I should've been clearer. The sentence says, '_The_ only affects Sonatype Nexus NuGet v2 feeds as it has been fixed for NuGet v3 feeds.' It should say '_This_ only affects . . .'

2023-09-14 11:39 UTC, pauby commented on input/en-us/guides/upgrading-to-chocolatey-v2-v6.md
> +The Sonatype Nexus Repository Manager has an [issue that can cause it to go into an infinite loop of querying for packages from a NuGet v2 feed](https://issues.sonatype.org/browse/NEXUS-13426) (you w
That's been done.

2023-09-14 11:41 UTC, pauby commented
This is ready for final review and merging.

2023-09-14 11:45 UTC, imm0rtalsupp0rt commented
LGTM!

2023-09-25 14:45 UTC, merged

2023-09-25 14:47 UTC, gep13 commented
@pauby thanks for getting this updated!