(doc) Add CCM 0.11.0 release notes
chocolatey/docs pull request #825
Opened 2023-09-18 11:14 UTC by AdmiringWorm

## Description Of Changes

Release notes for upcoming version of Chocolatey Central Management 0.11.0.

## Motivation and Context

We need release notes.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before 
submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2023-09-18 12:56 UTC, gep13 requested changes
A few minor tweaks, otherwise, this LGTM!

2023-09-18 12:56 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Add the ability to send email notifications when a deployment plan has finished - see [Licensed #328](https://github.com/chocolatey/chocolatey-licensed-issues/issues/328).
```suggestion
- Add the ability to send email notifications when a Deployment Plan has finished - see [Licensed #328](https://github.com/chocolatey/chocolatey-licensed-issues/issues/328).
```

2023-09-18 12:56 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Fix - When viewing the log for a Deployment Step, the text disappears from the Copy button when the mouse is hovered over it.
```suggestion
- Fix - When viewing the log for a Deployment Step, the text disappears from the `Copy` button when the mouse is hovered over it.
```

2023-09-18 12:56 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Ensure a computer's `ComputerName` and `FriendlyName` properties are in separate fields when the API returns data.
```suggestion
- Ensure a Computer's `ComputerName` and `FriendlyName` properties are in separate fields when the API returns data.
```

2023-09-18 12:56 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Reinstate the ‘Return To Deployments’ button when editing a deployment plan.
```suggestion
- Reinstate the ‘Return To Deployments’ button when editing a Deployment Plan.
```

2023-09-18 12:56 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Remove the ability to assign any user the `ChocoAdmin` role.
```suggestion
- Remove the ability to assign a User the `ChocoAdmin` Role.
```

2023-09-18 13:06 UTC, pauby reviewed
This is offset of the current release, but I'm curious about why this is needed. Let's not put more pressure on the Support team.

2023-09-18 13:06 UTC, pauby commented on input/en-us/central-management/release-notes.md
>  - Some issues may be held internally, please follow your support routes to learn more.
Why do we have this here? All resolved  issues should be on the release notes so this shouldn't be necessary.

2023-09-18 13:19 UTC, gep13 commented on input/en-us/central-management/release-notes.md
>  - Some issues may be held internally, please follow your support routes to learn more.
This is a hold over from the initial import of the release notes from the old location.  It has been around for quite a while, including in some of the other Product release notes.  Happy to remove this, but we should remove from all the places that it is located.

2023-09-18 13:46 UTC, gep13 requested changes
Just one final change.

2023-09-18 13:46 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Add the ability to Import and Export Deployment Plan Definitions.
```suggestion
- Add the ability to import and export Deployment Plan definitions.
```

2023-09-18 13:46 UTC, gep13 commented on input/en-us/central-management/release-notes.md
> +- Add the ability to Import and Export Deployment Plan Definitions.
Just so that we are consistent with the line below

2023-09-18 13:46 UTC, gep13 commented
Also, we will need to update the `TBD` with the actual release date.

2023-09-18 16:01 UTC, gep13 approved these changes
LGTM!

2023-09-18 18:24 UTC, vexx32 commented on input/en-us/central-management/release-notes.md
>  - Some issues may be held internally, please follow your support routes to learn more.
Resolving this for now so we can merge this and continue with the release.

2023-09-18 18:28 UTC, merged

2023-09-21 11:20 UTC, pauby commented
@gep13 @vexx32 @AdmiringWorm There are a couple of issues with the release notes:

> - Add an option to provide a default value for the `executionTimoutInSeconds` setting, which will be used for all new Deployment Steps.

There is a spelling mistake in the value name.

> - Move the `Action` button to the first column in all tables.
> - Reinstate the ‘Return To Deployments’ button when editing a Deployment Plan.

This is inconsistent. Either buttons should be in a code block or shouldn't.

Note that @gep13 fixed both of these issues and updated the original notes in GitLab.