(#817) Remove QDE Docs
chocolatey/docs pull request #828
Opened 2023-09-18 18:36 UTC by ryanrichter94

## Description Of Changes
Remove QDE documentation. Also removed any old xrefs between docs that used this outdated documentation.

## Motivation and Context
QDE is a deprecated solution. Thus the docs should be removed.

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* ~[ ] Minor documentation fix (typos etc.).~
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* ~[ ] New documentation page added.~
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~
    * ~Issue #~

## Change Checklist

* [X] Requires a change to menu structure (top or left hand side)/
* [X] Menu structure has been updated

## Related Issue

Fixes #817

2023-09-19 08:25 UTC, pauby commented
@gep13 I've added you as a reviewer to this.

2023-09-19 09:07 UTC, gep13 commented
@pauby the changes in this PR look good to me, but I do think we are missing something.

For example, what do we want to happen if someone has an existing link to the QDE environment page, for example, this link:

https://docs.chocolatey.org/en-us/c4b-environments/quick-deployment/

Do we want this to redirect through to the QSG home instead?  If so, we can put this in place using a `RedirectFrom` on that page.  If we go down this route, I would suggest that we should do it for each page that is being deleted.

Thoughts?

2023-09-19 15:58 UTC, steviecoaster commented
> @pauby the changes in this PR look good to me, but I do think we are missing something.
> 
> For example, what do we want to happen if someone has an existing link to the QDE environment page, for example, this link:
> 
> https://docs.chocolatey.org/en-us/c4b-environments/quick-deployment/
> 
> Do we want this to redirect through to the QSG home instead? If so, we can put this in place using a `RedirectFrom` on that page. If we go down this route, I would suggest that we should do it for each page that is being deleted.
> 
> Thoughts?

I agree with Gary, we should redirect  each deleted page to the top-level page for the Quickstart Environment guide.

2023-09-19 17:30 UTC, gep13 commented
I actually had a chat with @pauby about this earlier today, but didn't get a chance to reply here again...

What we discussed was to create a new landing page, that doesn't exist in the navigation menu, that all the deleted links point to. That page would hold words about QDE going away, and a link to the root of QSG. That way, anyone navigating to a QDE won't be completely confused as to why they got to QSG.

Thoughts?

2023-09-20 06:53 UTC, gep13 commented
@ryanrichter94 @steviecoaster let me know your thoughts on this [comment](https://github.com/chocolatey/docs/pull/828#issuecomment-1726192951). Thinking about it more, I really feel that we need some form of landing page (hidden from the navigation menu), to capture anyone still coming to these pages.  Let me know if you have any questions about setting it up.

2023-09-21 17:38 UTC, ryanrichter94 commented
After discussing internally we will create an unlisted landing page directing all old QDE documentation to the new landing page. The landing page will discuss why the QDE solution has been deprecated as well as link off to Quick Start Guide and it's documentation that can be used for things such as SSL certificate renewal.

2023-09-25 15:47 UTC, steviecoaster requested changes

2023-09-25 15:47 UTC, steviecoaster commented on input/en-us/c4b-environments/quick-start-environment/qde-deprecation.md
> +en-us/c4b-environments/quick-deployment/release-notes
Your YAML is incorrect here, I think this needs 2 spaces in front of each one.

2023-09-25 19:22 UTC, steviecoaster requested changes

2023-09-25 20:00 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/qde-deprecation.md
> +New versions of the [Jenkins package](https://community.chocolatey.org/packages/jenkins) are being continuously published to the Chocolatey Community Repository.
Added Jenkins Upgrade doc and linked it to this section.

2023-09-25 20:32 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/qde-deprecation.md
> +The beauty is while we don't support the Quick Deploy Environment as a new deployment option. If already deployed, you have the same components (Sonatype Nexus, Jenkins, and Chocolatey Central Manage
Fixed wording.

2023-09-25 20:32 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/qde-deprecation.md
> +Here is a link to our [Chocolatey Central Management Upgrade Documentation](xref:ccm-upgrade).
Fixed wording.

2023-09-26 13:54 UTC, steviecoaster approved these changes

2023-09-26 13:54 UTC, merged