(#826) Update Computers images and packages.config
chocolatey/docs pull request #829
Opened 2023-09-18 20:01 UTC by corbob

## Description Of Changes

This updates the images used on the computers page to reflect the UI in Chocolatey Central Management 0.11.0. In addition, this adds new documentation about the export to packages.config feature.

## Motivation and Context

- Updated interface in Chocolatey Central Management 0.11.0.
- Addition of ability to export to a `packages.config` file.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #826

2023-09-18 20:28 UTC, st3phhays commented on input/en-us/central-management/usage/website/computers.md
> +### What do I do if computers are not showing up in CCM
```suggestion
### What do I do if computers are not showing up in CCM?
```

All of the FAQs on the Deployments page end with a `?`, so I've added one here.

2023-09-19 09:32 UTC, gep13 requested changes

2023-09-19 09:32 UTC, gep13 commented on input/en-us/central-management/usage/website/computers.md
> +From the Computer details page in Central Management, select the `Export to packages.config` button.
```suggestion
From the Computer details page in Chocolatey Central Management, select the `Export to packages.config` button.
```

2023-09-19 15:33 UTC, st3phhays approved these changes
This LGTM!sss

2023-09-19 16:15 UTC, merged

2023-09-19 16:15 UTC, gep13 commented
@corbob thanks for getting this added!