(#843) Add page for configuring CCM with HSTS
chocolatey/docs pull request #845
Opened 2023-09-27 00:03 UTC by corbob

## Description Of Changes

Add a page regarding configuring CCM with HSTS.

## Motivation and Context

Adding documentation for ways to enable HSTS for CCM.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

Fixes #843

2023-09-28 11:45 UTC, pauby requested changes

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Description: How To Configure Chocolatey Central Management to use HSTS
```suggestion
Title: How to Configure Chocolatey Central Management to Use HSTS
Description: How to Configure Chocolatey Central Management to Use HSTS
```

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +> Although HTTP Strict Transport Security (HSTS) allows you to have reasonable certainty that your connection to Chocolatey Central Management is not intercepted, we recommend that you do not connect
```suggestion
> Although HTTP Strict Transport Security (HSTS) allows you to have reasonable certainty that your connection to Chocolatey Central Management is not intercepted, we recommend that you do not connect your Chocolatey Central Management server directly to the internet.
```

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +> Although HTTP Strict Transport Security (HSTS) allows you to have reasonable certainty that your connection to Chocolatey Central Management is not intercepted, we recommend that you do not connect
Lets avoid making recommendations that we don't provide additional information / configuration / setup for.

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Chocolatey Central Management is hosted by an IIS server, and can make use of the features available in IIS. Below is some general information about how to enable HSTS with IIS. You can also make use
```suggestion
Chocolatey Central Management is hosted by II and makes use of features available by it. Below is some general information about how to enable HSTS with both IIS and a reverse proxy.
```

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +If you are running IIS 10.0 version 1709 or later, you can enable HSTS using the `<hsts>` element of the `<site>` element. Microsoft has information as well as samples [here](https://learn.microsoft.
```suggestion
If you are running IIS 10.0 version 1709 or later, you can enable HSTS using the [documentation, and samples, provided by Microsoft](https://learn.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/hsts). If you are on newer versions of IIS, you may even have access to enabling HSTS within the IIS Management Console; steps to enable it this way are below.
```

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +If you are running IIS 10.0 version 1709 or later, you can enable HSTS using the `<hsts>` element of the `<site>` element. Microsoft has information as well as samples [here](https://learn.microsoft.
>  If you are on newer versions of IIS, you may even have access to enabling HSTS within the IIS Management Consol

I don't understand this. It says you may have access? What if you don't? What do they do? Is there a plugin / addin for IIS that is needed?

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +
```suggestion
1. Open the IIS Management Console.
1. In the **Connection** pane, expand the server and then **Sites** to select `ChocolateyCentralManagement`.
1. On the right, select **HSTS**  under **Configure** in the **Actions** pane.
1. Configure HSTS as desired.

```

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +### Enabling HSTS within IIS prior to IIS 10.0
```suggestion
### Enabling HSTS Within IIS Prior to IIS 10.0
```

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +### Enabling HSTS within IIS prior to IIS 10.0
Please be consistent with headings.

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +
Please be consistent with ending bullet points with full stops / periods.

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Although it sounds like HSTS is not available in IIS prior to 10.0 version 1709, you may be able to configure it with a custom setup. There is [an external blog post](https://www.saotn.org/enable-htt
> Although it sounds like
> you may be able to

This does not sound confident when reading it. Please state whether it's available or not and if you are not, advise the user how to determine for themselves.

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Although it sounds like HSTS is not available in IIS prior to 10.0 version 1709, you may be able to configure it with a custom setup. There is [an external blog post](https://www.saotn.org/enable-htt
This blog post is 8 years old. Is it accurate and useful for IIS 10 on a later OS?

2023-09-28 11:45 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +In order to configure HSTS outside of IIS, you could use a reverse proxy and configure HSTS on the reverse proxy server. For instance nginx has an [article covering HSTS configuration](https://www.ng
Can we change this to be more specific than 'Outside of IIS' and be more 'Nginx and Apache'?

2023-09-28 15:59 UTC, corbob commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Chocolatey Central Management is hosted by an IIS server, and can make use of the features available in IIS. Below is some general information about how to enable HSTS with IIS. You can also make use
There's a typo here in the suggestion. Adding a comment to remind myself to come back and edit the commit to add an S.

2023-09-28 16:56 UTC, steviecoaster commented
The steps as outlined for IIS 10.0 are accurate and work correctly, though I really don't know what any of the settings mean, outside of "redirect http to https"

2023-09-28 17:39 UTC, corbob commented
> The steps as outlined for IIS 10.0 are accurate and work correctly, though I really don't know what any of the settings mean, outside of "redirect http to https"

@steviecoaster Should we consider linking directly to the table of attributes [here](https://learn.microsoft.com/en-us/iis/configuration/system.applicationhost/sites/site/hsts#attributes)?

2023-09-28 17:40 UTC, corbob commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Chocolatey Central Management is hosted by an IIS server, and can make use of the features available in IIS. Below is some general information about how to enable HSTS with IIS. You can also make use
I've edited the `S` into the commit. Re-resolving this conversation.

2023-09-28 17:41 UTC, corbob commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +Although it sounds like HSTS is not available in IIS prior to 10.0 version 1709, you may be able to configure it with a custom setup. There is [an external blog post](https://www.saotn.org/enable-htt
I've reworded this section and linked to the Microsoft article.

2023-09-28 17:41 UTC, corbob commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +In order to configure HSTS outside of IIS, you could use a reverse proxy and configure HSTS on the reverse proxy server. For instance nginx has an [article covering HSTS configuration](https://www.ng
I've updated the heading and adjusted the wording of the start of the line.

2023-09-29 11:46 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +If you are running IIS 10.0 version 1709 or later, you can enable HSTS using the `<hsts>` element of the `<site>` element. Microsoft has information as well as samples [here](https://learn.microsoft.
Okay, can you reword this then to say that if you're on later version and you don't have the GUI see the Microsoft samples?

2023-09-29 11:51 UTC, pauby requested changes
This is looking good. Apologies for missing these.

2023-09-29 11:51 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +### Enabling HSTS Within IIS Prior to IIS 10.0
```suggestion
### Enabling HSTS Prior to IIS 10.0 Version 1709
```

2023-09-29 11:51 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +### Enabling HSTS Within IIS Prior to IIS 10.0
I'm assuming from the text in this section, that the heading is correct?

2023-09-29 11:51 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +While HSTS is available natively within IIS 10.0 version 1709, it is [possible although complicated](https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-
```suggestion
While HSTS is available natively within IIS 10.0 version 1709, it is [possible](https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-1709-hsts#challenges-on-enabling-hsts-before-iis-100-version-1709) to use it with IIS prior to this version.
```

2023-09-29 11:51 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +While HSTS is available natively within IIS 10.0 version 1709, it is [possible although complicated](https://learn.microsoft.com/en-us/iis/get-started/whats-new-in-iis-10-version-1709/iis-10-version-
'complicated' is a relative term. We should only providing information and facts.

2023-09-29 11:51 UTC, pauby commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +While Chocolatey Central Management runs on IIS, you could use a reverse proxy and configure HSTS on the reverse proxy server. For instance NGINX has an [article covering HSTS configuration](https://
```suggestion
While Chocolatey Central Management runs on IIS, you could use a reverse proxy and configure HSTS on the reverse proxy server. For instance NGINX has an [article covering HSTS configuration](https://www.nginx.com/blog/http-strict-transport-security-hsts-and-nginx/), or you could use Apache and follow a guide such as [this one](https://www.simplified.guide/apache/enable-hsts).

We provide this information as a reference for enabling HSTS and you should evaluate and apply the necessary configuration for your environment. 
```

2023-10-16 19:07 UTC, corbob commented on input/en-us/guides/organizations/configure-chocolatey-central-management-with-hsts.md
> +If you are running IIS 10.0 version 1709 or later, you can enable HSTS using the `<hsts>` element of the `<site>` element. Microsoft has information as well as samples [here](https://learn.microsoft.
I had some troubles wrapping my head around the best way to reword this. I ended up settling on adding a blurb afterwards that links to the Microsoft page for how to configure it in that version.

2023-10-17 16:31 UTC, pauby commented
> Is "if you tick this box in IIS, the Central Management Web Interface still works" good enough? 😂

I think this is a good approach to this. This has already grown arms and legs and was only intended to be a light overview of what can be done!

2023-10-17 16:43 UTC, pauby requested changes
Missed one. Other than this I'm happy to merge this.

2023-10-17 17:48 UTC, pauby approved these changes

2023-10-17 17:49 UTC, merged

2023-10-17 17:49 UTC, pauby commented
@corbob awesome work! Thanks for your contribution!