Reword Execution Policy In Setup Commands
chocolatey/docs pull request #847
Opened 2023-09-27 22:25 UTC by ryanrichter94

## Description Of Changes
- Add additional documentation around setting your execution policy to allow installing Chocolatey
- Fix up this pages linting
- Add markdown rule specifying the use of backticks for declaring code blocks.

## Motivation and Context
Change to wording for execution policy was requested in #766 

## Testing

* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [X] Minor documentation fix (typos etc.).
* ~[ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* ~[ ] New documentation page added.~
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~
    * ~Issue #~

## Change Checklist

* ~[ ] Requires a change to menu structure (top or left hand side)~
* ~[ ] Menu structure has been updated~

## Related Issue

Fixes #766

2023-09-27 23:07 UTC, ferdnyc commented on input/en-us/choco/setup.md
> +With PowerShell, there is an additional step. You must ensure your execution policy. The below steps cover how to check and set this value with supporting documentation.
This should probably still say "You must ensure your execution policy is not `Restricted`.", no?

Alternatively, it could say something like:
* "You must check your execution policy."
* "You must ensure your execution policy permits web downloads."

You don't "ensure" a noun. You ensure that some condition holds, or some truth.

2023-09-27 23:07 UTC, ferdnyc commented on input/en-us/choco/setup.md
> +```
Not strictly related to this change, but there's more than a little irony in the docs claiming that

```powershell
[System.Net.ServicePointManager]::SecurityProtocol = 
[System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
iwr https://community.chocolatey.org/install.ps1 -UseBasicParsing | iex
```

is "a more terse command that is easier to remember", relative to:

```powershell
[System.Net.ServicePointManager]::SecurityProtocol = 
[System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
iex ((New-Object System.Net.WebClient).DownloadString(
'https://community.chocolatey.org/install.ps1'))
```

I suppose it's _technically_ true, but... `¯\_(ツ)_/¯`

2023-09-27 23:24 UTC, ferdnyc commented on input/en-us/choco/setup.md
> +```
I've created #848 for this issue.

2023-09-28 18:18 UTC, ryanrichter94 commented on input/en-us/choco/setup.md
> +```
Resolving this as issue created around it has since been closed.

2023-10-20 12:04 UTC, pauby requested changes

2023-10-20 12:04 UTC, pauby commented on input/en-us/choco/setup.md
> +- Install Chocolatey again.
```suggestion
- Install Chocolatey CLI again.

```

2023-10-20 12:04 UTC, pauby commented on input/en-us/choco/setup.md
> +> - community.chocolatey.org now requires TLS 1.2 at a minimum. Please see https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/.
```suggestion
> - community.chocolatey.org now requires TLS 1.2 at a minimum. Please see [this blog post](https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/) for more information.

```

2023-10-20 12:04 UTC, pauby commented on input/en-us/choco/setup.md
> +> - If your server is restricted to TLS 1.1+, you need to add additional logic to be able to download and install Chocolatey (this is not necessary when running Chocolatey normally as it does this au
```suggestion
> - If your server is restricted to TLS 1.1+, you need to add additional logic to be able to download and install Chocolatey CLI (this is not necessary when running Chocolatey CLI normally as it does this automatically).

```

2023-10-20 12:04 UTC, pauby commented on input/en-us/choco/setup.md
> +- .NET Framework 4.5
This is out of date and needs updating.

2023-10-20 12:04 UTC, pauby commented on input/en-us/choco/setup.md
>  ## Uninstalling Chocolatey
```suggestion
## Uninstalling Chocolatey CLI

```

2024-06-01 13:09 UTC, pauby commented
@ryanrichter94 are you looking to address the issues above or should we close this?

2024-07-17 04:00 UTC, closed without merging