Adds C4B-Ansible initial documentation
chocolatey/docs pull request #853
Opened 2023-10-02 11:18 UTC by JPRuskin

## Description Of Changes
This adds the (now quite cut down and externally reference heavy) C4B Ansible documentation. It's possible that instead of linking across to other C4B documentation, we should use stubs for the replicated sections.

## Motivation and Context
This adds documentation for deploying the C4B suite of products using Ansible, and the playbook we've written for that purpose.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* ~[ ] Minor documentation fix (typos etc.).~
* ~[ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* [x] New documentation page added.
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~
It may be a good idea to provide a quick video around this, but I don't think it's a priority for now.

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

Fixes #852

2023-10-02 18:02 UTC, steviecoaster commented on input/en-us/c4b-environments/ansible/index.md
> +| **Chocolatey Central Management** | https://\<FQDN\>/        | ccmadmin         |
I don't like this placeholder....seems like it could cause confusion.

2023-10-09 00:52 UTC, Windos requested changes

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +      ansible_host: db1
```suggestion
all:
  vars:
    ansible_user: ansibleuser
    ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          [...]
  hosts:
    ccm_server:
      ansible_host: chocoserver
    nexus_server:
      ansible_host: nexus
    jenkins_server:
      ansible_host: chocorunner
    database_server:
      ansible_host: db1
```

Fixing indentation.

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +### Configuring your Hosts
I don't think the instructions themselves should be included here, but given there are example inventories included that don't include any of the WinRM things that would enable Ansible to connect to the hosts, should we link to a resource about managing Windows hosts?

Main concern is someone comes into this thinking the examples are complete and then complain.

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +  [...]
There's been a lot of example Vault placeholders throughout, It may pay to add a note (with a link to the docs) about Ansible Vault. To a novice "$ANSIBLE_VAULT;1.1;AES256" doesn't really mean anything.

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +If you would prefer to create and maintain them from scratch, you can modify the values of the following secrets within the `/group_vars/all.yml` file:
Link to the file

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +> You can add the values to an inventory file or the playbook directly, instead of being prompted at runtime.
What are the variables? If putting them in the inventory... where? (all, specific host, etc?)

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +| **Chocolatey Central Management** | https://\<FQDN\>/        | ccmadmin         |
Agreed, maybe code blocking the `<FQDN>` would be enough?

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/client-setup.md
> +To install the Chocolatey components and on-board clients, you should run the `ClientSetup.ps1` script provided with your Chocolatey for Business Ansible Environment.
Where do I find the script? On the Ansible host, or in Nexus, or?

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/client-setup.md
> +xref: c4b-ansible-client-setup
Probably out of scope, but possibly for a part 2... client setup with Ansible? If I've got a fleet of servers to on-board and I've used Ansible to setup the server then chances are my go to will be Ansible for configuring the rest of the fleet too.

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/license-update.md
> +You can either run through the process manually, or run the C4B Ansible playbook with the `licensepackage` tag, providing it the path to your new license:
Reading this sentence it feels like there should be headings for "Ansible" vs "Manual" as it's not currently clear that if you run the ansible example, then your don't need to follow the other instructions. Also the other headings being at the same level as "Summary" is confusing (imo). so putting them under a common heading in general would make the document easier to parse in general.

2023-10-09 00:52 UTC, Windos commented on input/en-us/c4b-environments/ansible/index.md
> +For portions of this guide using Ansible, we will assume that you either have an Ansible Execution Environment preconfigured, or are using the dev container to execute the playbooks. You should have
```suggestion
For portions of this guide using Ansible, we will assume that you either have an Ansible Execution Environment preconfigured, or are using the devcontainer to execute the playbooks. You should have the latest supported version of the `Chocolatey.Chocolatey` Ansible collection installed, along with any additional prerequisites listed in the `requirements.txt`.
```

Other instances in this doc have devcontainer as a single word. Also, this may be a new concept to readers, maybe link to docs about what a devcontainer is?

2023-10-09 17:46 UTC, pauby requested changes
It ended pretty abruptly. I don't know if that was intentional.


Please don't use C4B or CCM or other acronyms when talking about products. Please use the full name.

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +* A valid certificate for your chosen FQDN, in PFX format, with exportable private key
```suggestion
* A Chocolatey for Business license, or Trial license.
* One or more existing virtual machines accessible to your Ansible host.
* The ability to create a CNAME DNS record for your chosen FQDN.
* A valid certificate for your chosen FQDN, in PFX format, with exportable private key.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +For portions of this guide using Ansible, we will assume that you either have an Ansible Execution Environment preconfigured, or are using the dev container to execute the playbooks. You should have
How do you install the collection and any other prerequisites in `requirements.txt`?

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +The Chocolatey for Business Ansible Environment is designed to deploy Chocolatey Central Management and all of our suggested complimentary softwares to one or more VMs within your environment, and pr
```suggestion
The Chocolatey For Business Ansible Environment is designed to deploy Chocolatey Central Management and all of our suggested complimentary software to one or more virtual machines within your environment, and provide methods for deploying the Chocolatey For Business to your other endpoints.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +The Chocolatey for Business Ansible Environment is designed to deploy Chocolatey Central Management and all of our suggested complimentary softwares to one or more VMs within your environment, and pr
```suggestion
The Chocolatey for Business Ansible Environment is designed to deploy Chocolatey Central Management and all the suggested software to one or more virtual machines within your environment, and provide methods for deploying Chocolatey for Business to your other endpoints.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +You can deploy the Chocolatey for Business Ansible Environment to a single VM, or several. There are four services being installed:
```suggestion
You can deploy the Chocolatey for Business Ansible Environment to one or more virtual machines. There are four services being installed:
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +You can deploy the Chocolatey for Business Ansible Environment to a single VM, or several. There are four services being installed:
Note that you called these 'components' earlier. You need to be consistent. Use 'service' or 'component' but not both.

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +* Nexus Repository OSS
```suggestion
* Sonatype Nexus Repository
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +You can specify a separate host for any of these, or specify an existing database, or a single host which will have everything deployed to it.
I think you should delete that line. You said above that they can be installed on multiple virtual machines. The rest of that line doesn't make sense to me.

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +#### Installing to a Single Host
```suggestion
#### Installing On a Single Host
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +To install to a single host, create a host with the title `ccm_server`. This will be the default host to install anything to. There is an example of a hosts file containing a single host in the root
```suggestion
To install on a single host, create a host with the title `ccm_server`. This will be the default host. There is an example of a hosts file containing a single host in the root of the repository - `hosts.yml`.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +#### Installing to Multiple Hosts
```suggestion
#### Installing On Multiple Hosts
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +To install to multiple hosts, define hosts with the following names:
```suggestion
To install on multiple hosts, define hosts with the following names:
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +* `nexus_server`: Nexus Repository OSS
```suggestion
* `nexus_server`: Sonatype Nexus Repository
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +If any are not defined, the service will be installed to the `ccm_server` host.
```suggestion
If any are not defined, the service will be installed on the `ccm_server` host.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +#### Using an existing Database
```suggestion
#### Using An Existing Database
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +You can provide an existing connection string to the environment to use for storing Chocolatey Central Management data. This can have significant benefits for performance, as well as simplifying back
```suggestion
You can provide a connection string to the environment to use for storing Chocolatey Central Management data. This can have significant benefits for performance, as well as simplifying backups and load-balancing of instances.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +To use an existing database, follow the instructions for preparing it in [creating a database](xref:ccm-database) and provide the connection string when prompted by the playbook.
That doesn't make sense to read. If you have an existing database, follow the instructions for creating a database?

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +This will result in the specified packages (assuming there is a package with a matching ID on the Chocolatey Community Repository) being internalized and available on your environment.
```suggestion
This will result in packages matching the ID's being internalized from the Chocolatey Community Repository.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +### Configuring CCM
```suggestion
### Configuring Chocolatey Central Management
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +> You cannot create users in CCM until you have configured an SMTP server. To do this, please see [how to configure SMTP in CCM](xref:ccm-website#step-4.2-smtp-configuration).
```suggestion
> You cannot create users in Chocolatey Central Management until you have configured an SMTP server. To do this, please see [how to configure SMTP](xref:ccm-website#step-4.2-smtp-configuration).
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +> You can log in to CCM using the credentials provided in the credentials document (see [Accessing Services](#accessing-services), below).
```suggestion
> You can log in to Chocolatey Central Management using the credentials provided in the credentials document (see [Accessing Services](#accessing-services), below).
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +At this point, your environment should be deployed. You should be able to access the following services:
```suggestion
At this point, the Chocolatey for Business Ansible Environment should be deployed with the following acessible services:
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +| **Sonatype Nexus**                | https://\<FQDN\>/nexus   | admin            |
```suggestion
| **Sonatype Nexus Repository**     | https://\<FQDN\>/nexus   | admin            |
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +Passwords to log in to the services have been stored in the credentials directory within the root of the c4b-ansible repository.
```suggestion
Passwords to login to the services have been stored in the credentials directory within the root of the `c4b-ansible repository`.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +* Must have a password
```suggestion
* Needs to be in the PFX format.
* Needs to include an exportable Private Key.
* Must have a password.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +1. Run code similar to the following, modifying the filepath if necessary:
```suggestion
1. Run code similar to the following, modifying the `-FilePath` parameter if necessary:
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +$Cert | Export-PfxCertificate -FilePath ~\Desktop\$($Domain).pfx -Password $Password
```suggestion
$Cert | Export-PfxCertificate -FilePath $($Domain).pfx -Password $Password
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +$Cert | Export-PfxCertificate -FilePath ~\Desktop\$($Domain).pfx -Password $Password
Would it not be better just using the current directory rather than a folder off home?

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +> Your browser will display warnings when accessing the Chocolatey for Business Ansible Environment sites with a self-signed certificate. To stop these warnings, you need to import this certificate t
```suggestion
> Your browser will display warnings when accessing the Chocolatey for Business Ansible Environment sites with a self-signed certificate. To stop these warnings, you need to import this certificate to the `Trusted Root Certification Authorities` store on any computers used to access the services. Unless you know what you're doing, we would strongly recommend using a certificate from a CA like LetsEncrypt.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +#### Purchased/Acquired Certificates from CA
```suggestion
#### Purchased/Acquired Certificates From a Certificate Authority
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +Though we have made strides in improving this situation, if you see a similar failure you may need to login to the machine with RDP and re-run the playbook. It should then succeed.
```suggestion
This can be resolved by a login to the computer using RDP and re-running the playbook.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +### Timeout when downloading Jenkins Plugins
```suggestion
### Timeout When Downloading Jenkins Plugins
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +Due to the large amount of Jenkins plugins, we have seen this area fail the playbook due to timeouts depending on the reliability of the host connection. Rerunning the playbook after this failure sho
```suggestion
Sometimes the downloading of Jenkins plugins times out. Rerunning the playbook again should complete this.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +You can either run through the process manually, or run the C4B Ansible playbook with the `licensepackage` tag, providing it the path to your new license:
```suggestion
You can either run through the process manually, or run the Chocolatey for Business Ansible playbook with the `licensepackage` tag, providing it the path to your new license:
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +- You will need the API Key for your Nexus repository.
```suggestion
- You will need the FQDN of your Sonatype Nexus Repository computer.
- You will need the API Key for your Sonatype Nexus Repository.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +Please refer to [the C4B-Azure documentation](xref:c4b-azure-license-update#creating-a-new-license-package) for creating the license package.
```suggestion
Please refer to [the Chocolatey for Business Azure Environment documentation](xref:c4b-azure-license-update#creating-a-new-license-package) for creating the license package.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +We now need to upload this new package to the Nexus repository. Open a PowerShell window and run the following code (which will prompt you for information for values are not set):
```suggestion
We now need to upload this new package to the Sonatype Nexus Repository. Open a PowerShell window and run the following code (which will prompt you for values that are not set):
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +## Pushing the New License to Nodes
```suggestion
## Pushing the New License to Your Client Computers
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +You can either rely on automation to push this package (and updated license) to your nodes, or refer to [these documents](xref:ccm-deployments) to trigger a deployment manually.
```suggestion
You can either rely on automation to push this package (and updated license) to your client computers, or refer to [these documents](xref:ccm-deployments) to manually create a deployment.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +### Configuring your Hosts
```suggestion
### Configuring Your Hosts
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/offline-deployment.md
> +## Requirements
```suggestion
##  Prerequisites
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/offline-deployment.md
> +## Requirements
Everywhere else it said this, so being consistent.

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/offline-deployment.md
> +- A compatible PFX certificate to use for your deployment
```suggestion
- A Windows computer capable of running Chocolatey CLI.
- An internet connection.
- PowerShell 5.0+.
- A Chocolatey for Business license or Trial license.
- A compatible PFX certificate to use for your deployment.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/offline-deployment.md
> +1. To begin, download or clone the C4B-Ansible repository to your local machine.
```suggestion
1. To begin, download or clone the `c4b-ansible` repository to your local machine.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/offline-deployment.md
> +1. Open a PowerShell terminal and navigate to the repository directory.
```suggestion
1. Open a PowerShell terminal and navigate to the repository directory you downloaded the files to, above.
```

2023-10-09 17:46 UTC, pauby commented on input/en-us/c4b-environments/ansible/offline-deployment.md
> +        If you do not provide it, you will be prompted to enter it securely.
```suggestion
    a. `-LicensePath`: The path to your Chocolatey license file, if it's not installed in the default location.
    a. `-CertificatePath`: The path to your PFX certificate.
    a. `-CertificatePassword`: A `SecureString` of your PFX certificate password.
        If you do not provide it, you will be prompted to enter it securely.
```

2023-10-12 13:40 UTC, steviecoaster commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `ccm_client_salt`: This is the client-side salt additive. More information about this can be found in the [C4B Config Settings](xref:ccm-client#config-settings) docs. The value will have been provi
On the docs site, we have a Chocolatey For Business environment drop down, which houses the docs for our Azure marketplace image "environment", as well as the Quick Start guide "environment". I think we need to be consistent and consider this our "Ansible environment". The environment being "the complete collection of services to get the most out of your Chocolatey For Business installation".

2023-10-12 13:41 UTC, steviecoaster commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `ccm_service_salt`: This is the service salt additive. More information about this can be found in the [C4B Config Settings](xref:ccm-client#config-settings) docs. The value will have been provided
Same comment from above here.

2023-10-16 10:12 UTC, JPRuskin commented on input/en-us/c4b-environments/ansible/license-update.md
> +- You will need the API Key for your Nexus repository.
I'd like to quickly think out loud around our preferred nomenclature for the broadest term for "something you can install to", as I'm unsure computer makes sense here (in that it's too restrictive).

To me, a computer is a physical box. A machine can be virtual, but makes most sense if explicitly defined as such. A host or node can be any of the above without specifying (and can even refer to a SAAS URI, in my eyes)  - so I prefer those terms. I'll admit I haven't shown a strong preference, there, but did think "nodes" was how we referred to things-that-install-C4B-components-to, at least in terms of licensing.

2023-10-17 17:12 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `ccm_client_salt`: This is the client-side salt additive. More information about this can be found in the [C4B Config Settings](xref:ccm-client#config-settings) docs. The value will have been provi
So that would be:

> The value will have been provided during the deployment of the Chocolatey for Business Ansible environment.

Or

> The value will have been provided during the Ansible deployment of the Chocolatey for Business environment.

I prefer the last one?

2023-10-17 17:12 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `ccm_service_salt`: This is the service salt additive. More information about this can be found in the [C4B Config Settings](xref:ccm-client#config-settings) docs. The value will have been provided
Same options as above.

Same preference as above. :smile:

2023-10-17 17:22 UTC, pauby requested changes

2023-10-17 17:22 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +Description: How to setup a client machine to use Chocolatey for Business Ansible Environment
```suggestion
Description: How to Setup a Client Machine to Use the Chocolatey for Business Ansible Environment
```

2023-10-17 17:22 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +1. Ensure the client machine can access the Chocolatey Central Management instance on port 24020, and the Sonatype Nexus instance on 8443 (by default).
```suggestion
1. Ensure the client computer can access the Chocolatey Central Management instance on port 24020, and the Sonatype Nexus instance on 8443 (by default).
```

2023-10-17 17:22 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +Once you have your environment deployed, you'll need to get clients talking to it.
Should we say 'Ansible environment' here? I only ask to be consistent, but I'm fine either.

2023-10-17 17:22 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `ccm_client_salt`: This is the client-side salt additive. More information about this can be found in the [C4B Config Settings](xref:ccm-client#config-settings) docs. The value will have been provi
Something I meant to say here. We are consistently using Chocolatey for Business (note the non-capitalized 'for').  So we should use it throughout. I am happy whichever we do it, but we just need to be consistent.

2023-10-17 17:43 UTC, pauby requested changes
I missed a few things but this is looking pretty good now!

2023-10-17 17:43 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `chocouser_password`: The password for the `chocouser` account which is used by the client to access your environments' Sonatype Nexus service. The value will have been provided during the deployme
```suggestion
* `chocouser_password`: The password for the `chocouser` account which is used by the client to access your environments' Sonatype Nexus service. The value will have been provided during the deployment of the Chocolatey for Business environment.
```

2023-10-17 17:43 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +* `chocouser_password`: The password for the `chocouser` account which is used by the client to access your environments' Sonatype Nexus service. The value will have been provided during the deployme
See above comments as this may affect what we put here.

2023-10-17 17:43 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +You can deploy this using Ansible Automation Platform, an existing installation of the Ansible client, or the dev container image provided within the repository (as well as a variety of other methods
```suggestion
You can deploy this using Ansible Automation Platform, an existing installation of the Ansible client, or the dev container image provided within the repository (as well as a variety of other methods).
```

2023-10-17 17:43 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +If you would prefer to create and maintain them from scratch, you can modify the values of the following secrets within the [/group_vars/all.yml](https://github.com/chocolatey/c4b-ansible/blob/main/g
```suggestion
If you would prefer to create and maintain them from scratch, you can modify the values of the following secrets within the [`/group_vars/all.yml`](https://github.com/chocolatey/c4b-ansible/blob/main/group_vars/all.yml) file:
```

2023-10-17 17:43 UTC, pauby commented on input/en-us/c4b-environments/ansible/index.md
> +> Your browser will display warnings when accessing the Chocolatey for Business Ansible Environment sites with a self-signed certificate. To stop these warnings, you need to import this certificate t
```suggestion
> Your browser will display warnings when accessing the Chocolatey for Business Ansible Environment sites with a self-signed certificate. To stop these warnings, you need to import this certificate to the `Trusted Root Certification Authorities` store on any computers used to access the services. Unless you know what you're doing, we would strongly recommend using a certificate from a CA like [LetsEncrypt](https://letsencrypt.org/).
```

2023-10-17 17:43 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +Description: How to update the license in use on your Chocolatey for Business Ansible Environment
```suggestion
Description: How to Update the License in Use on Your Chocolatey for Business Ansible Environment
```

2023-10-17 17:57 UTC, JPRuskin commented
> I missed a few things but this is looking pretty good now!

Getting closer! 😅

2023-10-18 11:23 UTC, JPRuskin commented on input/en-us/c4b-environments/ansible/client-setup.md
> +Once you have your environment deployed, you'll need to get clients talking to it.
To me, "ansible environment" doesn't make sense in this context (I'm not meaning The Product, here, and an ansible environment to me says AWX or a runner). I'll make sure I'm consistent with "environment" when not referring to the full titled product itself, "Chocolatey for Business Ansible Environment".

2023-10-18 11:29 UTC, JPRuskin commented on input/en-us/c4b-environments/ansible/license-update.md
> +- You will need the API Key for your Nexus repository.
@pauby As you've requested `computer` in another area, I figured I'd ping you on this. Is computer the best term to use?

2023-10-18 11:38 UTC, JPRuskin commented on input/en-us/c4b-environments/ansible/client-setup.md
> +When you're ready, run the following script on the client from an elevated (Run as Administrator) PowerShell console:
@pauby Another thing for brief thought?

2023-10-18 12:03 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +Once you have your environment deployed, you'll need to get clients talking to it.
> 'Once you have your environment deployed'.

If you don't mean the Ansible environment, what environment are you referring to here?

2023-10-18 12:08 UTC, pauby commented on input/en-us/c4b-environments/ansible/license-update.md
> +- You will need the API Key for your Nexus repository.
But we frequently use computer, machine, device, node and a whole host other names all for the same thing. Client / server may be the best choice here, and server maybe the best choice in general. Client / server is a known architecture type, everybody knows what you mean by it and it's something that simply 'serves' clients. 

I don't think machine is the best term to use. A car is technically a machine. 

We need to pick one terminology and stick with it throughout our docs. It might be an idea to define it here and get it updated for our design docs.

To save a lot of back and forth, do we agree 'client', 'server' and 'virtual machine' are the best terms to use?

2023-10-18 12:13 UTC, pauby commented on input/en-us/c4b-environments/ansible/client-setup.md
> +When you're ready, run the following script on the client from an elevated (Run as Administrator) PowerShell console:
I would disagree you can elevate a shell, terminal or console. They are all tools. A shell is something that runs that you interact with. You can't elevate _it_. You can elevate _inside of it_. The same with terminal and console. A Terminal and console are something you interact with and is the tool you use to do that. You can't elevate them. 

You can, however, elevate a session within a shell running in a terminal or console. But those are, in my mind, strictly correct. People use these words interchangeably. I am trying to eliminate confusion and ensure we are consistent.

If it's something that the reader would immediately understand, then I don't think it really matters **as long as we are consistent**.

2023-10-20 13:10 UTC, steviecoaster submitted a review, later dismissed

2023-10-20 13:11 UTC, steviecoaster commented
@pauby I _think_ all outstanding are resolved. If you're happy with this, I can get it merged.

2023-10-20 14:31 UTC, steviecoaster commented
@pauby ignore me. I totally was reading those items wrong. I see now they're _suggestions_ and not actual commited changes! I......need a nap :joy:

2023-10-20 17:02 UTC, steviecoaster commented
@JPRuskin I'm not sure what's goin on here, but it looks like changes you've said are done actually aren't? Might I suggest individual commits instead of force pushes we can keep things straight? We can rebase when everyone is happy before merging. I know I'm personally having an impossible time keeping this all straight now.

2023-10-25 14:54 UTC, steviecoaster approved these changes

2023-10-25 15:09 UTC, steviecoaster approved these changes

2023-10-25 19:47 UTC, steviecoaster commented
@JPRuskin I put this in draft so we can't do anything with it until the ansible stuff is ready to go. Don't want an oopsie.

2023-11-17 16:06 UTC, steviecoaster approved these changes

2023-11-17 16:06 UTC, merged