#292 Correct broken link in install instructions page that returns 404
chocolatey/docs pull request #860
Opened 2023-10-22 15:17 UTC by LeaDevelop

## Description Of Changes
Link in the instruction text pointed to: `https://docs.chocolatey.org/en-us/choco/installation` which caused 404
Correction of url was done: `https://docs.chocolatey.org/en-us/choco/setup`

To verify change you find it in the _Option 2 - Updated PowerShell and .NET_ section of Setup/Install documnetation
```
try {
  # Set TLS 1.2 (3072) as that is the minimum required by Chocolatey.org
  # Use integers because the enumeration value for TLS 1.2 won't exist
  # in .NET 4.0, even though they are addressable if .NET 4.5+ is
  # installed (.NET 4.5 is an in-place upgrade).
  [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
} catch {
  Write-Warning 'Unable to set PowerShell to use TLS 1.2. This is required for contacting Chocolatey as of 03 FEB 2020. https://blog.chocolatey.org/2020/01/remove-support-for-old-tls-versions/. If you see underlying connection closed or trust errors, you may need to do one or more of the following: (1) upgrade to .NET Framework 4.5+ and PowerShell v3+, (2) Call [System.Net.ServicePointManager]::SecurityProtocol = 3072; in PowerShell prior to attempting installation, (3) specify internal Chocolatey package location (set $env:chocolateyDownloadUrl prior to install or host the package internally), (4) use the Download + PowerShell method of install. See https://docs.chocolatey.org/en-us/choco/installation for all install options.'
}

iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
```

## Motivation and Context
Resolved pointed issue in https://github.com/chocolatey/docs/issues/292. Installation instructions currently send user to page that doesn't help them out.
![2023-10-22 15_53_55-Lea](https://github.com/chocolatey/docs/assets/104503492/2439a01b-0107-4323-ac8d-08a19c7e53e0)
## Testing
* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.
![2023-10-22 16_13_09-Lea](https://github.com/chocolatey/docs/assets/104503492/1228eb50-3524-4fbc-8e64-c9b42948039f)

## Change Types Made
* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist
* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
Fixes https://github.com/chocolatey/docs/issues/292

2023-10-23 15:02 UTC, corbob requested changes
Thank you for this PR @LeaDevelop. Overall it looks good. There are a few things we'd like to adjust with it that you wouldn't have known about. If you are in a position to get these changes done, we'd appreciate it, but if you're not they are little things that we also can get fixed up for you:

- It's no where near your changes here, so GitHub won't let me put the suggestion in. Instead I'll add it here: To ensure that any existing scripts with this URL embedded in them will work, we'd like to add another `RedirectedFrom` to this file. Could you update the preamble and add a new line after line 8 to include: `- en-us/choco/setup`?
- As well, would you mind rewording your commit message to line up with https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#prepare-commits? In particular, the message itself is ever so slightly too long, and the issue number should be wrapped in parens.

2023-10-25 17:10 UTC, LeaDevelop commented
> Thank you for this PR @LeaDevelop. Overall it looks good. There are a few things we'd like to adjust with it that you wouldn't have known about. If you are in a position to get these changes done, we'd appreciate it, but if you're not they are little things that we also can get fixed up for you:
> 
>     * It's no where near your changes here, so GitHub won't let me put the suggestion in. Instead I'll add it here: To ensure that any existing scripts with this URL embedded in them will work, we'd like to add another `RedirectedFrom` to this file. Could you update the preamble and add a new line after line 8 to include: `- en-us/choco/setup`?
> 
>     * As well, would you mind rewording your commit message to line up with https://github.com/chocolatey/choco/blob/develop/CONTRIBUTING.md#prepare-commits? In particular, the message itself is ever so slightly too long, and the issue number should be wrapped in parens.

Sure can do, will take care of it in next 2 days 👍🏻

2023-10-25 17:52 UTC, LeaDevelop commented
Done both requested corrections and pull request title edit - made sure id is in between `()`

2024-01-26 17:38 UTC, corbob approved these changes

2024-01-26 17:40 UTC, corbob commented
Thanks for getting this fixed up @LeaDevelop. My apologies for taking so long to review it. I also noticed today when merging it that I had inadvertently requested the wrong RedirectFrom. So I got that fixed up.

I also rebased against master which eliminates the merge commits as they're not needed here.

2024-01-26 17:45 UTC, merged