(#862) Deployment to upgrade all Software
chocolatey/docs pull request #865
Opened 2023-10-27 20:49 UTC by st3phhays

## Description Of Changes
This adds documentation on how to upgrade all Software with an automatic Deployment Plan.

## Motivation and Context
This reflects changes made in Chocolatey Central Management 0.12.0

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
* #862

2023-10-30 11:13 UTC, AdmiringWorm requested changes
The referenced images are not included, until they are, this PR cannot be approved.

2023-10-30 11:13 UTC, AdmiringWorm commented on input/en-us/central-management/usage/website/software.md
> +Each Deployment Step will a Temporary Group that contains all the Computers the Software is currently installed on.
```suggestion
Each Deployment Step will create a Temporary Group that contains all the Computers the Software is currently installed on.
```

2023-10-30 13:34 UTC, st3phhays commented on input/en-us/central-management/usage/website/software.md
> +Each Deployment Step will a Temporary Group that contains all the Computers the Software is currently installed on.
This has been updated.

2023-10-30 15:07 UTC, st3phhays commented
> The referenced images are not included, until they are, this PR cannot be approved.

I have tracked the images that need updated.

2023-10-31 20:04 UTC, vexx32 approved these changes
Apart from the images that will need to be added later, this looks good :3

2023-11-27 15:42 UTC, AdmiringWorm approved these changes
LGTM

2023-11-27 18:48 UTC, corbob submitted a review, later dismissed

2023-11-28 12:58 UTC, gep13 requested changes

2023-11-28 12:58 UTC, gep13 commented on input/en-us/central-management/usage/website/software.md
> +![Button to upgrade all outdated Software from the Software main page](/assets/images/software/ccm-software-details-upgrade-all-software.png)
```suggestion
![Button to upgrade all outdated Software from the Software main page](/assets/images/software/ccm-software-upgrade-all-software.png)
```

2023-11-28 13:42 UTC, st3phhays commented on input/en-us/central-management/usage/website/software.md
> +![Button to upgrade all outdated Software from the Software main page](/assets/images/software/ccm-software-details-upgrade-all-software.png)
This has been fixed.

2023-11-28 13:56 UTC, gep13 requested changes

2023-11-28 13:56 UTC, gep13 commented on input/en-us/central-management/usage/website/software.md
> +From the Software main page in Chocolatey Central Management, click the **Create New Deployment Plan** button and select the **Upgrade Outdated Software** option.
```suggestion
From the Software main page, click the **Create New Deployment Plan** button and select the **Upgrade Outdated Software** option.
```

2023-11-29 09:37 UTC, AdmiringWorm approved these changes
LGTM

2023-11-29 13:20 UTC, gep13 approved these changes
LGTM!

2023-11-29 13:26 UTC, merged