(#862) Create a Deployment Plan from Group
chocolatey/docs pull request #866
Opened 2023-10-31 16:16 UTC by st3phhays

## Description Of Changes
This adds documentation on how to create a Deployment Plan directly from a Group.

## Motivation and Context
This adds new documentation to reflect Chocolatey Central Management 0.12.0

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
* #862

2023-10-31 16:20 UTC, st3phhays commented
Images needed have been tracked so they can be added later.

2023-10-31 20:17 UTC, vexx32 submitted a review, later dismissed
This one looks good to me as well :3

2023-11-01 07:30 UTC, gep13 commented on input/en-us/central-management/usage/website/groups.md
> +After adding a script command to the Deployment Step, the Deployment Plan can deployed as outlined in the [Deployment Plans documentation](xref:ccm-deployments).
```suggestion
After adding a script command to the Deployment Step, the Deployment Plan can be deployed as outlined in the [Deployment Plans documentation](xref:ccm-deployments).
```

2023-11-01 07:33 UTC, gep13 requested changes
Just a minor tweak, otherwise, this looks good to me!

2023-11-01 13:10 UTC, st3phhays commented on input/en-us/central-management/usage/website/groups.md
> +After adding a script command to the Deployment Step, the Deployment Plan can deployed as outlined in the [Deployment Plans documentation](xref:ccm-deployments).
This has been fixed.

2023-11-28 13:48 UTC, st3phhays commented on input/en-us/central-management/usage/website/groups.md
> +1. From the Group Details page in Chocolatey Central Management, click the **Create New Deployment Plan** button and select the **Draft Deployment Plan** option.
This has been fixed.

2023-11-28 13:52 UTC, gep13 approved these changes
LGTM!

2023-11-29 13:45 UTC, gep13 approved these changes
LGTM!

2023-11-29 13:52 UTC, merged