(#862) Draft Deployment Plan from Computer
chocolatey/docs pull request #867
Opened 2023-10-31 18:19 UTC by st3phhays

## Description Of Changes
This adds documentation on how to create a new draft Deployment Plan for a Computer. A new section has been added to the Computers page.

## Motivation and Context
This reflects changes made in Chocolatey Central Management 0.12.0.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
#862

2023-10-31 18:34 UTC, st3phhays commented
Images needed for this have been tracked.

2023-10-31 20:26 UTC, vexx32 submitted a review, later dismissed
This one looks good to me once the images are in, great work!

2023-10-31 20:37 UTC, vexx32 approved these changes

2023-11-01 07:28 UTC, gep13 commented on input/en-us/central-management/usage/website/computers.md
> +After adding a script command to the Deployment Step, the Deployment Plan can deployed as outlined in the [Deployment Plans documentation](xref:ccm-deployments).
```suggestion
After adding a script command to the Deployment Step, the Deployment Plan can be deployed as outlined in the [Deployment Plans documentation](xref:ccm-deployments).
```

2023-11-01 07:33 UTC, gep13 requested changes
Just a minor tweak, otherwise, this looks good to me!

2023-11-01 13:07 UTC, st3phhays commented on input/en-us/central-management/usage/website/computers.md
> +After adding a script command to the Deployment Step, the Deployment Plan can deployed as outlined in the [Deployment Plans documentation](xref:ccm-deployments).
This has been fixed.

2023-11-28 14:38 UTC, gep13 requested changes

2023-11-29 09:28 UTC, AdmiringWorm commented on input/en-us/central-management/usage/website/computers.md
> +1. From the Computer Details page in Chocolatey Central Management, click the **Create New Deployment Plan** button and select the **Draft Deployment Plan** option.
I have updated this PR with this change.

2023-11-29 13:32 UTC, gep13 approved these changes
LGTM!

2023-11-29 13:40 UTC, merged