(#862) Deployment Computer All software
chocolatey/docs pull request #868
Opened 2023-10-31 18:50 UTC by st3phhays

## Description Of Changes
This documents the process of upgrading all outdated Software on a single computer. This can be done from the Computers page as well as the Computer Details page.

## Motivation and Context
This is new documentation as part of Chocolatey Central Management 0.12.0.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue
* #862

2023-10-31 18:55 UTC, st3phhays commented
Images needed for this have been tracked.

2023-11-01 07:34 UTC, gep13 submitted a review, later dismissed
LGTM!

2023-11-27 16:43 UTC, AdmiringWorm commented
I have updated this PR to be based on #877 for temporary groups, and updated the mention of Temporary Groups to link to this section of the Groups Page.

2023-11-28 14:40 UTC, gep13 requested changes

2023-11-28 14:40 UTC, gep13 commented on input/en-us/central-management/usage/website/computers.md
> +1. From the Computer Details page in Chocolatey Central Management, click the **Create New Deployment Plan** button and select the **Upgrade Outdated Software** option.
```suggestion
1. From the Computer Details page, click the :gear: **Actions** button and select the **Upgrade Outdated Software** option.
```

2023-11-29 09:30 UTC, AdmiringWorm commented on input/en-us/central-management/usage/website/computers.md
> +1. From the Computer Details page in Chocolatey Central Management, click the **Create New Deployment Plan** button and select the **Upgrade Outdated Software** option.
I have updated this PR with this change.

2023-11-29 13:57 UTC, gep13 approved these changes
LGTM!

2023-11-29 14:09 UTC, merged