(#862) Add documentation about Temporary Groups
chocolatey/docs pull request #877
Opened 2023-11-10 14:16 UTC by AdmiringWorm

## Description Of Changes

This adds some information about what a Temporary Group is,
what the intention for such a group is, and where this Group will
be visible.

## Motivation and Context

To Document Temporary Groups.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

~* [ ] Minor documentation fix (typos etc.).~
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
~* [ ] New documentation page added.~

## Change Checklist

~* [ ] Requires a change to menu structure (top or left hand side)/~
~* [ ] Menu structure has been updated~

## Related Issue

Reference #862

2023-11-10 14:17 UTC, AdmiringWorm commented
@st3phhays you may want to update the Automatic Deployment Plan documentation to reference this section of the Group Page, at least on those you have mentioned Temporary Groups.

2023-11-27 16:04 UTC, gep13 requested changes

2023-11-27 16:04 UTC, gep13 commented on input/en-us/central-management/usage/website/groups.md
> +A Temporary Group can also not be Edited, Deleted or Duplicated manually by a user, as well as no other Group can have such a Group as a Sub/Child Group.
```suggestion
A Temporary Group can also not be Edited, Deleted or Duplicated manually by a user, as well as no other Group can have such a Group as a Sub-Group.
```

We refer to this as a Sub-Group elsewhere, so let's stick with that.

2023-11-27 18:53 UTC, corbob requested changes

2023-11-27 18:53 UTC, corbob commented on input/en-us/central-management/usage/website/groups.md
> +A Temporary Group can also not be Edited, Deleted or Duplicated manually by a user, as well as no other Group can have such a Group as a Sub-Group.
```suggestion
A Temporary Group can also not be Edited, Deleted, or Duplicated manually by a user. As well, no other Group can have such a Group as a Sub-Group.
```
Just a minor grammar fixup I think.

2023-11-29 10:35 UTC, gep13 approved these changes
LGTM!

2023-11-29 10:44 UTC, merged