(#889) Add script package tutorial
chocolatey/docs pull request #890
Opened 2023-11-20 18:16 UTC by steviecoaster

## Description Of Changes

Adds a tutorial for creating a script-type Chocolatey Package

## Motivation and Context

Making documentation for creating different types of packaging approachable is important to our end users.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #889

2023-11-27 10:04 UTC, gep13 requested changes

2023-11-27 10:04 UTC, gep13 commented on input/en-us/guides/create/create-script-package.md
> +3. Type `Chocolatey:` and select `Create new Chocolatey package` from the list of available commands
Am I right in saying that you are going to mention the installation of the Chocolatey VSCode extension in the `Preparing Your Environment for Package Creation` link?

2023-11-27 10:04 UTC, gep13 commented on input/en-us/guides/create/create-script-package.md
> +The `choco pack` is used to compile your Chocolatey package into a nupkg file.
Not sure which way round is better, but I think something needs to change here..

```suggestion
The `choco pack` command is used to compile your Chocolatey package into a nupkg file.
```

```suggestion
`choco pack` is used to compile your Chocolatey package into a nupkg file.
```

2023-11-27 13:20 UTC, pauby requested changes

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +2. Press `Ctrl+Shift+P` or select View > Command Palette
```suggestion
2. Press `Ctrl+Shift+P` or select **View** > **Command Palette**.
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +1. Open the tutorials folder in VSCode
```suggestion
1. Open the tutorials folder in VSCode.
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +5. Select `Default Template` when prompted
```suggestion
4. Give your package a name, e.g. `script-package`.
5. Select `Default Template` when prompted.
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +Our simple example here doesn't require anything special for an upgrade or uninstall scenario. In the VSCode explorer window find both the `chocolateyBeforeModify.ps1` and `chocolateyUninstall.ps1` f
```suggestion
Our simple example here doesn't require anything special for an upgrade or uninstall scenario. In the VSCode Explorer window find both the `chocolateyBeforeModify.ps1` and `chocolateyUninstall.ps1` files and remove them.
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +### Creating Your Nuspec File
```suggestion
### Creating The Package Metadata
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +### Creating Your Nuspec File
I feel the terms we use, nupkg and nuspec, don't heop make things easier for peopel to understand. They sound very complex, acronyms and technical. So this is my suggestion to help with that.

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +The nuspec file is the metadata for your package. It provides information to Chocolatey such as:
```suggestion
The package metadata is stored in a file with a `.nuspec`extension. It provides information to Chocolatey such as:
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +The nuspec file is the metadata for your package. It provides information to Chocolatey such as:
This is just a follow-on from the above.

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +You can find information on nuspec requirements in our [Package Validator Rules](http://localhost:5080/en-us/community-repository/moderation/package-validator/rules/#requirements) documentation.
```suggestion
You can find information on package metadata requirements in our [Package Validator Rules](http://localhost:5080/en-us/community-repository/moderation/package-validator/rules/#requirements documentation.
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +You can find information on nuspec requirements in our [Package Validator Rules](http://localhost:5080/en-us/community-repository/moderation/package-validator/rules/#requirements) documentation.
Following on from above. Also note the URL above is wrong (localhost?). I haven't fixed it as you'll likely need to use the xref for it.

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +Replace the contents of the nuspec file with the following:
```suggestion
In the VS Code Explorer window, find and open the `embedded-zip.nuspec` file.

Replace the contents of the file with the following:
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +The `choco pack` is used to compile your Chocolatey package into a nupkg file.
```suggestion
The `choco pack` is used to compile your package files into a usable Chocolatey package.
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +1. In VSCode press `ctrl+shift+p` or `View > Command Pallete`
```suggestion
1. In VSCode press `Ctrl+Shift+P` or **View** > **Command Pallete**
```

2023-11-27 13:20 UTC, pauby commented on input/en-us/guides/create/create-script-package.md
> +4. In the `additional arguments` dialog enter `--output-directory='C:\tutorials'` and press `Enter`
```suggestion
4. In the **Additional arguments** dialog enter `--output-directory='C:\tutorials'` and press `Enter`.
```

2023-11-28 14:48 UTC, steviecoaster commented on input/en-us/guides/create/create-script-package.md
> +3. Type `Chocolatey:` and select `Create new Chocolatey package` from the list of available commands
Yes, Preparing your environment covers the installation of VSCode and all the needed extensions.

2023-12-07 12:09 UTC, pauby commented
@steviecoaster I've made a couple of tweaks to this including renaming the script file (to make it clearer what it's for). Can you check and approve? I can merge.

2023-12-08 15:10 UTC, pauby approved these changes

2023-12-08 15:20 UTC, merged