Fill out the Reports page
chocolatey/docs pull request #891
Opened 2023-11-21 21:26 UTC by vexx32

## Description Of Changes

Add in some details about the Reports pages in CCM.

Note: This still requires some images to be added. I will add these to our tracking for when we do the images pass.

## Motivation and Context

Filling out some of the missing info in docs.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left hand side)/
* [ ] Menu structure has been updated

## Related Issue

- #862

2023-11-21 22:15 UTC, corbob requested changes

2023-11-21 22:15 UTC, corbob commented on input/en-us/central-management/usage/website/reports.md
> +The Deployment Plans report displays all completed Deployment Plans, and allows you to search for a subset of DeploymentPlans or adjust the sorting order, or filter the displayed reports by their fin
This feels a little clunky. I'm not sure if a semi-colon will help, or if perhaps it should be separated into two sentences?

```suggestion
The Deployment Plans report displays all completed Deployment Plans; it allows you to search for a subset of DeploymentPlans, adjust the sorting order, or filter the displayed reports by their final Status.
```

2023-11-22 10:10 UTC, gep13 commented
@vexx32 can you update the commit in this PR to reference the #862 issue? That is where we are tracking all this work.

2023-11-22 12:57 UTC, vexx32 commented on input/en-us/central-management/usage/website/reports.md
> +The Deployment Plans report displays all completed Deployment Plans, and allows you to search for a subset of DeploymentPlans or adjust the sorting order, or filter the displayed reports by their fin
I opted for splitting the sentence here, thank you!

2023-11-22 12:58 UTC, vexx32 commented
@gep13 @corbob I think I've addressed both of those, thank you for looking it over! :3

2023-11-27 15:32 UTC, AdmiringWorm commented
@corbob or @gep13, can you have another look over to ensure that the changes you wanted have been added?

2023-11-27 15:42 UTC, gep13 commented
@AdmiringWorm I have some local changes to this PR that have been made based on a conversation with @pauby I will be pushing up those changes shortly.

2023-11-27 15:44 UTC, gep13 commented
@corbob I have pushed up the changes that I had. @corbob I will leave this with you for final review.

2023-11-27 20:48 UTC, corbob approved these changes

2023-11-29 09:42 UTC, merged