(#862) Add CCM timezone information
chocolatey/docs pull request #892
Opened 2023-11-21 22:36 UTC by corbob

## Description Of Changes

Add in details about timezones within Chocolatey Central Management. Also fills out the General Settings page in Chocolatey Central Management.

Note: This still needs images. Our internal tracking of images has been updated.

## Motivation and Context

Updating Chocolatey Central Management documentation before the upcoming release.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [x] Requires a change to menu structure (top or left hand side)/
* [x] Menu structure has been updated

## Related Issue

Related to #862

2023-11-22 11:55 UTC, AdmiringWorm requested changes

2023-11-22 11:55 UTC, AdmiringWorm commented on input/en-us/central-management/faq.md
> +* `Yukon Standard Time`does not appear in Windows Server 2016 until you install 5031462 or later.
```suggestion
* `Yukon Standard Time` does not appear in Windows Server 2016 until you install 5031462 or later.

```

Also, I assume the mention of 5031462 is a Windows Update?
This should probably be made clearer.

2023-11-22 11:55 UTC, AdmiringWorm commented on input/en-us/central-management/faq.md
> +* `South Sudan Standard Time` does not appear in Windows Server 2016 until you install 5031462 or later.
Same on this one. Need to call out what 5031462 is.

2023-11-22 11:55 UTC, AdmiringWorm commented on input/en-us/central-management/faq.md
> +Starting in Chocolatey Central Management version 0.12.0, if the chosen timezone is detected to be invalid, we will set it back to the default timezone and alert you through a notification.
This implies that if the user has an invalid time zone set, they will be notified.

What if the global configuration for CCM Website is invalid, who will be notified in this case?

2023-11-23 14:21 UTC, corbob commented on input/en-us/central-management/faq.md
> +Starting in Chocolatey Central Management version 0.12.0, if the chosen timezone is detected to be invalid, we will set it back to the default timezone and alert you through a notification.
Ah, I had intended to update this section, but was running into some Docker fun and apparently forgot. I've updated this whole section to hopefully be more clear.

2023-11-27 09:31 UTC, AdmiringWorm submitted a review, later dismissed
LGTM, only thing left is to get the image added.

2023-11-28 14:45 UTC, gep13 requested changes

2023-11-28 14:45 UTC, gep13 commented on input/en-us/central-management/usage/website/administration/settings/general.md
> +The Chocolatey Central Management Administration Settings page loads the General tab by default. This page is used to set the Chocolatey Central Management default timezone.
```suggestion
The Administration Settings page loads the General tab by default. This page is used to set the default timezone.
```

2023-11-28 14:45 UTC, gep13 commented on input/en-us/central-management/usage/website/administration/settings/general.md
> +If a user does not set their own timezone for display from `My Settings`, then the selected timezone will be used for the display of all times within Chocolatey Central Management.
```suggestion
If a user does not set their own timezone for display from `My Settings`, then the selected timezone will be used for the display of all times.
```

2023-11-28 14:45 UTC, gep13 commented on input/en-us/central-management/faq.md
> +Starting in Chocolatey Central Management version 0.12.0, if the chosen timezone is detected to be invalid, we will set it back to the default timezone and alert you through a notification. If you ar
```suggestion
Starting in Chocolatey Central Management version 0.12.0, if the chosen timezone is detected to be invalid, we will set it back to the default timezone and alert you through a notification. If you are an Administrator, you may additionally receive a notification that the system timezone was invalid.

```

2023-11-28 14:45 UTC, gep13 commented on input/en-us/central-management/faq.md
> +If you received the below notification, then it means that the timezone used for your user account was invalid, and has been set back to the default used by Chocolatey Central Management. You can pic
```suggestion
If you received the below notification, then it means that the timezone used for your user account was invalid, and has been set back to the default timezone. You can pick your own default by clicking the user menu in the top right and selecting `My Settings`

```

2023-11-28 14:45 UTC, gep13 commented on input/en-us/central-management/faq.md
> +If you received the below notification, then it means that the timezone used for Chocolatey Central Management was invalid, and has been set back to the default of `UTC`. You can adjust the Chocolate
```suggestion
If you received the below notification, then it means that the system timezone was invalid, and has been set back to the default of `UTC`. You can adjust the default through the [Settings page](xref:ccm-administration-settings-general).

```

2023-11-29 00:16 UTC, corbob commented
@gep13 I've merged in your suggestions for some of the changes, but I'm hesitant to merge the last two that would refer to the system timezone. I was specifically trying to avoid the term "system" here as the "system" is ambiguous. It could refer to the system running CCM, or the system the user is accessing CCM from.

2023-11-29 10:49 UTC, gep13 approved these changes
LGTM!

2023-11-29 10:56 UTC, merged