(#902) Tutorial - Creating a template
chocolatey/docs pull request #905
Opened 2023-11-30 17:53 UTC by steviecoaster

## Description Of Changes

This adds a tutorial on how to create a Chocolatey template, as well as  how to use that template when making Chocolatey packages.

## Motivation and Context

Templates are not well-explained in an easy-to-follow manner currently

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [x] Requires a change to menu structure (top or left-hand side)/
* [x] Menu structure has been updated

## Related Issue

Fixes #902

2023-12-11 08:19 UTC, JPRuskin requested changes

2023-12-11 08:19 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +### Creating your template
```suggestion
### Creating Your Template
```

2023-12-11 08:19 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +One of the most powerful advantages of templates is there ability to use key:value pairs to pass specific data into a package. For example, you may have a need to create multiple packages whose only
```suggestion
One of the most powerful advantages of templates is their ability to use key-value pairs to pass specific data into a package. For example, you may have a need to create multiple packages whose only difference is the location in which they will be used. In this situation,
```

2023-12-11 08:19 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +- **Insert more ideas here**
- Outputs logs as the intro text to a Star Wars movie
- Installs something from the Windows store
- Depend on one or more other packages (link to metapackage example)
- Adds a hook, extension, or template to Chocolatey CLI

Line needs removing before merge, if nothing else.
```suggestion
```

2023-12-11 08:19 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +We'll next create a _very_ simple chocolateyInstall.ps1 script for our template.
```suggestion
We'll next create a _very_ simple `chocolateyInstall.ps1` script for our template.
```

2023-12-11 08:19 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +$contents | Set-Content 'C:\ProgramData\chocolatey\templates\TutorialTemplate\tools\chocolatyInstall.ps1'
I'd personally put this as `Set-Content -Path -Value @'...` (as the pipeline doesn't add much here, and may be confusing to newer folk), but would suggest being consistent with the example below?

```suggestion
@'
Write-Host "I am from [[Country]]"
'@ | Set-Content 'C:\ProgramData\chocolatey\templates\TutorialTemplate\tools\chocolatyInstall.ps1'
```

2023-12-11 08:19 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +#Substitute the country USA with your own Country below
```suggestion
# Substitute the country USA with your own Country below
```

Personal preference, but comments with spacing always read better to me.

2023-12-11 08:21 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +Templates are stored in the **C:\ProgramData\chocolatey\templates** directory. The name of the folder must match the name you wish to give the template.
I've often seen us use code blocks rather than bold for paths, but am unsure if that's policy or happy coincidence.

```suggestion
Templates are stored in the `C:\ProgramData\chocolatey\templates` directory. The name of the folder must match the name you wish to give the template.
```

2023-12-12 10:35 UTC, pauby commented on input/en-us/guides/create/create-template.md
> +Templates are stored in the **C:\ProgramData\chocolatey\templates** directory. The name of the folder must match the name you wish to give the template.
Paths / files / folders should be between backticks.

2023-12-14 21:13 UTC, steviecoaster commented on input/en-us/guides/create/create-template.md
> +$contents | Set-Content 'C:\ProgramData\chocolatey\templates\TutorialTemplate\tools\chocolatyInstall.ps1'
I'm confused as to what you're asking of me here.

2023-12-18 11:03 UTC, JPRuskin commented on input/en-us/guides/create/create-template.md
> +$contents | Set-Content 'C:\ProgramData\chocolatey\templates\TutorialTemplate\tools\chocolatyInstall.ps1'
In the example below (on line 48-67) we just pipe a herestring into `Set-Content`. My suggestion here was we should do the same thing, instead of storing it in a variable (`$contents`) and then piping the variable.

2023-12-18 16:02 UTC, JPRuskin approved these changes

2023-12-19 10:05 UTC, gep13 commented on input/en-us/guides/create/create-template.md
> +$contents | Set-Content 'C:\ProgramData\chocolatey\templates\TutorialTemplate\tools\chocolatyInstall.ps1'
Looks like this has been taken care of, so I will resolve the conversation.

2023-12-19 10:07 UTC, gep13 commented on input/en-us/guides/create/create-template.md
> +- **Insert more ideas here**
These suggestions haven't been added, but the line about inserting of more ideas has been removed, so going to mark this as resovled.

2023-12-19 10:07 UTC, gep13 commented on input/en-us/guides/create/create-template.md
> +One of the most powerful advantages of templates is there ability to use key:value pairs to pass specific data into a package. For example, you may have a need to create multiple packages whose only
This has been fixed up, resolving...

2023-12-19 10:07 UTC, gep13 commented on input/en-us/guides/create/create-template.md
> +### Creating your template
This has been fixed up, resolving...

2023-12-19 10:11 UTC, gep13 approved these changes
LGTM!

2023-12-19 10:11 UTC, gep13 commented
@steviecoaster @JPRuskin thanks for getting this added! I have enabled auto-merge, so it should get merged in once the CI build finishses.

2023-12-19 10:19 UTC, merged