(#910) Packaging Tutorial - MSI Installation
chocolatey/docs pull request #911
Opened 2023-12-04 14:12 UTC by JPRuskin

## Description Of Changes
This commit adds a tutorial for how to create an MSI installation package.

## Motivation and Context
We have a request for more tutorials around this area.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* ~[ ] Minor documentation fix (typos etc.).~
* ~[ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* [x] New documentation page added.
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~

## Change Checklist

* ~[ ] Requires a change to menu structure (top or left-hand side)/~
* ~[ ] Menu structure has been updated~

## Related Issue

Fixes #910

2023-12-04 18:48 UTC, steviecoaster requested changes

2023-12-04 18:48 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +You can inspect the full set of available parameters for this function at the link above, or by opening the script file on your machine - it'll be contained in `%ChocolateyInstall%\helpers\functions`
Drop this

2023-12-04 18:48 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +Chocolatey CLI contains a selection of PowerShell functions known as "helper functions", which are available during all Chocolatey scripts.
Drop this.

2023-12-04 18:48 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +You can inspect the full set of available parameters for this function at the link above, or by opening the script file on your machine - it'll be contained in `%ChocolateyInstall%\helpers\functions`
```suggestion
You can inspect the full set of available parameters for this function at the link above.
```

2023-12-05 18:23 UTC, steviecoaster requested changes

2023-12-05 18:23 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +When starting out with Chocolatey, why not start simple? Installing an MSI is a popular use of a Chocolatey package, and we'll walk you through how to do just that - assuming you've already run throu
xref for this link is `xref:howto-prepare-env`

2023-12-05 18:23 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +There are [package templates](#package-template-placeholder) to create various package types, including an MSI template!
What was this link going to go too?

2023-12-05 18:23 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +You'll want to open the `firefox-msi.nuspec` file, and fill out the following fields in the `metadata` section if required:
Give them the completed file. Too much room for error otherwise.

2023-12-05 18:23 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +You could inject additional configuration after the initial installation, if you wanted - or have this package simply install the software, and have a separate package for [applying configuration](#p
I think we know the xrefs now, so update this one.

2023-12-05 18:23 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +1. Press Enter, providing no additional input.
Make sure you instruct them on using --output-directory so it ends up in the tutorials root. Consistent with other tutorials.

2023-12-05 18:23 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +choco install firefox-msi --source='Tutorials' --confirm
What year is it?!?! `--confirm`?!?! What's wrong wtih `-y`, it's shorter and _much more common_. :D

2023-12-05 18:35 UTC, pauby requested changes

2023-12-05 18:35 UTC, pauby commented on input/en-us/guides/create/create-msi-package.md
> +When starting out with Chocolatey, why not start simple? Installing an MSI is a popular use of a Chocolatey package, and we'll walk you through how to do just that - assuming you've already run throu
```suggestion
When starting out with Chocolatey CLI, why not start simple? Installing an MSI is a popular use of a Chocolatey package, and we'll walk you through how to do just that - assuming you've already run through [Preparing Your Environment for Package Creation](#package-creation-env-placeholder).
```

2023-12-05 18:52 UTC, pauby requested changes

2023-12-05 18:52 UTC, pauby commented on input/en-us/guides/create/create-msi-package.md
> +1. Open your tutorials folder in VSCode.
```suggestion
1. Open your `Tutorials` folder in VSCode.
```

2023-12-06 11:47 UTC, JPRuskin commented on input/en-us/guides/create/create-msi-package.md
> +You could inject additional configuration after the initial installation, if you wanted - or have this package simply install the software, and have a separate package for [applying configuration](#p
If we don't merge all of the docs (and update this now), this will fail to build until day 6, I think?

2023-12-06 11:51 UTC, JPRuskin commented on input/en-us/guides/create/create-msi-package.md
> +choco install firefox-msi --source='Tutorials' --confirm
😅 

I'm going off a few things here, I thought that in general we suggest documents/saved scripts spell out the full arguments (similar to PowerShell scripts and docs). Personally, I find it a lot more readable / not having to remember what flags mean - let alone folk new to `choco`!

2023-12-06 11:53 UTC, JPRuskin commented on input/en-us/guides/create/create-msi-package.md
> +When starting out with Chocolatey, why not start simple? Installing an MSI is a popular use of a Chocolatey package, and we'll walk you through how to do just that - assuming you've already run throu
I'd argue that this use is "starting out with Chocolatey" [the products] rather than Chocolatey [the CLI]. This walkthrough _uses_ Chocolatey CLI but isn't specifically about it, similar to the usage with "use of a Chocolatey package" (we don't add CLI).

2023-12-06 13:12 UTC, JPRuskin commented on input/en-us/guides/create/create-msi-package.md
> +choco uninstall firefox-msi --confirm
> Always use the full option name. If the short option is -n, and the full option is --name, use --name. The only acceptable short option for use in scripts is -y.

I started chatting about this above, with Stevie, and went to find our guidelines (quoted above). Is this usage acceptable, or required? I prefer `--confirm` for various reasons.

2023-12-06 17:01 UTC, pauby requested changes

2023-12-06 19:53 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +choco uninstall firefox-msi --confirm
I've made this change

2023-12-06 19:53 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +You should be able to test the uninstall by running `choco uninstall` on your test environment:
I've made this change

2023-12-06 19:53 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +Launch an elevated terminal on your test environment, either using PowerShell or `cmd`. In the new window, run something like the following:
I've made this change

2023-12-06 19:53 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +Personally, I like to test this in a Windows Sandbox environment, or the [Chocolatey Test Environment](https://github.com/chocolatey-community/chocolatey-test-environment) (particularly if you alread
I've made this change

2023-12-06 19:54 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +When starting out with Chocolatey, why not start simple? Installing an MSI is a popular use of a Chocolatey package, and we'll walk you through how to do just that - assuming you've already run throu
I've made this change

2023-12-06 19:54 UTC, steviecoaster commented on input/en-us/guides/create/create-msi-package.md
> +choco install firefox-msi --source='Tutorials' --confirm
I've made this change

2023-12-06 19:58 UTC, steviecoaster commented
@pauby I've got the outstanding requested changes sorted here.

2023-12-07 10:20 UTC, pauby commented
I've made a few final changes, squashed the commits and set to auto-merge.

2023-12-07 10:56 UTC, merged