Tutorial - Extension Package
chocolatey/docs pull request #917
Opened 2023-12-05 10:26 UTC by JPRuskin

## Description Of Changes
Adds a brief tutorial for creating an extension package.

## Motivation and Context
We were requested to add short tutorials for this purpose.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* ~[ ] Minor documentation fix (typos etc.).~
* ~[ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* [x] New documentation page added.
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~

## Change Checklist

* ~[ ] Requires a change to menu structure (top or left-hand side)/~
* ~[ ] Menu structure has been updated~

## Related Issue

Fixes #914

2023-12-05 18:23 UTC, pauby requested changes

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +As we've mentioned in other articles, a Chocolatey package can do anything PowerShell can - including sharing functions and logic between packages.
```suggestion
As we've mentioned in other articles, a Chocolatey package can do almost anything PowerShell can - including sharing functions and logic between packages.
```

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +### What is an Extension Package
```suggestion
### What Is an Extension Package
```

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +### Why would I want to use one?
```suggestion
### Why Would I Want To Use One?
```

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +#### Creating your Install Script
```suggestion
#### Creating Your Install Script
```

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +You can _also_ include a tools directory, with the standard Chocolatey scripts (which could be used for system-specific configuration of the module), but it is not required.
```suggestion
You can _also_ include a `tools` directory, with the standard Chocolatey scripts (which could be used for system-specific configuration of the module), but it is not required.
```

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +Launch an elevated terminal on your test environment, and run the following:
```suggestion
In an _administrative PowerShell console_ run the following:
```

2023-12-05 18:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +At this point, you have created a package that extends the functionality of Chocolatey - and possibly used it in another package.
```suggestion
At this point, you have created a package that extends the functionality of Chocolatey CLI - and possibly used it in another package.
```

2023-12-05 18:36 UTC, pauby requested changes

2023-12-05 18:36 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +So, if you browse through the files in VS Code or Explorer, you should see a file structure like this:
```suggestion
So, if you browse through the files in VSCode or Explorer, you should see a file structure like this:
```

2023-12-05 18:36 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +- Open the config package `.nuspec` file in VS Code.
```suggestion
- Open the config package `.nuspec` file in VSCode.
```

2023-12-05 18:51 UTC, pauby requested changes

2023-12-05 18:51 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +Create a new directory within your Tutorials directory, and within that directory create a nuspec file for your new extension package - we're going to call ours `example.extension` in these examples,
```suggestion
Create a new directory within your `Tutorials` directory, and within that directory create a nuspec file for your new extension package - we're going to call ours `example.extension` in these examples, but you can change that to whatever you like!
```

2023-12-05 18:51 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +1. In your Tutorials folder, create a new folder for this package. For the example, we will call it `example.extension`.
```suggestion
1. In your `Tutorials` folder, create a new folder for this package. For the example, we will call it `example.extension`.
```

2023-12-11 08:27 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +So, if you browse through the files in VS Code or Explorer, you should see a file structure like this:
FWIW, the product is referred to as VS Code by Microsoft.

![image](https://github.com/chocolatey/docs/assets/1975761/af1b278f-ab19-4dd8-b86c-564e966b08c1)

Entirely possible that I've missed this before now, so it would be more consistent _within our docs_ to take this correction.

2023-12-11 10:18 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +So, if you browse through the files in VS Code or Explorer, you should see a file structure like this:
Had a quick search for examples in our docs, it doesn't look like we've used 'VSCode' much - mostly as a package ID.

2023-12-11 10:29 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +So, if you browse through the files in VS Code or Explorer, you should see a file structure like this:
All the docs created for the 12 days use 'VSCode'. If you want to use 'VS Code' they will need to be updated.

2023-12-12 11:07 UTC, pauby commented
Can you move the fixes to the other pages to a separate PR?

2023-12-12 11:23 UTC, pauby requested changes

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +Title: How to Create an Extension Package
```suggestion
Title: How To Create an Extension Package
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +### Why Would You Use An Extension Package
```suggestion
### Why Would You Use an Extension Package?
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +You might choose to use this over installing a full PowerShell module if you didn't want to expose the PowerShell module to the normal users of the machine - for instance, if you never wanted to expo
```suggestion
You might choose to use this over installing a full PowerShell module if you didn't want to expose the PowerShell module to the normal users of the computer, for example, if you never wanted to expose the functions outside of Chocolatey runspaces. If you just wanted to use an available PowerShell module, you might consider having a dependency on a package that installs that module, instead.
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +We'll now run through how to create an extension package, assuming you have an environment set up as in [Preparing Your Environment for Package Creation](#package-creation-env-placeholder).
```suggestion
We'll now run through how to create an extension package, assuming you have an [environment set up](xref:howto-prepare-env).
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +> **Shortcut:** You can use a [package template](#package-template-placeholder) to create an extension package!
```suggestion
> **Shortcut:** You can use a [package template](xref:create-custom-package-templates) to create an extension package!
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +Create a new directory to hold your package files, and within that directory create a nuspec file for your new extension package - we're going to call ours `example.extension` in these examples, but
```suggestion
Follow the steps below to get started:
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +You can _also_ include a `tools` directory, with the standard Chocolatey scripts (which could be used for system-specific configuration of the module), but it is not required.
```suggestion
You can _also_ include a `tools` directory, with the standard Chocolatey scripts (which could be used for configuration of the module), but it is not required.
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +You can now use `choco pack` to compile your Chocolatey package into a nupkg file, ready for installation!
```suggestion
You can now use `choco pack` to compile your Chocolatey package, creating a file with a `.nupkg` extension, ready for installation!
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +1. In VSCode, press `Ctrl + Shift + P` or use the `View` menu and click on `Command Palette`.
```suggestion
1. In VS Code, press `Ctrl + Shift + P` or use the **View** menu and click on **Command Palette**.
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +1. Press Enter, providing no additional input.
```suggestion
1. Press **Enter**, providing no additional input.
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +In an elevated command prompt on your test environment, run the following:
```suggestion
In an _elevated PowerShell command prompt_, run the following:
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +choco install example.extension --source='Tutorials' --confirm
```suggestion
choco install example.extension --source='tutorials' --y
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +At this point, you have created a package that extends the functionality of Chocolatey CLI - and possibly used it in another package.
```suggestion
At this point, you have created a package that extends the functionality of Chocolatey CLI and  used it in another package.
```

2023-12-12 11:23 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +If you've already created a [config package](#config-package-placeholder), why not try adding your newly available functions to it?
```suggestion
If you've already created a [config package](xref:howto-create-config-package), why not try adding your newly available functions to it?
```

2023-12-12 20:38 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +choco install example.extension --source='Tutorials' --confirm
It's capitalised in the setup doc (prepare-packaging-environment), but I see it's been changed in my other entries, that I think matched this. Is it a best practice I'm unaware of to lower-case the source name, and if so should we correct Day 1 in this PR or in another?

2023-12-12 20:38 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +1. Press Enter, providing no additional input.
A note on this one: adjusted the line to match another of my days, but we had some merged that add `--output-directory='C:\tutorials'`, which is outdated. As in another comment, do we want to fix that in this PR or another?

2023-12-12 20:38 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +At this point, you have created a package that extends the functionality of Chocolatey CLI - and possibly used it in another package.
We offer the option to do the previous day (on line 179), as this page should (hopefully) stand alone. They may not have done this?

2023-12-13 09:58 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +1. Press Enter, providing no additional input.
I don't understand this comment in the context of the suggestion that as made?

2023-12-13 09:59 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +At this point, you have created a package that extends the functionality of Chocolatey CLI - and possibly used it in another package.
This page is a tutorial that is followed from start to finish. So either that have added to another package or they haven't. 

Is the 'possibily' part relies on them maybe having done another page, then it should be removed.

2023-12-13 10:06 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +1. Press Enter, providing no additional input.
Stevie asked, in another PR, to update all of these to have an explicit output directory. I've added that too, here, but have not been consistent with some days. 

I wanted to make it clear why it wasn't consistent with all days (and with your suggestion), and to ask if you'd prefer a separate PR to correct the inconsistency.

2023-12-13 10:18 UTC, pauby commented on input/en-us/guides/create/create-extension-package.md
> +1. Press Enter, providing no additional input.
If you're making changes that isn't for 'Tutorial - Extension Package' then a new PR is needed.

2023-12-13 10:51 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +1. Press Enter, providing no additional input.
Sure thing! Is the format used here okay? I took it from the MSI package howto.

2023-12-13 10:55 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +At this point, you have created a package that extends the functionality of Chocolatey CLI - and possibly used it in another package.
Sure thing. I'll remove it.

2023-12-13 11:08 UTC, JPRuskin commented on input/en-us/guides/create/create-extension-package.md
> +At this point, you have created a package that extends the functionality of Chocolatey CLI - and possibly used it in another package.
To confirm, have removed mention that you might want to do it but left the section in place with some additional language making it clear that we're just using the linked package as an example, as re-writing a new unique package seemed silly and I felt that the section did add to the walkthrough as a whole.

2023-12-18 16:05 UTC, steviecoaster approved these changes

2023-12-18 16:08 UTC, merged