Package Tutorial - Configuration Package
chocolatey/docs pull request #918
Opened 2023-12-05 10:27 UTC by JPRuskin

## Description Of Changes
This adds a guide for creating a simple configuration package.

## Motivation and Context
We were requested to add short tutorials for this purpose.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* ~[ ] Minor documentation fix (typos etc.).~
* ~[ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).~
* [x] New documentation page added.
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~

## Change Checklist

* ~[ ] Requires a change to menu structure (top or left-hand side)/~
* ~[ ] Menu structure has been updated~

## Related Issue

Fixes #913

2023-12-05 18:26 UTC, steviecoaster requested changes

2023-12-05 18:26 UTC, steviecoaster commented on input/en-us/guides/create/create-config-package.md
> +You'll want to open the `example-config.nuspec` file, and fill out the following fields in the `metadata` section if required:
Give them a nuspec file here, don't leave filing the default one to chance.

2023-12-05 18:50 UTC, pauby requested changes

2023-12-05 18:50 UTC, pauby commented on input/en-us/guides/create/create-config-package.md
> +1. Open your tutorials folder in VSCode.
```suggestion
1. Open your `Tutorials` folder in VSCode.
```

2023-12-12 10:32 UTC, pauby approved these changes

2023-12-12 10:33 UTC, pauby commented
Thanks for fixing this up @JPRuskin. I made some minor changes, rebased and will auto-merge.

2023-12-12 10:55 UTC, merged