(#931) Update Java Dependency In Jenkins Upgrade Doc
chocolatey/docs pull request #932
Opened 2024-01-05 20:51 UTC by ryanrichter94

## Description Of Changes
- Update dependency to point out temurin21jre pkg
- Add link to Jenkins own Java support policy docs
- Fix typos and incorrect package references

## Motivation and Context
Documentation needed updated to reflect Jenkins own guidance for java dependency

## Testing
* [X] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [X] Minor documentation fix (typos etc.).
* [X] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* ~[ ] New documentation page added.~
* ~[ ] The change I have made should have a video added, and I have raised an issue for this.~
    ~* Issue #~

## Change Checklist
* ~[ ] Requires a change to menu structure (top or left-hand side)/~
* ~[ ] Menu structure has been updated~

## Related Issue
Fixes #931

2024-01-05 21:10 UTC, steviecoaster submitted a review, later dismissed

2024-01-06 01:09 UTC, steviecoaster requested changes

2024-01-08 15:13 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/upgrade-jenkins.md
> +> Here is a link to Jenkins own [java support policy documentation](https://www.jenkins.io/doc/book/platform-information/support-policy-java/).
fixed

2024-01-08 15:14 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/upgrade-jenkins.md
> +3. choco upgrade the temurin21jre and Jenkins packages (Example command provided below)
fixed

2024-01-08 15:15 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/upgrade-jenkins.md
> +1. Internalize the Jenkins package and push to your internal repo
fixed

2024-01-09 14:28 UTC, steviecoaster commented
This section needs changed:

```
This document outlines the process for upgrading Jenkins running inside our Quick Start Environment.
The script provided assumes your server has access to the internet to download the Jenkins package from the community repository.
If your server is restricted then internalize the package to your internal repository and update the source in the script appropriately.
```

There is no script referenced on this page anywhere, and where there _is_ code, we have placeholders for an internal repo url.

Instructions on this page call our internalization, so I think it's just this section that needs tweaked.

The language should _never_ assume pulling from the Chocolatey Community Repository, but rathe the internalization of the package, and then installation from an internal source, even in these seemingly one-off cases.

As we are updating documentation be sure to keep an eye out for this sort of thing, and change the language in the doc when found.

2024-01-09 14:28 UTC, steviecoaster requested changes
See previous comment. it won't let me suggest changes on the lines that need it for some reason.

2024-01-09 16:40 UTC, ryanrichter94 commented
> This section needs changed:
> 
> ```
> This document outlines the process for upgrading Jenkins running inside our Quick Start Environment.
> The script provided assumes your server has access to the internet to download the Jenkins package from the community repository.
> If your server is restricted then internalize the package to your internal repository and update the source in the script appropriately.
> ```
> 
> There is no script referenced on this page anywhere, and where there _is_ code, we have placeholders for an internal repo url.
> 
> Instructions on this page call out internalization, so I think it's just this section that needs tweaked.
> 
> The language should _never_ assume pulling from the Chocolatey Community Repository, but rather the internalization of the package, and then installation from an internal source, even in these seemingly one-off cases.
> 
> As we are updating documentation be sure to keep an eye out for this sort of thing, and change the language in the doc when found.

Updated wording used in this section above with last commit.

2024-01-09 17:04 UTC, steviecoaster requested changes

2024-01-09 17:04 UTC, steviecoaster commented on input/en-us/c4b-environments/quick-start-environment/upgrade-jenkins.md
> +This guide assumes your server has access to the internet to internalize the needed packages from the community repository.
```suggestion
Chocolatey community repository
```

2024-01-09 17:04 UTC, steviecoaster commented on input/en-us/c4b-environments/quick-start-environment/upgrade-jenkins.md
> +If your server is internet restricted, please internalize the needed packages on a machine that does have internet access. Then push these packages to your internal repository.
```suggstion
If your server is internet restricted, please internalize the needed packages on a machine that does have internet access, then push these packages to your internal repository.
```

2024-01-09 17:28 UTC, ryanrichter94 commented on input/en-us/c4b-environments/quick-start-environment/upgrade-jenkins.md
> +If your server is internet restricted, please internalize the needed packages on a machine that does have internet access. Then push these packages to your internal repository.
fixed

2024-01-09 17:28 UTC, steviecoaster approved these changes

2024-01-09 17:35 UTC, merged