(#143) Overhaul the package triage process
chocolatey/docs pull request #950
Opened 2024-02-12 12:31 UTC by pauby

## Description Of Changes
The package triage process no longer represents what happens today and needs to be overhauled. 

## Motivation and Context
There is a lot of information that is thrown at the user all at once and I have tried to extract some of that out to make the pages more digestible.

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [x] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

#143 (this doesn't fix that issue, as more neds to be done).

2024-02-12 12:51 UTC, pauby commented on input/assets/images/.directory
:+1:  I just threw it up without checking it. It would all come out in the wash as they say. Added it to `.gitignore'

2024-02-12 14:29 UTC, AdmiringWorm commented on input/en-us/community-repository/users/package-request.md
> +RedirectFrom: community-repository/users/package-triage-process#package-request-package-missing
Can you even use a URL fragment in the redirect from attribute?

2024-02-12 14:35 UTC, pauby commented on input/en-us/community-repository/users/package-request.md
> +RedirectFrom: community-repository/users/package-triage-process#package-request-package-missing
I don't know. But I added it so I could test it and also to remind me that I need to redirect that anchor to this page _somehow_.

2024-02-12 14:38 UTC, AdmiringWorm commented on input/en-us/community-repository/users/package-request.md
> +RedirectFrom: community-repository/users/package-triage-process#package-request-package-missing
I updated the comment once I found out.

It doesn't work, as the URL fragment is only available in the browser, not on the server side (at least not through typical means).

2024-02-12 14:52 UTC, AdmiringWorm requested changes

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/users/software-vendor.md
> +![Download packlage button on the Chocolatey Community Repository](/assets/images/triage-download.jpg)
```suggestion
![Download package button on the Chocolatey Community Repository](/assets/images/triage-download.jpg)
```

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/users/software-vendor.md
Should there be a section in this document for cases like a package is a remote package, and the Software Author have issues with it being downloaded from their site and want it to be changed?

Like with the `exiftool` package?

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> +1. [Contact the package Maintainers](#how-do-i-contact-the-package-maintainers). Some Maintainers have opted-out of receiving email, so this option may not be available.
Should probably mention to look for the package source URL if the maintainer has opted-out of emails.

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> +  ![Package Maintainers profile links on the Chocolatey Community Repository](/assets/images/triage-maintainerlinks.jpg)
Same as above


```suggestion
![Package Maintainers profile links on the Chocolatey Community Repository](/assets/images/triage-maintainerlinks.jpg)
```

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> +   ![Contact Site Admins link on the Chocolatey Community Repository package page](/assets/images/triage-siteadmins.jpg)
Same as above


```suggestion
![Contact Site Admins link on the Chocolatey Community Repository package page](/assets/images/triage-siteadmins.jpg)
```

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> + ![Package Source link on the Chocolatey Community Repository](/assets/images/triage-packagesource.jpg)
And again


```suggestion
![Package Source link on the Chocolatey Community Repository](/assets/images/triage-packagesource.jpg)
```

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> +
```suggestion
![Package Maintainers profile links on the Chocolatey Community Repository](/assets/images/triage-maintainerlinks.jpg)
![Package Maintainer profile on the Chocolatey Community Repository with GitHub repository link](/assets/images/triage-maintainerrepository.jpg)

```

2024-02-12 14:52 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> +See [#how-can-i-find-the-package-source].
This should probably be


```suggestion
See [#how-do-i-find-the-package-source].
```

2024-02-13 08:29 UTC, pauby commented on input/en-us/community-repository/faq.md
> +1. [Contact the package Maintainers](#how-do-i-contact-the-package-maintainers). Some Maintainers have opted-out of receiving email, so this option may not be available.
That is mentioned in the very next step?

2024-02-13 08:30 UTC, pauby commented on input/en-us/community-repository/faq.md
> +   ![Contact Maintainers link on the Chocolatey Community Repository package page](/assets/images/triage-maintainers.jpg)
There is inconsistent indentation for images in the docs. so it may have come over when I copy and pasted it. I'll remove it.

2024-02-13 08:31 UTC, pauby commented on input/en-us/community-repository/faq.md
> +   ![Contact Site Admins link on the Chocolatey Community Repository package page](/assets/images/triage-siteadmins.jpg)
Removed.

2024-02-13 10:16 UTC, pauby commented
My intention is squash the commits before merging (which is why the commits are not very informative).

2024-02-13 10:17 UTC, pauby commented on input/en-us/community-repository/faq.md
> +  ![Package Maintainers profile links on the Chocolatey Community Repository](/assets/images/triage-maintainerlinks.jpg)
Fixed.

2024-02-13 13:12 UTC, AdmiringWorm commented on input/en-us/community-repository/faq.md
> +   ![Contact Site Admins link on the Chocolatey Community Repository package page](/assets/images/triage-siteadmins.jpg)
Seems this has come back again 😕

2024-02-13 14:25 UTC, pauby commented on input/en-us/community-repository/faq.md
> +   ![Contact Site Admins link on the Chocolatey Community Repository package page](/assets/images/triage-siteadmins.jpg)
Fixed.

2024-02-13 15:26 UTC, mkevenaar approved these changes
Just a small suggestion from me

2024-02-13 15:26 UTC, mkevenaar commented on input/en-us/community-repository/users/software-vendor.md
> +If you have other questions, please [contact the Site Admins](xref:ccr-faq#how-do-i-contact-the-site-admins).
```suggestion
If you have other questions, please [reach out on Discord](https://ch0.co/community) or [contact the Site Admins](xref:ccr-faq#how-do-i-contact-the-site-admins).
```

2024-02-13 15:28 UTC, pauby commented on input/en-us/community-repository/users/software-vendor.md
> +If you have other questions, please [contact the Site Admins](xref:ccr-faq#how-do-i-contact-the-site-admins).
I thought about this. For Software Vendors, I think it's best if they reach out to the Site Admins rather than discussing it in public in Discord.

2024-02-13 15:30 UTC, mkevenaar commented on input/en-us/community-repository/users/software-vendor.md
> +If you have other questions, please [contact the Site Admins](xref:ccr-faq#how-do-i-contact-the-site-admins).
Software vendors will become (potential) maintainers. We want maintainers to ask questions on Discord, rather then via the Site Admins.

2024-02-13 18:32 UTC, pauby commented on input/en-us/community-repository/users/software-vendor.md
> +If you have other questions, please [contact the Site Admins](xref:ccr-faq#how-do-i-contact-the-site-admins).
We do. But when they become maintainers, they have a different page to look at (under maintainers). When they are not maintainers, they are looking at understanding how CCR works and whether their distribution rights have been violated, they will be on this page.

So this page serves the purpose of answering Software Vendor questions when they are trying to understand how their software got into a package on CCR and how they take over that package. And if they have any more questions about that, they would feel safer doing it in private rather than public _in my opinion_.

2024-02-13 18:42 UTC, mkevenaar commented on input/en-us/community-repository/users/software-vendor.md
> +If you have other questions, please [contact the Site Admins](xref:ccr-faq#how-do-i-contact-the-site-admins).
The vendor can choose Discord or email at their regression with this suggestion. Just _my opinion_ :wink:

2024-02-13 19:20 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/faq.md
> +The contents of every Chocolatey package is available to be inspected both on the Chocolatey Community Repository package page under the **Files** section.
Is it worth noting the pre-2014 packages that do not have visible files?

2024-02-13 19:25 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. The [package doesn't already have a newer version in moderation](xref:ccr-faq#how-do-i-see-all-versions-of-a-package). The maintainer(s) may already be actively working towards getting a newer ver
```suggestion
1. The [package doesn't already have a newer version in moderation](xref:ccr-faq#how-do-i-see-all-versions-of-a-package). The maintainer(s) may already be actively working towards getting a newer version up on the Community Repository.
```

2024-02-23 16:52 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. The [package doesn't already have a newer version in moderation](xref:ccr-faq#how-do-i-see-all-versions-of-a-package). The maintainer(s) may already be actively working towards getting a newer ver
Good catch. Fixed.

2024-02-23 16:54 UTC, pauby commented on input/en-us/community-repository/faq.md
> +The contents of every Chocolatey package is available to be inspected both on the Chocolatey Community Repository package page under the **Files** section.
Added a note to that affect.

2024-02-23 16:59 UTC, AdmiringWorm approved these changes
LGTM

2024-02-23 17:05 UTC, merged