(#954) Enhance and clarify proxy bypass list documentation
chocolatey/docs pull request #958
Opened 2024-02-24 02:21 UTC by corbob

## Description Of Changes

Enhance and clarify the proxy bypass list settings.

Additionally clarify the root certificates needed as that data appeared to be outdated.

## Motivation and Context

Need to be more clear that the bypass list is a regular expression list and not a globbing list.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #854

2024-02-26 10:16 UTC, pauby reviewed
Other than the one question I had, which we may just need to make clearer, this is good.

2024-02-26 10:16 UTC, pauby commented on input/en-us/configuration.md
> +* `proxyBypassOnLocal` = **'true'** - Bypass proxy for local connections. Requires explicit proxy location.
What does 'Requires explicit proxy location' mean?

2024-02-26 15:56 UTC, corbob commented on input/en-us/configuration.md
> +* `proxyBypassOnLocal` = **'true'** - Bypass proxy for local connections. Requires explicit proxy location.
It means that it requires the `proxy` configuration to be set explicitly. I was looking at the help for the command line switches and it was noted there:

```
     --proxy=VALUE
     Proxy Location - Explicit proxy location. Overrides the default proxy 
       location of ''.

     --proxy-user=VALUE
     Proxy User Name - Explicit proxy user (optional). Requires explicit 
       proxy (`--proxy` or config setting). Overrides the default proxy user of 
       ''.

     --proxy-password=VALUE
     Proxy Password - Explicit proxy password (optional) to be used with 
       username. Requires explicit proxy (`--proxy` or config setting) and user 
       name.  Overrides the default proxy password (encrypted in settings if 
       set).

     --proxy-bypass-list=VALUE
     ProxyBypassList - Comma separated list of regex locations to bypass on 
       proxy. Requires explicit proxy (`--proxy` or config setting). Overrides 
       the default proxy bypass list of ''.

     --proxy-bypass-on-local
     Proxy Bypass On Local - Bypass proxy for local connections. Requires 
       explicit proxy (`--proxy` or config setting). Overrides the default 
       proxy bypass on local setting of 'True'.
```

I just noticed that the password also includes that it requires an explicit proxy username to be set, so I'll add that too.

2024-02-26 16:54 UTC, pauby commented on input/en-us/configuration.md
> +* `proxyBypassOnLocal` = **'true'** - Bypass proxy for local connections. Requires explicit proxy location.
> It means that it requires the proxy configuration to be set explicitly. 

Can we say _that_ instead?

'Requires explicit proxy location' would have me look for an option that is related to location, rather than `--proxy`. Perhaps 'Requires `--proxy` to be set'? That's clear and is not open to interpretation _in my opinion_.?

2024-02-26 17:56 UTC, pauby commented on input/en-us/configuration.md
> +* `proxyBypassOnLocal` = **'true'** - Bypass proxy for local connections. Requires explicit proxy location.
Yeah. That's a good suggestion. It's still clear what is needed.

2024-03-21 19:12 UTC, vexx32 commented on input/en-us/choco/commands/install.md
> +       password (encrypted in settings if set).
I think this would be good 👍

2024-04-25 16:12 UTC, pauby requested changes
I'm happy with this. Can you make that one small change and we can merge?

2024-04-25 16:12 UTC, pauby commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
```suggestion
* `no_proxy` - Chocolatey CLI will treat this as a comma separated list of regex values.

```

2024-04-25 16:45 UTC, corbob commented on input/en-us/guides/usage/proxy-settings-for-chocolatey.md
I've updated and force pushed this @pauby

2024-04-30 09:41 UTC, pauby approved these changes

2024-04-30 09:42 UTC, pauby commented
Thanks @corbob. I've rebased this and set it to auto-merge when checks are complete.

2024-04-30 09:48 UTC, merged