(#959) Use Playwright generated images
chocolatey/docs pull request #960
Opened 2024-02-26 17:48 UTC by st3phhays

## Description Of Changes
This updates all the images used in the Chocolatey Central Management documentation to use ones that have been auto generated by Playwright.

All automated images are in the `ccm-playwright` folder, while any manual images have been moved to a new `ccm-manual` folder. This is so everything is better organized. The `ccm-playwright` folder is intended to be completely replaced whenever a new run of Playwright has been done.

## Motivation and Context
This will help speed up the process of replacing screenshots when a new version of Chocoaltey Central Management is released.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [x] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue
Fixes #959

2024-02-29 20:18 UTC, corbob requested changes

2024-02-29 20:18 UTC, corbob commented on input/en-us/central-management/faq.md
> +![Example notification for a user configured timezone being invalid](/assets/images/ccm-manual/notifications/system-timezone-invalid.png)
```suggestion
![Example notification for a user configured timezone being invalid](/assets/images/ccm-manual/notifications/user-timezone-invalid.png)
```

2024-02-29 20:18 UTC, corbob commented on input/en-us/central-management/faq.md
> +![Example notification for a Chocolatey Central Management configured timezone being invalid](/assets/images/ccm-manual/notifications/user-timezone-invalid.png)
```suggestion
![Example notification for a Chocolatey Central Management configured timezone being invalid](/assets/images/ccm-manual/notifications/system-timezone-invalid.png)
```

2024-02-29 20:25 UTC, corbob commented on input/en-us/central-management/usage/website/administration/audit-logs.md
It's not from your PR, so GitHub won't let me comment on it... But I just noticed the heading at the bottom of this page says `Changes logs` when it's `Change logs` in CCM.

2024-02-29 20:30 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/audit-logs.md
I've fixed this.

2024-02-29 20:38 UTC, corbob commented on input/en-us/central-management/usage/website/administration/sensitive-variables.md
> +    ![Central Management dashboard, arrow pointing to Sensitive Variables menu in the left sidebar entry on the CCM Dashboard](/assets/images/ccm-playwright/dashboard/left-menu-nested-sensitive-varia
Why are we showing this same image twice? Also: the alt text of each of them is different. I would probably suggest at the very least making the alt text the same.

2024-02-29 20:38 UTC, corbob commented on input/en-us/central-management/usage/website/administration/sensitive-variables.md
> +![Deployment Step Advanced script, showing the Sensitive Variables drop down with SERVICE_PASSWORD selected](/assets/images/ccm-playwright/deployment-plans/edit/modal-step-advanced-command-select-sen
This is no longer showing a drop down. We should update the alt text.

2024-02-29 21:04 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/settings/encryption-passphrase.md
> +  ![Chocolatey Central Management Settings, encryption passphrase required](/assets/images/ccm-playwright/administration/settings/security-alert-new-passphrase-danger.png)
This image is a little different due to not fully being able to get into the state to show the modal, so the Passphrase section is shown with the error. 

I see what you mean about the "x" on the alert though. I can definitely generate it to not be dismissible. I'll fix that up.

2024-02-29 21:26 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/settings/encryption-passphrase.md
> +  ![Chocolatey Central Management Settings, encryption passphrase required](/assets/images/ccm-playwright/administration/settings/security-alert-new-passphrase-danger.png)
I have fixed this up. I also fixed the one with the warning alert, since it had the same issue.

2024-02-29 21:26 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/sensitive-variables.md
> +![Deployment Step Advanced script, showing the Sensitive Variables drop down with SERVICE_PASSWORD selected](/assets/images/ccm-playwright/deployment-plans/edit/modal-step-advanced-command-select-sen
This is updated.

2024-02-29 21:27 UTC, st3phhays commented on input/en-us/central-management/usage/website/administration/sensitive-variables.md
> +    ![Central Management dashboard, arrow pointing to Sensitive Variables menu in the left sidebar entry on the CCM Dashboard](/assets/images/ccm-playwright/dashboard/left-menu-nested-sensitive-varia
For now, I've left the image but updated the alt text to match. I agree it's seems redundant having them so close to each other, but we have a few pages with this pattern, so maybe it's best to do that in a separate issue.

2024-02-29 22:30 UTC, vexx32 submitted a review, later dismissed
This looks good to me, great work Steph!

2024-03-01 00:03 UTC, corbob approved these changes
LGTM!

2024-03-01 00:04 UTC, merged

2024-03-01 00:05 UTC, corbob commented
Thanks for getting these updated @st3phhays 👍