(GH-97) Update package triage process
chocolatey/docs pull request #98
Opened 2020-12-14 22:50 UTC by TheCakeIsNaOH

1. Fixes numbering on triage process.
2. Removes contacting google groups step
(see chocolatey/choco-wiki#201)
3. Add image to contact maintainers step
4. Add timeline to wait before contacting admins.

I'm not sure if that covers everything that needs to be changed, so @pauby should take a look.

2020-12-15 09:17 UTC, gep13 commented
@TheCakeIsNaOH I have taken the liberty of updating this PR to bring it into line with the changes that I discussed in #97 (i.e. to separate the fixing of the numbering into its own issue).

@pauby Let us know if you want any additional changes to this PR.

2020-12-15 09:22 UTC, gep13 commented
@TheCakeIsNaOH @pauby the end result of this PR is the following:

![image](https://user-images.githubusercontent.com/1271146/102195836-004e4980-3eb7-11eb-907d-9df5afd0065f.png)

2020-12-15 15:41 UTC, TheCakeIsNaOH commented
> I have taken the liberty of updating this PR to bring it into line with the changes that I discussed in 97 (i.e. to separate the fixing of the numbering into its own issue).

Thanks, 

> the end result of this PR is the following:

👍 

I got the site preview working locally, so that looks the same as what I got. 

Speaking of which, it would probably be a good idea to document the dependencies needed to get the preview working.

2021-02-18 16:16 UTC, pauby requested changes
I appreciate you didn't make all the changes here so apologies for landing this on you.

2021-02-18 16:16 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. The first step is to contact the maintainers. Use the contact maintainers link on the package page.
Can we make this Contact Maintainers (ie. title case) as it's a thing they need to click on.

2021-02-18 16:16 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
>  1. If you are able to provide a fix, that's even better. Look for the maintainer's package source. Please look for package source url information on the package page.
I know these were not changed, but can we change these to Package Source (i.e title case).

2021-02-18 16:16 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the maintainer(s) do[es] not respond within a few days, it's possible they haven't received your message or don't watch the repository. It's also possible they are on holiday. After waiting for
Contact Site Admins (ie. title case)?

2021-02-18 16:16 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
>  1. If the maintainer(s) are unresponsive after a period of time (determined by the admins), the package is considered abandoned. The curators will TOS the package and new folks can be added as mainta
Maintainer / Moderators / Request For Maintainer.

Can we remove the word curators and add Moderators?

Can we also explain what 'TOS the package' means?

2021-02-18 19:55 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. The first step is to contact the maintainers. Use the contact maintainers link on the package page.
Done.

2021-02-18 19:55 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
>  1. If you are able to provide a fix, that's even better. Look for the maintainer's package source. Please look for package source url information on the package page.
Done

2021-02-18 19:56 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
>  1. If the maintainer(s) are unresponsive after a period of time (determined by the admins), the package is considered abandoned. The curators will TOS the package and new folks can be added as mainta
I'm not actually sure what TOS means in this context.

2021-02-18 19:56 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the maintainer(s) do[es] not respond within a few days, it's possible they haven't received your message or don't watch the repository. It's also possible they are on holiday. After waiting for
Done

2021-02-19 14:40 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
>  1. If the maintainer(s) are unresponsive after a period of time (determined by the admins), the package is considered abandoned. The curators will TOS the package and new folks can be added as mainta
Can we just remove TOS then? Unless @ferventcoder or @gep13 can shed some light on it?

2021-03-01 17:12 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
>  1. If the maintainer(s) are unresponsive after a period of time (determined by the admins), the package is considered abandoned. The curators will TOS the package and new folks can be added as mainta
I went ahead and re-worded this.

2021-03-03 17:30 UTC, pauby requested changes
These are more questions for discussion than anything else.

2021-03-03 17:30 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the maintainer(s) do[es] not respond within a few days, it's possible they haven't received your message or don't watch the repository. It's also possible they are on holiday. After waiting for
I would suggest this needs to be rewritten - we say 'no respond within a few days' at the start and then 'after waiting for a response of at least one week'.

2021-03-03 17:30 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the Maintainer(s) are unresponsive after a period of time (determined by the Moderators), the package is considered abandoned. It is at this point that a new person can be added as a maintainer
I don't reality understand this step - we're saying if the maintainers are unresponsive after a period of time (determined by the Moderators) but in the previous step it's 7 days they wait for. I think this step and the last one should be combined to be clearer.

2021-03-03 17:30 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the maintainer(s) do[es] not respond within a few days, it's possible they haven't received your message or don't watch the repository. It's also possible they are on holiday. After waiting for
Note that it's rare that the Moderators will take any more action than what the requestor has - unless the maintainer is known and active.

2021-03-03 18:13 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
>  So a package needs fixed or updated. You have reached out to the maintainer or Disqus already and are curious what the next steps are. We will elaborate on all of the steps here, including contacting
Simplifying the paragraph sounds fine to me.

----

In regards to Disqus, there are the occasional maintainers who disable email communication, so you cannot contact them that way.

So in those cases, Disqus might be just about the best that you can do to contact the maintainer.

2021-03-03 18:30 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If you are still looking for a way to provide a fix, but don't find a "Package Source" link on the package itself, you can try to find it in one of the maintainer's profiles (this is an older meth
Perhaps we could have the possibility to check the maintainers profile for a repository as an optional note, merged in with the previous step, instead of having it's own step.

2021-03-03 18:32 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
>  So a package needs fixed or updated. You have reached out to the maintainer or Disqus already and are curious what the next steps are. We will elaborate on all of the steps here, including contacting
It's difficult to manage multiple different ways a maintainer can be contacted so the official way is via the Contact Maintainers link. Other methods may work, but I don't feel we should document them as it only helps to complicate the steps whereas the goal should be simple and clear steps.

2021-03-03 18:34 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the maintainer(s) do[es] not respond within a few days, it's possible they haven't received your message or don't watch the repository. It's also possible they are on holiday. After waiting for
I'm fine with "hard coding" a wait time of a week.

2021-03-03 18:34 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the Maintainer(s) are unresponsive after a period of time (determined by the Moderators), the package is considered abandoned. It is at this point that a new person can be added as a maintainer
Fine with me.

2021-03-03 18:37 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If you are still looking for a way to provide a fix, but don't find a "Package Source" link on the package itself, you can try to find it in one of the maintainer's profiles (this is an older meth
If we can be clear on the options in that step - something like 'if you want to take over the package do a) and b) and if you don't do c)' then I'd agree. But as I said in the previous comment I updated, we need to make sure we don't put too many barriers in the way of people.

2021-03-03 20:16 UTC, gep13 commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If you are still looking for a way to provide a fix, but don't find a "Package Source" link on the package itself, you can try to find it in one of the maintainer's profiles (this is an older meth
There have been times when the Package Source URL isn't present, that a maintainer has added a GitHub link in their profile, so I have been able to track things down, so mentioning this as an option is something that should be included I think.

2021-03-03 23:36 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
>  So a package needs fixed or updated. You have reached out to the maintainer or Disqus already and are curious what the next steps are. We will elaborate on all of the steps here, including contacting
Fair enough.

I've updated this, should be good now.

2021-03-03 23:37 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If you are still looking for a way to provide a fix, but don't find a "Package Source" link on the package itself, you can try to find it in one of the maintainer's profiles (this is an older meth
I've combined these into one step, take a look, see if it looks ok now.

2021-03-03 23:37 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the Maintainer(s) are unresponsive after a period of time (determined by the Moderators), the package is considered abandoned. It is at this point that a new person can be added as a maintainer
Updated.

2021-03-03 23:38 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +1. If the maintainer(s) do[es] not respond within a few days, it's possible they haven't received your message or don't watch the repository. It's also possible they are on holiday. After waiting for
Updated.

2021-03-04 13:07 UTC, pauby requested changes
I'd again like to know what @gpe13 thinks of these new suggestions.

2021-03-04 13:07 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +Please include details of how and when you attempted to contact the Maintainer(s).
I would like to see this include the requestor confirming at this stage if they are interested in taking over maintenance of the package or not. That would cut down the time further down the steps.

2021-03-04 13:07 UTC, pauby commented on input/en-us/community-repository/users/package-triage-process.md
> +The moderators will ask if you would like to become a maintainer of the package. If you choose to become a new maintainer, see the next section.
As mentioned in the previous comment, if we can ask the requestor to confirm if they want to take over the package then we can add them at this stage. We don't need to ask them here so this potentially cuts down a step of interaction and shortens the time that this takes.

2021-03-04 14:05 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +Please include details of how and when you attempted to contact the Maintainer(s).
Yep, that would make sense to me.

2021-03-04 14:41 UTC, gep13 commented
>@pauby said...
I'd again like to know what @gpe13 thinks of these new suggestions.

This looks good to me.  I agree with the suggestion that @pauby has made about them mentioning whether they are interested in helping with the package maintenance.  Once that is in, I think we can :shipit:

2021-03-04 15:55 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +Please include details of how and when you attempted to contact the Maintainer(s).
Done

2021-03-04 15:55 UTC, TheCakeIsNaOH commented on input/en-us/community-repository/users/package-triage-process.md
> +The moderators will ask if you would like to become a maintainer of the package. If you choose to become a new maintainer, see the next section.
Done.

2021-03-04 16:01 UTC, TheCakeIsNaOH commented
I noticed that the final step said to look at the new maintainer section, and that the new maintainer section just basically said to look at the package handover page. Thus, it seems like the new maintainer section is pretty much redundant.

So I removed that section completely, and instead directly pointed people at the package handover page in the last step of the triage process.

2021-03-04 16:58 UTC, gep13 approved these changes
LGTM!

2021-03-10 11:11 UTC, merged

2021-03-10 17:25 UTC, gep13 commented
@TheCakeIsNaOH thanks for getting this section of the docs updated! Really appreciate it!