(doc) Add restricted Background Service option
chocolatey/docs pull request #988
Opened 2024-05-08 08:01 UTC by gep13

## Description Of Changes

Add `--ignore-pinned` to list of banned options for Background Service

## Motivation and Context

Following the release of Chocolatey CLI 2.3.0, an additional option has been added to the `choco upgrade` command. After discussion, it has been decided that this new option should not be allowed to be used via the Background Service.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2024-05-08 08:02 UTC, gep13 commented
@pauby I have assigned you as a reviewer to this PR, but this PR should not be merged until we are ready to ship the upcoming versions of Chocolatey products.

2024-05-08 08:20 UTC, pauby requested changes

2024-05-08 08:20 UTC, pauby commented on input/en-us/features/self-service-anywhere.md
> +* Added in Chocolatey Agent 2.1.3 and Chocolatey Licensed Extension 6.1.4
```suggestion
* Added in Chocolatey Agent 2.1.3 and Chocolatey Licensed Extension 6.1.4:
```

2024-06-05 16:04 UTC, gep13 commented
@pauby thank you for the review here.  I am going to get this merged once the CI build completes

2024-06-05 16:12 UTC, merged