Update cpmr0024.md explaining the prerelease tag should be in the version
chocolatey/docs pull request #991
Opened 2024-05-09 14:28 UTC by tunisiano187

Explain the solution to cpmr0024

## Description Of Changes
Explain that the prerelease tag should be in the version

## Motivation and Context
cpmr0024 page was a template, not a complete explanation

## Change Types Made
* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [X] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

[Related Issue](https://github.com/chocolatey/docs/issues/990)

2024-05-10 12:28 UTC, pauby requested changes
@tunisiano187 thank you very much for submitting this PR! I just wanted to suggest a few changes to make it clearer.

2024-05-10 12:28 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0024.md
> +In the nuspec, the id contains a prerelease tag, that tag should be located in the version instead
```suggestion
The `<id>` field in the package `.nuspec` file, contains a prerelease version name such as `alpha`, `beta`, etc.
```

2024-05-10 12:28 UTC, pauby commented on input/en-us/community-repository/moderation/package-validator/rules/cpmr0024.md
> +Please update the nuspec so that the id only contains the real name, and add the prerelease part to the version, that will be added as prerelease on chocolatey and made available through the **--pre*
```suggestion
Please update the `<id>` field in the `.nuspec` file to ensure it only contains the name. The prerelease version name should be added to the `<version>` field. Prerelease packages can be [installed](https://docs.chocolatey.org/en-us/choco/commands/install#options-and-switches) or [upgraded](https://docs.chocolatey.org/en-us/choco/commands/upgrade#options-and-switches) using the `--pre` option in Chocolatey CLI.
```

2024-05-10 12:31 UTC, tunisiano187 reviewed
Corrected, thank you Paul

2024-06-01 10:56 UTC, pauby approved these changes

2024-06-01 11:44 UTC, pauby commented
Thanks @tunisiano187 for the docs update! I've rebased it and merged.

2024-06-01 11:51 UTC, merged