(#966) Switch to Astro
chocolatey/docs pull request #997
Opened 2024-05-17 20:00 UTC by st3phhays

## Description Of Changes

## Motivation and Context

## Testing

* [ ] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [ ] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

Fixes #

2024-05-17 20:11 UTC, st3phhays commented
This is draft due to a few things:

1. The PR's for choco-theme and choco-astro will need to be merged first, packages released, and updated here. 
2. Looking into a `iFrame` component for videos in docs to go along with our `<Collpase />` and `<Tabs />` components.
3. Need to clean up some loose ends, possible get ESLint running here.

2024-05-17 20:18 UTC, st3phhays commented
A reason why this might be stuck in "Expected - Waiting for status to be reported" on the checks: https://github.com/orgs/community/discussions/26698#discussioncomment-3252954

2024-06-06 13:00 UTC, st3phhays commented on src/content/docs/en-us/choco/setup.mdx
> +* `Install-Package chocolatey`
No problem, thanks for the suggestion!

2024-06-07 19:35 UTC, st3phhays commented
@gep13 I've added on a GitHub Actions workflow to run Playwright tests. I'm a little unsure whether this should be it's own workflow, or if we should just add in the Playwright bits to the existing Build Pull Request workflow. Is there a need to keep them separate?

2024-06-11 09:37 UTC, gep13 requested changes
I have just taken this for a spin, and it looks really good!

I haven't done a side-by-side comparison of each page of the docs, but I have done a couple, and the expected changes to use new way of doing xrefs, callouts, etc. all seem to be in place.  I have no reason to think that the other pages won't have the same changes, so I wasn't planning on comparing each page that we have, as there are quite a few :smile:

I did notice a small issue where the iframes for videos are not showing up for me, for example on this page:

```
/en-us/chocolatey-gui/setup/configuration/features/show-console-output
```

This could be a me problem, so would be good to chat about this when you are online today.

2024-06-11 09:37 UTC, gep13 commented on README.md
> +This will run all Playwright test and report and errors for further investigation.
```suggestion
This will run all Playwright tests and report any errors for further investigation.
```

2024-06-11 09:37 UTC, gep13 commented on README.md
> +To run a the Playwright tests, first run the following command:
```suggestion
To run all the Playwright tests, first run the following command:
```

2024-06-11 09:37 UTC, gep13 commented on src/content/docs/en-us/guides/create/create-zip-package.mdx
> +You can find information on `.nuspec` requirements in our [Package Validator Rules](http://localhost:5080/en-us/community-repository/moderation/package-validator/rules/#requirements) documentation.
I think this might be copy/paste from original document, but this URL shouldn't be going to localhost.

2024-06-11 09:37 UTC, gep13 commented on README.md
> +docker run -p 5086:5086 -v $(pwd):/app chocolatey-docs-container
I don't think this section is quite right.  I have made some changes to the devcontainer.json file locally on my machine, and this part wasn't required.

2024-06-11 09:37 UTC, gep13 commented on README.md
> +Connect to the Docker Container in Visual Studio Code. This will launch Visual Studio Code and open a terminal that is running inside the Docker Container whose configuration is defined in `/.devcont
The `Dockerfile` is being deleted in this PR, so this part needs to be updated to reflect that.

2024-06-11 16:53 UTC, st3phhays commented on README.md
> +docker run -p 5086:5086 -v $(pwd):/app chocolatey-docs-container
I have reworked this section to make more sense.

2024-06-11 16:53 UTC, st3phhays commented on README.md
> +Connect to the Docker Container in Visual Studio Code. This will launch Visual Studio Code and open a terminal that is running inside the Docker Container whose configuration is defined in `/.devcont
I have reworked this section to make more sense.

2024-06-11 17:13 UTC, st3phhays commented
@gep13 I've made the changes suggested and rebased on master, I think this is ready for another look!

2024-06-12 13:07 UTC, gep13 approved these changes
LGTM!

2024-06-12 13:07 UTC, merged