(doc) Update docs for v2.3.0
chocolatey/docs pull request #999
Opened 2024-05-27 16:50 UTC by gep13

## Description Of Changes

The changes here are as a result of running GenerateDocs.ps1, and also some manual changes to the source files in CLI and CLE to try to bring things into line.

## Motivation and Context

With the upcoming release of Chocolatey CLI v2.3.0, there are some changes to the docs needed.

## Testing

* [x] I have previewed these changes using the [Docker Container](https://github.com/chocolatey/docs/tree/master/.devcontainer) or another method before submitting this pull request.

## Change Types Made

* [x] Minor documentation fix (typos etc.).
* [ ] Major documentation change (refactoring, reformatting or adding documentation to existing page).
* [ ] New documentation page added.
* [ ] The change I have made should have a video added, and I have raised an issue for this.
    * Issue #

## Change Checklist

* [ ] Requires a change to menu structure (top or left-hand side)/
* [ ] Menu structure has been updated

## Related Issue

N/A

2024-05-27 17:47 UTC, corbob commented on input/en-us/choco/commands/rule.md
Has the `ch0.co` shorturl been generated for this new command? Do we need to generate it?

2024-05-27 17:47 UTC, corbob commented on input/en-us/create/functions/index.md
It looks like the encoding on this file changed. Also: Are we intentionally removing reference to the functions that have been updated to be cmdlets?

2024-05-27 18:47 UTC, gep13 commented on input/en-us/choco/commands/rule.md
Yes, I have created it.

2024-05-27 18:49 UTC, gep13 commented on input/en-us/create/functions/index.md
I will get the encodings fixed up.

Yes, @vexx32 has another PR here: https://github.com/chocolatey/docs/pull/993 for making a split between Functions and Cmdlets.

2024-05-28 13:15 UTC, st3phhays requested changes
I noticed some of the new notes that were added are not in the right format. I'm unsure why these were not caught by the GenerateDocs.ps1 file, but I *think I have this working in my Astro branch. I will confirm that soon.

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/feature.md
> + better integration and scripting.
These new alerts will not be rendered correctly on the website.  I believe I have this working in my Astro changes I have made, but I'll double check that.

```suggestion
> :choco-info: **NOTE**
> 
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/pin.md
> + better integration and scripting.
```suggestion
> :choco-info: **NOTE**
> 
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/setapikey.md
> + better integration and scripting.
```suggestion
> :choco-info: **NOTE**
> 
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/sources.md
> + better integration and scripting.
```suggestion
> :choco-info: **NOTE**
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/unpackself.md
> +> :choco-info: **NOTE** Unpackself has been deprecated and will be removed in version 3.0.0.
```suggestion
> :choco-info: **NOTE**
>
> Unpackself has been deprecated and will be removed in version 3.0.0. 

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/upgrade.md
> +> :choco-info: **NOTE** Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes'
```suggestion
> :choco-info: **NOTE**
> 
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes'

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/create/commands/api-key.md
> + better integration and scripting.
```suggestion
> :choco-info: **NOTE**
> 
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/config.md
> + better integration and scripting.
```suggestion
> :choco-info: **NOTE**
>
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-28 13:15 UTC, st3phhays commented on input/en-us/choco/commands/features.md
> + better integration and scripting.
```suggestion
> :choco-info: **NOTE**
> 
> Starting in v2.3.0, if you have the feature 'useEnhancedExitCodes' turned on, then choco will provide enhanced exit codes that allow better integration and scripting.

```

2024-05-30 15:15 UTC, gep13 commented on input/en-us/create/functions/index.md
@corbob that change here was to move from UTF-8 to UTF-8 with BOM, so this is a valid change from what I can see.

2024-05-30 15:16 UTC, gep13 commented
@corbob @st3phhays this is ready for another review.  Still not ready to merge, but it you are happy, leave an approval and I can merge when getting ready for the release.

2024-06-05 08:12 UTC, gep13 commented
@JPRuskin I know that this is in draft, but would you mind having a look over this, and hopefully give a final approval before we release? Thanks!

2024-06-05 11:50 UTC, JPRuskin reviewed
LGTM, some weirdness around eol-whitespace being brought into markdown (might trigger some rules later).

2024-06-05 16:23 UTC, gep13 commented
@corbob @st3phhays @JPRuskin thank you all for the reviews here!  Going to merge this once the CI build finishes

2024-06-05 16:23 UTC, merged